### ISSUE TITLE
is there a way to calculate load average in windows using windows exporter

### ISSUE THREAD

**Issue by ghost** [prometheus-community/windows_exporter#1000]
We are using windows exporter to montior resources on windows system and we want to have load average metric to show up on dashboard. However we can not find the default metric to be used. Is there a way we can calculate the Load Average for windows. Need some suggestions.

Thanks.

**Comment by prabooo21** [comment]
Interesting, am also looking for same solution

**Comment by breed808** [comment]
My answer in https://github.com/prometheus-community/windows_exporter/issues/866#issuecomment-968240306 is still relevant: there's no way to calculate a load average with the metric sources currently used by the exporter.

If you can find a metric source that provides a load average, or would allow for the calculation of one, let me know and we can add it to the exporter.
