### ISSUE TITLE
Windows exporter .prom not seen on machine

### ISSUE THREAD

**Issue by VulpeanuAdrian** [prometheus-community/windows_exporter#1001]
Hello I have several computers with windows exporter .
The metrics are working on all of them and I have a script which is generating a .prom file which is working only on 3 on them.
I really cant figure why... the only difference would be that on those 2 which is not working they are have 2 Program files dir ( a normal one and a Program files(x86) ones..( also seems that those which are working are V16 / which are not working V18)
The .prom files are almost identical on those which work and which not work( only the value differ..). I've move the windows_exporter dir to the x86 one too .. but same I can not see the variables I have inside the prom ..

**Comment by VulpeanuAdrian** [comment]
I was able to solve the problem after: stop window_exporter services-> delete windows_exporter-> re-install newest version-> add again the same prom file-> start window exporter

**Comment by breed808** [comment]
Thanks for noting the fix for your situation. If it re-occurs, re-open this issue and we can have a closer look.
