### ISSUE TITLE
windows_exporter Verison 0.18.1 will not be showed in grafana V 8.0.6

### ISSUE THREAD

**Issue by mazbeh** [prometheus-community/windows_exporter#1002]
Hello,
i have installed windows_exporter v 0.18.1 in a windows server v 16 . The installation is ok and i can access the metrics in browser under server-name:9182. In prometheus i have configured it also under static-configs with some other servers ( the other servers are linux servers and only this one is a windows server). Prometheus will be used in Grafana.
The problem is that only the windows server will not be showed in grafan dashboard and in prometheus dashboard in browser.

Can someone please give a tip?

Thanks !

**Comment by breed808** [comment]
Are the targets in Prometheus showing as "up"?

**Comment by breed808** [comment]
You'll want to use the `windows_cs_logical_processors` metric.

**Comment by mazbeh** [comment]
@breed808 thanks alot, it shows what i needed !

**Comment by breed808** [comment]
That query appears to be correct, what error are you receiving?

**Comment by mazbeh** [comment]
the problem is that i dont get any error. This query does not show any thing in Grafana -_-

**Comment by breed808** [comment]
Remove the `instance` label from the query and see if any data is returned. If there's still no data, you'll want to ensure the `cpu` collector is enabled and that Prometheus is successfully scraping the host.

**Comment by mazbeh** [comment]
i just tried it. i do not get yet any response. It is funny because with such a metric for example  ,, windows_cpu_time_total{core="0,0",mode="idle"} ,, i receive the data.

sory, that i take your time alot !

**Comment by breed808** [comment]
It would be worth re-checking your query, or building upon it from scratch in order to identify the cause of the missing query data.

I.E. start with `windows_cpu_time_total`, and begin refining the query by adding flags. Once you've confirmed that data is being returned with the flags, add a `sum` operator and see if data is still returned.

If you continue to experience issues querying the data, it may be worth asking in one of the Prometheus support channels.

**Comment by yevhenhnes** [comment]
The same issue, I can't see the windows host in Grafana's dashboard. Host present in prometheus targets and opens in browsers as well on localhost as from another pc.
