### ISSUE TITLE
windows_exporter log spam the eventviewer of VM

### ISSUE THREAD

**Issue by zenzedoon** [prometheus-community/windows_exporter#1008]
Windows_exporter spam the event viewer with  gigabytes of errors related to iis  collector, dose any one get this issue before and how can i resolve it , 

![image](https://user-images.githubusercontent.com/50891244/175327726-1c21932c-01dd-44fb-88ce-0c366f77ed03.png)
![image](https://user-images.githubusercontent.com/50891244/175328226-e434711a-bce7-4bd0-a05a-18166925670d.png)

**Comment by breed808** [comment]
Yes, this has been raised in #975.
