### ISSUE TITLE
IIS collector is broken on 0.18.1

### ISSUE THREAD

**Issue by phmvan** [prometheus-community/windows_exporter#1009]
Hi,
windows_exporter 0.18.1 IIS collector is not working as expected when I delete the website in IIS.
Exporter 0.18.1 running on windows 2019 IIS 10

Reproduce the error : windows_exporter is working correctly. If I delete any the website in IIS. after that exporter has error. Only when I restart IIS the exporter will work again.

Exporter error like below:

An error has occurred while serving metrics:

324 error(s) occurred:
* collected metric "windows_iis_current_anonymous_users" { label:<name:"site" value:"test.santino.com.vn" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_current_blocked_async_io_requests" { label:<name:"site" value:"test.santino.com.vn" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_current_cgi_requests" { label:<name:"site" value:"test.santino.com.vn" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_current_connections" { label:<name:"site" value:"test.santino.com.vn" > gauge:<value:0 > } was collected before with the same name and label values
* collected metric "windows_iis_current_isapi_extension_requests" { label:<name:"site" value:"test.santino.com.vn" > gauge:<value:0 > } was collected before with the same name and label values

**Comment by breed808** [comment]
Does the Perflib counterset include the old IIS website, before restarting IIS?

```powershell
# List counters for set
Get-Counter -ListSet 'Web Service' 
# Get a counter from the set
Get-Counter -Counter '\Web Service(*)\Current Blocked Async I/O Requests'
```

**Comment by phmvan** [comment]
> Does the Perflib counterset include the old IIS website, before restarting IIS?
> 
> ```powershell
> # List counters for set
> Get-Counter -ListSet 'Web Service' 
> # Get a counter from the set
> Get-Counter -Counter '\Web Service(*)\Current Blocked Async I/O Requests'
> ```

the old IIS website (had been deleted) appear before and after I restart IIS if I ran the command bellow 
Get-Counter -Counter '\Web Service(*)\Current Blocked Async I/O Requests'

**Comment by phmvan** [comment]
> That would indicate that IIS is still exposing metrics for the old IIS website in Perflib, which we can't do much about.
> 
> I'm not overly familiar with IIS; hopefully someone else is able to investigate why the metrics are exposed in Perflib after a site removal.

When I re-install older version of exporter. Exactly version 0.16 , it had no error when I get metric even I delete the IIS website.

**Comment by phmvan** [comment]
I think It have a bit different in verion 0.16 and 0.18

**Comment by breed808** [comment]
It's possible this was from the move to Perflib as a metric source in 82f17fd60723c0d1a8ad184e4c427c4f623165ca.

Perhaps someone else could bisect the issue and identify the originating commit?

**Comment by neighbour-oldhuang** [comment]
Same problem for me in v0.20.0

**Comment by gillg** [comment]
I add the same thing again in 0.20 but this time I launched the precious commands from @breed808 !

```
                          \\server\web service(abcde)\current blocked async i/o requests :
                          0

                          \\server\web service(abcdf)\current blocked async i/o requests :
                          0

                          \\server\web service(abcdg)\current blocked async i/o requests :
                          0

                          \\server\web service(abc#1)\current blocked async i/o requests :
                          0

                          \\server\web service(abc)\current blocked async i/o requests :
                          0
```
We can clearly see the site `abc` appears twice, including one with a `#1`

**Comment by gillg** [comment]
Test done : launching `iisreset.exe` fix the problem.

**Comment by gillg** [comment]
Oh ! Checking something else I falled on that comment : https://github.com/prometheus-community/windows_exporter/blob/f5a3cf78396cffbc5c344688afa3efb111758201/collector/process.go#L214

IIS collector should follow the same logic.

**Comment by breed808** [comment]
@gillg to confirm, is the `abc#1` entry one that you have created, or an "extra" entry exposed in the performance counters?

**Comment by breed808** [comment]
@feelproud could you see the above comment and let me know if the entries containing "#1" are manually created?

**Comment by gillg** [comment]
> @gillg to confirm, is the `abc#1` entry one that you have created, or an "extra" entry exposed in the performance counters?

It's exactly the output of the percounters query. I added nothing by hand, except changing dummy names.

**Comment by FeelProud** [comment]
> @FeelProud could you see the above comment and let me know if the entries containing "#1" are manually created?

Not manually created for my part, it's completely automatic.

**Comment by breed808** [comment]
Great, sounds like they can be safely ignored then :+1:

**Comment by breed808** [comment]
I've raised a fix for the issue. If you're not able to test the feature branch, let me know and I'll merge it for the next release.

**Comment by FeelProud** [comment]
Thanks. Ignoring can be in fact the solution, but it seems that in my case the name with the suffix "#" is the good website and the initial name without the suffix is an old version of my website not working anymore...

**Comment by breed808** [comment]
Ah, that complicates things. We'd need to determine which of the two entries is desirable, which may not be possible by the name alone.

Does anyone know why the additional entries are being created by Perflib?

**Comment by gillg** [comment]
@breed808 I don't "know" but seems logic that perflib adds increment for duplicated metrics.
So I guess the other similar trick in the "process" collector makes the values a little bit wrong.

In the case of IIS 2 sites with the same name can't run at the same time, so keeping the higher increment seems make sense to me.

**Comment by EricTsai1107** [comment]
seem the fixes didn't merge in v0.21.0 releases, it's terrible ....

**Comment by breed808** [comment]
@EricTsai1107 v0.21.0 was released to get other fixes into a public release.
I still need to incorporate @gillg's helpful suggestion into the iis (and possibly the process) collector.
I'm hoping to have this done for the v0.22.0 release when I have time.

As always, merge requests for fixes are welcome.

**Comment by breed808** [comment]
Hi all, I've updated the associated pull request. Collector will now de-duplicate site names, keeping the name with the highest suffix value.

E.G. Given the following list of site names, "Site_B" would be discarded, and "Site_B#2" would be kept and presented as "Site_B" in the collector metrics.
`[ "Site_A", "Site_B", "Site_C", "Site_B#2" ]`

Please test and let me know if the change is working as expected.

**Comment by phmvan** [comment]
seem the fixes didn't merge in v0.22.0 releases. I had tested in v0.22.0 and the still error

**Comment by breed808** [comment]
@phmvan the change hasn't been merged and made available in a release yet.
I'd prefer it to be tested first, to avoid breaking the collector.

Are you able to test the PR linked in my previous comment? I can provide binaries If that's preferable.

**Comment by phmvan** [comment]
> @phmvan the change hasn't been merged and made available in a release yet. I'd prefer it to be tested first, to avoid breaking the collector.
> 
> Are you able to test the PR in #1133? I can provide binaries If that's preferable.

yes. You can provide binaries. I will test it. Thanks

**Comment by breed808** [comment]
Apologies for the delay with this, life keeps getting in the way. I've uploaded the files here: https://filetransfer.io/data-package/vAUp4rmp#link

The ZIP archive contains checksums signed with my PGP key, you can use that to verify integrity/authenticity of the files.

**Comment by phmvan** [comment]
> Apologies for the delay with this, life keeps getting in the way. I've uploaded the files here: https://filetransfer.io/data-package/vAUp4rmp#link
> 
> The ZIP archive contains checksums signed with my PGP key, you can use that to verify integrity/authenticity of the files.

I have checked this version. And I confirm this issue have been resoled for my case. I think you can public the new version.
Thanks

**Comment by edgrz** [comment]
Hi @breed808,

Do you know when there are plans to do next release that will include such changes?
