### ISSUE TITLE
Inaccurate value with logon collector

### ISSUE THREAD

**Issue by PapyCat** [prometheus-community/windows_exporter#1011]
Hello, 

I try to get the number of active connections with  `windows_logon_logon_type{status="interactive"}`

But the result is not accurate, when I have 2 active users, the exporter report a larger number like 6 or 8, not identical depending on the server. 

When I request directly the WMI with ` gwmi win32_logonSession` I get the correct result.

**Comment by breed808** [comment]
The collector is sourcing metrics from the same WMI class, so the discrepancy is unexpected.
Does the collector value change when users login and logout of this host?

**Comment by PapyCat** [comment]
I thought the output of the WMI was ok, in fact, I don't know how to interpret it. 
The result looks similar on a server with 2 or 100 users. 

Here the result of the WMI with a server with 1 active user : 

================================
AuthenticationPackage : Negotiate
LogonId              : 230979621
LogonType          : 10
Name                  :
StartTime            : 20220705104545.715073+120
Status                 :

AuthenticationPackage : Kerberos
LogonId              : 431825583
LogonType          : 3
Name                  :
StartTime             : 20220706104153.322386+120
Status                  :

AuthenticationPackage : Kerberos
LogonId               : 414264480
LogonType           : 3
Name                   :
StartTime             : 20220706085625.882283+120
Status                 :

AuthenticationPackage : Kerberos
LogonId               : 230979565
LogonType           : 10
Name                   :
StartTime             : 20220705104545.714572+120
Status                  :

AuthenticationPackage : Negotiate
LogonId               : 229270401
LogonType           : 10
Name                  :
StartTime             : 20220705103722.520919+120
Status                 :

AuthenticationPackage : Negotiate
LogonId               : 85336818
LogonType           : 10
Name                   :
StartTime             : 20220704163216.592768+120
Status                  :

AuthenticationPackage : Kerberos
LogonId               : 229270324
LogonType           : 10
Name                  :
StartTime            : 20220705103722.520919+120
Status                 :

AuthenticationPackage : Kerberos
LogonId               : 85336496
LogonType           : 10
Name                  :
StartTime             : 20220704163216.592267+120
Status                  :

================================

And this is the output of the exporter : 

windows_logon_logon_type{status="batch"} 0
windows_logon_logon_type{status="cached_interactive"} 0
windows_logon_logon_type{status="cached_remote_interactive"} 14
windows_logon_logon_type{status="cached_unlock"} 0
windows_logon_logon_type{status="interactive"} 8
windows_logon_logon_type{status="network"} 6
windows_logon_logon_type{status="network_clear_text"} 0
windows_logon_logon_type{status="new_credentials"} 0
windows_logon_logon_type{status="proxy"} 0
windows_logon_logon_type{status="remote_interactive"} 14
windows_logon_logon_type{status="service"} 3
windows_logon_logon_type{status="system"} 1
windows_logon_logon_type{status="unlock"} 0

**Comment by cmeis** [comment]
I've got a similar problem on two RDS hosts (one running Windows Server 2012 R2, one 2019).
It seems that WMI is returning bad results, the windows_exporter is just forwarding the wrong input it's given. So that's clearly not a windows_exporter bug, and there's nothing windows_exporter could do about it.

Querying WMI directly for Win32_LogonSession with LogonType 10 (remote) does give me more results than people are logged in (as seen in task manager or the server managers' RDP properties).
Rebooting the servers resets the value to 0 correctly, but over time the "overhead" of counted users does increase again. Seems like for some sessions logging off is not correctly detected and represented in WMI?

Anyone got any insight in reasons for this behaviour or a solution?

**Comment by pixelrebel** [comment]
Rebooting doesn't help for me.  `win32_logonSession` over reports even from a fresh reboot.

**Comment by breed808** [comment]
With the WMI source being inaccurate, it may be worth removing the `logon` collector, or finding an alternate source. Thoughts?

**Comment by PapyCat** [comment]
As an alternative, I've written a script that uses the WMI "win32_Process" class to monitor the "shellexperiencehost.exe" process. 
I compared the results with the command "quser" who give me correct results. 

Here is a quick protype : 
```
package main

import (
	"fmt"
	"github.com/StackExchange/wmi"
)

type Win32Process struct {
	SessionID uint32
}

func main() {
	var processes []Win32Process
	err := wmi.Query("SELECT SessionID FROM win32_Process WHERE Name='shellexperiencehost.exe' AND SessionID<>0", &processes)
	if err != nil {
		panic(err)
	}
	sessions := make(map[uint32]bool)
	for _, process := range processes {
		sessions[process.SessionID] = true
	}
	activeUsers := len(sessions)
	fmt.Printf("Number of active users: %d\n", activeUsers)
}
```
Since I'm very bad in Go, I wouldn't be able to redo a logon module that works like this.
