### ISSUE TITLE
We are not seeing any results for windows_process_working_set_private_bytes

### ISSUE THREAD

**Issue by prabooo21** [prometheus-community/windows_exporter#1016]
We are unable to see this metric( **windows_process_working_set_private_bytes**) from any of our machines, please let us know if we can see this metric.

**Comment by breed808** [comment]
Is the `process` collector returning a successful result?

See `windows_exporter_collector_success{collector="process"}`

**Comment by cas-cloud-user** [comment]
Yes it shows successful result but I think this is related to version. You can try changing the version of windows_exporter.

**Comment by babli-coditas** [comment]
You can try changing the version. Hope this helps!
