### ISSUE TITLE
windows_ exporter is disconnect from Prometheus but not restarted .

### ISSUE THREAD

**Issue by lailb** [prometheus-community/windows_exporter#1017]
###windows_exporter 0.18.1  ##
windows_ exporter is disconnect from Prometheus but not restarted .
And these metrics have not changed between the windows_exporter disconnected.
![image](https://user-images.githubusercontent.com/108862841/177724634-9dea251c-ccb0-4197-a96e-7e6786ba609b.png)
There are no events about windows_exporter in Windows Events.This situation will lead to the sending a warning.

**Comment by breed808** [comment]
Are you saying the exporter has failed to start for some reason?

**Comment by lailb** [comment]
> 
No. The exporter has not restarted but disconnected for about 30s-1min .There are no metrics during this period. Only oneortwo exporter have problems and it's random。

**Comment by breed808** [comment]
Are there any relevant event logs being emitted by the exporter?

It's also worth confirming if this is affected only certain collectors.

**Comment by lailb** [comment]
> 
There are no any relevant event logs by the exporter. The UP status has been affected.So all other collectors are affected.
It will happen once a day or two and different customers have the same problems.
In addition to the default， I had enabled the **process and textfile** collectors.
![image](https://user-images.githubusercontent.com/108862841/178170050-8f0bae5b-dc00-4593-b1a5-401fb436deb5.png)
![image](https://user-images.githubusercontent.com/108862841/178170133-5641d9a8-c322-48a7-9152-75b36386649f.png)

**Comment by breed808** [comment]
By UP status, do you mean that the exporter is not accessible for this period by the Prometheus instance?

Are you able to confirm if the exporter is not accessible locally during these times, to confirm if this is not an issue external to the exporter, such as network connectivity?
