### ISSUE TITLE
Msi fails with error code 1603

### ISSUE THREAD

**Issue by baldurfour** [prometheus-community/windows_exporter#1018]
I managed to install this one one windows server but fails on others with error code:

`Action start 10:57:19: ExecuteAction.
Action ended 10:57:19: ExecuteAction. Return value 3.
Action ended 10:57:19: INSTALL. Return value 3.
=== Logging stopped: 7/7/2022  10:57:19 ===
MSI (c) (0C:4C) [10:57:19:143]: Product: windows_exporter -- Installation failed.

MSI (c) (0C:4C) [10:57:19:143]: Windows Installer installed the product. Product Name: windows_exporter. Product Version: 0.18.1. Product Language: 1033. Manufacturer: prometheus-community. Installation success or error status: 1603.`
The program just runs for 1 sec and then stops. Any clue?

**Comment by breed808** [comment]
https://docs.microsoft.com/en-us/troubleshoot/windows-server/application-management/msi-installation-error-1603#cause

Are you performing the installation with administrative privileges? If so, what arguments are being supplied to the MSI installation command?

**Comment by baldurfour** [comment]
So i'm installing with Admin rights and the arguments are the default ones.

**Comment by baldurfour** [comment]
Sorry guys so i was able to install it on a bunch of servers but some of them were reporting 1603 as I said, a server restart did the trick xD but i couldn't do it because they are in production. PSExec works just fine:
psexec.exe -s \\$server msiexec /i C:\temp\windows_exporter-0.18.1-386.msi /q /L C:\temp\log.txt
