### ISSUE TITLE
How do I enable SSL for WMI Exporter

### ISSUE THREAD

**Issue by BhusanBibhuti** [prometheus-community/windows_exporter#1040]
Hello team ,
I would like to configure https for my WMI exporter metrics endpoint . Could you please guide me how to do this ?

**Comment by breed808** [comment]
Hi there, details for TLS configuration can be found in the [Flags](https://github.com/prometheus-community/windows_exporter#flags) section of the project README. See the `--web.config.file` flag for a link to further documentation.
