### ISSUE TITLE
How to install Windows 32-bit system windows_exporter

### ISSUE THREAD

**Issue by renziyou** [prometheus-community/windows_exporter#1044]
How to install Windows 32-bit system windows_exporter

**Comment by breed808** [comment]
You'll want to use the 386 EXE or MSI from the [releases page](https://github.com/prometheus-community/windows_exporter/releases/tag/v0.19.0), and then follow the documentation in the project README.

If you encounter any issues during installation, feel free to re-open this issue.

**Comment by renziyou** [comment]
But my Windows 2008 32-bit can't install   386 EXE

**Comment by breed808** [comment]
Could you provide additional detail on the failure? The EXE isn't an installer, it's a standalone executable for running the exporter.

What flags and/or config file are you providing when running the executable? Is the exporter logging any output?

**Comment by renziyou** [comment]
![Uploading 32.png…]()

Not effective 32-bit programs

**Comment by renziyou** [comment]
Not effective 32-bit programs
![32](https://user-images.githubusercontent.com/8150303/186867848-440b392d-b773-4c53-ae64-402a13f53b1d.png)

**Comment by breed808** [comment]
Is this output received when running the exporter with no flags? I.E. `.\windows_exporter.exe`?

**Comment by renziyou** [comment]
Yes, can't run

**Comment by breed808** [comment]
It may be worth compiling the exporter on the affected system and determining if that build also fails. Perhaps settings `GOARCH` to the various [supported values](https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63#goarch-values) to see if any of the builds work.
