### ISSUE TITLE
Missing Metrics on some server

### ISSUE THREAD

**Issue by zenzedoon** [prometheus-community/windows_exporter#1050]
Hello ,
I have a farm of Windows server 2019 on which i have set up windows exporter (v0.18.1) all with ansible (some config) 
when i tried to create a dashboard on grafana i found that one server dosen't display all the metrics as the other server, 
the version of OS , and windows_exporter are the same , the config file is the same , but some metrics are missing on one servers:
exple of mising metrics: 
-windows_cpu_time_total
-windows_net_bytes_sent_total
-windows_os_physical_memory_free_bytes

![image](https://user-images.githubusercontent.com/50891244/187169596-8f859974-7523-411d-bb60-c8a8f93c2bdd.png)
![image](https://user-images.githubusercontent.com/50891244/187170264-b68737b7-0a82-4ff6-8d94-7fcdceb3d475.png)

**Comment by breed808** [comment]
Are the collectors returning a successful result? Check the `windows_exporter_collector_success` metric.

**Comment by TriBallscom** [comment]
I have the same issue, 300+ servers and a hand full give problems
time="2023-02-01T11:48:06+01:00" level=error msg="failed collecting system metrics:<nil> counter not found" source="system.go:73"
time="2023-02-01T11:48:06+01:00" level=error msg="collector logical_disk failed after 0.003275s: counter not found" source="exporter.go:207"
time="2023-02-01T11:48:06+01:00" level=error msg="failed collecting os metrics:<nil> counter not found" source="os.go:137"
time="2023-02-01T11:48:06+01:00" level=error msg="collector os failed after 0.009092s: counter not found" source="exporter.go:207"
time="2023-02-01T11:48:06+01:00" level=error msg="collector system failed after 0.007947s: counter not found" source="exporter.go:207"
time="2023-02-01T11:48:06+01:00" level=debug msg="collector logon succeeded after 0.039326s." source="exporter.go:210"
time="2023-02-01T11:48:06+01:00" level=debug msg="collector service succeeded after 0.549366s." source="exporter.go:210"

All servers come from the same deployment image. I tried rebuilding the performance counters but it has no result on the exporter.

**Comment by breed808** [comment]
@TriBallscom you'll need to verify if the performance counters exist on these hosts:

```powershell
# List counters for set
Get-Counter -ListSet 'LogicalDisk' 
# Get a counter from the set
Get-Counter -Counter '\LogicalDisk(*)\% Free Space'
```

The name of the counter set is defined in the `registerCollector()` call for each collector. E.G. for the `logical_disk` collector: https://github.com/prometheus-community/windows_exporter/blob/master/collector/logical_disk.go#L16
