### ISSUE TITLE
Process Id - Flags for PEr Process metrics. 

### ISSUE THREAD

**Issue by G31st** [prometheus-community/windows_exporter#1053]
Hi, 

How would I set the exporter to include the process id ? I'm currently starting up the collector via cmd input, but the output is only including the processname ? 

windows_netframework_clrloading_loader_heap_size_bytes{process="powershell"} 2.502656e+06

"C:\wmi_exporter\wmi_exporter.exe" 
--log.format logger:eventlog?name=wmi_exporter 

--collectors.enabled 
cpu,
cs,
logical_disk,
memory,
net,
os,
process,
service,
system,
tcp,
textfile,
netframework_clrexceptions,
netframework_clrinterop,
netframework_clrjit,
netframework_clrloading,
netframework_clrlocksandthreads,
netframework_clrmemory,
netframework_clrremoting,
netframework_clrsecurity 

--telemetry.addr :9182 
--collector.process.whitelist="MyService.+|MyOtherService.+" 
--collector.textfile.directory D:\Data\PrometheusMetrics \
--collector.service.services-where="Name='MyService'"

**Comment by breed808** [comment]
I assume you're referring to the `process` collector? There's an [`IDProcess`](https://github.com/prometheus-community/windows_exporter/blob/15be1c1bd64e67d403c1417e337d5b1167af001e/collector/process.go#L166) variable that's not currently exposed by the exporter. I'll have a look and confirm if this is the process ID.

**Comment by G31st** [comment]
@breed808 - Thanks you can close the issue, it doesn't seem like your can get the process id for netframework collectors, I incorrectly assumed because the process name is exposed that the id would be readily available.
