### ISSUE TITLE
Eventlog System / Registry support

### ISSUE THREAD

**Issue by awohlmut71** [prometheus-community/windows_exporter#1054]
Hi all,
I am currently in a project to migrate existing monitoring tool.

Linux is mostly done successfully, which is very cool.

On Windows servers I am struggling with eventlog and registry  queríes.
Is this intended to have this directly in the exporter ?

I.e Eventlog unexpected reboot ID 1001
I.e Regkey Windows is not licensed

I know for Eventlog there are tools to collect at central place. But this also means extra cost for hardware etc.

Or what is the best approach?

Thanks for any hint
Andreas

**Comment by breed808** [comment]
This tool could support exposing **metrics** for the eventlog and registry, but would not support parsing, exposing or shipping of **logs** as these are outside the scope of this program.

If you're looking to centrally collect logs, you'll need to search for another tool.

**Comment by xblane** [comment]
Hi Andreas, I use a powershell script on a schedule plus the textfile collector to capture custom metrics. Not pretty but gets the job done.

**Comment by awohlmut71** [comment]
HI,

thanks for info. I want to provide metrics based on local filter. Seems this is the same like xblane already doing it.
I did not found a doc about syntax of the custom metric format. 
So I have to think about to create scheduledTask/Service + custom metric or to extend the exporter with new collector evtlog and regkey.

@xblane, I will contact you :-)

thanks
Andreas

**Comment by breed808** [comment]
Refer to the [OpenMetrics specification](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md) for syntax.

If you're planning to scrape metric sources, such as Perflib or WMI, you can add collectors to the exporter and create a pull request. If you're scraping logs for metrics you'll need to create your own process to export the metrics for the `textfile` collector.
