### ISSUE TITLE
Exchange Collector Metric Types

### ISSUE THREAD

**Issue by xblane** [prometheus-community/windows_exporter#1057]
Noticed with metric windows_exchange_ldap_read_time_sec , but I assume it applies to others, the type is counter where gauge appears more appropriate

**Comment by breed808** [comment]
Is the metric not incrementing?

**Comment by xblane** [comment]
The metric does increment. 

Sorry, I may have been working on a false assumption that the metric should represent the underlying data? ie if the source data acts as a gauge, the metric should act as a gauge.

**Comment by breed808** [comment]
It depends on the metric. Some act as gauges when presented by Windows, but are exposed by Perflib (the source we use for most metrics) as counters.

Generally, if the metric is incrementing over time it's a counter. Documentation on a lot of these metrics is nonexistent, so it's entirely possible we have some counters that should be gauges, and vice versa.

If you spot any that are incorrect I'd be happy to merge a PR or implement any required changes.
