### ISSUE TITLE
Windows_exporter v0.19.0 memory leak

### ISSUE THREAD

**Issue by AvdeevArtem** [prometheus-community/windows_exporter#1063]
Hello. We use windows_exporter v0.19.0 with this collectors: os,cpu,cpu_info,cs,memory,net,system,tcp,process,service,logical_disk,mssql,scheduled_task,textfile --collector.service.services-where="Name LIKE '%SQL%'", after upgrade from 0.17.1 we noticed memory leak. 
In 0.19.0 we also added scheduled_task collector
<img width="1891" alt="image" src="https://user-images.githubusercontent.com/45825379/190667292-ec616fbe-33b1-4472-b762-95cb0e9e2f79.png">

**Comment by breed808** [comment]
Do you continue to experience this behavior after disabling the `scheduled_task` collector? If so I wonder if this is related to #813

**Comment by AvdeevArtem** [comment]
We disabled scheduled_task collector and the problem is gone

**Comment by davideverall** [comment]
Just to confirm that we are experiencing the same issue on `windows_exporter v0.20.0` with `scheduled_task` collector enabled.

![image](https://user-images.githubusercontent.com/74308196/196484644-bce02a98-5e98-4268-aad6-57dcaff0a8c3.png)
