### ISSUE TITLE
In Windows server 2022 with hyper-v ,Thermal's value looks like  not correct

### ISSUE THREAD

**Issue by fishg** [prometheus-community/windows_exporter#1064]
In Windows server 2022 with hyper-v ,Thermal's value is fixed value?
<img width="847" alt="image" src="https://user-images.githubusercontent.com/1423545/190861267-f0a771cd-f946-4d3b-b6ae-0832ae2c26e0.png">

**Comment by breed808** [comment]
Are the underlying metrics changing at all? Query with `Get-CimInstance Win32_PerfRawData_Counters_ThermalZoneInformation`.

**Comment by fishg** [comment]
starting params:
windows_exporter-0.19.0-amd64.exe --collectors.enabled="cpu,memory,net,logical_disk,thermalzone"

**Comment by breed808** [comment]
Does the underlying WMI class change at all? `Get-CimInstance Win32_PerfRawData_Counters_ThermalZoneInformation` will tell you if Windows is reporting an unchanging temperature metric to the exporter.

**Comment by fishg** [comment]
> Does the underlying WMI class change at all? `Get-CimInstance Win32_PerfRawData_Counters_ThermalZoneInformation` will tell you if Windows is reporting an unchanging temperature metric to the exporter.

how could I confirm this? Any guide or curl command ?

**Comment by breed808** [comment]
It's a Powershell command, you'll want to run it with the Powershell interpreter on the host experiencing the issue.

**Comment by fishg** [comment]
looks like not changed. I was run many times.
 Get-CimInstance Win32_PerfRawData_Counters_ThermalZoneInformation


Caption                  :
Description              :
Name                     : \_TZ.TZ00
Frequency_Object         : 0
Frequency_PerfTime       : 0
Frequency_Sys100NS       : 10000000
Timestamp_Object         : 0
Timestamp_PerfTime       : 0
Timestamp_Sys100NS       : 133096915759207662
HighPrecisionTemperature : 3232
PercentPassiveLimit      : 100
Temperature              : 323
ThrottleReasons          : 0
PSComputerName           :


<img width="807" alt="image" src="https://user-images.githubusercontent.com/1423545/194678601-f933d74c-7a56-473d-83e7-4922bbafad38.png">

**Comment by breed808** [comment]
Unfortunately if Windows is reporting incorrect or unchanging values there's not much that can be done with the exporter.
You'll want to investigate the cause of the unchanging metrics at the Windows/WMI level.
