### ISSUE TITLE
exporter fails with error 500

### ISSUE THREAD

**Issue by shabnamEsmaeili** [prometheus-community/windows_exporter#1067]
Im using windows exporter v0.19.0 and when I launched http://localhost:9182/metrics
I get many errors saying "was collected before with the same name and label values"
such as "collected metric "windows_iis_current_anonymous_users" was collected before with the same name and label values"
and when I installed v0.16 this problem was solved. but with later version I got this error.

**Comment by breed808** [comment]
Duplicate of  #1009
