### ISSUE TITLE
Failed to get process level information

### ISSUE THREAD

**Issue by vishalkalal22** [prometheus-community/windows_exporter#1068]
Hi,

I want to track the CPU, Memory and total count of processes running on the server.
I am using the below command to initiate the windows exporter -

**c:\PROGRA~1\windows_exporter\windows_exporter.exe --collector.process.whitelist="chrome.+"**

But, I am getting only services-level information, nothing related to the process. 

C:\WINDOWS\system32>"C:\Program Files\windows_exporter\windows_exporter.exe" --log.format logger:eventlog?name=windows_exporter  --telemetry.addr :9182 --collectors.enabled "[defaults],memory,process,tcp" --collector.process.whitelist="chrome.+"
time="2022-09-27T12:18:45+05:30" level=warning msg="No where-clause specified for service collector. This will generate a very large number of metrics!" source="service.go:48"
time="2022-09-27T12:18:45+05:30" level=info msg="Enabled collectors: net, tcp, cpu, os, cs, logical_disk, service, system, textfile, memory, process" source="exporter.go:348"
time="2022-09-27T12:18:45+05:30" level=info msg="Starting windows_exporter (version=0.17.1, branch=heads/tags/v0.17.1, revision=d9f4264fc4ee183462fc23032ce9b60444411b87)" source="exporter.go:400"
time="2022-09-27T12:18:45+05:30" level=info msg="Build context (go=go1.17.5, user=runneradmin@fv-az177-480, date=20220102-09:24:12)" source="exporter.go:401"
time="2022-09-27T12:18:45+05:30" level=info msg="Starting server on :9182" source="exporter.go:404"
time="2022-09-27T12:18:46+05:30" level=info msg="TLS is disabled." source="gokit_adapter.go:38"

**Comment by vishalkalal22** [comment]
@carlpett or @breed808 Can you please help me with this?

**Comment by breed808** [comment]
Replace the plus with an asterisk. `chrome.+` -> `chrome.*`

Alternatively remove the whitelist flag and determine the process name before creating the regex.

**Comment by vishalkalal22** [comment]
Thanks, @breed808 for the help.
