### ISSUE TITLE
How can Windows Exporter Be configured to push

### ISSUE THREAD

**Issue by wyzdzyk** [prometheus-community/windows_exporter#1070]
I want to configure Windows Exporter to push information to the Pushgateway. What parameters should I add?

**Comment by breed808** [comment]
The exporter was never written with the intention of pushing metrics to the Pushgateway, as it's only recommended for batch jobs:

> Usually, the only valid use case for the Pushgateway is for capturing the outcome of a service-level batch job

You'd need a separate tool or script to collect the metrics exposed by this exporter and push them to a Pushgateway.
