### ISSUE TITLE
Failed to capture memory utilization per process

### ISSUE THREAD

**Issue by vishalkalal22** [prometheus-community/windows_exporter#1071]
Hi,

I need to capture the CPU & memory consumption. I was able to get the CPU-related data using the below command. 

```
100 * sum by (mode) (rate(windows_process_cpu_time_total{instance=~"$server", process=~".*tcserver.*"}[5m])) / sum by(mode) (rate(windows_cpu_time_total{instance="$server"}[5m]))
```

But, I am not able to get the data for the memory % consumption and total memory used by the process.

@breed808 can you please help me with this?

**Comment by breed808** [comment]
For process memory you'll want to look at the `process` collector, likely the `windows_exporter_process_working_set_bytes` metric.

Aggregate memory stats can be found with `windows_exporter_os_physical_memory_free_bytes` and `windows_exporter_cs_physical_memory_bytes`.

**Comment by vishalkalal22** [comment]
Thanks, @breed808 for the help.

Issue resolved.
