### ISSUE TITLE
Monitor services on auto, auto (delayed), auto(trigger) separately. 

### ISSUE THREAD

**Issue by bhattanil** [prometheus-community/windows_exporter#1076]
Is there any method by which we can monitor windows service on the basis of automatic , automatic (delayed start), automatic (trigger start) differently? Can any one help on this how is this possible?

**Comment by trippinnik** [comment]
for your service collector argument can you try:
--collector.service.services-where="startmode=auto"

For auto (delayed) etc add that to the filter. Basically, this parameter
lets you send the commandline filter arguments.

**Comment by bhattanil** [comment]
Failed collecting emi service metrics. Invalid query. This is not working for me.

**Comment by trippinnik** [comment]
success for me like this:
windows_exporter-0.18.1-amd64.exe
--collector.service.services-where="StartMode='Auto'"

**Comment by breed808** [comment]
@bhattanil were the example queries in #1072 not suitable? Combining the `windows_service_state` and `windows_service_start_mode` metrics should allow you to distinguish services by the start mode.

**Comment by bhattanil** [comment]
Yes it gives start mode with auto but in auto also there are three category that is not distinguish. These are automatic (delayed), automatic (trigger) and automatic.
 I am expecting that thing.

**Comment by trippinnik** [comment]
If you can filter it in wmi query add that to your config. I gave you the
start, you can take it the last mile

**Comment by bhattanil** [comment]
How I can add in config?  How to start? Could you share idea how?

**Comment by breed808** [comment]
> Yes it gives start mode with auto but in auto also there are three category that is not distinguish. These are automatic (delayed), automatic (trigger) and automatic.

The [WMI class](https://learn.microsoft.com/en-us/windows/win32/cimwin32prov/win32-service?redirectedfrom=MSDN) sourced by the `service` collector doesn't distinguish between these three automatic types: you'll only see "auto" for these services.
