### ISSUE TITLE
Nessus finding: Microsoft Windows Unquoted Service Path - windows exporter

### ISSUE THREAD

**Issue by albionb96** [prometheus-community/windows_exporter#1079]
When running Nessus Scan to scan my system for vulnerabilities, the Nessus scan listed the following vulnerability coming from Prometheus windows exporter:
```
Nessus found the following services with an untrusted path :
  windows_exporter : C:\Program Files\windows_exporter\windows_exporter.exe
```
I think the reason we get this vulnerability is because the path contains whitespaces and the whole path is not quoted. Quoting the service path would resolve the issue, I think.

**Comment by breed808** [comment]
I don't think this is of great concern, as it would require an attacker to modify `C:\program.exe` which would require Administrator rights (if I'm reading this correctly). Would still be good to get it fixed though.

I believe this is an upstream bug with [wix3](https://github.com/wixtoolset/wix3), as we're specifying the directory and path for the service binary path as per the documentation: https://github.com/prometheus-community/windows_exporter/blob/eb73859393991318a6ae08da53f863cee4a9d2a1/installer/windows_exporter.wxs#L48-L50

**Comment by albionb96** [comment]
Thank you @breed808 for your comment,but who could create a PR to fix that bug, I don't really understand what should be changed on that file, I am missing the know how

**Comment by breed808** [comment]
The file I referenced shouldn't need to be changed. An issue should be raised upstream to add quotes to the compiled service binary path.
