### ISSUE TITLE
Service not being created on Windows 11

### ISSUE THREAD

**Issue by servebeer** [prometheus-community/windows_exporter#1087]
I just installed the windows exporter on my Windows 11 test system. I tried both the msi and the exe. Both ran without any errors, but the service and firewall rules are nowhere to be found.

**Comment by servebeer** [comment]
It is odd that it is listed under "Add or Remove Programs" but the service and firewall rule does not show up.

**Comment by breed808** [comment]
I'm unable to reproduce this on a Windows 11 VM. Double-clicking the MSI correctly installs the applications with service and firewall entries.

Could you provide more information on the issue? Does it occur with all Windows 11 hosts? Does the installer provide any output when run with `msiexec` [logging to a file](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/msiexec)?

**Comment by servebeer** [comment]
@breed808 what are the names of the firewall rules? I am looking for something starting with "Prometheus", if they are not named this, I might be missing them. Same goes for the service. I have attached screenshots of both interfaces showing a lack of both.

![services](https://user-images.githubusercontent.com/8514341/203568779-d0e0cfd2-38fd-415a-b23b-b67e115a1fd9.png)
![firewall](https://user-images.githubusercontent.com/8514341/203568782-e60c7d6e-9def-41bc-9b76-4ee62cce7c10.png)

**Comment by breed808** [comment]
From memory both the service entry and firewall rule will be named "windows_exporter".

**Comment by servebeer** [comment]
Ah Ha! It definitely helps to know what to look for ;-) I do have a windows_exporter service running, and I do have a windows_exporter inbound rule. This still confuses me though. If this service is exporting data, shouldn't it be an outbound rule instead?

**Comment by dbond007** [comment]
> If this service is exporting data, shouldn't it be an outbound rule instead?

It collects information, but it's a service running on the windows system, listening on a specific port, waiting for an external system to open a connection to it and request that info,  so inbound needed.
Outbound would be needed only if the collector started the connection and you had set windows to block all outbound connections, which is not default,  only inbound is.

**Comment by servebeer** [comment]
makes sense...

**Comment by mr-rycho** [comment]
windows exporter used to add firewall exception but as of version 0.28.2 it doesn't even if I use the option `ADDLOCAL=FirewallException` . 
my full command line is :
```
msiexec /i windows_exporter-0.28.2-amd64.msi ENABLED_COLLECTORS=cpu,logical_disk,memory,net,os,physical_disk,system ADDLOCAL=FirewallException
```
beside that the service is properly installed, running, and the option enabled_collectors is properly interpreted (lack of `service` collector reduced number of exported statistics 8 times!)

I also have version 0.22.0 that _does_ add the firewall rule named `windows_exporter (HTTP )` for program `.../windows_exporter.exe`.

**Comment by jkroepke** [comment]
> EDIT: is the installation progress logged somewhere?

Re-run msiexec with `/L*V "installer.log"` logs everything

**Comment by mr-rycho** [comment]
Sorry, I rechecked and for 0.28.2 correct is:
* whenever I don't require adding firewall exception, the service is installed
* if I require the firewall exception to be added neither firewall rule nor service is installed

I also compared the output log files (stripped time signatures for easier comparison). Regardless of whether I use the `ADDLOCAL=FirewallException` option, this part is the same:
```
MSI (s) : : Doing action: Wix5SchedFirewallExceptionsInstall_X64
Action start : Wix5SchedFirewallExceptionsInstall_X64.
MSI (s) : : Invoking remote custom action. DLL: C:\Windows\Installer\MSI7EB2.tmp, Entrypoint: SchedFirewallExceptionsInstall
SchedFirewallExceptions:  Component 'C_FirewallException' action state (0) doesn't match request (1)
SchedFirewallExceptions:  No firewall exceptions scheduled
Action ended : Wix5SchedFirewallExceptionsInstall_X64. Return value 1.
MSI (s) : : Doing action: InstallServices
Action start : InstallServices.
Action ended : InstallServices. Return value 1.
```

but this is different (appears only when I don't use the firewall option):
```
MSI (s) : : Invoking remote custom action. DLL: C:\Windows\Installer\MSI7EC3.tmp, Entrypoint: SchedServiceConfig
MSI (s) (84!A8) : PROPERTY CHANGE: Adding Wix4RollbackServiceConfig_X64 property. Its value is 'SchedServiceConfig'.
MSI (s) (84!A8) : Doing action: Wix4RollbackServiceConfig_X64
Action start : Wix4RollbackServiceConfig_X64.
Action ended : Wix4RollbackServiceConfig_X64. Return value 1.
MSI (s) (84!A8) : PROPERTY CHANGE: Adding Wix4ExecServiceConfig_X64 property. Its value is 'SchedServiceConfigwindows_exporter1restartrestartrestart060'.
MSI (s) (84!A8) : Doing action: Wix4ExecServiceConfig_X64
Action start : Wix4ExecServiceConfig_X64.
Action ended : Wix4ExecServiceConfig_X64. Return value 1.
```

here's the batch file I've used:
```
@echo off

msiexec /i windows_exporter-0.28.2-amd64.msi
call :testdir "(1a)"
msiexec /quiet /x windows_exporter-0.28.2-amd64.msi

msiexec /i windows_exporter-0.28.2-amd64.msi /l*v log1.log
call :testdir "(1b)"
msiexec /quiet /x windows_exporter-0.28.2-amd64.msi


msiexec /i windows_exporter-0.28.2-amd64.msi ADDLOCAL=FirewallException
call :testdir "(2a)"
msiexec /quiet /x windows_exporter-0.28.2-amd64.msi

msiexec /i windows_exporter-0.28.2-amd64.msi /l*v log2.log ADDLOCAL=FirewallException
call :testdir "(2b)"
msiexec /quiet /x windows_exporter-0.28.2-amd64.msi

msiexec /i windows_exporter-0.28.2-amd64.msi ENABLED_COLLECTORS=cpu,logical_disk,memory,net,os,physical_disk,system
call :testdir "(3a)"
msiexec /quiet /x windows_exporter-0.28.2-amd64.msi

msiexec /i windows_exporter-0.28.2-amd64.msi /l*v log3.log ENABLED_COLLECTORS=cpu,logical_disk,memory,net,os,physical_disk,system
call :testdir "(3b)"
msiexec /quiet /x windows_exporter-0.28.2-amd64.msi

msiexec /i windows_exporter-0.28.2-amd64.msi ENABLED_COLLECTORS=cpu,logical_disk,memory,net,os,physical_disk,system ADDLOCAL=FirewallException
call :testdir "(4a)"
msiexec /quiet /x windows_exporter-0.28.2-amd64.msi

msiexec /i windows_exporter-0.28.2-amd64.msi /l*v log4.log ENABLED_COLLECTORS=cpu,logical_disk,memory,net,os,physical_disk,system ADDLOCAL=FirewallException
call :testdir "(4b)"
msiexec /quiet /x windows_exporter-0.28.2-amd64.msi


goto :eof


:testdir
if exist "C:\Program Files\windows_exporter\windows_exporter.exe" (
   echo exporter exists %1
) else (
    echo exporter does NOT exist %1
)

goto :eof
```

output:
```
exporter exists "(1a)"
exporter exists "(1b)"
exporter does NOT exist "(2a)"
exporter does NOT exist "(2b)"
exporter exists "(3a)"
exporter exists "(3b)"
exporter does NOT exist "(4a)"
exporter does NOT exist "(4b)"
```
