### ISSUE TITLE
Kubernetes daemonset fails to start with latest

### ISSUE THREAD

**Issue by knabben** [prometheus-community/windows_exporter#1092]
Running the daemonset on a `1.25 Kubernetes cluster, containerd version 1.7.0 - Win 2022` cluster using  `latest` (2022-11-08) image. The interface fails to bind using hostNetwork/HPC, as the error below:

```
❯ kubectl logs windows-exporter-mbpvv
Defaulted container "windows-exporter" out of: windows-exporter, configure-firewall (init)
time="2022-11-07T14:48:08Z" level=info msg="Loading configuration file: C:\\hpc/config.yml" source="config.go:37"
time="2022-11-07T14:48:08Z" level=info msg="Running as NT AUTHORITY\\SYSTEM" source="exporter.go:336"
time="2022-11-07T14:48:08Z" level=info msg="Enabled collectors: net, os, container, service, cs, system, textfile, cpu, logical_disk" source="exporter.go:341"
time="2022-11-07T14:48:08Z" level=info msg="Starting windows_exporter (version=0.20.1_19, branch=master, revision=6ddab61fa5f53107c53fa8e34a3ac41bd68373de)" source="exporter.go:393"
time="2022-11-07T14:48:08Z" level=info msg="Build context (go=go1.19.2, user=runneradmin@fv-az277-82, date=20221025-06:13:19)" source="exporter.go:394"
time="2022-11-07T14:48:08Z" level=fatal msg="cannot start windows_exporter: listen tcp :9182: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted." source="exporter.go:399"
```

The solution for now is to use <=0.20.0 tag.

**Comment by knabben** [comment]
cc @jsturtevant

**Comment by jsturtevant** [comment]
It looks like this dependency bump is causing the issue: https://github.com/prometheus-community/windows_exporter/pull/1082, we use latest Prometheus image in our upstream perf tests and they broke on same day this was merged: https://testgrid.k8s.io/sig-windows-soak-tests#periodics-soak-tests-capz-windows-2019

**Comment by jaimegag** [comment]
Repeated tests on a testbed with k8s `v1.23.8`, containerd `v1.6.6` and using Win Server `2019`:

- Using windows-exporter image `v0.19.0`: tests were successful. Go host port 9182 to bind properly:
`time="2022-11-08T20:00:24Z" level=info msg="Starting server on :9182" source="exporter.go:416"`

- Using windows-exporter image `v0.20.0`: tests were unsuccessful. Logs:
```
time="2022-11-08T19:58:25Z" level=info msg="Loading configuration file: C:\\C\\0943f6a65c40f47776bdadc93fe2383e98e1cb28c6072d98b3400a0c36adc8b8/config.yml" source="config.go:37"
time="2022-11-08T19:58:25Z" level=info msg="Running as NT AUTHORITY\\SYSTEM" source="exporter.go:336"
time="2022-11-08T19:58:25Z" level=info msg="Enabled collectors: textfile, cs, logical_disk, system, net, container, service, cpu, os" source="exporter.go:341"
time="2022-11-08T19:58:25Z" level=info msg="Starting windows_exporter (version=0.20.1_19, branch=master, revision=6ddab61fa5f53107c53fa8e34a3ac41bd68373de)" source="exporter.go:393"
time="2022-11-08T19:58:25Z" level=info msg="Build context (go=go1.19.2, user=runneradmin@fv-az277-82, date=20221025-06:13:06)" source="exporter.go:394"
time="2022-11-08T19:58:25Z" level=fatal msg="cannot start windows_exporter: listen tcp :9182: bind: Only one usage of each socket address (protocol/network address/port) is normally permitted." source="exporter.go:399"
[07:59:02 PM 2022 jaime@jumpbox-harbor tkg-zone
```

**Comment by knabben** [comment]
This is a kingpin behavior, calling `Parse()`  on the following flag

```
 k.CommandLine.Flag(
     "web.listen-address",
     "Addresses on which to expose metrics and web interface. Repeatable for multiple addresses.",
).Default(":9182").Strings()
```

will make it be defaulted twice, `[:9182, :9182]`. The first parse call is made for the flags and the second parse the configuration content.

**Comment by roidelapluie** [comment]
How do we prevent this to happen without changing the toolkit? It looks like then the toolkit would always listen to the default address.

**Comment by knabben** [comment]
> How do we prevent this to happen without changing the toolkit? It looks like then the toolkit would always listen to the default address.

The correct fix IMO would be in the cli library, which does not seem to have been maintained for a few years, to shortest (not necessarily the most accurate) was to dedup in the web exporter, and bump here later.
Doing a sanitization of the flags in the CLI is as ugly as heading the issue responsibility to the exporter lib.

This is still open to discussion...

**Comment by roidelapluie** [comment]
It we fix the bug in the proposed way I am afraid this exporter will always listen to the default interface even another value is specified in the config file.
