### ISSUE TITLE
How can I get Volume Label

### ISSUE THREAD

**Issue by soroush-ghorbani** [prometheus-community/windows_exporter#1101]
Hello,
I need Windows disk Label.
Because in cluster SQL I have some volume that is not mounted and the volume name is Harddiskvolume1..n 
But recognize it as very difficult.
I label it but I have no information about it in metric.

**Comment by soroush-ghorbani** [comment]
Subject

**Comment by soroush-ghorbani** [comment]
windows_logical_disk_*

**Comment by breed808** [comment]
Unmounted volumes are tricky, as the underlying WMI class (Win32_PerfRawData_PerfDisk_LogicalDisk) used by the `logical_disk` collector doesn't provide any identifying information for the volume label.
