### ISSUE TITLE
Question: Does this exporter support Windows Server 2008 R2 Standard?

### ISSUE THREAD

**Issue by chavalikesavanand** [prometheus-community/windows_exporter#1103]
Does this exporter support Windows Server 2008 R2 Standard?

**Comment by breed808** [comment]
Yes, see the [project README](https://github.com/prometheus-community/windows_exporter#supported-versions) for details.

It's worth noting that with Extended Security Updates for Windows Server 2008 ending soon (2023-01-10), support for Windows Server 2008 may be dropped by the exporter in the future.
