### ISSUE TITLE
Question: How to expose "Maximum Memory" on an HyperV VM?

### ISSUE THREAD

**Issue by Kiara0107** [prometheus-community/windows_exporter#1106]
**Goal**: measure the memory usage against the maximum available memory on a VM in an HyperV cluster.
See the orange arrow in this picture:
![image](https://user-images.githubusercontent.com/120710410/208062666-b8e3ddd0-3240-40d6-a5a2-bd44a9b8f7d4.png)

I'm unable to find this metric in one of the collectors.
Does anyone know how the get this metric the easiest?

Online I found something like this:
`Get-WmiObject -namespace root\cimv2 -class Win32_PerfRawData_Counters_HyperVDynamicMemoryIntegrationService | Select-Object MaximumMemoryMBytes`

Is the best option to try with the text collector, doesn't sound ideal? Am I missing something?

**Comment by breed808** [comment]
The `hyperv` collector already uses WMI. You could submit a PR adding the `Win32_PerfRawData_Counters_HyperVDynamicMemoryIntegrationService` class to the collector. Alternatively the `textfile` collector could be used, but wouldn't be the ideal solution.
