### ISSUE TITLE
Is it possible to add an option to selectively disable some metrics?

### ISSUE THREAD

**Issue by Za7BD** [prometheus-community/windows_exporter#1107]
Hi. 
Is it possible to add an option to selectively disable some metrics? For example, on some MSSQL instances, I'm missing some metrics, causing the event log to be full of errors.
Thanks.
![image](https://user-images.githubusercontent.com/99027019/208087587-6312f849-7c98-414c-8662-50039f04ca44.png)

**Comment by breed808** [comment]
In this case you'd want to disable the `iis` collector.  If enabling/disabling individual collectors is too large a scope, you can [drop the metrics with `metric_relabel_configs` in Prometheus](https://www.robustperception.io/dropping-metrics-at-scrape-time-with-prometheus/)
