### ISSUE TITLE
Is it possible to get the per-process network io like the resource monitor does

### ISSUE THREAD

**Issue by LaurenceChau** [prometheus-community/windows_exporter#1116]
Resource monitor in windows can show process disk io/network io. I am wondering if it is possible to get the process network io/ disk io separately in stead of an aggregated process io? Thanks

![image](https://user-images.githubusercontent.com/13799490/210389990-b0661522-47d5-4686-8ae7-74c45dd73a40.png)

**Comment by breed808** [comment]
This isn't possible with the current metric source for the `process` collector. Perflib consolidates all IO to a single metric and exposes this to the collector.

If you can find an alternative metric source, we could include it into the collector.
