### ISSUE TITLE
Ignore collectors if criteria not met

### ISSUE THREAD

**Issue by DavidSkDerivco** [prometheus-community/windows_exporter#1122]
Is it possible to have collectors be ignored if the criteria is not met?
To explain:
we have multple config files for multiple server configs
example:
we have servers that have sql and no clustering and sql servers with clustering.

Question:
Without having to create multiple config files to manage, we would like to create a "master" config with all the collectors we care about. Is there a switch or command so that this can be possible?
Thanks in advance

**Comment by breed808** [comment]
Which configuration management tool are you using to manage the exporter's config file?

**Comment by DavidSkDerivco** [comment]
> Which configuration management tool are you using to manage the exporter's config file?

I use Ansible to rol out the exporter and register with consul (this includes copying a base config) through Ansible tasks and PowerShell run through Ansible Modules.
I have since worked on a PowerShell script to update the config file based off of what is installed on the server.
There is a PowerShell script that runs on a schedule to update the documents if a #vx.x (hashed out version check) is different to what is in the current file.

I do not have any other tool to manage the configs
