### ISSUE TITLE
A collector in Windows exporter to expose layer information of container images?

### ISSUE THREAD

**Issue by bingbing8** [prometheus-community/windows_exporter#1126]
We currently can find out the image set pulled to the windows nodes in AKS cluster. Some images creators want to know how many containers in AKS have one of the their layers in there layer hierarchy. for example, how many containers are built against [OpenJDK layers](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fhub.docker.com%2Flayers%2Flibrary%2Fopenjdk%2Fwindowsservercore%2Fimages%2Fsha256-c4a4900b81e6a75e27907c9f0be4330efb416450c553dcac6bcfe2f73811b890%3Fcontext%3Dexplore&data=05%7C01%7Cyawang%40microsoft.com%7Cc306dd093c0f441afe2208dadf8f4dbf%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638068103882746738%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=dsOWP96EpsY%2FokOMxzPKPs5HBlt%2FQQHf341e4ww4Gfs%3D&reserved=0) 

Is this the right place to add that support? Please let me know your recommendation?

**Comment by breed808** [comment]
What's the intended format of the metrics? Something like `windows_container_layers{layer_id="sha256:ec18bb940f84d9d1b929f4e6f176a3979b1ef3da3307bccd2f058030d68d374e"} 1`?

It's certainly possible, but we'd need a suitable metrics source for such a collector. If not, a custom script combined with the `textfile` collector may be adequate.

**Comment by bingbing8** [comment]
> What's the intended format of the metrics? Something like `windows_container_layers{layer_id="sha256:ec18bb940f84d9d1b929f4e6f176a3979b1ef3da3307bccd2f058030d68d374e"} 1`?
> 
> It's certainly possible, but we'd need a suitable metrics source for such a collector. If not, a custom script combined with the `textfile` collector may be adequate.

I will reply with more details after collect requirements
