### ISSUE TITLE
Windows Host Process Containers not being picked up in container metrics

### ISSUE THREAD

**Issue by BenHesketh21** [prometheus-community/windows_exporter#1128]
I am running the windows_exporter as a host process container in K8s and currently it is not picking its own container related metrics as well as any other host process container metrics. I am running the 0.20.0-lts2022 container image version.

**Comment by breed808** [comment]
I'm not able to test the exporter running in a k8s platform; does the documentation in https://github.com/prometheus-community/windows_exporter/tree/master/kubernetes assist at all?

**Comment by BenHesketh21** [comment]
> I'm not able to test the exporter running in a k8s platform; does the documentation in https://github.com/prometheus-community/windows_exporter/tree/master/kubernetes assist at all?

I used that daemonset when running it in my cluster and it worked for me

**Comment by jsturtevant** [comment]
Duplicate of https://github.com/prometheus-community/windows_exporter/issues/964. The main issue is outlined in https://github.com/prometheus-community/windows_exporter/issues/964#issuecomment-1095523596
