### ISSUE TITLE
Missing metrics from 'container' collector

### ISSUE THREAD

**Issue by bragi92** [prometheus-community/windows_exporter#1129]
The following [document](https://github.com/prometheus-community/windows_exporter/blob/54f86001ad296b9b2334f8e0a7af6bb0c4f95bf3/docs/collector.container.md) states that windows_container_network_receive_bytes_total is supposed to be present when one has enabled the container collector in windows exporter.

I have an AKS cluster where I deployed windows exporter as a [daemonset ](https://github.com/Azure/prometheus-collector/blob/main/internal/windowsExporterInstaller/windows-exporter-daemonset.yaml) with the container collector enabled.

I see that the following two metrics : `windows_container_network_received_bytes_total` and `windows_container_network_transmitted_bytes_total` are not present when I query for them using `http://{NODE_IP}:9182/metrics`.

I do see similar metrics present from the [net](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.net.md) collector  called  `windows_net_bytes_received_total` and `windows_net_bytes_sent_total`.

Have the former metrics been deprecated in lieu of the latter?

**Comment by breed808** [comment]
Might this be an incorrect metric name? `windows_container_network_receive_bytes_total` is in the documentation and code, but not `windows_container_network_received_bytes_total`.
It appears to be a similar situation with transmitted -> transmit.

These particular metrics haven't been modified since introduction in 8841091f9c7c9e88e6a5948a656af1bc29cfcd58.

**Comment by bragi92** [comment]
@breed808 Sorry, I made a typo when creating the issue. I have been using the proper name present in the documenation and code i.e. `windows_container_network_receive_bytes_total` and `windows_container_network_transmit_bytes_total`. and I do not see the metrics at all.

When I query `http://{NODE_IP}:9182/metrics.` I do not see any metrics that start with the format `windows_container_network_*` too. I'm not sure if this was ever working but its possible the underlying methods to fetch the container network metrics are now silently failing?

**Comment by breed808** [comment]
Are any container metrics being exposed by the collector? Is the `container` collector returning a successful result? I.E. `windows_exporter_collector_success{collector="container"} 1`

It'd be worth enabling debug logging and viewing the exporter output (if possible in a container).

**Comment by bragi92** [comment]
Yes, I have verified that the success metrics returns 1:
![image](https://user-images.githubusercontent.com/28612268/221984818-bf86d94b-4c6a-4819-927a-36b58229463d.png)

and I only see windows cpu, memory and availability metrics being returned but not network metrics.
Please see the attached list :
[windows_exporter_metrics.txt](https://github.com/prometheus-community/windows_exporter/files/10854956/windows_exporter_metrics.txt)

**Comment by jsturtevant** [comment]
I believe this is a difference between using docker and containerd.  More info in https://github.com/kubernetes/kubernetes/issues/104286

We will need to upgrade the query to use the v2 schema by going to the HNS component as done in https://github.com/kubernetes/kubernetes/pull/105744

**Comment by dineshsharmads** [comment]
@jsturtevant yes we are using containerd runtime.

**Comment by bragi92** [comment]
@jsturtevant , @breed808 Do you know if anyone will be able to help out with this upgrade?

**Comment by jsturtevant** [comment]
I am not going to have a chance to get to this for at least a couple weeks.  The code I linked above has the necessary changes if anyone wants to give this a try.

**Comment by bragi92** [comment]
Hey @jsturtevant, let me know if you have gotten a chance to look at this issue.

**Comment by jsturtevant** [comment]
@jsturtevant go for it and let me know if you have any questions

**Comment by tzifudzi** [comment]
Have opened a PR with a fix. Progress can be tracked in https://github.com/prometheus-community/windows_exporter/pull/1218
