### ISSUE TITLE
windows_time_computed_time_offset_seconds doesn't show correct difference

### ISSUE THREAD

**Issue by callMe-Root** [prometheus-community/windows_exporter#1130]
Hello, I have tried to observe if windows_time_computed_time_offset_seconds is really works as I expected (I wasn't sure if I understood the documentation correctly). I would like to catch time difference on clients with this metric. 

To test it, I've used `Set-Date -Adjust -0:10:0 -DisplayHint Time` ps command to alter time on the client, and I observed that this difference didn't show up in the metrics: 

<img width="1768" alt="resim" src="https://user-images.githubusercontent.com/68336965/216036913-25711809-130c-48fb-8638-be053baa5e7a.png">

I confirmed the time difference with `w32tm /stripchart /computer:foo`, the output is like this:

```

PS C:\Users\baruser> w32tm /stripchart /computer:foo.my.domain
Tracking foo.my.domain [x.y.z.t:123].
The current time is 1.02.2023 14:34:59.
14:34:59, d:+00.0002322s o:+600.0106644s  [                           |                          @]
14:35:01, d:+00.0003498s o:+600.0107934s  [                           |                          @]
```

Both my ntp client and server are server 2019, what am i missing? My windows_exporter version is 0.20.0

**Comment by breed808** [comment]
I've just noticed this issue was created after responding to #870. Here's the response in case it's missed:

Is Perflib returning the same metric values? You could watch with:

```powershell
while ($true) {
    Get-Counter -Counter '\Windows Time Service\Computed Time Offset'
    Start-Sleep -Seconds 1
}
```
