### ISSUE TITLE
Missing cs collector in Windows Exporter Agent 

### ISSUE THREAD

**Issue by yoda1204** [prometheus-community/windows_exporter#1131]
On 39 windows servers the Windows Exporter is not pulling the cs and service collectors. When going directly to the server with chrome ip_address:9182\metrics, there are no errors in the page the collectors are not there. The data that what be there if the collector was there, is also not there.

I install the agent with the following line:
`msiexec /i c:\downloads\windows_exporter-0.20.0-amd64.msi ENABLED_COLLECTORS=system,cpu_info,memory,logical_disk,net,service,os,cs LISTEN_PORT=9182`

Here is a piece of the metrics page for one of the servers:
```
"# HELP windows_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which windows_exporter was built.
# TYPE windows_exporter_build_info gauge
windows_exporter_build_info{branch="heads/tags/v0.20.0",goversion="go1.19.1",revision="677a7c8d67deb99b92f4f24b8c890e0a4c152b0c",version="0.20.0"} 1
# HELP windows_exporter_collector_duration_seconds windows_exporter: Duration of a collection.
# TYPE windows_exporter_collector_duration_seconds gauge
windows_exporter_collector_duration_seconds{collector="cpu_info"} 0.0144364
windows_exporter_collector_duration_seconds{collector="logical_disk"} 0.0005497
windows_exporter_collector_duration_seconds{collector="memory"} 0.0005497
windows_exporter_collector_duration_seconds{collector="net"} 0.0005497
windows_exporter_collector_duration_seconds{collector="os"} 0.0045539
windows_exporter_collector_duration_seconds{collector="system"} 0
# HELP windows_exporter_collector_success windows_exporter: Whether the collector was successful.
# TYPE windows_exporter_collector_success gauge
windows_exporter_collector_success{collector="cpu_info"} 1
windows_exporter_collector_success{collector="logical_disk"} 1
windows_exporter_collector_success{collector="memory"} 1
windows_exporter_collector_success{collector="net"} 1
windows_exporter_collector_success{collector="os"} 1
windows_exporter_collector_success{collector="system"} 1"
```

Any help appreciated

**Comment by yoda1204** [comment]
On the Windows 2019 server. I did run wbemtest application and I can see the csname on the server. So I know that the OS has the information, but windows exporter is not pulling it.

**Comment by breed808** [comment]
The absence of the `windows_exporter_collector_success{collector="cs"}` metric indicates the collector hasn't been enabled, which is interesting.

Can you enable debug logging and provide the output?
