### ISSUE TITLE
ReFs Collector 

### ISSUE THREAD

**Issue by Andrej26091997a** [prometheus-community/windows_exporter#1140]
Hello!

Please help me collect metrics from ReFS. Completed collector.

Interested in metrics such as:
Total Capacity
Free Capacity
Used Capacity
Disk Health

![image](https://user-images.githubusercontent.com/125920848/220189344-9e1ae297-347b-4779-93cb-a3cb58ffc67e.png)

**Comment by Andrej26091997a** [comment]
or at least suggest a class that can be used

**Comment by JDA88** [comment]
I am almost sure the `logical_disk` collector will give you the first 3 metrics regardless of the filesystem.
For the `Disk Health` it's subjective. What do you need exactly?
