### ISSUE TITLE
mssql and iis collector documentation

### ISSUE THREAD

**Issue by Mak0tin** [prometheus-community/windows_exporter#1143]
I've been reviewing [mssql](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.mssql.md) and [iis](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.iis.md) collector documentation and some metrics are documented as `counter` but when you check source code they appear to be a `gauge`.

Example:

IIS documentation:

Collector: `iis`
Metric name: `windows_iis_current_anonymous_users`
Type: `counter`

![image](https://user-images.githubusercontent.com/106690360/222104394-9abf47df-1d91-4ac2-9d89-93f302059c9e.png)

Code:

Collector: `iis`
Metric name: `CurrentAnonymousUsers`
Type: `gauge`

[https://github.com/prometheus-community/windows_exporter/blob/master/collector/iis.go#L900](url)

![image](https://user-images.githubusercontent.com/106690360/222105449-646cc00b-2d97-42db-897c-c5358f02d384.png)

Am I missing something? If these metrics have to be modified I can submit a pull request.

Regards

**Comment by breed808** [comment]
You're right, the metric type in the documentation should match what is set in the code.

A pull request to update the documentation would be welcome.
