### ISSUE TITLE
Metrics for .NET Data Provider for SqlServer not present

### ISSUE THREAD

**Issue by ankom2007** [prometheus-community/windows_exporter#1147]
\.NET Data Provider for SqlServer()\HardConnectsPerSecond
\.NET Data Provider for SqlServer()\HardDisconnectsPerSecond
\.NET Data Provider for SqlServer()\SoftConnectsPerSecond
\.NET Data Provider for SqlServer()\SoftDisconnectsPerSecond
\.NET Data Provider for SqlServer()\NumberOfNonPooledConnections
\.NET Data Provider for SqlServer()\NumberOfPooledConnections
\.NET Data Provider for SqlServer()\NumberOfActiveConnectionPoolGroups
\.NET Data Provider for SqlServer()\NumberOfInactiveConnectionPoolGroups
\.NET Data Provider for SqlServer()\NumberOfActiveConnectionPools
\.NET Data Provider for SqlServer()\NumberOfInactiveConnectionPools
\.NET Data Provider for SqlServer()\NumberOfActiveConnections
\.NET Data Provider for SqlServer()\NumberOfFreeConnections
\.NET Data Provider for SqlServer()\NumberOfStasisConnections
\.NET Data Provider for SqlServer()\NumberOfReclaimedConnections

**Comment by breed808** [comment]
Could you provide more context on this request? Are you asking for these metrics to be added as a new collector, are they missing from an existing collector, or are you experiencing an issue scraping already-configured metrics?

**Comment by ankom2007** [comment]
@breed808 Yes, I am hoping we can have these metrics to be added as a new collector
