### ISSUE TITLE
Create Grafana Community Dashboard

### ISSUE THREAD

**Issue by mabed-fr** [prometheus-community/windows_exporter#1149]
Hello,

Do you have/want to create community dashboard ?

Since 2021 no update https://grafana.com/grafana/dashboards/14694-windows-exporter-dashboard/

Mathieu

**Comment by breed808** [comment]
Hi Matthieu, we don't currently provide a Grafana dashboard for the exporter. The scope of metrics collected by the exporter is rather large, but a dashboard for basic metrics (CPU, memory, disk, network, etc) could be supported.
PRs for this would be welcome.

**Comment by v-zhuravlev** [comment]
If someone is familiar with jsonnet's monitoring-mixins, you can find quite detailed set of dashboards and alerts for windows here:
https://github.com/grafana/jsonnet-libs/tree/windows-lib/windows-observ-lib
