### ISSUE TITLE
Should apply file lock when the textfile collector try to access file?

### ISSUE THREAD

**Issue by LaurenceChau** [prometheus-community/windows_exporter#1153]
When the textfile collector was accessing a prom file, there was often an error `unexpected end of input stream`. I am thinking it may be due to the process being accessed by another process at the same time(another process was updating the file), the file could be overwritten by another process and result in an error. 

![image](https://user-images.githubusercontent.com/13799490/224758432-653ec29d-4d73-4dbe-8b8f-bcb10a158482.png)

https://pkg.go.dev/github.com/zbiljic/go-filelock

**Comment by breed808** [comment]
Is the other process renaming a file, or updating a .prom file in-place? Renames are generally atomic, whilst copies or updates often aren't.

I'd like to confirm that renaming is in use before introducing another dependency to the exporter.

**Comment by LaurenceChau** [comment]
> Yes, there is another job updating the .prom file. Do you mean to write the new metrics to another file instead of updating the .prom file in place?

**Comment by breed808** [comment]
> Do you mean to write the new metrics to another file instead of updating the .prom file in place?

Yes, have the external process write to a different file, then rename it on completion to have a .prom extension.

**Comment by JDA88** [comment]
> > Do you mean to write the new metrics to another file instead of updating the .prom file in place?
> 
> Yes, have the external process write to a different file, then rename it on completion to have a .prom extension.

It's very dependent on the process you use to create the file. The 2 best options we tested with success so far are:

- Create the file in memory then flush it to the disk erasing the previous file
- Create the file in a temporary location, then move and erase the previous file

You have to make it so the time between the N and N+1 file is minimal
