### ISSUE TITLE
Collector whitelist

### ISSUE THREAD

**Issue by DancoPanco** [prometheus-community/windows_exporter#1155]
Hi everybody. Im new to this kind of staf and im currently working on my final thesis, in which i need to be able to visualize windows processes in grafana.  Everything is currently working fine, but i cant see specific processes in grafana. I know i have to add white list for processes collector, but me knowleadge ends here. 
Do I need to create a config.yml file ? if I create it, how do I make the exporter work from this file ?

As i said, im newbie so have a patience with me please 🙏 😄

**Comment by breed808** [comment]
You can provide parameters to the exporter either with command line flags, or with a configuration file. See https://github.com/prometheus-community/windows_exporter#using-a-configuration-file for details on using a config file.

The `process` collector exposes several flags, allowing the user to filter processes (by default the collector will return metrics for _every_ process). See [the collector documentation](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.process.md) for more info. You'll need to ensure the `process` collector is enabled as it's not enabled by default.
