### ISSUE TITLE
Export local disk size to invalid value.

### ISSUE THREAD

**Issue by Arinashin3** [prometheus-community/windows_exporter#1156]
Hello, this issue occurred in wmi_exporter-0.7.0-386.exe.
The data that wmi exporter collects is different from the actual performance data.
Does anyone know the solution?

wmi_exporter-0.7.0-386.exe
version : 0.7.0
os : windows 2008  |  32 bits

'wmi_logical_disk_size_bytes'
Actual Drive 'C:' Size : 50GB
Collected as wmi exporter : 15013699911680

'wmi_logical_disk_free_bytes' work fine.

**Comment by JDA88** [comment]
This is a vey old version, would you mind reproduce the issue with the latest release?
