### ISSUE TITLE
[question] collectors.enabled working not as expected

### ISSUE THREAD

**Issue by Turum** [prometheus-community/windows_exporter#1159]
Hi team,
Just trying to start the exporter by command `windows_exporter-0.21.0-386.exe --config.file="C:\prom_exporter\config.yml" --collectors.enabled textfile` and still see some go_memstat*  and windows_exporter_collector_* metrics, self metrics in another words. Can I disable it somehow? In node exporter there is parameter --web.disable_exporter-metrics. Will it work here?
The second question is can I collect metrics from multiple files or only one? By default I received error in the output.
Thanks.

**Comment by breed808** [comment]
Sure, that seems a simple change for the flag.

> The second question is can I collect metrics from multiple files or only one?

The `textfile` collector will scrape metrics from any files ending in `.prom` in the [collection directory](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.textfile.md#flags)

**Comment by breed808** [comment]
The error you're receiving is for detected differences in a metric's HELP text. For the ingested .prom files, is the help text for the `login_speed` metric consistent?
