### ISSUE TITLE
Install/update the windows_exporter on multiple Windows machines remotely?

### ISSUE THREAD

**Issue by simone80an** [prometheus-community/windows_exporter#1172]
Hi, i have multiple Windows Servers with the agent installed, it is possible to update it if i want to install a new release without entering on every single machine and do it manually?

I have found a PS script https://kimconnect.com/powershell-install-windows-exporter/ (i have tried the second script) but currently seems only install the agent on machines where there isn't installed. If it's installed it tells you that is already installed but not perform the uninstallation of the current version of the service / program and installation of the new version.

Thanks in advice.

**Comment by breed808** [comment]
It's possible and encouraged to perform updates in an automated manner. You'll want to look into configuration management tools such as Ansible, Puppet, SCCM, etc. I believe group policy can also be used to install & update the exporter.
