### ISSUE TITLE
Collection timed out, still waiting for 

### ISSUE THREAD

**Issue by xinjie-sunshine** [prometheus-community/windows_exporter#1175]
Error occurred, Collection timed out, still waiting for, how to handle it

**Comment by breed808** [comment]
Which collector is reporting this failure? Is the issue occurring on multiple hosts, or just one?

Without additional context it is not possible to provide support.

**Comment by xinjie-sunshine** [comment]
multiple hosts， The specific error message is as follows:
time ="2023-04-04T09:38:41 +08:00" level=warning msg="Connection timed out, still waiting for [cs OS service]" source=exporter.go:202"

**Comment by breed808** [comment]
Are there any additional log entries for those failing collectors? If not, try enabling debug logging.

What version of the exporter are you using?

**Comment by xinjie-sunshine** [comment]
Thank you, I have found the reason, because the server does not support some indicators, resulting in an error. After updating to the latest version, it will be solved.
