### ISSUE TITLE
time-taken field in IIS

### ISSUE THREAD

**Issue by RohanAdhith** [prometheus-community/windows_exporter#1190]
Do we have any metrics on the iis collector that calculates the time-taken field?

"The time-taken field measures the length of time that it takes for a request to be processed."

**Reference:**
https://learn.microsoft.com/en-GB/troubleshoot/developer/webapps/iis/health-diagnostic-performance/time-taken-field-http-log

**Comment by breed808** [comment]
There's no request duration metrics exposed by the `iis` collector; from memory Perflib doesn't expose request duration counters, and we don't scrape log files for metrics.

If you can find a suitable metric source for IIS request durations (Perflib, WMI, etc), I'd be open to integrating it into the collector.
