### ISSUE TITLE
textfile: the same metric occurring with different labels in two different prom files trigger error due to inconsistent help message in processFile

### ISSUE THREAD

**Issue by cbryant42** [prometheus-community/windows_exporter#1191]
There's an issue that was fixed in node-exporter, but I seem to be running in to with Windows Exporter. Basically, I have a script writing to 2 different files with the same metric names but different label sets. The exporter is throwing an error because the help message reads 2 different file names. Has this been fixed and I am just unaware of a configuration flag for this, or is this something that needs to be addressed here as well?

https://github.com/prometheus/node_exporter/issues/1885
https://github.com/prometheus/node_exporter/pull/2475

**Comment by JDA88** [comment]
Can you please provide the 2 exact files that trigger the error (or a subset)? And also the exact error message?
What version of `windows exporter` are you using?

I currently have multiple servers where multiple files are generated (with same metrics but different labels and I have no issues)
`# HELP` and `# TYPE` are present and exactly the same on all files

**Comment by jezhiggins** [comment]
I've have the same issue

If I have one file 
```test.prom
fruit{type="lemon"} 15
fruit{type="apple"} 12
```
everything runs as it should. 

However, if those two metrics are in different files 
```test.prom
fruit{type="lemon"} 15
```
```breaks.prom
fruit{type="apple"} 12
```
then all then no metrics are produced - not just from text files, we get nothing. 

The error message on `/metrics` is 

```
An error has occurred while serving metrics:

* collected metric fruit label:<name:"type" value:"lemon" > untyped:<value:15 >  has help "Metric read from C:\\Program Files\\windows_exporter\\textfile_inputs\\test.prom" but should have "Metric read from C:\\Program Files\\windows_exporter\\textfile_inputs\\breaks.prom"
```

If we have more labelled metrics in other text files, we get an extra error for each additional file. 

This is using version 0.22.0, but I've seen the same behaviour (without having identified the error) in earlier versions.

**Comment by jezhiggins** [comment]
To be clear, having reread https://github.com/JDA88's comment, these are text files on the same machine, being collected by a single instance of windows_exporter. Aggregating labelled metrics across machines works fine, aggregated labelled metrics with the same exporter fails.

**Comment by jezhiggins** [comment]
I think the fix in https://github.com/prometheus/node_exporter/pull/2475 will work pretty much as is. I will try and raise a PR, but should caveat by noting I'm not a regular user of go and I'm in the middle of moving house. 

It's clear the node_exporter and windows_exporter textfile collectors started from the same place, but have diverged over time. There's some minor incident differences (`!present` vs `present == false`) which it would nice to but aren't significant. However, there's a whole load of error checking, particularly around duplicate detection that windows_exporter is doing that perhaps should be carried back into node_exporter.

**Comment by JDA88** [comment]
From my experience if you two files look like this it will work. `# HELP` and `# TYPE` **must** be on every metrics in every files

```
# HELP fruit Fruit inventory
# TYPE fruit gauge
fruit{type="lemon"} 15
```

```
# HELP fruit Fruit inventory
# TYPE fruit gauge
fruit{type="apple"} 12
```
