### ISSUE TITLE
scheduled_task collector doesn't really return last run result

### ISSUE THREAD

**Issue by pjwj** [prometheus-community/windows_exporter#1198]
In docs for scheduled_task collector following metric is mentioned:

<html>
<body>

windows_scheduled_task_last_result | The result that was returned the last time the registered task was run | gauge | task
-- | -- | -- | --

</body>
</html>

However, I observed, that it doesn't actually show the last run result code (which are for exampled documented here: https://en.wikipedia.org/wiki/Windows_Task_Scheduler). 
From what I can see in source code (https://github.com/prometheus-community/windows_exporter/blob/master/collector/scheduled_task.go#L187) the actual last run result code is compared to "0x0". The results of this comparison are two cases:
- last run result code **is equal** to "0x0": in this case the collector shows/returns a "1" for the metric
- last run result code **is not equal** to "0x0": in this case the collector shows/returns a "0" for the metric

My opinion on this is:
- either the **documentation** for scheduled_task collector is wrong/misleading since metric "windows_scheduled_task_last_result" doesn't actually show "The result that was returned the last time the registered task was run", but 1 for successful and 0 for failure
- or the **implementation** of the collector is wrong, since it doesn't show what is documented.

**Comment by breed808** [comment]
I agree with your findings here; the metric in question is informing the user of a failure or success from the last run of a scheduled task. However, the metric name and description do not make this clear to the user, instead implying the metric result is the return code of the last scheduled task run.

I can see two solutions to this, which you've identified.

A: Display the actual return code as the metric value
B: Change the metric name and description to clarify that only a success/failure is displayed. 

E.G.
```
Name: windows_scheduled_task_last_result_**success**
Description: Returns 1 if the last run of the registered task was successful (return code of 0x0).
```

Option B is simpler to implement, but if anyone using the collector desires the return code as the metric value, that can be done.
