### ISSUE TITLE
Empty MSMQ private queues disappearing from metrics

### ISSUE THREAD

**Issue by frankhetterich** [prometheus-community/windows_exporter#1210]
Whe´re using the MSMQ collector of windows_exporter and noticed that empty MSMQ private queues are randomly disappearing (and coming back) from the Metrics. The Queues where not deleted, they are still existing . 
What i can point out is that this happens only to queues that are mostly empty or empty for a longer time. 

It seems that this issue is there for a longer time because the gaps in the metrics are visible since at least 6 month ago. 

The problem exists on several servers all with the same OS Windows Server 2016. 

Whe´re using currently Windows Exporter Version 0.22.0 , but issue exists also in v.20.0

**Comment by breed808** [comment]
I'm not too familiar with MSMQ; do the underlying metrics also disappear at these times?

Querying the `Win32_PerfRawData_MSMQ_MSMQQueue` WMI class will confirm if these metrics are no longer available to the `msmq` collector.
