### ISSUE TITLE
AKS Windows Pod no metrics

### ISSUE THREAD

**Issue by yuangeqingian** [prometheus-community/windows_exporter#1213]
AKS 1.24.9
Nodepool Windows OS: server 2019
Containerd on Windows Version:  1.6.14+azure
I have already deployed windows exporter as daemonset in AKS and I have got the Windows Node Level metrics.
![image](https://github.com/prometheus-community/windows_exporter/assets/9658083/a28ef5ff-027d-4ab4-b948-4dd5b2aad645)

However, in  the POD level prometheus stack, my windows pod don't have any metrics.
In folder 
![image](https://github.com/prometheus-community/windows_exporter/assets/9658083/f6ae1a3c-c36f-4760-9473-1aff4cb1c535)

Windows POD only showed IP, running on node name, and the container resource request and limits.

![image](https://github.com/prometheus-community/windows_exporter/assets/9658083/ed1b4100-aaa1-4615-8de0-d900243f68b0)

Anything I need to modify or change to get windows pod metrics?

**Comment by breed808** [comment]
This may be due to the `windows_exporter` pod running as a host process. See #1252
