### ISSUE TITLE
how to use curl to fetch container collector network related metrics?

### ISSUE THREAD

**Issue by snowflying** [prometheus-community/windows_exporter#1217]
I use below command to fetch windows pod's network related metrics data after I deploy the windows_exporter. but no data presented. May you correct me if the command is wrong?.

utils@bashutil:~$ curl -G --data-urlencode "query=windows_container_network_transmit_bytes_total{container=\"guidgenerator\", pod=\"guidgenerator-5cd59bbc75-qmcjx\", namespace=\"default\"}" http://10.0.70.52:9090/api/v1/query

{"status":"success","data":{"resultType":"vector","result":[]}}

windows-exporter-config configmap:

apiVersion: v1
data:
  config.yml: |
    collectors:
      enabled: '[defaults],container'
    collector:
      service:
        services-where: "Name='containerd' or Name='kubelet'"
kind: ConfigMap
metadata:
  annotations:
  creationTimestamp: "2023-06-01T06:15:57Z"
  labels:
    app: windows-exporter
  name: windows-exporter-config
  namespace: monitoring
  resourceVersion: "171546981"
  uid: 455f5369-dce7-4b87-96f0-7385557a911b

**Comment by breed808** [comment]
It may be worth accessing the Prometheus web interface and ensuring the windows_exporter target(s) are being successfully scraped. That interface can also be used to submit queries in an interactive manner.

You can also `curl` the windows_exporter endpoint directly to view all metrics exposed by the exporter.
