### ISSUE TITLE
Switch to the official host process containers base image

### ISSUE THREAD

**Issue by jkroepke** [prometheus-community/windows_exporter#1221]
See: https://github.com/microsoft/windows-host-process-containers-base-image#overview

To reduce the container size of windows_exporter, consider to use this image

`mcr.microsoft.com/oss/kubernetes/windows-host-process-containers-base-image:v1.0.0` instead the nanoserver once.

**Comment by profnandaa** [comment]
/cc. @jsturtevant

**Comment by breed808** [comment]
I'm happy to take a pull request for this change, but I have no way of testing the new image. Would someone be able to test this?

**Comment by jkroepke** [comment]
If you can provide the build image, I able to test it.

**Comment by breed808** [comment]
You'd have to build it yourself, see the [Dockerfile](https://github.com/prometheus-community/windows_exporter/blob/master/Dockerfile) in the project repository. You can change the image there and test both the image build process and running of the built image.

**Comment by jkroepke** [comment]
I didn't have any Windows environment with Docker. The AKS nodes are using containerd. Maybe its possible to build intermediate images through Github Actions

**Comment by breed808** [comment]
> I didn't have any Windows environment with Docker

Same here :laughing:. I'll have a look at Github Actions for this, I may be able to build an intermediate image in my forked version of the repo sometime this week

**Comment by PixelRobots** [comment]
you could use the Azure container registry to build the image.

az acr build --image sample/hello-world:v1 \
  --registry myContainerRegistry008 \
  --file Dockerfile . 

https://learn.microsoft.com/en-us/azure/container-registry/container-registry-quickstart-task-cli

**Comment by jkroepke** [comment]
You can also build windows container on linux, using cross os builds

```Dockerfile
ARG BASE=mcr.microsoft.com/oss/kubernetes/windows-host-process-containers-base-image:v1.0.0

FROM --platform=$BUILDPLATFORM golang:1.21 as builder
ARG TARGETARCH
ARG TARGETOS

# Get dependencies
WORKDIR /w
COPY go.mod go.sum ./
RUN go mod download
RUN go install github.com/prometheus/promu@latest

# Build windows_exporter
COPY . ./
RUN GOOS=$TARGETOS GOARCH=$TARGETARCH make windows_exporter.exe

FROM $BASE
COPY --from=builder /w/windows_exporter.exe /windows_exporter.exe
ENTRYPOINT ["windows_exporter.exe"]
```

Then 

```bash
docker buildx build -t a --platform=windows/amd64 .
```

**Comment by jkroepke** [comment]
Unstale
