### ISSUE TITLE
Allow multiple instances of the windows_exporter when using a library. 

### ISSUE THREAD

**Issue by mattdurham** [prometheus-community/windows_exporter#1226]
Allow the windows_exporter to be used as a library and allow multiple instances of the exporter running at time. The Grafana Agent embeds the windows_exporter and for the longest time we used it as a singleton but now needing the ability to run it multiple times.

**Comment by breed808** [comment]
I believe this has been resolved from @jkroepke's recent work on the exporter. Let us know if this is still an issue.
