### ISSUE TITLE
How to Get a Virtual Machine Not Started on Hyper-V

### ISSUE THREAD

**Issue by chinaxushi** [prometheus-community/windows_exporter#1228]
I have tested that the exporter does not have the output of this virtual machine when the virtual machine is not started.

**Comment by breed808** [comment]
Could you provide more information on the issue you're experiencing? The `hyperv` collector relies on WMI classes for metrics; if you can provide the missing metric(s) I can provide you with the WMI class(es) to investigate.

**Comment by chinaxushi** [comment]
I have a pretty good idea of which WMI class to use, it's just that Windows exporter isn't fetching data through this class right now.
root\virtualization\v2     MSVM_ComputerSystem  
Here you can get general information about all virtual machines on Hyper, including those that are not powered on
