### ISSUE TITLE
AKS Windows exporter container network collector error

### ISSUE THREAD

**Issue by yuangeqingian** [prometheus-community/windows_exporter#1229]
AKS Version: 1.24.9,  Windows Node version: AKSWindows-2019-containerd-17763.4010.230223

Windows Exporter POD log: 
time="2023-06-14T04:50:26Z" level=error msg="Error reading textfile collector directory \"C:\\\\C\\\\fbd8c125a1661a2d5a2267d80c5dfd826e33ac51da8da80d17698d812dd287f6\\\\textfile_inputs\": open C:\\C\\fbd8c125a1661a2d5a2267d80c5dfd826e33ac51da8da80d17698d812dd287f6\\textfile_inputs: The system cannot find the file specified." source="textfile.go:249"
time="2023-06-14T04:50:26Z" level=info msg="No Network Stats for container: 07576725a913dd52a498ec805558999e06bb59528cafe5225b55a05041d7a5e8" source="container.go:262"
time="2023-06-14T04:50:26Z" level=info msg="No Network Stats for container: 0d5a5baa0196a3df26a34eb15ba02a0b8cf1a6d8f21a6ea856bc6c42f8e0faa9" source="container.go:262

![image](https://github.com/prometheus-community/windows_exporter/assets/9658083/e918e18e-4147-4d74-a001-d7a389926d20)

**Comment by yuangeqingian** [comment]
Collecting Windows container metrics only include: 
cpu, memory, count and available , no network, no storage metrics

**Comment by breed808** [comment]
Is this issue still present in the latest version of the exporter?

**Comment by shbali** [comment]
I have the same  error related to reading textfile in the latest version of windows exporter **0.24** 
` level=error collector=textfile msg="Error reading textfile collector directory \"C:\\\\C\\\\016526190029d51c7ec75413da860811f2ebffb913a51d72ce78021afe93b661\\\\textfile_inputs\"" err="open C:\\C\\016526190029d51c7ec75413da860811f2ebffb913a51d72ce78021afe93b661\\textfile_inputs: The system cannot find the file specified."`

**Comment by breed808** [comment]
@shbali what flags and/or configuration for the `textfile` collector is being provided to the exporter here?

**Comment by jlcrow** [comment]
@breed808 I'm having the same issue on AKS.
K8s: v1.26.3
Exporter: v0.23.1
`apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: windows-exporter
  name: windows-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: windows-exporter
  template:
    metadata:
      labels:
        app: windows-exporter
    spec:
      tolerations:
      - key: app
        operator: Equal
        value: twmwin
        effect: NoSchedule
      securityContext:
        windowsOptions:
          hostProcess: true
          runAsUserName: "NT AUTHORITY\\system"
      hostNetwork: true
      initContainers:
        - name: configure-firewall
          image: mcr.microsoft.com/windows/nanoserver:1809
          command: ["powershell"]
          args: ["New-NetFirewallRule", "-DisplayName", "'windows-exporter'", "-Direction", "inbound", "-Profile", "Any", "-Action", "Allow", "-LocalPort", "9182", "-Protocol", "TCP"]
      containers:
      - args: 
        - --config.file=%CONTAINER_SANDBOX_MOUNT_POINT%/config.yml
        name: windows-exporter
        image: ghcr.io/prometheus-community/windows-exporter:0.23.1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9182
          hostPort: 9182
          name: http
        volumeMounts:
        - name:  windows-exporter-config
          mountPath: /config.yml
          subPath: config.yml
      nodeSelector:
        kubernetes.io/os: windows
      volumes:
      - name: windows-exporter-config
        configMap:
          name: windows-exporter-config
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: windows-exporter-config
  namespace: monitoring
  labels:
    app: windows-exporter
data:
  config.yml: |
    collectors:
      enabled: '[defaults],container'
    collector:
      service:
        services-where: "Name='containerd' or Name='kubelet'"
`
