### ISSUE TITLE
No CPU/Memory limit in windows-exporter-daemonset.yaml

### ISSUE THREAD

**Issue by AbelHu** [prometheus-community/windows_exporter#1234]
There is no CPU/Memory limit in windows-exporter-daemonset.yaml so it may over-provision the Windows nodes

https://kubernetes.io/docs/concepts/configuration/windows-resource-management/#resource-reservation
```
Caution:
As you deploy workloads, set resource memory and CPU limits on containers. This also subtracts from NodeAllocatable and helps the cluster-wide scheduler in determining which pods to place on which nodes.

Scheduling pods without limits may over-provision the Windows nodes and in extreme cases can cause the nodes to become unhealthy.
```

**Comment by breed808** [comment]
The daemonset definition in this repository is more an example than a working manifest suitable for most environments. Quoting Helm:
> We usually recommend not to specify default resources and to leave this as a conscious choice for the user. This also increases chances charts run on environments with little resources, such as Minikube.

I'd recommend looking into the [community-provided Helm chart for the exporter](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-windows-exporter).
