### ISSUE TITLE
Error: Connection refused

### ISSUE THREAD

**Issue by tringler** [prometheus-community/windows_exporter#1235]
Hello,

I deployed the daemonset from the documentation on an AKS (v1.25.6) and get `connection refused` if I try to access `podip:9182/metrics` by portforwarding. From the pod itself it is possible to fetch the metrics.

The mentioned firewall rule is applied and I even tried to disable the firewall completely. No luck.
I also tried the 1809 and the 2022ltsc image. 

I'm very thankful for every idea how to get rid that issue.

Thanks in Advance!

**Comment by breed808** [comment]
From where are you trying to access `podip:9182/metrics`? I've not used AKS myself, but [the documentation indicates NAT is in play here](https://learn.microsoft.com/en-us/azure/aks/configure-kubenet):

> Pods receive an IP address from a logically different address space to the Azure virtual network subnet of the nodes. Network address translation (NAT) is then configured so the pods can reach resources on the Azure virtual network. The source IP address of the traffic is NAT'd to the node's primary IP address.

As there's no k8s Service defined the `podip:9182/metrics` endpoint would only be accessible from within the cluster, and with `kubectl port-forward` as you discovered.

**Comment by tringler** [comment]
Hello @breed808,

maybe I described it poorly. With `by portforwarding` I meant it is not reachable by `kubectl port-forward <podname>` while it is possible to `curl 127.0.0.1:9182/metrics` inside the pod by `kubectl exec -it <podname>`

**Comment by breed808** [comment]
Could you provide the full commands used for the port forward and connection? E.G.

```bash
kubectl --namespace monitoring port-forward pod/$podname 9182:9182
curl http://localhost:9182/metrics
```

**Comment by tringler** [comment]
Working inside Pod:
`kubectl exec -it windows-exporter-f8t8r -n monitoring -- powershell.exe`

```
PS C:\C\a1fbd37caeffa4595f1b16b70ac7d527db3674575f8bea6a990f1de4f9487e6d> Invoke-WebRequest -Uri 127.0.0.1:9182/metrics -UseBasicParsing


StatusCode        : 200
StatusDescription : OK
Content           : # HELP go_gc_duration_seconds A summary of the pause        
                    duration of garbage collection cycles.
                    # TYPE go_gc_duration_seconds summary
                    go_gc_duration_seconds{quantile="0"} 0
                    go_gc_duration_seconds{quantile...
RawContent        : HTTP/1.1 200 OK
                    Transfer-Encoding: chunked
                    Content-Type: text/plain; version=0.0.4; charset=utf-8      
                    Date: Mon, 17 Jul 2023 22:06:50 GMT

                    # HELP go_gc_duration_seconds A summary of the pause        
                    duratio...
Forms             :
Headers           : {[Transfer-Encoding, chunked], [Content-Type, text/plain;   
                    version=0.0.4; charset=utf-8], [Date, Mon, 17 Jul 2023      
                    22:06:50 GMT]}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        :
RawContentLength  : 46502
```

Not working outside pod:
`kubectl port-forward windows-exporter-f8t8r 9182:9182 -n monitoring`

```
curl 127.0.0.1:9182
curl: (52) Empty reply from server
```

On the forwarding console the forwarding dies with:

```
Forwarding from 127.0.0.1:9182 -> 9182
Forwarding from [::1]:9182 -> 9182
Handling connection for 9182
E0717 22:11:10.435277  125340 portforward.go:409] an error occurred forwarding 9182 -> 9182: error forwarding port 9182 to pod b0474733069da3268096c41a51b485cbb8f82c6fa1c0e459a50a02bd18806144, uid : failed to execute port forward in sandbox: : failed to exec in sandbox: failed to create exec "4fedd582de33ecc3f8335b484163ddd4350bb4d3d3e5d88d9ba03453fd8c2f5a": WCOW Pod task should never issue exec: not implemented
error: lost connection to pod
```

**Comment by breed808** [comment]
What k8s version is the cluster running, and what is the version of the `kubectl` tool you're using? Searching indicates the E0717 error might be due to a version mismatch, but I can't find anything defnitive.

Either way, this isn't an issue with the exporter: the port-forward is failing.

**Comment by tringler** [comment]
Thanks for the hint, but same behaviour if I'm streamline the client/server version:

```
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"ff2c119726cc1f8926fb0585c74b25921e866a28", GitTreeState:"clean", BuildDate:"2023-01-18T19:22:09Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.6", GitCommit:"94c50547e633f1db5d4c56b2b305670e14987d59", GitTreeState:"clean", BuildDate:"2023-06-12T18:46:30Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by breed808** [comment]
I assume pod to pod network connectivity is functioning correctly? Besides that, it'd be worth taking a packet capture to see if the windows_exporter container is receiving the request, and which address is sending the TCP RST to Prometheus when it attempts a scrape.

**Comment by breed808** [comment]
One thing I've just noticed is that `hostNetwork` is set to `true` in the daemonset, so it'd be worth attempting to connect to one of the node IPs on 9182/TCP.

**Comment by tringler** [comment]
Indeed :-o - That's the solution! Thanks a lot!
