### ISSUE TITLE
Msi install EXTRA_FLAGS Syntax Process.include not working

### ISSUE THREAD

**Issue by kocy33** [prometheus-community/windows_exporter#1237]
Hello,

I am trying to monitor a process on multiple windows machines.
I try to use the process collector for that but i am unable to find the correct syntax to pass the EXTRA_FLAGS.

It either just fails and says the syntax is incorrect or it gets stuck during install.

I tried multiple variants already and also ' quotes to no avail.
My best guess was:

msiexec /i windows_exporter-0.22.0-amd64.msi ENABLED_COLLECTORS="ad,adfs,cache,cpu,cpu_info,cs,container,dfsr,dhcp,dns,fsrmquota,iis,logical_disk,logon,memory,msmq,mssql,netframework_clrexceptions,netframework_clrinterop,netframework_clrjit,netframework_clrloading,netframework_clrlocksandthreads,netframework_clrmemory,netframework_clrremoting,netframework_clrsecurity,net,os,process,remote_fx,service,system,tcp,time,vmware" EXTRA_FLAGS="--collector.process.include="firefox.*"" TEXTFILE_DIR="C:\custom_metrics" LISTEN_PORT="9182"

I found --collector.process.include="firefox.*" on the windows_exporter/docs/collector.process.md page.
I also tried to move the "EXTRA_FLAGS" to the end. 

I already searched the issues here.
I am sorry if I didnt find the correct answer by someone else or am missing something.

Thanks in advance.

**Comment by breed808** [comment]
The `--collector.process.include` flag is in `master` but hasn't yet made it to a stable release. Have a look at the [v0.22.0 documentation for the process collector](https://github.com/prometheus-community/windows_exporter/blob/v0.22.0/docs/collector.process.md).

**Comment by breed808** [comment]
See #679 for context on the change. Sorry you had to waste that time due to the differing documentation versions.
