### ISSUE TITLE
Integrate perflib_exporter into windows_exporter

### ISSUE THREAD

**Issue by jkroepke** [prometheus-community/windows_exporter#1240]
Hi,

writing this issue at this time seems like [perflib_exporter](https://github.com/leoluk/perflib_exporter) has some lacks of maintenance. It includes the maintenance of outdated dependencies and other bugs seen as issue or PR.

The author of the library confirms that he is not longer using windows in production.
https://github.com/leoluk/perflib_exporter/issues/25

I would like to ask if it make sense to merge the perflib_exporter into the windows_exporter to reduce the amount of unmaintained libraries. Since windows_exporter mostly depends on WMI metrics, it could be benefit of this.

**Comment by jkroepke** [comment]
@breed808 also let me know, if you need some assistance for maintenance. I'm already a member of the prometheus-community group.

**Comment by breed808** [comment]
I open to assisting in the maintenance of perflib_exporter. Dependency management with Dependabot has been simple since it was introduced for windows_exporter.

Bugs would be harder for me to assist with; I don't currently use either exporter in a production/business environment

Do you envision perflib_exporter being added into the windows_exporter project as a separate Go package, or kept in a separate project?

**Comment by jkroepke** [comment]
> Bugs would be harder for me to assist with; I don't currently use either exporter in a production/business environment

At least, we plan to use windows_exporter as part of [Grafana Agent](https://github.com/grafana/agent) for VM monitoring + Kubernetes monitoring (windows nodes).

I also recently add a [helm chart](https://github.com/prometheus-community/helm-charts/pull/3476) for windows_exporter on the prometheus-community/helm-charts repository.

I would see the perflib_exporter as part of the windows_exporter project as a separate Go package. 
Alternative we cloud craft a new go package with code fragments from perflib_exporter to create a lightweight version of perflib_exporter that may only works with the windows_exporter and optimized it. I would personally not support use-cases outside windows_exporter for the perflib_exporter package.

**Comment by breed808** [comment]
Sound good. I believe the MIT license applied to the Perflib exporter would allow us to copy the code into the windows_exporter project, so long as we include the [copyright and permission notice](https://github.com/leoluk/perflib_exporter/blob/master/LICENSE).

I'd like to avoid a situation where both the perflib_exporter and the windows_exporter projects maintain separate copies of the perflib_exporter code.
@leoluk what are your thoughts on the potential migration discussed here?

**Comment by jkroepke** [comment]
I open #1241 as example where I copy only a essential subset of the code which is required for windows_export. I also remove the HelpText queries, since they are not manadory for windows_exporter.
