### ISSUE TITLE
Exchange_prometheus

### ISSUE THREAD

**Issue by Zakariaa222** [prometheus-community/windows_exporter#1244]
Hi sir,
how I can collect exchange metrics, and where I can embed the code you created here please.

**Comment by breed808** [comment]
You'll want to enable the Exchange collector. See the [collector documentation](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.exchange.md) and the [main README](https://github.com/prometheus-community/windows_exporter#flags) for details on enabling collectors:
