### ISSUE TITLE
windows_exporter.exe cat: VERSION: No such file or directory

### ISSUE THREAD

**Issue by gerijani** [prometheus-community/windows_exporter#1247]
Running [Kubernetes container image build ](https://github.com/prometheus-community/windows_exporter/blob/master/kubernetes/kubernetes.md)under WSL-Ubuntu-22.04 getting the below error.

cat: VERSION: No such file or directory
/mnt/c/docker build --build-arg=BASE=mcr.microsoft.com/windows/nanoserver:1809 -f Dockerfile -t myrepo/windows-exporter:-1809 .
invalid argument "myrepo/windows-exporter:-1809" for "-t, --tag" flag: invalid reference format.

$(shell cat VERSION) does not yield any result at variable definition VERSION as the file is missing.

Node is a Windows 10 22H2 with WSL-Ubuntu-22.04. Any thoughts?

**Comment by breed808** [comment]
The `VERSION` file isn't present in the repository, it's being [populated during the release pipeline](https://github.com/prometheus-community/windows_exporter/blob/89cb5439b8aa1b8f147ff9d36ee21692c6f31963/.github/workflows/release.yml#L46) which isn't mentioned in the documentation you linked.

There's a few options to get the build working:
* Set the `VERSION` environment variable to a value of your choosing
* Create a `VERSION` file and set the contents to a value of your choosing

You could use the existing container images built by our release pipelines: https://github.com/prometheus-community/windows_exporter/pkgs/container/windows-exporter

**Comment by gerijani** [comment]
THX!
