### ISSUE TITLE
windows_logical_disk_idle_seconds_total idles more time than possible

### ISSUE THREAD

**Issue by izone2207** [prometheus-community/windows_exporter#1249]
When I rate or irate windows_logical_disk_idle_seconds_total, value goes over 1. 
I tried to use different intervals, still value overcomes 1.
![image](https://github.com/prometheus-community/windows_exporter/assets/137502073/dfafacd5-b358-4bc0-b5a8-0e39feb60d3f)

**Comment by breed808** [comment]
Apologies that I hadn't responded to this earlier.

Unfortunately I don't have a large group of hosts to test this against. The largest value greater than 1 I've seen during tests has been 1.007, using `irate` on a `HarddiskVolume`. Using `rate` with drive labels (`C:`, `D:`, etc) has returned a maximum of 1.0009.

1.06 does seem too high, is this occurring on multiple hosts?
