### ISSUE TITLE
Configure MSSQL collector instance registry key name

### ISSUE THREAD

**Issue by vacgo** [prometheus-community/windows_exporter#1250]
Is it possible to rebuild the exporter and mssql collector?

I would like to add MSSQL instance name as a parameter or change the MSSQLSERVER registry key name.

For example: Under HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SQL Server\Instance Names\ there is a XY key. The XY key's value is the instance name.

The problem: Couldn't open registry to determine SQL instances:The system cannot find the file specified.
We have full admin access and we run the exporter as administrator.

Thank you for the help!

**Comment by breed808** [comment]
The default instance name for the collector is `MSSQLSERVER`, though the collector attempts to read the `HKLM\Software\Microsoft\Microsoft SQL Server\Instance Names\SQL` key to detect SQL instances.

Is this registry key present on the affected host(s)?
