### ISSUE TITLE
[question] normal for windows_exporter to exit about once a day

### ISSUE THREAD

**Issue by elliotnev27** [prometheus-community/windows_exporter#1269]
Is it normal for windows_exporter to exit about once a day? When looking at Event Viewer I noticed that the service is re-launching windows_exporter.exe about once a day. 

It always happens during off-hours I do not see any error messages that indicate windows_exporter.exe is crashing, so I'm wondering if this is expected behavior.

**Comment by breed808** [comment]
No, it's not normal behaviour, though it's good that the service is recovering from the failure with restarts.

Is this occurring for all hosts? Is there any unusual behaviour observed here? It may be worth enabling debug logging to see what is causing the crash.
