### ISSUE TITLE
BUG: This installation package could not be opened.

### ISSUE THREAD

**Issue by selfagency** [prometheus-community/windows_exporter#1288]
Using the current MSI, I'm getting the following error attempting to install on Windows Server 2019 Datacenter (10.0.17763):

```powershell
msiexec /i ~\Downloads\windows_exporter-0.23.1-386.msi ENABLED_COLLECTORS=cache,cpu,cpu_info,cs,os,iis,system,net,process,scheduled_task,service,logical_disk,logon
```

> This installation package could not be opened. Verify that the package exists and that you can access it, or contact the application vendor to verify that this a valid Windows Installer package.

![image](https://github.com/prometheus-community/windows_exporter/assets/2541728/6544e8f0-948f-4a63-8578-9b9966683019)

**Comment by DiniFarb** [comment]
Yeah [msiexe](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/msiexec) is a bit tricky with the path, I don't think that ~ works well. Just use absolute path like:

```
msiexec /i C:\Users\MYUSER\Downloads\windows_exporter-0.23.1-386.msi ENABLED_COLLECTORS=cache,cpu,cpu_info,cs,os,iis,system,net,process,scheduled_task,service,logical_disk,logon
```
or something like:

```
msiexec /i $env:USERPROFILE\Downloads\windows_exporter-0.23.1-386.msi ENABLED_COLLECTORS=cache,cpu,cpu_info,cs,os,iis,system,net,process,scheduled_task,service,logical_disk,logon
```
or just cd in right to the .msi file and just:

```
msiexec /i windows_exporter-0.23.1-386.msi ENABLED_COLLECTORS=cache,cpu,cpu_info,cs,os,iis,system,net,process,scheduled_task,service,logical_disk,logon
```

**Comment by selfagency** [comment]
Thanks that did the trick
