### ISSUE TITLE
Upgrading windows exporter

### ISSUE THREAD

**Issue by Siva-22m** [prometheus-community/windows_exporter#1289]
Hi 
I'm using Prometheus version `V6.0` and Windows exporter version `V0.6` in my prod server. And I need to upgrade windows exporter to the latest version `V0.23.1`. I need to know is there any command or documentation available so that I can refer to.

As this is my production server, I need to analyze what impact it may cause.

**Comment by breed808** [comment]
The exporter is stateless; you can remove the existing `v0.6.0` installation and replace with `v0.23.1`. See the [installation](https://github.com/prometheus-community/windows_exporter#installation) section of the project README for details on installation commands for the MSI and EXE.

I'd advise testing the upgrade process on a non-production server first.

**Comment by Siva-22m** [comment]
Thank you buddy @breed808
