### ISSUE TITLE
Will windows_exporter collect Windows Docker Container resource stats?

### ISSUE THREAD

**Issue by Christoper-Lloyd2** [prometheus-community/windows_exporter#1290]
I need to monitor the resource usage of my Windows Docker Containers, but it is unclear what resource stats `windows_exporter` will collect when I run it in a Windows Docker Container. Will it collect resource stats from the Host machine or the just the resource usage of the container?

If it's just the host machine, is there an alternative that I can use for collecting Container-level resource stats on Windows docker containers?

Note: these are not Linux containers running on a Windows machine, I mean Docker Containers running Windows running on a Windows machine

**Comment by jkroepke** [comment]
Hi @Christoper-Lloyd2 

windows_exports exports container level statistics gathered from the [Windows Host Compute Service Shim](https://github.com/microsoft/hcsshim)
