### ISSUE TITLE
Collector process timeout because of the [WMI:root\WebAdministration > WorkerProcess] query

### ISSUE THREAD

**Issue by JDA88** [prometheus-community/windows_exporter#1291]
I’m not an expert on GO so please forget me if I misinterpreted something.

On the `process.go` file into the `Collect` function there is a WMI query `wmi.QueryNamespace(q_wp, &dst_wp, "root\\WebAdministration")` that does `SELECT * FROM WorkerProcess`.

I’m not exactly sure of the purpose of this query but the issue I’m having is the following:
On most machine `Get-WmiObject -Query "SELECT * FROM WorkerProcess" -Namespace "ROOT\WebAdministration"` return or fail quite fast.
But on some it timeout after a 2min with the message `Get-WmiObject : Provider load failure`. So as soon as I enable the `process` collector I have both the `process` and `service` collectors that timeout (no idea of why the `service` one timeout also).

I have a couple of question / suggestion:

- Does this WMI query is really needed for the process collector?
- Is the SELECT * optimal anyway? It should select only the field needed no?
- Is there a way to make the timeout faster?

Full Logs (0.22 and 0.23.1) have the same issue:
`windows_exporter.exe --collectors.enabled cs,process --collector.process.include="explorer.*" --log.level=debug
`
```
ts=2023-09-25T09:26:41.035Z caller=exporter.go:157 level=debug msg="Logging has Started"
ts=2023-09-25T09:26:41.035Z caller=exporter.go:91 level=debug msg="Initializing SWbemServices"
ts=2023-09-25T09:26:41.139Z caller=collector.go:51 level=debug msg="Detected Windows version 6.300000\n"
ts=2023-09-25T09:26:41.163Z caller=exporter.go:216 level=info msg="Running as xxx"
ts=2023-09-25T09:26:41.164Z caller=exporter.go:221 level=info msg="Enabled collectors: cs, process"
ts=2023-09-25T09:26:41.166Z caller=exporter.go:295 level=info msg="Starting windows_exporter" version="(version=0.23.1, branch=heads/tags/v0.23.1, revision=05091643c64e43d84be0141c27f6db3694653668)"
ts=2023-09-25T09:26:41.166Z caller=exporter.go:296 level=info msg="Build context" build_context="(go=go1.20.6, platform=windows/amd64, user=runneradmin@fv-az464-587, date=20230721-22:50:05, tags=unknown)"
ts=2023-09-25T09:26:41.167Z caller=exporter.go:297 level=debug msg="Go MAXPROCS" procs=4
ts=2023-09-25T09:26:41.168Z caller=tls_config.go:274 level=info msg="Listening on" address=x.x.x.x:yyyyy
ts=2023-09-25T09:26:41.168Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=x.x.x.x:yyyyy
ts=2023-09-25T09:26:46.865Z caller=prometheus.go:191 level=debug msg="collector cs succeeded after 0.000527s."
ts=2023-09-25T09:26:46.866Z caller=wmi.go:26 level=debug collector=process msg="Generated WMI query SELECT * FROM WorkerProcess"
ts=2023-09-25T09:26:56.366Z caller=prometheus.go:170 level=warn msg="Collection timed out, still waiting for [process]"
ts=2023-09-25T09:28:46.877Z caller=process.go:260 level=debug collector=process msg="Could not query WebAdministration namespace for IIS worker processes: Exception occurred. (Provider load failure ). Skipping"
ts=2023-09-25T09:28:46.877Z caller=prometheus.go:191 level=debug msg="collector process succeeded after 120.015391s."
```

PS: I can help get more logs / it needed, it’s very easy to reproduce.

**Comment by JDA88** [comment]
Just tested with 0.24.0, issue is still there

**Comment by breed808** [comment]
Apologies, didn't have time to look into this one before the `v0.24.0` release.

That particular query is used for IIS processes, appending the worker process name to the corresponding `w3wp` process. If this is causing impact where IIS is not in use, I think investigation into the query/timeout is warranted, or perhaps having the query be enabled with a feature flag.

**Comment by JDA88** [comment]
> If this is causing impact where IIS is not in use

The server where we can reproduce the issue have IIS. But it's an SCCM server and WMI sometimes have inconsistant behaviour on those machines.

**Comment by JDA88** [comment]
Ok I found another 7 serveurs where this problem is present.

I use a small powershell block to detect if the problem:
`Get-CimInstance -Class "WorkerProcess" -Namespace "ROOT\WebAdministration" -OperationTimeoutSec 2 -ErrorAction Stop`

On a normal machine the command return instantly, on machine with the issue, it timeout

**Comment by breed808** [comment]
You're correct, both #1062 are #933 are related. I'll get #1062 updated and merged, as that introduced the flag for this WMI behaviour I mentioned earlier.

**Comment by JDA88** [comment]
Correct me if I'm wrong but if you push the change by default it will only look for "standard" process and with the flag it will also look on this WMI class. Am I right?

If it's the case it's a breaking change for those who use it (I am not) but it's a more logical behaviour.

**Comment by breed808** [comment]
That's right, it'll be a breaking change for anyone relying on that the `WorkerProcess` class.

**Comment by JDA88** [comment]
On every server where I have issues with the `Process` collector the `Service` one also timeout. As soon as I remove the `Process` collector everything goes back to normal. Do you have, by any chance, any idea of why those timeouts are related? They are supposed to be in separate threads no?

**Comment by breed808** [comment]
That's right, each collector is run in a separate Goroutine: https://github.com/prometheus-community/windows_exporter/blob/a41abdf22d8ca331f409a377abd014d48b95872d/collector/prometheus.go#L117

Both the `process` and `service` collectors are "heavy", in that they both use WMI queries and return a high number of metrics by default, so it's possible the addition of one could cause the other to time out.

Does this issue persist when filters are added to both collectors, or if the API flag for the `process` collector is used?

**Comment by JDA88** [comment]
> Does this issue persist when filters are added to both collectors, or if the API flag for the `process` collector is used?

I always use filters for both `process` and `service` collectors I only get around 1-5 max of each and yes the issue persist with the filters in place. I think you are right the WMI timeout in the `process` is preventing the `service` collector to get his data in time.

Sorry but I didn't find the "API flag for the `process` collector" in the documentation. Is it new or did i miss it?

**Comment by breed808** [comment]
Yes, I was referring to the `--collector.service.use-api` flag. I'll see if I can reproduce this, can you raise a separate issue for it?

**Comment by JDA88** [comment]
We started deploying `v0.25` and the gain in performance for the process collector is amazing.

Statistics of the average process collector duration over 4 days (~`200 `client `v0.25` vs ~**550** `v0.23.1`)
![image](https://github.com/prometheus-community/windows_exporter/assets/67072186/869cb7ef-0cab-460e-9bf1-2fc11cf95db9)

Thanks you for the fix!
