### ISSUE TITLE
windows_exporter does not work collector NET

### ISSUE THREAD

**Issue by kselas** [prometheus-community/windows_exporter#1297]
<img width="1013" alt="image" src="https://github.com/prometheus-community/windows_exporter/assets/117058154/46ab1c32-a9b2-4d8a-9a6d-20bad859ff1a">
At some point exporter cannot collect network metrics from windows server 2019 (datacenter). Reinstalling windows_exporter did not help, other collectors work fine.
Can you please tell me how to resuscitate the system/windows_exporter (v. 0.23.1)?

**Comment by Kherm13** [comment]
Does an older or newer version work? Does this query bring back anything? 
`Get-WmiObject -Query "SELECT * FROM meta_class WHERE __this ISA 'Win32_PerfRawData'" | ? Name -like "*Tcpip*" | Select -ExpandProperty Name`

**Comment by kselas** [comment]
Tried versions 0.22, 0.23, 0.24 - all have the identical error. 
`Get-WmiObject -Query "SELECT * FROM meta_class WHERE __this ISA 'Win32_PerfRawData'" | ? Name -like "*Tcpip*" | Select -ExpandProperty Name
Win32_PerfRawData_TCPIPCounters_TCPIPPerformanceDiagnostics
Win32_PerfRawData_TCPIPCounters_TCPIPPerformanceDiagnosticsPerCPU`

**Comment by kselas** [comment]
Problem solved, this article helped - [link](https://answers.microsoft.com/en-us/windows/forum/all/perfmon-problems-unable-to-add-counters/e90f231d-0014-457d-8b1f-5f342971597a)
