### ISSUE TITLE
Question: Windows Events from EventLog

### ISSUE THREAD

**Issue by Stephanevg** [prometheus-community/windows_exporter#1298]
Hi all,

I was searching to get a hold on Windows events that show up in the Windows event log (eventvwr.msc).
Basically, I would like to trigger alarms using alert manager based on specific events (specific event id's that occur in a specific source).

I couldn't find anything that 'sounded' like what I was searching. Is this actually possible ? 

Cheers

**Comment by JDA88** [comment]
Not natively in windows_exporter.
Can be done with a custom PowerShell script that write a metric file read by windows_exporter

**Comment by jkroepke** [comment]
Hi, sorry. Log based alerts are out of scope of windows_exporter. I would recommend to use loki for generate rules based on logs
