### ISSUE TITLE
Add revision to windows_os_info

### ISSUE THREAD

**Issue by Masterwow3** [prometheus-community/windows_exporter#1300]
Is: Currently, no Windows revision number is included in windows_os_info.

Would it be possible to output the Windows revision number in the windows_os_info?
The revision changes with every Windows update, so it is possible to determine how up-to-date a machine is.

Example:
````
# HELP windows_os_info OperatingSystem.Caption, OperatingSystem.Version
# TYPE windows_os_info gauge
windows_os_info{revision="4737",build_number="17763",major_version="10",minor_version="0",product="Microsoft Windows Server 2019 Standard",version="10.0.17763"} 1
````

Example in CMD:
![image](https://github.com/prometheus-community/windows_exporter/assets/14217001/41e2d2e3-77b9-4463-a502-1504d84eabbe)

**Comment by DiniFarb** [comment]
Is someone working on that? If not, I'd like to implement it.

@breed808 ok if I work on this ?
