### ISSUE TITLE
Windows service status issues

### ISSUE THREAD

**Issue by groupe3sun** [prometheus-community/windows_exporter#1301]
I want to create a table who display the status of windows service. But he display all status (degraded, ok, unknow... with the values (0 false and 1 true). I juste want to display the status when the value = 1. How i do ?

**Comment by breed808** [comment]
Try `windows_service_status == 1` for the Prometheus query.

**Comment by JDA88** [comment]
You might want to take a look at #938 if you plan to display the status in a dashboard.

**Comment by groupe3sun** [comment]
I succeeded with "query == 1" thx dudes !
