### ISSUE TITLE
Collection timed out

### ISSUE THREAD

**Issue by invlol** [prometheus-community/windows_exporter#1306]
I have the collector service timeout

```
# HELP windows_exporter_collector_success windows_exporter: Whether the collector was successful.
windows_exporter_collector_success{collector="service"} 0

# HELP windows_exporter_collector_timeout windows_exporter: Whether the collector timed out.
windows_exporter_collector_timeout{collector="service"} 1
```

Checking the application logs 
caller=prometheus.go:170 level=warn msg="Collection timed out, still waiting for [service]"

i change the timeout and still
caller=prometheus.go:188 level=error msg="collector service failed after 30.457124s" err="Exception occurred. (Server execution failed )"

Is there any solution for this, I even start the program with the extra_flag filter for service and still have the issue

same issue as this one
https://github.com/prometheus-community/windows_exporter/issues/469

**Comment by breed808** [comment]
A few questions:

* How frequently are you scraping this host for metrics?
* Do you have a filter defined for the `service` collector?
* Is this issue occurring with multiple hosts, or is this host an outlier?
* Does querying the WMI table (Win32_Service) result in a similar time out on the affected host(s)?
