### ISSUE TITLE
AD metrics not showing

### ISSUE THREAD

**Issue by Siva-22m** [prometheus-community/windows_exporter#1308]
Hi 
I'm using windows Exporter `V0.23.0` in my production server and I need to query ad services with my target domain controller machines.

But I can't able to see the AD metrics in this version

**Comment by breed808** [comment]
Are the AD WMI counters present on this system? Try querying the  `Win32_PerfRawData_DirectoryServices_DirectoryServices` WMI class to see if any data is returned.
