### ISSUE TITLE
TextFile Epoch

### ISSUE THREAD

**Issue by Silmariil** [prometheus-community/windows_exporter#1314]
Help me please. How to specify time in metrics on textfile?
When I specify the epoch after the counter or gauge, I get the error: "windows_textfile_scrape_error 1".
For example:
```
# TYPE MyMetricName_received counter
MyMetricName_received 4 1698127672757
```

**Comment by breed808** [comment]
The `textfile` collector doesn't currently support timestamps for metrics; Only the metric value should be included.

**Comment by jkroepke** [comment]
There is a long discussion on node_exporter to follow-up: https://github.com/prometheus/node_exporter/pull/769#issuecomment-380980122

This issue is non-trivial and like node_exporter, we are not plan to support epoch/timestamp on textfile collector
