### ISSUE TITLE
The description for Event ID 3299 from source windows_exporter cannot be found

### ISSUE THREAD

**Issue by DavidSkDerivco** [prometheus-community/windows_exporter#1318]
I have recently rolled out v0.24.0 to our servers (combination of Server 2016-2022) and have noticed that the even is filled with the following errors:

"The description for Event ID 3299 from source windows_exporter cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

ts=2023-10-30T07:26:44.404Z caller=tls_config.go:277 level=info msg="TLS is disabled." http2=false address=[::]:9182

The message resource is present but the message was not found in the message table"

As a test, I rolled back to v0.22.0 and the 3299 events no longer existed and ran with the usual event id 101/102.
I can see that if I have v0.22.0 installed the "Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\windows_exporter" has many more fields than v0.24.0

**Comment by DavidSkDerivco** [comment]
Can I get a bump on this please?

**Comment by riyadibayu** [comment]
Also having a similar case on v0.23.1

> The description for Event ID 3299 from source windows_exporter cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer. 
If the event originated on another computer, the display information had to be saved with the event.
The following information was included with the event: 
ts=2023-12-01T16:49:42.804Z caller=service.go:60 level=warn collector=service msg="No where-clause specified for service collector. This will generate a very large number of metrics!"

**Comment by jkroepke** [comment]
Do you use the installer to install windows-exporter?

**Comment by breed808** [comment]
I suspect this was introduced in 8509bc69a60bb6b608d390fabdf6e4d64b939b2e. As mentioned in the opening comment, I'm able to reproduce the issue in v0.23.1, but not in v0.22.0. Event IDs 100 and 101 are seen in v0.22.0.

**Comment by DavidSkDerivco** [comment]
> I suspect this was introduced in [8509bc6](https://github.com/prometheus-community/windows_exporter/commit/8509bc69a60bb6b608d390fabdf6e4d64b939b2e). As mentioned in the opening comment, I'm able to reproduce the issue in v0.23.1, but not in v0.22.0. Event IDs 100 and 101 are seen in v0.22.0.

Would this be addressed in v0.24.0 or will the 3299 events be the new way of event logging?

**Comment by jkroepke** [comment]
@breed808 If you are running windows_exporter on a system where MSI installer not run before, then the event ID 100 and 101 result in non-readable messages. Thats why I introduce the 3299 event it.

However, the MSI installer register an event source which makes the event id unusable. 

https://github.com/prometheus-community/windows_exporter/blob/5a872a227c2f588e64505ab42587205719e1f390/installer/windows_exporter.wxs#L60

**Comment by DavidSkDerivco** [comment]
> @breed808 If you are running windows_exporter on a system where MSI installer not run before, then the event ID 100 and 101 result in non-readable messages. Thats why I introduce the 3299 event it.
> 
> However, the MSI installer register an event source which makes the event id unusable.
> 
> https://github.com/prometheus-community/windows_exporter/blob/5a872a227c2f588e64505ab42587205719e1f390/installer/windows_exporter.wxs#L60

Is there a switch i should use to "refresh" the or re-create the Eventlog?
98% of the servers i ran this on used to have windows exporter (from version 16 to 22) installed on them. I did do this on a new built server and it seemd to do the same. I can confirm this later this week.

**Comment by jkroepke** [comment]
Remove the Registry Key (the folder) 

`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\EventLog\Application\windows_exporter`

Then event shows correct.

<img width="786" alt="image" src="https://github.com/prometheus-community/windows_exporter/assets/1560587/d0fa543c-5e85-4717-8b61-989912636605">


I tested that on a Windows Server. You may have to restart the Event Viewer.

**Comment by jkroepke** [comment]
@breed808 do you know if its possible to run commands with wix installer? we could remove the registry key on next upgrade

**Comment by dansimov04012022** [comment]
On `v0.25.0` faced an issue when `RemoveEventSource` resulted in 1603 code while trying to install msi with `msiexec` on Windows container, which broke the installation:
```
MSI (s) (20:10) [10:54:44:866]: Executing op: CustomActionSchedule(Action=RemoveEventSource,ActionType=3137,Source=BinaryData,Target=WixSilentExec,)
MSI (s) (20:E8) [10:54:44:882]: Invoking remote custom action. DLL: C:\Windows\Installer\MSIE176.tmp, Entrypoint: WixSilentExec
MSI (s) (20:00) [10:54:44:882]: Generating random cookie.
MSI (s) (20:00) [10:54:44:913]: Created Custom Action Server with PID 916 (0x394).
MSI (s) (20:18) [10:54:44:993]: Running as a service.
MSI (s) (20:18) [10:54:45:009]: Hello, I'm your 64bit Elevated Non-remapped custom action server.
WixSilentExec:  Error 0x80070057: Failed to get command line data
WixSilentExec:  Error 0x80070057: Failed to get Command Line
WixSilentExec:  Error 0x80070057: Failed in ExecCommon method
MSI (s) (20:10) [10:54:45:088]: Executing op: ActionStart(Name=ProcessComponents,Description=Updating component registration,)
CustomAction RemoveEventSource returned actual error code 1603 but will be translated to success due to continue marking
```

**Comment by jkroepke** [comment]
Could you explain, why it breaks the installation? The error is marked as ignore.

**Comment by dansimov04012022** [comment]
You're right, I removed that block from the wxs file and still, it seems like starting the service leads to the 1603 error. Still trying to understand why.

**Comment by jkroepke** [comment]
No log output of the service?

**Comment by dansimov04012022** [comment]
> No log output of the service? Its better to open a new issue here, since the error has an other source.

From the eventlog I just see it restarts multiple times (the actual process starts successfully also if I just call the startup command from the powershell). I'd create a separate issue if I won't find the root cause.

It also acts the same on 0.21.0, so I think it's not the issue of the particular release.
