### ISSUE TITLE
Have you considered adding batch-resp-statistics to mssql?

### ISSUE THREAD

**Issue by Rabbit-st** [prometheus-community/windows_exporter#1319]
https://learn.microsoft.com/en-us/sql/relational-databases/performance-monitor/sql-server-batch-resp-statistics-object?view=sql-server-ver16

**Comment by breed808** [comment]
Hi @Rabbit-st, I'm not currently looking into this (largely due to an inability to test any changes made to the `sql` collector).

If you're able to submit a Pull Request for this change I'd be happy to review it.
