### ISSUE TITLE
An error has occurred while serving metrics

### ISSUE THREAD

**Issue by fabricesemti80** [prometheus-community/windows_exporter#1322]
Hello,

I have deployed version `0.23.1` (and latter `0.24.0`) to a number of Windows hosts (some of the new deployments are `Windows Server 2016`...I am aware these are running out of support soon, but due to business needs we had to deploy some recently).

The installation was done using https://github.com/DanielWeeber/ansible-role-windows_exporter . (I am aware that this is a 3rd party role, but the installer worked well to most - near 300 - servers, and the log / health check is all state that installation of the exporter was a-OK.)

For refrerence my parameters were:
version: `'0.24.0' `
collectors: `ENABLED_COLLECTORS="ad,cache,cpu,cpu_info,cs,iis,logical_disk,memory,net,os,process,service,system,tcp,time"`

Checking a host with problems:

```powershell
Clear-host
$server = 'dc1modftb04p.<domain>'

Write-Host "Prometheus status on $server :" -ForegroundColor Yellow
((Invoke-WebRequest -Uri "http://$($server):9182/health").content | ConvertFrom-Json).Status

# Prometheus status on dc1modftb04p.<domain> :
# ok
```

then
```powershell
Write-Host "Prometheus version on $server :" -ForegroundColor Yellow
(Invoke-WebRequest -Uri "http://$($server):9182/version").content | ConvertFrom-Json

Prometheus version on dc1modftb04p.<domain> :


# version   : 0.24.0
# revision  : 5e7462a70e19cc1147cb930a61982897413b9120
# branch    : heads/tags/v0.24.0
# buildUser : runneradmin@fv-az282-478
# buildDate : 20230926-08:57:56
# goVersion : go1.21.1
```

But here is my problem:

```powershell
Write-Host "Prometheus metrics on $server :" -ForegroundColor Yellow
Invoke-WebRequest -Uri "http://$($server):9182/metrics"

# Prometheus metrics on dc1modftb04p.<domain> :
# Invoke-WebRequest : An error has occurred while serving metrics: error collecting metric Desc{fqName: # "windows_exporter_collector_success", help: "windows_exporter: Whether the collector was successful.", constLabels: {}, variableLabels: # [{collector }]}: 
# failed to prepare scrape: EOF
# At line:2 char:1
# + Invoke-WebRequest -Uri "http://$($server):9182/metrics"
# + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
#     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

What am I missing? And more importantly: how to rectify?

**Comment by fabricesemti80** [comment]
For clarification, issue is happening both with latest and latest -1 release. Ansible gives all thumbs-up with both, but no metrics
<img width="676" alt="image" src="https://github.com/prometheus-community/windows_exporter/assets/37410363/51cd0c41-6560-4259-b387-c0d65bc9b171">
<img width="510" alt="image" src="https://github.com/prometheus-community/windows_exporter/assets/37410363/a517e790-963d-43ea-b213-e15a6fd7114d">

**Comment by deajan** [comment]
Same here, but found the solution.
I've run `windows_exporter.exe` manually with `log.file mylogfile.txt` in order to diagnose.
Actually, you cannot enable modules that the machine doesn't have.
Eg, I had `mssql` and `iis` modules enabled.

I'm currently working on a script to detect ad / dns / mssql / iis in order to enable collectors only when necessary.
I just uploaded my initial work at https://github.com/netinvent/windows_exporter_installer
Contribs are welcome ;)
