### ISSUE TITLE
Windows service can't stop without an error.

### ISSUE THREAD

**Issue by Techni-P** [prometheus-community/windows_exporter#1352]
With windows_exporter 0.24.0 we have again the same Issue like:
https://github.com/prometheus-community/windows_exporter/issues/1258

When I try to stop the windows_exporter service (v0.24.0), it always returns an error:
![image](https://github.com/prometheus-community/windows_exporter/assets/152503042/a12a6edd-42fe-4aef-a1c5-6d0ec6ef53de)
and the Process is still running in the Background.

**Comment by jkroepke** [comment]
@DiniFarb this issue can be close, right?
