### ISSUE TITLE
Difference in threads/processes 

### ISSUE THREAD

**Issue by MatiasLGonzalez** [prometheus-community/windows_exporter#1353]
Hello, sorry for opening an issue for a question, but the discussion tab is no enabled in this repo. It's not clear to me the difference between `windows_system_threads`, `windows_process_threads` and `windows_os_processes`, what I understand so far is:
- `windows_system_threads` is the number of Windows and Windows only threads count.
- `windows_process_threads` is the number of threads from the processes specified by its collector include/exclude.
- `windows_os_processes` is the number of processes (OS or otherwise) running or loaded.

Is this correct? Thanks in advanced

**Comment by breed808** [comment]
You're very close. `windows_process_threads` is the number of threads currently active for the process listed in the `process` and/or `process_id` flags. When aggregated these threads _should_ match the number of threads shown in `windows_system_threads`.

`windows_system_threads` is "[the number of threads in the computer at the time of data collection](https://web.archive.org/web/20050830140516/http://msdn.microsoft.com/library/en-us/wmisdk/wmi/win32_perfrawdata_perfos_system.asp)".

To simplify, `windows_system_threads` will provide the total number of active threads.
`windows_process_threads` will provide a per-process active thread count, but can also be aggregated for a holistic view of system threads.
`windows_os_processes` is exactly as you've described.
