### ISSUE TITLE
Release 0.25 Task list

### ISSUE THREAD

**Issue by jkroepke** [prometheus-community/windows_exporter#1356]
I would like to cut a new release windows_exporter. From my point of view, the following items should be resolved.

* https://github.com/prometheus-community/windows_exporter/pull/1340
* https://github.com/prometheus-community/windows_exporter/pull/1343
* https://github.com/prometheus-community/windows_exporter/issues/1318

@breed808 Do you want something else in the next release?

**Comment by breed808** [comment]
The above looks good :+1:. I don't have any particular items that need to be implemented by the next release.

**Comment by breed808** [comment]
Do you mean the changelog in previous releases? That's been automatically generated by Github (there's a button when drafting new releases for generation) with some manual additions, such as breaking changes. In the past I've also sorted some of the changes into sections (dependency updates) to make the change list clearer.

**Comment by jkroepke** [comment]
For the next release after 0.25, we can start to category PRs based on label.

For example: https://github.com/jkroepke/openvpn-auth-oauth2/blob/main/.github/release.yml

Results in https://github.com/jkroepke/openvpn-auth-oauth2/releases/tag/v1.11.0

**Comment by jkroepke** [comment]
@breed808 tasks are done. It just create a GH release? or more?

**Comment by breed808** [comment]
Yep, just a Github release is required. The CI will trigger a release build for the artifacts once the release is published.

**Comment by jkroepke** [comment]
Thanks, it works
