### ISSUE TITLE
Unable to connect Grafana to Exporter node

### ISSUE THREAD

**Issue by tuxmeister** [prometheus-community/windows_exporter#1359]
Grafana v10.2.2
Windows Exporter v0.24.0
```
Windows Server Edition:	Windows Server 2022 Standard
Version	                                 21H2
Installed on	‎                         2023-‎02-‎24
OS build	                         20348.1547
```
I cannot configure a new Grafana Data Source pointing to a test node running the latest version of Exporter. 

Grafana error: 

`ReadObject: expect { or , or } or n, but found <, error found in #1 byte of ...|<html lang=|..., bigger context ...|<html lang="en"> <head> <meta charset="UTF-8"|... - There was an error returned querying the Prometheus API.`

I am able to CURL the /metrics endpoint, and I get a simple output, but via any browser, the metrics are wrapped in HTML code. 

![image](https://github.com/prometheus-community/windows_exporter/assets/3372817/695a4316-02f4-48f4-975c-39836f7ff2e8)

**Comment by breed808** [comment]
Grafana doesn't support retrieving metrics directly from exporters. You'd need to scrape the exporter with metrics or another supported datasource, and point Grafana to that datasource.

See here for the list of supported Grafana datasources: https://grafana.com/docs/grafana/latest/datasources/#built-in-core-data-sources
