### ISSUE TITLE
Can we add CPU temperature monitoring

### ISSUE THREAD

**Issue by yomixvii** [prometheus-community/windows_exporter#1366]
Hello,

I have a monitoring requirement for the temperature of the system CPU. Can our collector support this content

**Comment by jkroepke** [comment]
Should be provided by [thermalzone](https://github.com/prometheus-community/windows_exporter/blob/b1c272a9963e897a5aad11685ae0d25a0460fad3/docs/collector.thermalzone.md) collector.
