### ISSUE TITLE
windows server 2008r2 insert error

### ISSUE THREAD

**Issue by m84686660** [prometheus-community/windows_exporter#1393]
error: 
 Exception 0xc0000005

C:/hostedtoolcache/windows/go/1.21.5/x64/src/runtime/sys_windows_amd64.s

**Comment by m84686660** [comment]
windows_exporter 0.25.1

**Comment by m84686660** [comment]
D:\>.\windows_exporter.exe
Exception 0xc0000005 0x8 0x0 0x0
PC=0x0

runtime.asmstdcall()
        C:/hostedtoolcache/windows/go/1.21.5/x64/src/runtime/sys_windows_amd64.s
:65 +0x75 fp=0x22fca0 sp=0x22fc80 pc=0x473af5

**Comment by breed808** [comment]
Does this error occur with previous `windows_exporter` releases? Are both the binary and operating system 64bit?

**Comment by bcruvelier** [comment]
> `windows_exporter` doesn't work on Windows 2008 anymore. This OS is unsuported. last release working on Windows 2008 was v0.9.0, anything after that will not work.

It is supposed to work with 2008R2 (cf. https://github.com/prometheus-community/windows_exporter#supported-versions) and was working with version 0.24.0 but not anymore.

**Comment by JDA88** [comment]
ho, you are right `v0.9.0` was the last working on 2008. but 2008R2 was still working on `v0.24.0`
Unfortunately I don't have any 2008* anymore and cannot test on my side.

**Comment by ordimans** [comment]
I confirm, 0.24.0 is working perfectly with 2008 R2, but no 0.25.0 and 0.25.1

**Comment by jkroepke** [comment]
windows_exporter supports 2016 at minimum with best-effort support for 2012R2.

There is no support from Microsoft as well. Even extended security updates not longer available.
