### ISSUE TITLE
Unit of windows_process_start_time

### ISSUE THREAD

**Issue by trippinnik** [prometheus-community/windows_exporter#1404]
Unclear what the unit being used is (not noted in docs). I'm visualizing in grafana and haven't found something that lines up with what I would expect given last restart of service

**Comment by jkroepke** [comment]
It should the time where the process has been started

**Comment by trippinnik** [comment]
In what format or unit? The value is not corresponding to anything that resembles time

**Comment by jkroepke** [comment]
I should be a [unix timestamp](https://en.wikipedia.org/wiki/Unix_time) in floating point format
