### ISSUE TITLE
Can I drop specific labels within config.yml

### ISSUE THREAD

**Issue by boaz-raz** [prometheus-community/windows_exporter#1407]
Can I drop some specific labels with in the config.yml? 

https://github.com/prometheus-community/windows_exporter/blob/master/docs/example_config.yml

**Comment by breed808** [comment]
The config file is an alternative to the flags typically supplied to the `windows_exporter` binary. It doesn't offer additional features, such as dropping labels.

Is the [relabel configuration](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) in Prometheus not suitable to your situation?
