### ISSUE TITLE
Custom performance counters

### ISSUE THREAD

**Issue by dcarrion87** [prometheus-community/windows_exporter#1414]
Hate to dig up this old one: 

- https://github.com/prometheus-community/windows_exporter/issues/585

But is the advice still to use the text file collector.

I've got a few things I want to do that are available in Perfmon and I can't see a way to extend this for custom metrics easily. This would be such a handy feature not having to have multiple metrics endpoints.

**Comment by DerfOh** [comment]
Adding the ability to configure custom perf counter queries is something I'm very interested in doing as well. My devs write custom perf counters that are pretty much a royal pain in the ass to get to without some bending over backwards. Seems like for the windows_exporter this functionality would be **incredibly** useful given it's reputation for exporting performance metrics.
