### ISSUE TITLE
CryptoAPI

### ISSUE THREAD

**Issue by jerveree** [prometheus-community/windows_exporter#1419]
Hi,

Our Windows Servers get an auto-enrolled certificate from Active Directory Certificate Services added to their Local Machine Certificate Store with a non-exportable private key.

It would be usefull to be able to reference this certificate and have the exporter use CryptoAPI to enable https scheme instead of using other means to place a certificate and private key file.

**Comment by JDA88** [comment]
I agree that been able to use a cert from the local store could be nice!

**Comment by jkroepke** [comment]
there a no plans to implement this feature, since it requires a lot of complex logic to archive this. But if you require this, take a look at Grafana Alloy. They implement that feature of the https listener.
