### ISSUE TITLE
How do I update windows exporter with config-file...using msiexec?   more in-depth docs on using config file

### ISSUE THREAD

**Issue by njoylif** [prometheus-community/windows_exporter#1420]
Hello, new to github, so bear with me if improper process/formatting...

I'm trying to get this exporting using a config file and can't figure out formatting when updating with msiexec.
I've tried: 
      msiexec /i c:\netdata\windows_exporter-0.25.1-amd64.msi --% EXTRA_FLAGS="--config.file=c:\netdata\netdata_config.yaml"
I've been able to get it exporting defaults using:
      msiexec /i c:\netdata\windows_exporter-0.25.1-amd64.msi ENABLED_COLLECTORS="[default]"
that works.
I can't seem to get IIS exporting when using config nor this commandline:
      msiexec /i c:\netdata\windows_exporter-0.25.1-amd64.msi ENABLED_COLLECTORS="[default],iis,process"
      
I also need formatting examples of config file past what's there.  not sure what's right and cant seem to test it yet.
i.e. do I just remove this section if I want all services and tasks?  Are wildcards supported?
#collector:
  service:
    services-where: Name='windows_exporter'
  scheduled_task:
    include: /Microsoft/.+

TYIA

**Comment by ankurkdubey** [comment]
One way - msiexec /i C:\windows_exporter-0.25.1-amd64.msi ENABLED_COLLECTORS=cpu,cs,iis,logical_disk,net,os,memory,process,tcp,service,system,textfile LISTEN_PORT=9182


The second way - using the config file 
msiexec /i "C:\windows_exporter\windows_exporter-0.25.1-amd64.msi" --% EXTRA_FLAGS="--config.file=C:\windows_exporter\config.yml" 


config.yml 

# Note this is not an exhaustive list of all configuration values #cpu,cs,logical_disk,net,os,service,system,textfile,iis
collectors:
  enabled: cpu,iis,cs,logical_disk,net,os     #please add collector name here using comma separated
collector:
  service:
    services-where: Name='windows_exporter'
  scheduled_task:
    include: /Microsoft/.+
log:
  level: debug
scrape:
  timeout-margin: 0.5
telemetry:
  path: /metrics
  max-requests: 5
web:
  listen-address: ":9182"

**Comment by njoylif** [comment]
ok, not to proud....PICNIC.

was in CMD...needed to be in powershell.

msiexec /i windows_exporter-0.25.1-amd64.msi --% EXTRA_FLAGS="--config.file=C:\Users\<username>\downloads\config.yml"

worked when in right env.  sigh.
Thanks for response
