### ISSUE TITLE
There is no Windows_os_* return on a certain Windows

### ISSUE THREAD

**Issue by chinaxushi** [prometheus-community/windows_exporter#1426]
ts=2024-03-06T11:10:41.338Z caller=prometheus.go:186 level=error msg="collector os failed after 0.043007s" err="The system cannot find the file specified."

This is a log error

It has been confirmed that there is a return value for the Win32_OperatingSystem class in WMI on the machine

I saw that there were similar issues before, but they all said that the page file problem had been solved.

**Comment by jkroepke** [comment]
Are you running Windows Server 2012R2? If yes, should be fixed in  #1446

**Comment by chinaxushi** [comment]
It's 2012, but not all Windows 2012 have this issue

**Comment by jkroepke** [comment]
Could you test this binary for us, if it resolve your issue?

https://github.com/prometheus-community/windows_exporter/actions/runs/8767881067/artifacts/1432390524

**Comment by chinaxushi** [comment]
Sorry, I only saw the message now. I have tested it and using the version above, the information for Windows_os * has been released. I am not sure if the data is complete. But the previously missing system versions and memory usage are now available.

**Comment by chinaxushi** [comment]
I also ran version 0.25.1 on this machine. There is no data for "Windows_os_*"
