### ISSUE TITLE
wmi_net_bytes_* counters all show zero; expose other bytes metrics?

### ISSUE THREAD

**Issue by trickv** [prometheus-community/windows_exporter#143]
I've just started using wmi_exporter on a bunch of Server 2012 VMs and it's working pretty well so far.
However I'm seeing zeroes for all of the wmi_net_bytes_* metrics, but the wmi_net_packets_* metrics are working fine:

```
[pv@LON-IX-L-763 ~]$ curl -s http://test-adb01.london.mintel.ad:9182/metrics | egrep net_\(bytes\|packets\).*total
# HELP wmi_net_bytes_received_total (Network.BytesReceivedPerSec)
# TYPE wmi_net_bytes_received_total counter
wmi_net_bytes_received_total{nic="Intel_R__PRO_1000_MT_Network_Connection"} 0
wmi_net_bytes_received_total{nic="isatap__DDF12FF4_1AAE_46B4_B347_52CA8ED032BD_"} 0
# HELP wmi_net_bytes_sent_total (Network.BytesSentPerSec)
# TYPE wmi_net_bytes_sent_total counter
wmi_net_bytes_sent_total{nic="Intel_R__PRO_1000_MT_Network_Connection"} 0
wmi_net_bytes_sent_total{nic="isatap__DDF12FF4_1AAE_46B4_B347_52CA8ED032BD_"} 0
# HELP wmi_net_bytes_total (Network.BytesTotalPerSec)
# TYPE wmi_net_bytes_total counter
wmi_net_bytes_total{nic="Intel_R__PRO_1000_MT_Network_Connection"} 0
wmi_net_bytes_total{nic="isatap__DDF12FF4_1AAE_46B4_B347_52CA8ED032BD_"} 0
# HELP wmi_net_packets_received_total (Network.PacketsReceivedPerSec)
# TYPE wmi_net_packets_received_total counter
wmi_net_packets_received_total{nic="Intel_R__PRO_1000_MT_Network_Connection"} 3.628166e+06
wmi_net_packets_received_total{nic="isatap__DDF12FF4_1AAE_46B4_B347_52CA8ED032BD_"} 0
# HELP wmi_net_packets_sent_total (Network.PacketsSentPerSec)
# TYPE wmi_net_packets_sent_total counter
wmi_net_packets_sent_total{nic="Intel_R__PRO_1000_MT_Network_Connection"} 807263
wmi_net_packets_sent_total{nic="isatap__DDF12FF4_1AAE_46B4_B347_52CA8ED032BD_"} 0
# HELP wmi_net_packets_total (Network.PacketsPerSec)
# TYPE wmi_net_packets_total counter
wmi_net_packets_total{nic="Intel_R__PRO_1000_MT_Network_Connection"} 4.435429e+06
wmi_net_packets_total{nic="isatap__DDF12FF4_1AAE_46B4_B347_52CA8ED032BD_"} 0
```

Looking a bit further, it looks like the actual counters (presumably the same ones) are showing zero bytes, whilst the broadcast / multicast / unicast byte counters are working fine:
```
TEST-ADB01 C:\ PS> Get-NetAdapter -ifindex 12 | Get-NetAdapterStatistics | Format-List *

ifAlias                  : Ethernet
InterfaceAlias           : Ethernet
ifDesc                   : Intel(R) PRO/1000 MT Network Connection
Caption                  : MSFT_NetAdapterStatisticsSettingData 'Intel(R) PRO/1000 MT Network Connection'
Description              : Intel(R) PRO/1000 MT Network Connection
ElementName              : Intel(R) PRO/1000 MT Network Connection
InstanceID               : {DDF12FF4-1AAE-46B4-B347-52CA8ED032BD}
InterfaceDescription     : Intel(R) PRO/1000 MT Network Connection
Name                     : Ethernet
Source                   : 2
SystemName               : test-adb01.pc.london.mintel.ad
OutboundDiscardedPackets : 0
OutboundPacketErrors     : 0
RdmaStatistics           :
ReceivedBroadcastBytes   : 95065339
ReceivedBroadcastPackets : 0
ReceivedBytes            : 0
ReceivedDiscardedPackets : 0
ReceivedMulticastBytes   : 145360678
ReceivedMulticastPackets : 0
ReceivedPacketErrors     : 0
ReceivedUnicastBytes     : 2275532332
ReceivedUnicastPackets   : 3643179
RscStatistics            :
SentBroadcastBytes       : 697554
SentBroadcastPackets     : 0
SentBytes                : 0
SentMulticastBytes       : 10752
SentMulticastPackets     : 0
SentUnicastBytes         : 139602802
SentUnicastPackets       : 812638
SupportedStatistics      : 4163583
PSComputerName           :
CimClass                 : ROOT/StandardCimv2:MSFT_NetAdapterStatisticsSettingData
CimInstanceProperties    : {Caption, Description, ElementName, InstanceID...}
CimSystemProperties      : Microsoft.Management.Infrastructure.CimSystemProperties
```

This is a rather bog standard Windows 2012 R2 installation running on KVM using a emulated Intel E1000 NIC with a Microsoft standard driver.  I wonder if anyone else has seen issues with byte counters being zero on this or other NICs?

Is it possible for the wmi_exporter to expose metrics for (received|sent)_(broadcast|multicast|unicast)_bytes?

**Comment by carlpett** [comment]
Hi,
That's strange. I'm travelling, but I can take a look next week, hopefully. We could definitely expand the reported metrics as you suggest, perhaps as a label. Not sure if those are not present on older versions, perhaps, since they aren't included now...

**Comment by martinlindhe** [comment]
This could possibly be a driver issue, as I guess the driver might be responsible for exporting metrics to WMI.

**Comment by spouter** [comment]
I have the same problem
OS:WIndows Server 2008 R2 Enterprise
VM:KVM

# TYPE wmi_net_bytes_received_total counter
wmi_net_bytes_received_total{nic="Intel_R__PRO_1000_MT_Network_Connection"} 0
wmi_net_bytes_received_total{nic="Teredo_Tunneling_Pseudo_Interface"} 0
wmi_net_bytes_received_total{nic="isatap__B67FCAEB_7C33_4C7E_9474_4D3DF37F60AE_"} 0
# HELP wmi_net_bytes_sent_total (Network.BytesSentPerSec)
# TYPE wmi_net_bytes_sent_total counter
wmi_net_bytes_sent_total{nic="Intel_R__PRO_1000_MT_Network_Connection"} 0
wmi_net_bytes_sent_total{nic="Teredo_Tunneling_Pseudo_Interface"} 0
wmi_net_bytes_sent_total{nic="isatap__B67FCAEB_7C33_4C7E_9474_4D3DF37F60AE_"} 0

**Comment by txg1550759** [comment]
I have the same problem
OS:WIndows Server 2008 R2 Enterprise
VM:KVM   I
the 9182 port print  metrics
 Intel(R) PRO/1000 MT Network Connection

# HELP windows_net_bytes_received_total (Network.BytesReceivedPerSec)
# TYPE windows_net_bytes_received_total counter
windows_net_bytes_received_total{nic="Intel_R__PRO_1000_MT_Network_Connection"} 0
windows_net_bytes_received_total{nic="isatap__F0BD027A_EB1B_4065_AD84_066BDDDBD2DA_"} 0
# HELP windows_net_bytes_sent_total (Network.BytesSentPerSec)
# TYPE windows_net_bytes_sent_total counter
windows_net_bytes_sent_total{nic="Intel_R__PRO_1000_MT_Network_Connection"} 0
windows_net_bytes_sent_total{nic="isatap__F0BD027A_EB1B_4065_AD84_066BDDDBD2DA_"} 0
# HELP windows_net_bytes_total (Network.BytesTotalPerSec)
# TYPE windows_net_bytes_total counter
windows_net_bytes_total{nic="Intel_R__PRO_1000_MT_Network_Connection"} 0
windows_net_bytes_total{nic="isatap__F0BD027A_EB1B_4065_AD84_066BDDDBD2DA_"} 0
