### ISSUE TITLE
[requirements]   IIS version number

### ISSUE THREAD

**Issue by chinaxushi** [prometheus-community/windows_exporter#1449]
There is no version number in the returned data of IIS. I see that the code has obtained the version, but there is no data to return the version number. Can this be added.

**Comment by jkroepke** [comment]
I have added a info metric in #1450

Can you test this for me? I do not have a IIS environment yet.

Binary to test: https://github.com/prometheus-community/windows_exporter/actions/runs/8773637934/artifacts/1433348385

**Comment by chinaxushi** [comment]
The returned indicators have the following fields

# HELP windows_iis_info ISS information
# TYPE windows_iis_info gauge
windows_iis_info{version="10.0"} 1

**Comment by jkroepke** [comment]
Does it meet your expectation?

**Comment by chinaxushi** [comment]
That's all I need
