### ISSUE TITLE
A single list in the Dashboard for Enabled/Disabled servers

### ISSUE THREAD

**Issue by img0043** [prometheus-community/windows_exporter#1457]
![photo1711632362](https://github.com/prometheus-community/windows_exporter/assets/54365449/c03ec258-6081-43b5-a642-7c7a0822ca3a)

Greetings!
Please tell me.
This's dashboard for Win servers that receive metrics from windows exporter via Prometheus.
Here are the queries for the source selection panel:

![photo1711632274](https://github.com/prometheus-community/windows_exporter/assets/54365449/a0ee859a-6559-4109-ab51-f2da6a943fd5)
Job:
`abel_values(windows_cs_hostname, job)`

Name:
`label_values(windows_cs_hostname{job=~\"$job\"}, hostname)`

Instance:
`label_values(windows_cs_hostname{job=~\"$job\",hostname=~\"$hostname\"}, instance)`

How to make it so that even disabled/unavailable servers (instance) are displayed, so that it is visible that no information is received from them in the single general list.

It may also be a matter of PromQL queries that return Instance and time UP on the server :

`sum by (instance) (windows_service_state{job=~"$job",instance=~"$instance",state=~"running"})`

`time() - windows_system_system_up_time{job=~"$job",instance=~"$instance"}`

Please help me with this.

The dashboard: 
[1. WINDOWS SERVERS FULL.json](https://github.com/prometheus-community/windows_exporter/files/15095134/1.WINDOWS.SERVERS.FULL.json)

**Comment by chinaxushi** [comment]
Under normal circumstances, if it's not a problem with the values, it's just a problem with the dashboard. You should go to Grafana and ask questions

**Comment by breed808** [comment]
It may be worth looking at the `absent` and `absent_over_time` PromQL functions for unavailable servers. Disabled servers that still respond to Prometheus scrapes would need to be identified by a particular custom metric, possibly one provided by a hypervisor.

https://prometheus.io/docs/prometheus/latest/querying/functions/#absent
