### ISSUE TITLE
Windows service collector takes over 500s to scrape data

### ISSUE THREAD

**Issue by paologallinaharbur** [prometheus-community/windows_exporter#1458]
We have been noticing the exporter taking more time to scrape data than expected both if executed with `use-api` or with the old `WMI` while filtering services
```
$ windows_exporter.exe --collectors.enabled service --log.level debug --collector.service.services-where "Name='***'" 
or
$ windows_exporter.exe --collectors.enabled service --log.level debug --collector.service.use-api
```

We have a "normal" number of services that are scraped, but the exporter takes a lot to answer, in particular I find weird the following metrics
```
windows_exporter_collector_duration_seconds{collector="service"} 0.434567
windows_exporter_perflib_snapshot_duration_seconds 528.34678
```

I have the feeling that scraping the services is "quick" but crating a perflib snapshot wastes a lot of time, [even thought the service has an empty list of perfCounters
](https://github.com/prometheus-community/windows_exporter/blob/f6b91e5cb0f710550777c7ff261c21e6296c27a9/pkg/collector/service/service.go#L87-L88)
 - Do you have any idea why this could be happening?
 - Is the perflib snapshot creation something that be avoided somehow? As far as I know it reports the time taken by [this function](https://github.com/prometheus-community/windows_exporter/blob/f6b91e5cb0f710550777c7ff261c21e6296c27a9/pkg/perflib/utils.go#L10) to be executed, but I was unable to understand more 😕

**Comment by jkroepke** [comment]
That feels strange, because service collector doesn't interact with perflib

**Comment by jkroepke** [comment]
@paologallinaharbur by any chance, I would like to know, if #1497 help you.

> Do you have any idea why this could be happening?

WMI is slow, and the API based approach is asking each single service about status and query.

#1497 is using a different approach by asking the Windows API once. On my local system, it's quite fast but It wont provide all information, like run_as, pid or start mode

**Comment by jkroepke** [comment]
It could be possible that query nothing takes up to 300 seconds on your system.

**Comment by jkroepke** [comment]
Maybe you are hitting a bug in windows_exporter.

With 

> windows_exporter.exe --collectors.enabled service

you only have enabled a collectors which does not register and request any perflib counters.

This leads to an situation where is `where` clause gets empty. (This is what I mean with query nothing). I guess thats unknown behavior here. An empty where clause cloud also leads to return all data. But I'm unable to verify that.

Background: In windows_exporter, perfdata is always collected before collectors are called. On startup, collectors can register perfdata counters. Then if Prometheus is calling /metrics, windows_exporter scrape all registered perfdata once and will provide the data to each collector.

if you configure

> windows_exporter.exe --collectors.enabled service,os

then, there is a where clause. It would be great to know if this helps and validate the assumption. 

From perfdata point of view, there is no difference between zero collector or service collector enabled.

---

You can also try to use

> windows_exporter.exe --collectors.enabled textfile --collector.textfile.directories=path_to_dir_with_empty_file

which should do nothing. But with zero collectors, windows_exporter would still ask for perfdata.

**Comment by jkroepke** [comment]
@paologallinaharbur In case, you are still active, do you want to try out an snapshot build which should resolve your issue?`

https://github.com/prometheus-community/windows_exporter/actions/runs/10670590125/artifacts/1883017045

**Comment by paologallinaharbur** [comment]
Hello! sadly I have no access to the environment. 
Back then in order to avoid breaking the metrics (since we were using an old version and we were not able to upgrade) we added a new collector interacting with `perflib` just ti register and request some perflib counters.
That reduced dramatically the time needed to execute from 500s to 3s. That worked for us. 😄 

I think that in that old version perflib was always scraped and without any counter specified it was scraping them all 🤯

**Comment by jkroepke** [comment]
> I think that in that old version perflib was always scraped and without any counter specified it was scraping them all 🤯

Yeah, I go down the path until ReqQueryCommand and it's documented that if the key is empty, then "default" is returned.
