### ISSUE TITLE
Release plan 0.26.0

### ISSUE THREAD

**Issue by jkroepke** [prometheus-community/windows_exporter#1462]
Plans for the next official release:

If @breed808 agrees, would like to create a rc0 soon in hope to gain feedback around the recent merges. 

For an additional rc1, I would like to pull in #1451 and #1459.

One week later, after releasing rc1 and if there are no critical bugs, I would publish 0.26.0

**Comment by breed808** [comment]
> If @breed808 agrees, would like to create a rc0 soon in hope to gain feedback around the recent merges.

Yep, go right ahead.

I still need to review #1459; let me know if the perfdata collector needs to make it into this release.

**Comment by jkroepke** [comment]
> I still need to review https://github.com/prometheus-community/windows_exporter/pull/1459; let me know if the perfdata collector needs to make it into this release.

Yes, please. I will fix the lint issues together with the changes from the review.
