### ISSUE TITLE
Use labels to categorize changes

### ISSUE THREAD

**Issue by jkroepke** [prometheus-community/windows_exporter#1463]
Hi @breed808 

After releasing 0.26.0, I would like to introduce a new concept for better changelog generation.

I would introduce new issue labels to categorize changes (pull requests) on my projects, I'm using this schema:

* https://github.com/jkroepke/openvpn-auth-oauth2/blob/main/.github/release.yml

Additional, I have an CI check which enforce the labels on PRs: https://github.com/jkroepke/openvpn-auth-oauth2/blob/main/.github/workflows/pr-check.yaml

The result would be some from user point of view generated Changelogs, for example: https://github.com/jkroepke/openvpn-auth-oauth2/releases/tag/v1.20.0

What did you think about?

**Comment by breed808** [comment]
I think it'll be a good improvement to our current method of generating changelogs, where we use the Github-generated output and manually modify (such as adding categories).

A couple questions:
1. Is an additional tool required to parse the schema and PR labels?
2. As all PRs will now require labels, would the project maintainers need to ensure each PR is labelled? Could we possibly allow contributors to label their own PRs (if that's even a good idea)?

**Comment by jkroepke** [comment]
> Is an additional tool required to parse the schema and PR labels?

No, it's an native feature of Github-generated changelogs

> Could we possibly allow contributors to label their own PRs? 

That would be only possible with an action that labels the PR based on a PR title prefix. In general contributor does not have permissions to define labels.

**Comment by breed808** [comment]
> No, it's an native feature of Github-generated changelogs

Nice! Let's go ahead and use the schema.

> That would be only possible with an action that labels the PR based on a PR title prefix. In general contributor does not have permissions to define labels.

I had a feeling this was the case but thought it worth asking. Let's leave the behaviour for this unchanged, and we can add labels to PRs. There's not so many PRs coming through that there'd be labelling work.
