### ISSUE TITLE
Introduce a flag to disable the default home page

### ISSUE THREAD

**Issue by JDA88** [prometheus-community/windows_exporter#1465]
Multiple security audits got triggered on our company because they found the windows exporter service responded with an html page at the root and exposed the endpoint from there (`/metrics`, `/health`, `/version`)

Even though I’m not a big fan of security by obfuscation maybe introducing a flag to disable the home page (`/`) could make sense and make the exporter less visible in enterprise environment.

**Comment by JDA88** [comment]
Is this similar to the fix https://github.com/prometheus-community/windows_exporter/pull/1448 ?

**Comment by maomaoaichirou** [comment]
@jkroepke  hi jkroepke   How do I configure it to disable secondary path debug/pprofh/ ？

**Comment by jkroepke** [comment]
https://github.com/prometheus-community/windows_exporter/pull/1448
