### ISSUE TITLE
Question: default config file?

### ISSUE THREAD

**Issue by elfranne** [prometheus-community/windows_exporter#1466]
Is a default config file location a good idea? A lot of Linux programs have a default location for a config file that it will try to use, and if not present it it will use the default settings.

Context:
I have spend multiple hours trying to install with the `--config.file` and gave up. I ended up changing the Registry key for the service. It might also be related to #1368, not changing the Registry key for the service as it was present ?

**Comment by jkroepke** [comment]
Fixed in #1611
