### ISSUE TITLE
Metrics for Latency Buckets

### ISSUE THREAD

**Issue by trippinnik** [prometheus-community/windows_exporter#1467]
Is there a way to get metrics for Latency Buckets on disk writes or reads? Like information in Event 505, StorPort

Ex:

For latency buckets of 256us, 1ms, 4ms, 16ms, 128ms, 2000ms, 6000ms, 10000ms, 20000ms, 20000+ms,
The IO Success counts are 13,21249, 2823, 243, 1, 0, 0, 0, 0, 0, 0, 0,

It would be really helpful if we could get this. I don't see anything in the current available metrics for this.

**Comment by breed808** [comment]
Unfortunately not, `windows_exporter` doesn't observe any events, but rather scrapes metrics exposed by various Windows APIs. The result is that we're limited to Counters and Gauges.

If in the future Windows exposed events or histogram/summary metrics, we'd be happy to include them in the exporter.
