### ISSUE TITLE
windows_os_timezone not updating

### ISSUE THREAD

**Issue by Oestle** [prometheus-community/windows_exporter#1486]
The metric windows_os_timezone seems to only update with a restart of the windows exporter service, which is kind of useless when you want to monitor/alert if the timezone ever changes to something it shouldn't 😅

**Comment by breed808** [comment]
After some reading this appears to be a long-outstanding issue with how the `time` library caches the timezone: https://github.com/golang/go/issues/28020

As with the [`node_exporter`](https://github.com/prometheus/node_exporter) we may want to document that a restart of the exporter is required to detect timezone changes.

**Comment by morshaq** [comment]
from where you can get  windows_os_timezone  , do we have a way to get the current time on windows server ?

**Comment by jkroepke** [comment]
> from where you can get windows_os_timezone , do we have a way to get the current time on windows server ?

No, the Windows API which is in use for that, handles timezone only. https://learn.microsoft.com/en-us/windows/win32/api/timezoneapi/nf-timezoneapi-getdynamictimezoneinformation
