### ISSUE TITLE
Document error  collector.diskdrive.md

### ISSUE THREAD

**Issue by jacbo0112** [prometheus-community/windows_exporter#1494]
The metric name prompted in this document is "disk_drive_info", but the name returned by the program is "diskdrive_info"

**Comment by jacbo0112** [comment]
If the document and the program return value names don't match, what's wrong? If the program returns the data, then I can change the document. But personally, I think there's something wrong with the data returned by the program.

**Comment by jkroepke** [comment]
Changing the program would result into a broken dashboard at end-user. 

I would the docs here, unless the current metrics are totally wrong.
