### ISSUE TITLE
Feature Request: windows_container_health_checks_failed_total

### ISSUE THREAD

**Issue by Masterwow3** [prometheus-community/windows_exporter#1503]
Is: Currently I cannot find a way to query the health checks of the containers. On Linux you can find this metric `engine_daemon_health_checks_failed_total`.

I would be happy if the windows_exporter would also get these metrics.

https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.container.md

**Comment by jkroepke** [comment]
> I would be happy if the windows_exporter would also get these metrics.

It seems like that the container service doesn't provide such metrics to get.
