### ISSUE TITLE
DFSR Collector Broken > 0.25.0

### ISSUE THREAD

**Issue by davideverall** [prometheus-community/windows_exporter#1505]
The dfsr collector is working in version 0.24.0.

- After upgrading to version 0.25.0 the exporter is not pulling any dfsr metrics
- Version 0.25.1 has the same behaviour
- OS version: Windows Server 2019 Standard

Log messages show that the collector is enabled:

```
ts=2024-05-30T09:32:19.515Z caller=dfsr.go:142 level=info collector=dfsr msg="dfsr collector is in an experimental state! Metrics for this collector have not been tested."

ts=2024-05-30T09:32:19.600Z caller=exporter.go:172 level=info msg="Enabled collectors: cs, dfsr, logical_disk, net, service, textfile, process, scheduled_task, cpu, physical_disk, os, system, tcp"

```

**Comment by jkroepke** [comment]
Add

> --collectors.dfsr.sources-enabled=connection,folder,volume

should solve the issue.
