### ISSUE TITLE
windows exoprter on win7 - TLS issue

### ISSUE THREAD

**Issue by morshaq** [prometheus-community/windows_exporter#1509]
I'm trying to install WinExporter version 0.24.0, but it fails each time with the error message: msg="TLS is disabled" http2=false address[::]:9182. I have also attempted the installation using various different ports. Additionally, I tried enabling TLS with the following commands: 
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord

Despite these steps, the issue persists. Do you have any idea why this is happening and how to fix it?

**Comment by jkroepke** [comment]
the error you mention isn't an error. It's an info log line.
