### ISSUE TITLE
AD collector Failed collecting ad metrics

### ISSUE THREAD

**Issue by Netsky349** [prometheus-community/windows_exporter#152]
Hello Everyone ,

I want to use "ad" collector so when i run this command from powershell :

.\wmi.exporter.exe "-collectors.enabled" "ad" 

I have this errors (on my server active directory) :

> 2018/02/06 15:38:27 [ERROR] failed collecting ad metrics: <nil> Une exception s'est produite. (Demande non valide )
> time="2018-02-06T15:38:27+01:00" level=error msg="ERROR: ad collector failed after 0.018784s: Une exception s'est produi
> te. (Demande non valide )" source="exporter.go:90"

You have any ideas ?

**Comment by carlpett** [comment]
Hi,
Typically this happens when the wmi class is for some reason not registered in Windows. Can you try running this in Powershell?
`Get-WmiObject Win32_PerfRawData_DirectoryServices_DirectoryServices`

**Comment by Netsky349** [comment]
Hi Carl,

When i run this command i have this results : 

> 
> > 
> > __GENUS                                                          : 2
> > __CLASS                                                          : Win32_PerfRawData_DirectoryServices_DirectoryService
> >                                                                    s
> > __SUPERCLASS                                                     : Win32_PerfRawData
> > __DYNASTY                                                        : CIM_StatisticalInformation
> > __RELPATH                                                        : Win32_PerfRawData_DirectoryServices_DirectoryService
> >                                                                    s.Name="NTDS"
> > __PROPERTY_COUNT                                                 : 178
> > __DERIVATION                                                     : {Win32_PerfRawData, Win32_Perf,
> >                                                                    CIM_StatisticalInformation}
> > __SERVER                                                         : ADOEUX
> > __NAMESPACE                                                      : root\cimv2
> > __PATH                                                           : \\xxx\root\cimv2:Win32_PerfRawData_DirectoryServi
> >                                                                    ces_DirectoryServices.Name="NTDS"
> > ABANRPersec                                                      : 0
> > ABBrowsesPersec                                                  : 0
> > ABClientSessions                                                 : 0
> > ABMatchesPersec                                                  : 0
> > ABPropertyReadsPersec                                            : 0
> > ABProxyLookupsPersec                                             : 0
> > ABSearchesPersec                                                 : 0
> > ApproximatehighestDNT                                            : 28950
> > ATQEstimatedQueueDelay                                           : 0
> > ATQOutstandingQueuedRequests                                     : 0
> > ATQRequestLatency                                                : 0
> > ATQThreadsLDAP                                                   : 1
> > ATQThreadsOther                                                  : 0
> > ATQThreadsTotal                                                  : 7
> > BasesearchesPersec                                               : 3006329
> > Caption                                                          :
> > DatabaseaddsPersec                                               : 140
> > DatabasedeletesPersec                                            : 90
> > DatabasemodifysPersec                                            : 418990
> > DatabaserecyclesPersec                                           : 36
> > Description                                                      :
> > DigestBindsPersec                                                : 0
> > DirSyncsessionsinprogress                                        : 0
> > DirSyncsessionthrottlingrate                                     : 0
> > DRAHighestUSNCommittedHighpart                                   : 0
> > DRAHighestUSNCommittedLowpart                                    : 47815730
> > DRAHighestUSNIssuedHighpart                                      : 0
> > DRAHighestUSNIssuedLowpart                                       : 47815731
> > DRAInboundBytesCompressedBetweenSitesAfterCompressionPersec      : 0
> > DRAInboundBytesCompressedBetweenSitesAfterCompressionSinceBoot   : 0
> > DRAInboundBytesCompressedBetweenSitesBeforeCompressionPersec     : 0
> > DRAInboundBytesCompressedBetweenSitesBeforeCompressionSinceBoot  : 0
> > DRAInboundBytesNotCompressedWithinSitePersec                     : 180965960
> > DRAInboundBytesNotCompressedWithinSiteSinceBoot                  : 180965960
> > DRAInboundBytesTotalPersec                                       : 180965960
> > DRAInboundBytesTotalSinceBoot                                    : 180965960
> > DRAInboundFullSyncObjectsRemaining                               : 0
> > DRAInboundLinkValueUpdatesRemaininginPacket                      : 0
> > DRAInboundObjectsAppliedPersec                                   : 149701
> > DRAInboundObjectsFilteredPersec                                  : 174
> > DRAInboundObjectsPersec                                          : 25272
> > DRAInboundObjectUpdatesRemaininginPacket                         : 0
> > DRAInboundPropertiesAppliedPersec                                : 30154
> > DRAInboundPropertiesFilteredPersec                               : 25798
> > DRAInboundPropertiesTotalPersec                                  : 55952
> > DRAInboundSyncLinkDeletionPersec                                 : 0
> > DRAInboundTotalUpdatesRemaininginPacket                          : 0
> > DRAInboundValuesDNsonlyPersec                                    : 256
> > DRAInboundValuesTotalPersec                                      : 64755
> > DRAOutboundBytesCompressedBetweenSitesAfterCompressionPersec     : 0
> > DRAOutboundBytesCompressedBetweenSitesAfterCompressionSinceBoot  : 0
> > DRAOutboundBytesCompressedBetweenSitesBeforeCompressionPersec    : 0
> > DRAOutboundBytesCompressedBetweenSitesBeforeCompressionSinceBoot : 0
> > DRAOutboundBytesNotCompressedWithinSitePersec                    : 153512608
> > DRAOutboundBytesNotCompressedWithinSiteSinceBoot                 : 153512608
> > DRAOutboundBytesTotalPersec                                      : 153512608
> > DRAOutboundBytesTotalSinceBoot                                   : 153512608
> > DRAOutboundObjectsFilteredPersec                                 : 25390
> > DRAOutboundObjectsPersec                                         : 3844
> > DRAOutboundPropertiesPersec                                      : 12962
> > DRAOutboundValuesDNsonlyPersec                                   : 62
> > DRAOutboundValuesTotalPersec                                     : 12180
> > DRAPendingReplicationOperations                                  : 0
> > DRAPendingReplicationSynchronizations                            : 0
> > DRASyncFailuresonSchemaMismatch                                  : 0
> > DRASyncRequestsMade                                              : 64430
> > DRASyncRequestsSuccessful                                        : 64430
> > DRAThreadsGettingNCChanges                                       : 0
> > DRAThreadsGettingNCChangesHoldingSemaphore                       : 0
> > DSClientBindsPersec                                              : 202765
> > DSClientNameTranslationsPersec                                   : 227725
> > DSDirectoryReadsPersec                                           : 2490361
> > DSDirectorySearchesPersec                                        : 6273791
> > DSDirectoryWritesPersec                                          : 419256
> > DSMonitorListSize                                                : 24
> > DSNameCachehitrate                                               : 190995250
> > DSNameCachehitrate_Base                                          : 209689941
> > DSNotifyQueueSize                                                : 0
> > DSPercentReadsfromDRA                                            : 0
> > DSPercentReadsfromDRA_Base                                       : 2490361
> > DSPercentReadsfromKCC                                            : 32732
> > DSPercentReadsfromKCC_Base                                       : 2490361
> > DSPercentReadsfromLSA                                            : 107316
> > DSPercentReadsfromLSA_Base                                       : 2490361
> > DSPercentReadsfromNSPI                                           : 0
> > DSPercentReadsfromNSPI_Base                                      : 2490361
> > DSPercentReadsfromNTDSAPI                                        : 0
> > DSPercentReadsfromNTDSAPI_Base                                   : 2490361
> > DSPercentReadsfromSAM                                            : 2341371
> > DSPercentReadsfromSAM_Base                                       : 2490361
> > DSPercentReadsOther                                              : 8942
> > DSPercentReadsOther_Base                                         : 2490361
> > DSPercentSearchesfromDRA                                         : 0
> > DSPercentSearchesfromDRA_Base                                    : 6273791
> > DSPercentSearchesfromKCC                                         : 8183
> > DSPercentSearchesfromKCC_Base                                    : 6273791
> > DSPercentSearchesfromLDAP                                        : 4274788
> > DSPercentSearchesfromLDAP_Base                                   : 6273791
> > DSPercentSearchesfromLSA                                         : 35753
> > DSPercentSearchesfromLSA_Base                                    : 6273791
> > DSPercentSearchesfromNSPI                                        : 0
> > DSPercentSearchesfromNSPI_Base                                   : 6273791
> > DSPercentSearchesfromNTDSAPI                                     : 241947
> > DSPercentSearchesfromNTDSAPI_Base                                : 6273791
> > DSPercentSearchesfromSAM                                         : 1421943
> > DSPercentSearchesfromSAM_Base                                    : 6273791
> > DSPercentSearchesOther                                           : 291177
> > DSPercentSearchesOther_Base                                      : 6273791
> > DSPercentWritesfromKCC                                           : 0
> > DSPercentWritesfromKCC_Base                                      : 419256
> > DSPercentWritesfromLDAP                                          : 25247
> > DSPercentWritesfromLDAP_Base                                     : 419256
> > DSPercentWritesfromLSA                                           : 254
> > DSPercentWritesfromLSA_Base                                      : 419256
> > DSPercentWritesfromNSPI                                          : 0
> > DSPercentWritesfromNSPI_Base                                     : 419256
> > DSPercentWritesfromNTDSAPI                                       : 16360
> > DSPercentWritesfromNTDSAPI_Base                                  : 419256
> > DSPercentWritesfromSAM                                           : 373576
> > DSPercentWritesfromSAM_Base                                      : 419256
> > DSPercentWritesOther                                             : 27
> > DSPercentWritesOther_Base                                        : 419256
> > DSSearchsuboperationsPersec                                      : 14970550
> > DSSecurityDescriptorPropagationsEvents                           : 0
> > DSSecurityDescriptorPropagatorAverageExclusionTime               : 0
> > DSSecurityDescriptorPropagatorRuntimeQueue                       : 0
> > DSSecurityDescriptorsuboperationsPersec                          : 131
> > DSServerBindsPersec                                              : 1
> > DSServerNameTranslationsPersec                                   : 498222
> > DSThreadsinUse                                                   : 1
> > ExternalBindsPersec                                              : 0
> > FastBindsPersec                                                  : 4305
> > Frequency_Object                                                 : 0
> > Frequency_PerfTime                                               : 14318180
> > Frequency_Sys100NS                                               : 10000000
> > LDAPActiveThreads                                                : 1
> > LDAPBindTime                                                     : 0
> > LDAPClientSessions                                               : 24
> > LDAPClosedConnectionsPersec                                      : 1526609
> > LDAPNewConnectionsPersec                                         : 1526633
> > LDAPNewSSLConnectionsPersec                                      : 3368
> > LDAPSearchesPersec                                               : 6017288
> > LDAPSuccessfulBindsPersec                                        : 1425349
> > LDAPUDPoperationsPersec                                          : 424832
> > LDAPWritesPersec                                                 : 3019
> > LinkValuesCleanedPersec                                          : 26
> > Name                                                             : NTDS
> > NegotiatedBindsPersec                                            : 1420736
> > NTLMBindsPersec                                                  : 2
> > OnelevelsearchesPersec                                           : 511174
> > PhantomsCleanedPersec                                            : 0
> > PhantomsVisitedPersec                                            : 0
> > SAMAccountGroupEvaluationLatency                                 : 0
> > SAMDisplayInformationQueriesPersec                               : 0
> > SAMDomainLocalGroupMembershipEvaluationsPersec                   : 8399975
> > SAMEnumerationsPersec                                            : 30
> > SAMGCEvaluationsPersec                                           : 0
> > SAMGlobalGroupMembershipEvaluationsPersec                        : 709711
> > SAMMachineCreationAttemptsPersec                                 : 10
> > SAMMembershipChangesPersec                                       : 339
> > SAMNonTransitiveMembershipEvaluationsPersec                      : 277186
> > SAMPasswordChangesPersec                                         : 926
> > SAMResourceGroupEvaluationLatency                                : 0
> > SAMSuccessfulComputerCreationsPersecIncludesallrequests          : 10
> > SAMSuccessfulUserCreationsPersec                                 : 25
> > SAMTransitiveMembershipEvaluationsPersec                         : 14110763
> > SAMUniversalGroupMembershipEvaluationsPersec                     : 5001077
> > SAMUserCreationAttemptsPersec                                    : 25
> > SimpleBindsPersec                                                : 1291
> > SubtreesearchesPersec                                            : 2756288
> > Timestamp_Object                                                 : 0
> > Timestamp_PerfTime                                               : 15068454280002
> > Timestamp_Sys100NS                                               : 131624095191730000
> > TombstonesGarbageCollectedPersec                                 : 107
> > TombstonesVisitedPersec                                          : 157
> > Transitiveoperationsmillisecondsrun                              : 0
> > TransitiveoperationsPersec                                       : 4
> > TransitivesuboperationsPersec                                    : 12
> > PSComputerName                                                   : xxx
> > 
> > __GENUS                                                          : 2
> > __CLASS                                                          : Win32_PerfRawData_DirectoryServices_DirectoryService
> >                                                                    s
> > __SUPERCLASS                                                     : Win32_PerfRawData
> > __DYNASTY                                                        : CIM_StatisticalInformation
> > __RELPATH                                                        : Win32_PerfRawData_DirectoryServices_DirectoryService
> >                                                                    s.Name="NTDS"
> > __PROPERTY_COUNT                                                 : 178
> > __DERIVATION                                                     : {Win32_PerfRawData, Win32_Perf,
> >                                                                    CIM_StatisticalInformation}
> > __SERVER                                                         : xxxx
> > __NAMESPACE                                                      : root\cimv2
> > __PATH                                                           : \\xxxx\root\cimv2:Win32_PerfRawData_DirectoryServi
> >                                                                    ces_DirectoryServices.Name="NTDS"
> > ABANRPersec                                                      : 0
> > ABBrowsesPersec                                                  : 0
> > ABClientSessions                                                 : 0
> > ABMatchesPersec                                                  : 0
> > ABPropertyReadsPersec                                            : 0
> > ABProxyLookupsPersec                                             : 0
> > ABSearchesPersec                                                 : 0
> > ApproximatehighestDNT                                            : 28950
> > ATQEstimatedQueueDelay                                           : 0
> > ATQOutstandingQueuedRequests                                     : 0
> > ATQRequestLatency                                                : 0
> > ATQThreadsLDAP                                                   : 1
> > ATQThreadsOther                                                  : 0
> > ATQThreadsTotal                                                  : 7
> > BasesearchesPersec                                               : 3006329
> > Caption                                                          :
> > DatabaseaddsPersec                                               : 140
> > DatabasedeletesPersec                                            : 90
> > DatabasemodifysPersec                                            : 418990
> > DatabaserecyclesPersec                                           : 36
> > Description                                                      :
> > DigestBindsPersec                                                : 0
> > DirSyncsessionsinprogress                                        : 0
> > DirSyncsessionthrottlingrate                                     : 0
> > DRAHighestUSNCommittedHighpart                                   : 0
> > DRAHighestUSNCommittedLowpart                                    : 47815730
> > DRAHighestUSNIssuedHighpart                                      : 0
> > DRAHighestUSNIssuedLowpart                                       : 47815731
> > DRAInboundBytesCompressedBetweenSitesAfterCompressionPersec      : 0
> > DRAInboundBytesCompressedBetweenSitesAfterCompressionSinceBoot   : 0
> > DRAInboundBytesCompressedBetweenSitesBeforeCompressionPersec     : 0
> > DRAInboundBytesCompressedBetweenSitesBeforeCompressionSinceBoot  : 0
> > DRAInboundBytesNotCompressedWithinSitePersec                     : 180965960
> > DRAInboundBytesNotCompressedWithinSiteSinceBoot                  : 180965960
> > DRAInboundBytesTotalPersec                                       : 180965960
> > DRAInboundBytesTotalSinceBoot                                    : 180965960
> > DRAInboundFullSyncObjectsRemaining                               : 0
> > DRAInboundLinkValueUpdatesRemaininginPacket                      : 0
> > DRAInboundObjectsAppliedPersec                                   : 149701
> > DRAInboundObjectsFilteredPersec                                  : 174
> > DRAInboundObjectsPersec                                          : 25272
> > DRAInboundObjectUpdatesRemaininginPacket                         : 0
> > DRAInboundPropertiesAppliedPersec                                : 30154
> > DRAInboundPropertiesFilteredPersec                               : 25798
> > DRAInboundPropertiesTotalPersec                                  : 55952
> > DRAInboundSyncLinkDeletionPersec                                 : 0
> > DRAInboundTotalUpdatesRemaininginPacket                          : 0
> > DRAInboundValuesDNsonlyPersec                                    : 256
> > DRAInboundValuesTotalPersec                                      : 64755
> > DRAOutboundBytesCompressedBetweenSitesAfterCompressionPersec     : 0
> > DRAOutboundBytesCompressedBetweenSitesAfterCompressionSinceBoot  : 0
> > DRAOutboundBytesCompressedBetweenSitesBeforeCompressionPersec    : 0
> > DRAOutboundBytesCompressedBetweenSitesBeforeCompressionSinceBoot : 0
> > DRAOutboundBytesNotCompressedWithinSitePersec                    : 153512608
> > DRAOutboundBytesNotCompressedWithinSiteSinceBoot                 : 153512608
> > DRAOutboundBytesTotalPersec                                      : 153512608
> > DRAOutboundBytesTotalSinceBoot                                   : 153512608
> > DRAOutboundObjectsFilteredPersec                                 : 25390
> > DRAOutboundObjectsPersec                                         : 3844
> > DRAOutboundPropertiesPersec                                      : 12962
> > DRAOutboundValuesDNsonlyPersec                                   : 62
> > DRAOutboundValuesTotalPersec                                     : 12180
> > DRAPendingReplicationOperations                                  : 0
> > DRAPendingReplicationSynchronizations                            : 0
> > DRASyncFailuresonSchemaMismatch                                  : 0
> > DRASyncRequestsMade                                              : 64430
> > DRASyncRequestsSuccessful                                        : 64430
> > DRAThreadsGettingNCChanges                                       : 0
> > DRAThreadsGettingNCChangesHoldingSemaphore                       : 0
> > DSClientBindsPersec                                              : 202765
> > DSClientNameTranslationsPersec                                   : 227725
> > DSDirectoryReadsPersec                                           : 2490361
> > DSDirectorySearchesPersec                                        : 6273791
> > DSDirectoryWritesPersec                                          : 419256
> > DSMonitorListSize                                                : 24
> > DSNameCachehitrate                                               : 190995250
> > DSNameCachehitrate_Base                                          : 209689941
> > DSNotifyQueueSize                                                : 0
> > DSPercentReadsfromDRA                                            : 0
> > DSPercentReadsfromDRA_Base                                       : 2490361
> > DSPercentReadsfromKCC                                            : 32732
> > DSPercentReadsfromKCC_Base                                       : 2490361
> > DSPercentReadsfromLSA                                            : 107316
> > DSPercentReadsfromLSA_Base                                       : 2490361
> > DSPercentReadsfromNSPI                                           : 0
> > DSPercentReadsfromNSPI_Base                                      : 2490361
> > DSPercentReadsfromNTDSAPI                                        : 0
> > DSPercentReadsfromNTDSAPI_Base                                   : 2490361
> > DSPercentReadsfromSAM                                            : 2341371
> > DSPercentReadsfromSAM_Base                                       : 2490361
> > DSPercentReadsOther                                              : 8942
> > DSPercentReadsOther_Base                                         : 2490361
> > DSPercentSearchesfromDRA                                         : 0
> > DSPercentSearchesfromDRA_Base                                    : 6273791
> > DSPercentSearchesfromKCC                                         : 8183
> > DSPercentSearchesfromKCC_Base                                    : 6273791
> > DSPercentSearchesfromLDAP                                        : 4274788
> > DSPercentSearchesfromLDAP_Base                                   : 6273791
> > DSPercentSearchesfromLSA                                         : 35753
> > DSPercentSearchesfromLSA_Base                                    : 6273791
> > DSPercentSearchesfromNSPI                                        : 0
> > DSPercentSearchesfromNSPI_Base                                   : 6273791
> > DSPercentSearchesfromNTDSAPI                                     : 241947
> > DSPercentSearchesfromNTDSAPI_Base                                : 6273791
> > DSPercentSearchesfromSAM                                         : 1421943
> > DSPercentSearchesfromSAM_Base                                    : 6273791
> > DSPercentSearchesOther                                           : 291177
> > DSPercentSearchesOther_Base                                      : 6273791
> > DSPercentWritesfromKCC                                           : 0
> > DSPercentWritesfromKCC_Base                                      : 419256
> > DSPercentWritesfromLDAP                                          : 25247
> > DSPercentWritesfromLDAP_Base                                     : 419256
> > DSPercentWritesfromLSA                                           : 254
> > DSPercentWritesfromLSA_Base                                      : 419256
> > DSPercentWritesfromNSPI                                          : 0
> > DSPercentWritesfromNSPI_Base                                     : 419256
> > DSPercentWritesfromNTDSAPI                                       : 16360
> > DSPercentWritesfromNTDSAPI_Base                                  : 419256
> > DSPercentWritesfromSAM                                           : 373576
> > DSPercentWritesfromSAM_Base                                      : 419256
> > DSPercentWritesOther                                             : 27
> > DSPercentWritesOther_Base                                        : 419256
> > DSSearchsuboperationsPersec                                      : 14970550
> > DSSecurityDescriptorPropagationsEvents                           : 0
> > DSSecurityDescriptorPropagatorAverageExclusionTime               : 0
> > DSSecurityDescriptorPropagatorRuntimeQueue                       : 0
> > DSSecurityDescriptorsuboperationsPersec                          : 131
> > DSServerBindsPersec                                              : 1
> > DSServerNameTranslationsPersec                                   : 498222
> > DSThreadsinUse                                                   : 1
> > ExternalBindsPersec                                              : 0
> > FastBindsPersec                                                  : 4305
> > Frequency_Object                                                 : 0
> > Frequency_PerfTime                                               : 14318180
> > Frequency_Sys100NS                                               : 10000000
> > LDAPActiveThreads                                                : 1
> > LDAPBindTime                                                     : 0
> > LDAPClientSessions                                               : 24
> > LDAPClosedConnectionsPersec                                      : 1526609
> > LDAPNewConnectionsPersec                                         : 1526633
> > LDAPNewSSLConnectionsPersec                                      : 3368
> > LDAPSearchesPersec                                               : 6017288
> > LDAPSuccessfulBindsPersec                                        : 1425349
> > LDAPUDPoperationsPersec                                          : 424832
> > LDAPWritesPersec                                                 : 3019
> > LinkValuesCleanedPersec                                          : 26
> > Name                                                             : NTDS
> > NegotiatedBindsPersec                                            : 1420736
> > NTLMBindsPersec                                                  : 2
> > OnelevelsearchesPersec                                           : 511174
> > PhantomsCleanedPersec                                            : 0
> > PhantomsVisitedPersec                                            : 0
> > SAMAccountGroupEvaluationLatency                                 : 0
> > SAMDisplayInformationQueriesPersec                               : 0
> > SAMDomainLocalGroupMembershipEvaluationsPersec                   : 8399975
> > SAMEnumerationsPersec                                            : 30
> > SAMGCEvaluationsPersec                                           : 0
> > SAMGlobalGroupMembershipEvaluationsPersec                        : 709711
> > SAMMachineCreationAttemptsPersec                                 : 10
> > SAMMembershipChangesPersec                                       : 339
> > SAMNonTransitiveMembershipEvaluationsPersec                      : 277186
> > SAMPasswordChangesPersec                                         : 926
> > SAMResourceGroupEvaluationLatency                                : 0
> > SAMSuccessfulComputerCreationsPersecIncludesallrequests          : 10
> > SAMSuccessfulUserCreationsPersec                                 : 25
> > SAMTransitiveMembershipEvaluationsPersec                         : 14110763
> > SAMUniversalGroupMembershipEvaluationsPersec                     : 5001077
> > SAMUserCreationAttemptsPersec                                    : 25
> > SimpleBindsPersec                                                : 1291
> > SubtreesearchesPersec                                            : 2756288
> > Timestamp_Object                                                 : 0
> > Timestamp_PerfTime                                               : 15068454280002
> > Timestamp_Sys100NS                                               : 131624095191730000
> > TombstonesGarbageCollectedPersec                                 : 107
> > TombstonesVisitedPersec                                          : 157
> > Transitiveoperationsmillisecondsrun                              : 0
> > TransitiveoperationsPersec                                       : 4
> > TransitivesuboperationsPersec                                    : 12
> > PSComputerName                                                   : xxxx
> 
> 
>

**Comment by carlpett** [comment]
Ok, so the WMI parts are working, good.
I see from your original post that you are running this from a terminal? Was it run in an administrative terminal?

**Comment by Netsky349** [comment]
yes of course :) 

![captureadwmi](https://user-images.githubusercontent.com/22470084/35906386-8ba00bc0-0bea-11e8-8501-66072d18fa4f.JPG)

**Comment by carlpett** [comment]
This is odd. We're not doing much else than what that powershell call does. I'm beginning to wonder if there might be something to do with non-english locales - this type of problems have been reported very often with different language settings... 
Do other collectors work fine on this machine?

**Comment by carlpett** [comment]
From looking a bit closer at the output you gave, it seems your machine actually does not report one of the counters we expect, `DSPercentWritesfromDRA`. What is the version of Windows you are using?

**Comment by Netsky349** [comment]
I'm using the Windows 2016 server, I just changed language system but I have the same problem on the AD collector.

**Comment by carlpett** [comment]
I've built a test-build which removes the counter that was not present on your system, could you give it a shot and see if it works?
[wmi_exporter.zip](https://github.com/martinlindhe/wmi_exporter/files/1706840/wmi_exporter.zip)

**Comment by Netsky349** [comment]
It works:) good ! thank's for your help. Can you give me the msi too?

**Comment by carlpett** [comment]
Nice! The patch is a breaking change, though, so I'll have to try to make it compatible before merging it in. 
Also would be interesting to figure out how come your system does not have that counter...

**Comment by Netsky349** [comment]
yes indeed I don't have any specific configuration on AD. Can you tell me what counter is missing?

**Comment by carlpett** [comment]
It is named `DSPercentWritesfromDRA`, and is related to the replication agent. Do you have multiple sites in your AD?

**Comment by Netsky349** [comment]
Hello,
yes I have two active directory sites. but I don't know why I don't have DSPercentWritesfromDRA :) !

**Comment by carlpett** [comment]
Ok, thanks for checking that. I was wondering if it perhaps didn't show up if you only had one site, but then we can remove that possibility. 
I haven't had time to look at how to do "feature detection" yet, it is a bit tricky to get right, sadly
