### ISSUE TITLE
version windows

### ISSUE THREAD

**Issue by darkamumu** [prometheus-community/windows_exporter#1520]
the exporter is not update for indentify windows 11 versions it always stay in windows 10

windows_os_info{build_number="22631",major_version="10",minor_version="0",product="Microsoft Windows 10 Pro",revision="3672",version="10.0.22631"} 1

![image](https://github.com/prometheus-community/windows_exporter/assets/52228854/ad66961c-7c56-4231-b07f-0f5d898c328f)

**Comment by jkroepke** [comment]
Hi,

this is correct and by design. The major version of Windows 11 is still 10. "Windows 11" is just the product name.

ref: https://learn.microsoft.com/en-us/answers/questions/586548/in-the-official-version-of-windows-11-why-the-key
