### ISSUE TITLE
switching on process does not work

### ISSUE THREAD

**Issue by tune007** [prometheus-community/windows_exporter#1521]
Good day, apologies if this is the incorrect place to log this, I am trying to switch on processes inside the windows_exporter to only expose CPU usage for a single process but it does not seem to be working. Running the following line to test windows_exporter starts and metrics are available but not for process, please can you tell me what I am doing wrong here: windows_exporter-0.25.1-amd64.exe --collector.process.include="instana.*" --collector.process.exclude="ssm.*"

**Comment by jkroepke** [comment]
Try

> windows_exporter-0.25.1-amd64.exe --collector.process.include="instana.*" --collector.process.exclude="ssm.*"

**Comment by tune007** [comment]
hi previous comment was incorrect I already had the settings like this 

    windows_exporter-0.25.1-amd64.exe --collector.process.include="instana.*" --collector.process.exclude="ssm.*"

**Comment by jkroepke** [comment]
did you enable the process collector?

> --collectors.enabled="[defaults],process"

**Comment by tune007** [comment]
awesome that worked thank you, must have missed the enable part somehwere in the documentation

**Comment by tune007** [comment]
closing the issue
