### ISSUE TITLE
remote_fx spamming log

### ISSUE THREAD

**Issue by wermuthy** [prometheus-community/windows_exporter#1523]
The remote_fx collector causes my event viewer to get spammed with the following error every 10 seconds:
ts=2024-06-13T07:07:04.463Z caller=prometheus.go:186 level=error msg="collector remote_fx failed after 0.000000s" err="counter not found"

I used the following command to install windows_exporter:
msiexec.exe /norestart /i "windows_exporter-0.25.1-amd64.msi" ENABLED_COLLECTORS=logical_disk,cpu,cs,os,system,net,vmware,logon,terminal_services,tcp,remote_fx

The server is Windows Server 2022 and running as a virtual machine on vSphere.

Is there any way to stop the log spam?

**Comment by jkroepke** [comment]
removing remote_fx from ENABLED_COLLECTORS should resolve your issue.

**Comment by wermuthy** [comment]
I would like to have remote_fx enabled to look at rdp session stats.
Are there any requirements to enable this?

**Comment by jkroepke** [comment]
Pretty sure, you may hit this bug: https://github.com/prometheus-community/windows_exporter/pull/1511

The current workaround is downgrade to 0.24.

**Comment by wermuthy** [comment]
After the downgrade to 0.24.0 i still get the same Error

Error in eventviewer:
Die Beschreibung für die Ereignis-ID "3299" aus der Quelle "windows_exporter" wurde nicht gefunden. Entweder ist die Komponente, die dieses Ereignis auslöst, nicht auf dem lokalen Computer installiert, oder die Installation ist beschädigt. Sie können die Komponente auf dem lokalen Computer installieren oder reparieren.

Falls das Ereignis auf einem anderen Computer aufgetreten ist, mussten die Anzeigeinformationen mit dem Ereignis gespeichert werden.

Die folgenden Informationen wurden mit dem Ereignis gespeichert: 

ts=2024-06-14T08:52:04.460Z caller=prometheus.go:188 level=error msg="collector remote_fx failed after 0.000000s" err="counter not found"


Die Nachrichtenressource ist vorhanden, die Nachricht wurde in der Nachrichtentabelle jedoch nicht gefunden


I installed it like this:
msiexec.exe /norestart /i "windows_exporter-0.24.0-amd64.msi" ENABLED_COLLECTORS=logical_disk,cpu,cs,os,system,net,vmware,logon,remote_fx,terminal_services,tcp

**Comment by jkroepke** [comment]
Maybe the collectors are not availible on Windows 2022 or disabled by default. Not sure.

**Comment by jkroepke** [comment]
I can confirm, the https://github.com/prometheus-community/windows_exporter/pull/1511 is resolving the issue.
