### ISSUE TITLE
Windows Status Service NOT change when service restart less 2s

### ISSUE THREAD

**Issue by quoctuan2311** [prometheus-community/windows_exporter#1528]
Windows Exporter Version: v0.21.0
I start windows exporter with default config.

But when used
- Metrics `windows_service_status` and `status="ok"`
- Metrics `windows_service_state` and `state="running"`

It not change from 1 to 0 when have service restart less 2s with 2 metrics.
Because windows_exporter will collect data each 30s. Therefore missing this data.
I have testing with metrics `windows_process_start_time` but process it not match with service name.

Have option to check start time service? Or How to check service restart with time restart very fast?

**Comment by andonovski** [comment]
Query for check start time in Grafana:
`windows_process_start_time{instance="HOST:PORT",process="ProcessName"} * 1000
`
On the left side, under **Standard** options for Unit choose **Datetime ISO**

And try to use the latest exporter. There are bugfixes between 0.21.0 and latest one 0.26.2. Maybe it was some bug in 0.21.0.

**Comment by quoctuan2311** [comment]
> Query for check start time in Grafana: `windows_process_start_time{instance="HOST:PORT",process="ProcessName"} * 1000 ` On the left side, under **Standard** options for Unit choose **Datetime ISO**
> 
> And try to use the latest exporter. There are bugfixes between 0.21.0 and latest one 0.26.2. Maybe it was some bug in 0.21.0.

When using `windows_process_start_time`, My problem is process_name not match with my service name and this not is unique.

If you run 2 services with different service names but using the same .exe file, the process names will be the same. They will only differ in `process_id` and not show service_name such as metric `windows_service_status `. Therefore, I need to use the service name to distinguish them.

**Comment by jkroepke** [comment]
I implement a metric on the service collector which provide the start time of the process.

Would it be possible that someone test that?

Pre-build binaries are here: https://github.com/prometheus-community/windows_exporter/actions/runs/10541416422/artifacts/1850768213

**Comment by jkroepke** [comment]
fixed by #1584
