### ISSUE TITLE
Can we able to genrate log file to Windows_Exporter?

### ISSUE THREAD

**Issue by sumanth4356** [prometheus-community/windows_exporter#1532]
I have deployed same window exporter exe file and its required config files to all the servers. But from one server i am getting error like "Server returned HTTP status 500 internal error" i have cleared cache of the browser, reinstalled in the server still i am getting same error. Until localhost:portnumber i can able to hit once i can see metrics, health check, version info. Once i hit Metrics i am getting 500 internal server error, if i hit health check some json file is getting downloaded which is strange, if i hit version info i an able to see version details. So if possible to generate log files it would be really great .Please help me with this issue.

**Comment by jacbo0112** [comment]
Try textfile
