### ISSUE TITLE
could not identify physical drive for D:

### ISSUE THREAD

**Issue by aa-matthias** [prometheus-community/windows_exporter#1543]
### Current Behavior

getting this warning in event log every minute

ts=2024-07-30T09:29:08.286Z caller=logical_disk.go:309 level=warn collector=logical_disk msg="failed to get disk ID for D:" err="could not identify physical drive for D:"

### Expected Behavior

this volume is dynamic and spanning multiple physical volumes

![image](https://github.com/user-attachments/assets/6c007bfb-cf9a-4fdd-9b24-76f34b5c6e87)

disk_id should be allowed to be empty / first one / no warning to appear in that case?

### Environment

- windows_exporter Version: 0.26
- Windows Server Version: 2019

### windows_exporter logs

```shell
ts=2024-07-30T09:29:08.286Z caller=logical_disk.go:309 level=warn collector=logical_disk msg="failed to get disk ID for D:" err="could not identify physical drive for D:"
```

**Comment by jkroepke** [comment]
Could you please assist, what I have todo on a Windows server to replicate this? A step by step, or something similar would help.

**Comment by jkroepke** [comment]
Could you please test, if #1544 resolve your issue?

Link to binary builds: https://github.com/prometheus-community/windows_exporter/actions/runs/10170493307/artifacts/1757685369

**Comment by aa-matthias** [comment]
Hi @jkroepke - thanks, solves the issue. One minor thing: can we make the disk ids unique?

![image](https://github.com/user-attachments/assets/ffc2afd6-d1ac-4699-8a7c-b6cd4af7d8bf)

**Comment by jkroepke** [comment]
I hope, it just works. 

https://github.com/prometheus-community/windows_exporter/actions/runs/10175711056/artifacts/1758902425

**Comment by aa-matthias** [comment]
@jkroepke - perfect, thanks!

![image](https://github.com/user-attachments/assets/02b27127-df6c-4f5c-a9fa-f269aa4f520f)
