### ISSUE TITLE
EventID 3299 Log Entry Errors / terminal_services collector

### ISSUE THREAD

**Issue by calaneo** [prometheus-community/windows_exporter#1546]
### Current Behavior

We're running windows_exporter with terminal_services collector, and after update to 26.0, and later 26.1, it generates log entries every cycle (15sec), all the same, see below. windows_exporter was installed via the MSI and is running as a service with the following command line:
"C:\Program Files\windows_exporter\windows_exporter.exe" --log.file eventlog --web.listen-address 0.0.0.0:9182 --collectors.enabled "[defaults],terminal_services,logon"

Same behaviour on all three of our RDSH.

### Expected Behavior

I expect no errors. ;)

### Environment

- windows_exporter Version: 26.1
- Windows Server Version: 2019

### windows_exporter logs

```shell
The description for Event ID 3299 from source windows_exporter cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

ts=2024-08-01T13:07:16.428Z caller=wtsapi32.go:171 level=error collector=terminal_services msg="failed to free memory" err="The operation completed successfully."
```

### Anything else?

![image](https://github.com/user-attachments/assets/e4bdd7ec-0ab6-4119-8382-336149043f5f)

**Comment by jkroepke** [comment]
Sounds like that success is handled as error. I have to exclude it.

**Comment by jkroepke** [comment]
Cloud you please test https://github.com/prometheus-community/windows_exporter/actions/runs/10220353457/artifacts/1770439067 if the issues are resolved on your end?

**Comment by taotao-zkl** [comment]
May I ask how this problem was solved

**Comment by jkroepke** [comment]
install latest version
