### ISSUE TITLE
404 not found on localhost:9182 after installing v0.26.2

### ISSUE THREAD

**Issue by lordfurafura** [prometheus-community/windows_exporter#1553]
### Current Behavior

I have a working instance of windows_exporter v0.24.0 running on Server 2019 Datacenter.
When I run the msi to upgrade to v0.26.2 I get a 404 not found on localhost:9182.

### Expected Behavior

I expect to see the metrics on localhost:9182 after the upgrade.

### Steps To Reproduce

```Markdown
1. On Windows Server 2019 Datacenter
2. Run windows_exporter v0.26.2 MSI without any parameters
3. open localhost:9182 in any browser
4. see 404 not found
```

### Environment

- windows_exporter Version: 0.26.2
- Windows Server Version: 2019 Datacenter

### windows_exporter logs

```shell
Windows Event Log shows
ts=2024-08-09T06:33:01.666Z caller=ad.go:468 level=error collector=ad msg="failed collecting ad metrics" desc=null err="Exception occurred. (Invalid class )"
```

**Comment by jkroepke** [comment]
You habe to open `localhost:9182/metrics`

**Comment by irnmn** [comment]
![win_exp_0262](https://github.com/user-attachments/assets/8d01ba0a-03de-41e1-a174-f158ce1396f3)
![win_exp_0251](https://github.com/user-attachments/assets/aafc04d5-098e-4d7d-83d8-9082106872ef)

this check is suitable if you install via ansible and do the check

`    - name: "Verify is responding to requests {{ windows_exporter_bin_name }}"
      ansible.windows.win_uri:
        url: http://localhost:9182/
        return_content: true
      register: metrics_output
      failed_when: "'Metrics' not in metrics_output.content"
      when:
        - windows_exporter_start_mode != 'disabled'
        - windows_exporter_start_mode != 'manual'
        - windows_exporter_state == 'started' or windows_exporter_state == 'restarted'

    - name: "Print metrics_output {{ windows_exporter_bin_name }}"
      ansible.builtin.debug:
        msg:
          # -  all metrics "{{ metrics_output }}"
          - "Response URI: {{ metrics_output.response_uri }}"
          - "Status Code: {{ metrics_output.status_code }}"
          - "Status Description: {{ metrics_output.status_description }}"`

**Comment by irnmn** [comment]
`TASK [../../windows-roles/windows-exporter : Print metrics_output windows_exporter] **********************************************************************************************
Friday 09 August 2024  17:00:22 +0300 (0:00:01.741)       0:00:01.848 ********* 
Friday 09 August 2024  17:00:22 +0300 (0:00:01.742)       0:00:01.848 ********* 
ok: [server_name1] => {
    "msg": [
        "Response URI: http://localhost:9182/",
        "Status Code: 200",
        "Status Description: OK"
    ]
}`

**Comment by jkroepke** [comment]
You have to open localhost:9182/metrics

The landing page at / is gone.

**Comment by lordfurafura** [comment]
I'd also like to add that I also got confused by the following change:
> installer: Disable Windows Firewall Exception by default. Can be re-enabled with ADD_FIREWALL_EXCEPTION=yes
404 on landing page + missing data in Grafana due to missing firewall rules made me panic

**Comment by LeiYangGH** [comment]
> /metrics

should be added to readme.
