### ISSUE TITLE
Missing windows_cpu_ metrics in latest version 0.26.2 (counter not found)

### ISSUE THREAD

**Issue by andonovski** [prometheus-community/windows_exporter#1554]
### Current Behavior

After upgrading from version 0.25.1, metrics with name windows_cpu_ were missing, except windows_cpu_info. The windows_exporter service is stopped before upgrade.
After a restart of windows_exporter service the missing metrics appeared again.

### Expected Behavior

After upgrade all metrics should be present, no metrics should be missing.

### Steps To Reproduce

```Markdown
1. Download windows_exporter version 0.26.2
2. Stop the windows_exporter service
3. Run the MSI installer
4. Check the metrics on host by going to the URL http://HOST:8192/metrics, and all metrics with name starting with windows_cpu_ are missing
```

### Environment

- windows_exporter Version: 0.26.2
- Windows Server Version: 2022

### windows_exporter logs

```shell
ts=2024-08-09T19:17:26.377Z caller=prometheus.go:186 level=error msg="collector cpu failed after 0.000000s" err="counter not found"
ts=2024-08-09T19:17:26.400Z caller=time.go:105 level=error collector=time msg="failed collecting time metrics" err="counter not found"
ts=2024-08-09T19:17:26.426Z caller=prometheus.go:186 level=error msg="collector time failed after 0.025390s" err="counter not found"
```

### Anything else?

This happened on my two servers where I upgraded the exporter. I will wait for some reply before upgrading the exporter on other servers. Maybe I can run some debug while doing upgrade or start service in debug mode, so it might help in troubleshooting if there is a real issue or not.

**Comment by jkroepke** [comment]
Could you try to follow the step from here:

https://learn.microsoft.com/en-us/troubleshoot/windows-server/performance/manually-rebuild-performance-counters#rebuild-all-performance-counters-including-extensible-and-third-party-counters

**Comment by haipengzzz** [comment]
> Could you try to follow the step from here:
> 
> https://learn.microsoft.com/en-us/troubleshoot/windows-server/performance/manually-rebuild-performance-counters#rebuild-all-performance-counters-including-extensible-and-third-party-counters

Thanks for your reply, this solved my problem

**Comment by jkroepke** [comment]
> I will wait for some reply before upgrading the exporter on other servers.

Please hold your updates, if you plan more. I guess the issue is in the MSI installer and I will fix it soon.

**Comment by andonovski** [comment]
> > I will wait for some reply before upgrading the exporter on other servers.
> 
> Please hold your updates, if you plan more. I guess the issue is in the MSI installer and I will fix it soon.

I upgraded one other server, no issues with so. Maybe something wrong with first two.

I still have 4 other servers to upgrade. Will wait if you find some bug. 

Thanks! 

> > I will wait for some reply before upgrading the exporter on other servers.
> 
> Please hold your updates, if you plan more. I guess the issue is in the MSI installer and I will fix it soon.
