### ISSUE TITLE
Event_Viewer

### ISSUE THREAD

**Issue by MohammedSalehAk** [prometheus-community/windows_exporter#1578]
### Problem Statement

Hi guys,
I would like to ask if there is a windows_exporter collector for the error log (critical error) on the server. 
like the os and logon collectors

Depend on the issues. There is no collector for this future, and I should use Loki for this future. If this is correct, I would like the owner to add this future. 

I want the Error log from the windows logs
 
### Environment

- windows_exporter Version:0.26/0.25
- Windows Server Version:2022

**Comment by jkroepke** [comment]
Hi, there is not such collector planned. 

As I know, WMI can used for get the number of event logs based on criteria.

**Comment by MohammedSalehAk** [comment]
Hello,

So by use windows_exporter i can't have the event viewer logs (error) so to do this i should use power-shell to return if there is any error in windows logs

**Comment by jkroepke** [comment]
Currently, yes.

**Comment by MohammedSalehAk** [comment]
Another question,

so can i return if there any disk failure based on any metrics
