### ISSUE TITLE
cache collector

### ISSUE THREAD

**Issue by Sixty502** [prometheus-community/windows_exporter#1579]
### Problem Statement

I enabled the Cache collector on 0.27.2 and used the query listed in the docs: windows_cache_copy_read_hits_total / windows_cache_copy_reads_total * 100 .  The result is always zero.  When I looked at just windows_cache_copy_read_hits_total, it is always zero which seems to explain why the query is always zero.

I checked a machine running 0.24.0 and windows_cache_copy_read_hits_total is not zero.

### Environment

- windows_exporter Version: 0.27.2
- Windows Server Version: WS19, WS22

**Comment by Sixty502** [comment]
One thing I noticed is that windows_cache_copy_read_hits_total shows as a gauge in 0.24.0 (working) but is now a counter.

**Comment by jkroepke** [comment]
Hi @Sixty502 
could you test https://github.com/prometheus-community/windows_exporter/actions/runs/10623448322/artifacts/1872263723 if its solve your issue?

**Comment by Sixty502** [comment]
It appears to.  Thanks!
