### ISSUE TITLE
Install on Windows 7

### ISSUE THREAD

**Issue by daniel-al-santos** [prometheus-community/windows_exporter#1589]
### Problem Statement

I'm having trouble installing windows_exporter on Windows 7. When I click on the executable, nothing happens and if I try to use the MSI file, I receive a permission warning. When i solved the warning, the executable moved to C: and nothing. Can someone help me with this issue?

### Environment

- windows_exporter Version: windows_exporter-0.27.2-amd64
- Windows Server Version: Windows 7 Professional

**Comment by jkroepke** [comment]
It must be executed from cmd.exe Double click does nothing as I know
