### ISSUE TITLE
0.28.0 There is an error during operation

### ISSUE THREAD

**Issue by jacbo0112** [prometheus-community/windows_exporter#1598]
### Problem Statement

msg="Failed to get process information" pid=0 err="failed to open process: The parameter is incorrect."
msg="Failed to get process information" pid=4 err="failed to open process with limited permissions: Access is denied."

The above are two types of error messages. Especially the second one, there are many such error messages

### Environment

- windows_exporter Version: 0.28.0
- Windows Server Version: Windows 10

**Comment by jkroepke** [comment]
Hi, thanks for the report. I prepare 0.28.1 which fixes what issue.
