### ISSUE TITLE
Installer Parameter Default Not Set for 'ADD_FIREWALL_EXCEPTION'

### ISSUE THREAD

**Issue by shawnfunke** [prometheus-community/windows_exporter#1608]
### Current Behavior

The MSI parameter `ADD_FIREWALL_EXCEPTION` has currently no default value set, resulting in the firewall rule not being created without extra configuration.

### Expected Behavior

The MSI parameter `ADD_FIREWALL_EXCEPTION` should be set to `yes` by default, as this is also described in the README.

https://github.com/prometheus-community/windows_exporter/blob/2008dc5b239872a76202b92a4bd34dccc84d06ae/installer/windows_exporter.wxs#L20

https://github.com/prometheus-community/windows_exporter/blob/2008dc5b239872a76202b92a4bd34dccc84d06ae/README.md?plain=1#L112

### Steps To Reproduce

```Markdown
1. Install exporter using Windows MSI without setting the parameter
```

### Environment

- windows_exporter Version: `0.26.0` or above
- Windows Server Version: *

### windows_exporter logs

```shell
Not Applicable
```

**Comment by jkroepke** [comment]
Hey @shawnfunke 

thanks for the report. The docs are incorrect. It's correct that FW is not enabled by default.

Ref: https://github.com/prometheus-community/windows_exporter/pull/1447
