### ISSUE TITLE
v0.29.0-rc.0 Installer

### ISSUE THREAD

**Issue by Kherm13** [prometheus-community/windows_exporter#1622]
### Current Behavior

Installing new version windows_exporter v0.29.0.rc.0 how I normally would via PowerShell and windows service not starting up. Windows Event Viewer shows 'Cannot create another system semaphore.'

Normal Install Process:
`msiexec.exe /i "C:\temp\windows_exporter-0.29.0-rc.0-amd64.msi" /q --% EXTRA_FLAGS="--config.file=C:\windows_exporter\config\windows_exporter-config.yml"`

After looking at the windows service, it looks like its passing the new default path for --config.file AND also my extra_flags (along with --collectors.enabled [defaults])

windows_exporter path to executable
`"C:\Program Files\windows_exporter\windows_exporter.exe" --log.file eventlog --config.file="C:\Program Files\windows_exporter\config.yaml" --collectors.enabled [defaults]    --config.file=C:\windows_exporter\config\windows_exporter-config.yml   `

If I remove the first --config.file and --collectors.enabled[defaults] via the registry for the windows service, it works as expected.

`"C:\Program Files\windows_exporter\windows_exporter.exe" --log.file eventlog  --config.file=C:\windows_exporter\config\windows_exporter-config.yml   `

### Expected Behavior

powershell install with custom config file should work normally. With the new installer, its passing arguments that I don't want/need. It should take into consideration what's being passed unless there is some other way I should be passing them now?

### Steps To Reproduce

```Markdown
Run installer via PowerShell and pass EXTRA_FLAGS
Windows Service does not start up and throws 'Cannot create another system semaphore' in Event Viewer
Removing the additional --config.file and --collectors.enabled[defaults] from registry manually fixes it
```

### Environment

- windows_exporter Version: v0.29.0-rc.0
- Windows Server Version: Windows Server 2022

### windows_exporter logs

```shell
Cannot create another system semaphore.
```

**Comment by jkroepke** [comment]
Hey @Kherm13 

thanks for open a report. I appreciate that you test pre-releases.

> Cannot create another system semaphore.

Thats an error that I even observe on healthy system from windows_exporter. At the moment, I have no idea what the root cause here. 

I will introduce a separate flag similar to EXTRA_FLAGS which makes the config file configurable. If empty, the flat will be omit.
The background is https://github.com/prometheus-community/windows_exporter/issues/1466 where we would introduce a default config yaml without having the requirement to configure a YAML file.

If `ENABLED_COLLECTORS`  is set to an empty string, e.g. `msiexec.exe /i "C:\temp\windows_exporter-0.29.0-rc.0-amd64.msi" /q ENABLED_COLLECTORS=`, then the `collectors.enabled` flag will be omit to.

I guess the best solution here is to revert the change and leave the property with an empty value by default.

**Comment by jkroepke** [comment]
Hi,

could you test a snapshot build https://github.com/prometheus-community/windows_exporter/actions/runs/10820325762/artifacts/1922009735 if it meets your expectation? keep the new docs in mind, https://github.com/jkroepke/windows_exporter/blob/arm64/README.md

**Comment by Kherm13** [comment]
Ran the amd64 installer with the following command

`msiexec.exe /i "C:\temp\windows_exporter-0.29.0-rc.0-5-g2d5b0a7-amd64.msi" /q --% EXTRA_FLAGS="--config.file=C:\windows_exporter\config\windows_exporter-config.yml"`

It not longer has the --collectors.enabled [defaults] but it still has the first --config.file entry for the windows_exporter service

windows_exporter path to executable
`"C:\Program Files\windows_exporter\windows_exporter.exe" --log.file eventlog --config.file="C:\Program Files\windows_exporter\config.yaml"   --config.file=C:\windows_exporter\config\windows_exporter-config.yml  `

**Comment by jkroepke** [comment]
>  but it still has the first --config.file entry for the windows_exporter service

This is expected. You have 2 choices here:

> msiexec.exe /i "C:\temp\windows_exporter-0.29.0-rc.0-5-g2d5b0a7-amd64.msi" /q --% CONFIG_FILE="" EXTRA_FLAGS="--config.file=C:\windows_exporter\config\windows_exporter-config.yml"

or 

> msiexec.exe /i "C:\temp\windows_exporter-0.29.0-rc.0-5-g2d5b0a7-amd64.msi" /q --% CONFIG_FILE="C:\windows_exporter\config\windows_exporter-config.yml"

**Comment by Kherm13** [comment]
Got ya - will give it another try and report back! Thanks for the quick responses

**Comment by Kherm13** [comment]
This appears to work

`msiexec.exe /i "C:\temp\windows_exporter-0.29.0-rc.0-5-g2d5b0a7-amd64.msi" /q --% CONFIG_FILE="C:\windows_exporter\config\windows_exporter-config.yml"`

**Comment by jkroepke** [comment]
I'm aware that there is a breaking change, I will try to highlight this more at the final changelog. 

The background was that some users had serious issues like https://github.com/prometheus-community/windows_exporter/issues/1466 and the msi installer is not so fully flexible to cover a breaking change.

I hope thats fine here.
