### ISSUE TITLE
event log spamming in 0.29.0-rc2

### ISSUE THREAD

**Issue by aa-matthias** [prometheus-community/windows_exporter#1629]
### Current Behavior

after updating to 0.29.0-rc2 i'm getting a lot of error entries to windows event log

why is the succeeded message considered as an error? and does it really take that long? if i'm loading the /metris endpoints it loads within a second easily.

ts=2024-09-13T10:02:57.603+02:00 level=error caller=prometheus.go:238 msg="collector logical_disk succeeded after 9s"

### Expected Behavior

no errors should be added to event log when metrics are fetched successfully.

### Environment

- windows_exporter Version: 0.29.0-rc2
- Windows Server Version: 2019

### windows_exporter logs

```shell
ts=2024-09-13T10:02:57.603+02:00 level=error caller=prometheus.go:238 msg="collector logical_disk succeeded after 9s"
```

**Comment by jkroepke** [comment]
Hi @aa-matthias 

that issue is fixed by #1626 but I thought it not worth enough to release an other RC for that, but maybe I will do it.

**Comment by jkroepke** [comment]
https://github.com/prometheus-community/windows_exporter/releases/tag/v0.29.0-rc.3

**Comment by aa-matthias** [comment]
thanks! v0.29.0-rc.3 fixed the issue!
