### ISSUE TITLE
Ability to adjust labels for metrics

### ISSUE THREAD

**Issue by acx-dartemiev** [prometheus-community/windows_exporter#1630]
### Problem Statement

Hello Guys,

Help me understand how to customize/reconfigure the labels to get more information about Kubernetes pods, because right now I only see the container_id label, and it's not clear which specific pod it is and how to identify it. I would like to see more information like container_name, namespace, etc.

### Environment

- windows_exporter Version: v0.28.1
- Windows Server Version: 2022

**Comment by jkroepke** [comment]
Hi @acx-dartemiev 

this is natively impossible. the common practice is to install kube-state-metrics on the cluster and than combine the metrics together based on the container_id

```
  windows_container_network_transmit_bytes_total{container_id!=""}
* on (container_id) group_left (container, pod, namespace)
  max by (container, container_id, pod, namespace) (kube_pod_container_info{container_id!=""})
```
