### ISSUE TITLE
information log - Event viewer windows exporter

### ISSUE THREAD

**Issue by JuanJose99** [prometheus-community/windows_exporter#1661]
### Problem Statement

Regards, hope all of you be okay.

I've been seeing this event every five or fifteen seconds in the event viewer:

"The description for Event ID 3299 from source windows_exporter cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

ts=2024-10-02T07:37:05.021-05:00 level=info caller=prometheus.go:276 msg="collector service succeeded after 185.2739ms, resulting in 3449 metrics""

It happens with the last version 0.29.1 and happened with older releases.
¿It is normal this behavior ?

### Environment

- windows_exporter Version: 0.29.1-amd64
- Windows Server Version: 2016 Standard 10.0.14393

**Comment by jkroepke** [comment]
Hi @JuanJose99 

the error appears, if windows_exporter was upgrades from a very old version.

Until 0.28, the command `reg delete HKLM\SYSTEM\CurrentControlSet\Services\EventLog\Application\windows_exporter /f` where executed inside the msi installer once.

Now, the command must be run manually or and older installer, like 0.28 must the executed first.

**Comment by JuanJose99** [comment]
Hi @jkroepke.
Thanks for your answer.

I look for the reg directly in the regedit but i didn't find "windows exporter" and run manually didnt work.
So, Proced to uninstall the new version and install 0.28 as you said and the event every 5 or 15 secs has stopped.

I said, ok, I'm going to install again 0.29.1, but when it finished i see the same log every seconds.
![image](https://github.com/user-attachments/assets/6e98c16f-9ad3-4fb8-ae8e-3fb602392303)

But I see that every event at the end is:
"collector service succeeded after 228.7339ms, resulting in 3530 metrics"
"collector os succeeded after 8.999ms, resulting in 14 metrics"
"collector logical_disk succeeded after 1.9983ms, resulting in 68 metrics"

I can assume that it is reporting the task being performed, leaving out the message:
"The description for Event ID 3299 from source windows_exporter cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer."

¿Should I put attention to this or ignore it, or stay in version 0.28.?

Thank you very much for your work.

**Comment by Kherm13** [comment]
I have a new server that never had windows_exporter installed on it before. Installed version 0.29.1 and am also getting the 3299 logs spammed anytime its collecting metrics.

Reg key `HKLM\SYSTEM\CurrentControlSet\Services\EventLog\Application\windows_exporter` does not exist

**Comment by jkroepke** [comment]
Now I got it. Could you please try 0.29.2

**Comment by Kherm13** [comment]
So far so good on my side

**Comment by Samuel-Howe11** [comment]
@jkroepke  it appears that we are still having issues. upgraded from 0.29.1 to 0.29.2 (on Windows Server 2019 Standard Version 1809.) Now, instead of getting spam info logs I'm not getting any metrics. Any suggestions?

![Radmin_wwa46swknx](https://github.com/user-attachments/assets/ef002bb4-f4e5-4b8b-819a-bfc57a43cc54)
