### ISSUE TITLE
Version 0.29.1 issue with monitoring services

### ISSUE THREAD

**Issue by andonovski** [prometheus-community/windows_exporter#1669]
### Current Behavior

I don't know if it's really a bug or something with my configuration. In version 0.29.1 I get alerts for stopped services whose start type is Automatic Triggered. In version 0.27.2 this is not happening. I did upgrade from0.27.2 to 0.29.1

On my machines there are 3 services that are stopped and start type is Automatic Triggered:

- Software protection
- Delivery Optimization
- Remote registry

Now, for Software protection there is no alert, for other two I have alert. Server restart or windows exporter service restart doesn't help.

### Expected Behavior

Expected behavior is that there are no alerts for services that are stopped, and they have start type Automatic, Triggered. This was the case in 0.27.2, which I can confirm, I still have one machine with this older version.

### Environment

- windows_exporter Version: 0.29.1
- Windows Server Version: 2022

### windows_exporter logs

```shell
There are no logs for this, just very different behavior from previous version.
```

**Comment by JDA88** [comment]
Can you please post the alerting rule that trigger?

**Comment by andonovski** [comment]
This is alert rule that triggers the alert:
(windows_service_state{name!~"remoteregistry|sppsvc|edgeupdate|staterepository|dosvc",state="stopped"} == 1) * on (name, instance) windows_service_start_mode{start_mode="auto"} == 1

Now that I look at this, it is strange that I am getting alerts only for two services which should be excluded. It seems my alerting rule is suddenly wrong.

Now, for windows exporter 0.27.2, no alert for these services. For 0.29.1, I have alerts for these services. Strange behavior, I haven't seen any change for metrics for services. Maybe I missed something or my alerting rule is bad from the start but it was working somehow.

**Comment by JDA88** [comment]
Ho ok, you added the `windows_service_start_mode` to the query.
I can't test this atm but #1584 refactored the service collector in 0.29.0, look at the row metrics to see if one of the changes affected your query

**Comment by andonovski** [comment]
To answer to myself, and anyone else who might have same issue, now the service names are not all small caps. In Prometheus the service names are now like this:
old -> remoteregistry is now RemoteRegistry
old-> dosvc is now DoSvc

So, now it matches exactly how the service is seen in Windows, small and capital letters. I can't find in any change that this is now new behavior.

**Comment by JDA88** [comment]
Ho! damn sorry I found this one also and forgot about it! You are right and in fact is not documented!

A good way to deal with it and have the alert compatible with both versions is to have the RegEx case insensitive `(?i)`

**Comment by jkroepke** [comment]
I have added this to the documentation change (https://github.com/prometheus-community/windows_exporter/pull/1584).

Is there an issue left to mention?

**Comment by andonovski** [comment]
No, no other issues. Thank you very much foe thw help!
