### ISSUE TITLE
Add cmdline to the metric "windows_process_working_set_bytes"

### ISSUE THREAD

**Issue by mg-i-alf-dan** [prometheus-community/windows_exporter#1677]
### Problem Statement

Hi everyone,

I wanted to ask if it was possible to add the cmdline to the "windows_process_working_set_bytes" metric to allow you to search for RAM consumption by subprocess. such as, RAM consumption for AppPool on IIS

**Comment by jkroepke** [comment]
Which version you are using?

**Comment by mg-i-alf-dan** [comment]
i stay use v0.29.1

**Comment by jkroepke** [comment]
Could you try this:

```
windows_process_working_set_bytes * on(process_id) group_left(cmdline) windows_process_info
```

**Comment by mg-i-alf-dan** [comment]
i get this error, i have already tried:
`
execution: found duplicate series for the match group {process_id="1344"} on the right hand-side of the operation: [{__name__="windows_process_info", cmdline="\"C:\\Program Files\\IIS\\Microsoft Web Deploy\\MsDepSvc.exe\" -runService:MsDepSvc", creating_process_id="620", instance="10.10.10.88:9182", job="WCMS04", owner="NETWORK SERVICE\\NT AUTHORITY", process="MsDepSvc", process_group_id="524", process_id="1344"}, {__name__="windows_process_info", cmdline="\"C:\\Program Files\\IIS\\Microsoft Web Deploy\\MsDepSvc.exe\" -runService:MsDepSvc", creating_process_id="616", instance="10.10.10.92:9182", job="WCMS08", owner="NETWORK SERVICE\\NT AUTHORITY", process="MsDepSvc", process_group_id="520", process_id="1344"}];many-to-many matching not allowed: matching labels must be unique on one side
`
