### ISSUE TITLE
Ask for WMI origin of windows_iis_connection_attempts_all_instances_total

### ISSUE THREAD

**Issue by mg-i-alf-dan** [prometheus-community/windows_exporter#1678]
### Problem Statement

Hi All!
As the topic, I wanted to ask from which WMI the windows_iis_connection_attempts_all_instances_total metric originates, if it were possible to know

### Environment

- windows_exporter Version: v0.29.1
- Windows Server Version: Windows Server 2019

**Comment by jkroepke** [comment]
It's a Performance Counter `\Web Service(*)\Total Connection Attempts (all instances)`, not a WMI query.
