### ISSUE TITLE
services.services-where

### ISSUE THREAD

**Issue by Kherm13** [prometheus-community/windows_exporter#1684]
### Problem Statement

It looks like that services.services-where flag was removed and now we have to use include. Is there a way to do wildcards for services? Before, I could do something like `Name LIKE "Serv%"' and it would grab all the services that started with Serv. Does't look like include has the same functionality or maybe documentation just needs updated?

### Environment

- windows_exporter Version: 0.29.1+
- Windows Server Version: Server 2022
https://github.com/prometheus-community/windows_exporter/pull/1634

**Comment by jkroepke** [comment]
You have to use regex now. `.*` is an wildcard replacement, like `Serv.*`

**Comment by Kherm13** [comment]
Got ya - this is working as expected after changing to regex. Had to include `(?)` in my include as we have a mix of services that all follow the same pattern but it appears some are capitalized and some are not.

Thank you!
