### ISSUE TITLE
Provide official choco package for installation of windows_exporter

### ISSUE THREAD

**Issue by mplieske** [prometheus-community/windows_exporter#1695]
### Problem Statement

A choco package would be great for convenience, especially for automation with puppet etc. I know there is an unofficial choco package available, but it laggs behind. Also it would be way more trustworthy, if there would be an official source.

### Proposed Solution

- Add a step to the release workflow to build and upload a choco package.

### Additional information

I would be down to implement the change. I have some experience with choco packages. If you consider adding this to your project, I would like to discuss here, what the criteria would be.

**Comment by jkroepke** [comment]
On context of puppet, the builtin package resource supports msi installer and the file resource can be used to download that msi packages, if not available via UNC path.

At the moment, the chances are quite low to distribute an addiitonal choco package

**Comment by mplieske** [comment]
Thank you for the advice with puppet. I still would love to see a choco package, but I can understand, that you do not want to manage a lot of distribution methods.

**Comment by jkroepke** [comment]
@mplieske BeforeI would invest in choco, I would more interest into a scoop package, since the scoop eco system offers auto updates for package maintainers. 

My personal preference is still winget (Windows native package manager), but it's not availible to Windows Server
