### ISSUE TITLE
Add process username to windows_process_private_bytes metric

### ISSUE THREAD

**Issue by faridprogrammer** [prometheus-community/windows_exporter#1696]
### Problem Statement

The current windows_process_private_bytes metric lacks information about the process owner (username). This information is valuable for detailed process monitoring and security analysis.

Proposed Enhancement:

- Extend the windows_process_private_bytes metric to include a "username" label.
- Update the collect method to include the process owner information.
- Utilize the existing getProcessInformation function to retrieve the process owner.

**Comment by jkroepke** [comment]
Something like that should work for you

> windows_process_working_set_bytes * on(process_id) group_left(owner) windows_process_info
