### ISSUE TITLE
Windows_exporter service collector returns the value of the "name" field using mixed case letters. Previously, lower case letters were the standard.

### ISSUE THREAD

**Issue by maciektoja** [prometheus-community/windows_exporter#1698]
### Current Behavior

windows_service_state{name=~'mssql.*',state='running'} == 1
it returns 0 rows

i have to enter name of service just like in original system is (i this case with upper case)
windows_service_state{name=~'MSSQL.*',state='running'} == 1

### Expected Behavior

exporter should export metrics in lowercase

### Environment

- windows_exporter Version: 0.29.2
- Windows Server Version: all

### windows_exporter logs

```shell
no suitable log files found
```

**Comment by jkroepke** [comment]
> exporter should export metrics in lowercase

That has been changed. Windows exporter just exporter all the names as is.

If you want to exporter all names in lower case, you can archive this through an relabel rule.

Alternativly, use as case insensitive matcher

> windows_service_state{name=~"(?i:(mssql.*))",state='running'} == 1
