### ISSUE TITLE
Unable to install/start

### ISSUE THREAD

**Issue by gr1-pro** [prometheus-community/windows_exporter#1706]
### Current Behavior

Previous versions (up to 0.20) have been installed using a PowerShell script:
`msiexec.exe /i windows_exporter-0.20.0-amd64.msi ENABLED_COLLECTORS=[defaults],process EXTRA_FLAGS="--collector.process.whitelist=""<process names specified using RegEx""" | Out-Null
`
Current version cannot be installed 'silent', so I have entered parameters by hand in the GUI.
However the installation freezes at 'Starting services'.
After a long timeout the msi allows me to cancel.

The service is now installed but cannot be started.
The EventLog contains entries with 'Cannot create another system semaphore. '

It was not possible to uninstall the failed version in the normal way.
The Program Install and Uninstall troubleshooter was however able to clean up.

### Expected Behavior

It should be possible to install and start service -preferably by a 'silent' installation

### Environment

- windows_exporter Version: 0.29.2
- Windows Server Version: 2022

### windows_exporter logs

```shell
The EventLog contains entries with 'Cannot create another system semaphore. '
```

**Comment by jkroepke** [comment]
You have to use the `/qn` flags, since thats the official slient flag for msi packages.

**Comment by gr1-pro** [comment]
> You have to use the `/qn` flags, since thats the official slient flag for msi packages.
> 
> > Cannot create another system semaphore.
> 
> That a known bug. It's logging that line while it has no real impact.

I am not bothered by the logging, but it is not possible to start windows exporter as a service.
It is however possible to start the exe from an elevated command prompt.

**Comment by jkroepke** [comment]
try without EXTRA_FLAGS first. I guess you are providing an invalid regex which lead to that situation. 

In general, the installation and service start work fine. Otherwise, we would have tons of bug reports.

**Comment by gr1-pro** [comment]
> try without EXTRA_FLAGS first. I guess you are providing an invalid regex (or powershell does some silly things here) which lead to that situation.
> 
> In general, the installation and service start work fine. Otherwise, we would have tons of bug reports.

The regex is unchanged from earlier versions.
Starting the exe from elevated command prompt (with data from EXTRA_FLAGS registered in Registry) works, while the service terminates immediately (The windows_exporter service terminated unexpectedly).

After removing the data from EXTRA_FLAGS from Registry the service starts as well.

**Comment by gr1-pro** [comment]
Found the issue:

The parameter `collector.process.whitelist` has been renamed to `collector.process.include`
