### ISSUE TITLE
What is the default configuration?

### ISSUE THREAD

**Issue by jeme** [prometheus-community/windows_exporter#1710]
### Problem Statement

So mostly a question but perhaps this could also be turned into an action.

When running a completely default install it looks like it creates a empty configuration file.
But obviously there is enabled counters.

Now I know that there is a "checkmark" on the default collectors on the landing page here, that would indicate that the default collectors are:

```
collectors:
  enabled: cpu,logical_disk,memory,net,os,physical_disk,service,system
```

But first of all that does not apear to be in sync with each page, e.g. CS is not checked by default acording to that list however navigating to the page it claims that it is (it also states that it's deprecated on that page).

So I think it would be usefull to have an actual default configuration:
 - either with the installer (so it was an actual default config, that would perhaps ensure that it was maintained).
 - or alternatively just as a reference config somewhere in the repository.

### Environment

- windows_exporter Version: 0.29.2
- Windows Server Version: 2022

**Comment by jkroepke** [comment]
here all default collectors defined:

https://github.com/prometheus-community/windows_exporter/blob/582d8dd29cddf65c9fabe9652f1f5660233a88ee/internal/types/const.go#L6

In the config, you can use `[defaults]` as placeholder, e.g. `[defaults],cpu_info` is allowed as well.
