### ISSUE TITLE
Cannot extract any objects/counters from PerfMon

### ISSUE THREAD

**Issue by Tomas-Big-Z** [prometheus-community/windows_exporter#1718]
### Problem Statement

I want to extract the available metrics in PerfMon and then feed them to Prometheus:

![image](https://github.com/user-attachments/assets/b56700f7-0d93-4fd3-bb56-d990d7e16d9a)

I followed the [tutorial](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.perfdata.md) and issued the identical command as shown there to query Memory metrics (i am using CMD as an admin):

`windows_exporter.exe --collectors.enabled "collector.perfdata" --collector.perfdata.objects="[{\"object\": \"Memory\", \"counters\": {\"Cache Faults/sec\": {\"type\": \"counter\"}}}]"`

![image](https://github.com/user-attachments/assets/ba0916cb-a134-4575-bfaa-fc5f6bbc0c79)

However, when i refresh localhost:9182/metrics i do not see any metrics starting with "windows_perfdata_"

And yes, i issued these after installation of windows_exporter:

```
lodctr.exe /E:Lsa
lodctr.exe /E:PerfProc
lodctr.exe /R
```

### Environment

- windows_exporter Version: 0.29.2
- Windows Server Version: 2022

**Comment by jkroepke** [comment]
> --collectors.enabled "collector.perfdata"

The name of the collector is just `--collectors.enabled "perfdata"`. The next version of windows_exporter notice that, if a unknown collector is configured on CLI.

**Comment by Tomas-Big-Z** [comment]
thank you, it works
