### ISSUE TITLE
We are seeing some vulnerabilities in windows-exporter binaries

### ISSUE THREAD

**Issue by shivpratap1992** [prometheus-community/windows_exporter#1720]
### Problem Statement

See these vulnerabilities in windows exporter binary for v0.25.1 version. Due to this our production system got flagged red. Can someone help and fix them quickly

Vulnerabilities along with Id:
- Libcurl Denial of Service (DoS) Vulnerability  => 380508
- GO (Go) Security Update for github.com/containerd/containerd (GHSA-7ww5-4wqc-m92c) => 996377
- GO (Go) Security Update for google.golang.org/protobuf (GHSA-8r3f-844c-mc37) => 997706
- GO (Go) Security Update for golang.org/x/net/http2 (GHSA-4v7x-pqxf-cx7m) => 997957

![image](https://github.com/user-attachments/assets/a7e5dc30-e4f3-4acb-84af-7894434c6fcb)

**Comment by jkroepke** [comment]
Update to 0.29?
