### ISSUE TITLE
Add metric or metrics to monitor ASP.net and the Queues

### ISSUE THREAD

**Issue by EricSchroeder12** [prometheus-community/windows_exporter#1732]
### Problem Statement

We have many ASP.net apps and pools and want to monitor the queues. We want something along the lines asp queue and asp.net requests queued specifically. The IIS collector is good for the IIS side but not ASP side.
 

### Proposed Solution

add a metric at least to track windows_iis_worker_requests_queued or Windows_iis_asp_queued to track these app pools

**Comment by jkroepke** [comment]
Is there an Performance Counter available for that kind of metric?

**Comment by jkroepke** [comment]
images are not visible, when you are reply by mail

**Comment by EricSchroeder12** [comment]
<img width="478" alt="image" src="https://github.com/user-attachments/assets/dee6d20d-2d28-44ee-aaf6-39fd5be3746b">

**Comment by jkroepke** [comment]
Is ASP.net standalone and should be a separate collector?

Or should be the ASP.net part of the IIS collector, since ASP.net can be only run on with IIS?

**Comment by EricSchroeder12** [comment]
Technically you would normally have an app inside IIS but you can run ASP APIs and core applications without IIS.

**Comment by jkroepke** [comment]
I guess you could try out to use the generic [perfdata](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.perfdata.md) collector

```
--collectors.enabled=perfdata --collector.perfdata.objects="[{\"object\":\"ASP.NET\",\"counters\":{\"Requests Queued\":{\"type\":\"gauge\"}}}]"
```

**Comment by EricSchroeder12** [comment]
How do I insert that into the Alloy config?

**Comment by EricSchroeder12** [comment]
So I should be able to just add it here? I m still learning the Alloy language so excuse my lack of knowledge.

`prometheus.exporter.windows "integrations_windows_exporter" {
  enabled_collectors = ["iis","cpu", "cs", "logical_disk", "net", "os", "service", "system", "time", "diskdrive"]
  service { 
    where_clause = "Name LIKE 'it%' OR Name = 'bot'"   } 

}`

**Comment by jkroepke** [comment]
> So I should be able to just add it here? 

Once alloy updated the embedded windows_exporter version, you can use it.

**Comment by EricSchroeder12** [comment]
Yep I understand that part I am just trying to make sense of how this is written in the alloy config so it will work once this collector is enabled

`prometheus.exporter.windows "integrations_windows_exporter" {
  enabled_collectors = ["perfdata","iis","cpu", "cs", "logical_disk", "net", "os", "service", "system", "time", "diskdrive"]
  perfdata { 
    objects="[{\"object\":\"ASP.NET\",\"counters\":{\"Requests Queued\":{\"type\":\"gauge\"}}}]"   } 

}`

This is my guess. Does this look correct?

**Comment by jkroepke** [comment]
Could be, depends on the implemention.

**Comment by jkroepke** [comment]
Its not an issue at windows_exporter.

May ask here; https://github.com/grafana/alloy.
