### ISSUE TITLE
MSCluster - Limited Info/Metrics

### ISSUE THREAD

**Issue by fredericklessing** [prometheus-community/windows_exporter#1743]
### Problem Statement

Hi, not sure if its just me missing something here, but;

From what I can see, this mostly just pulls a bunch of cluster configurational settings. For example, I am busy using grafana to explore the metrics, and I seem to be struggling to find things like Cluster name, Cluster resource owner, Cluster resources (ie VMs, vCPU used count, RAM, Network, VHDX metrics), Cluster events, Cluster Shared Volume (ie IO, latency, throughput), etc. Basically, all things that would pertain to monitoring the MS Failover cluster health and uptime/metrics and then be able to build alerts around that.

### Proposed Solution

Expand on what the mscluster scapers/exporters can provide. Take a look at an MS Cluster through Windows Admin Centre, and capture all of that information, just better than what WAC does it :) and faster, good grief WAC is slow.

### Additional information

Some example configs, grafana dashboards that I can just import would be hella appreciated.

Also just thank you!

### Acceptance Criteria

Proper MS Failover Cluster metrics that can be used to monitor and alert on cluster and cluster resource heath, etc
Example configs with relabeling steps, to improve metric search/discover

**Comment by jkroepke** [comment]
The docs for MSCluster are here: https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.mscluster.md

But I dont run MSCluster right now, help from the community maybe nessesary.

**Comment by fredericklessing** [comment]
Hey, ok so I think I found my issue. I have a config file, but it seems the exporter is just collecting default collector values.
The command used to install: msiexec /i <path-to-msi-file> --% CONFIG_FILE="D:\config.yaml"
This is my config:

collectors:
  enabled: cpu,cpu_info,cache,diskdrive,logical_disk,logon,memory,net,os,process,service,system,tcp,udp,time,terminal_services,hyperv,mscluster
collector:
  service:
    include: "windows_exporter"
log:
  level: warn

But looking at HTTP://<windows_exporter_host>:9182 , I can for example search cpu_info, or windows_hyperv, or windows_mscluster, but nothing comes up. This leads me to believe, either my config file is wrong, or its just not being used even though I specified it.

2nd part that I see, after going through the documentation, but not sure how, is where or how in the config file do I specify the flags?

I get that with the command, I can specify flags, but I don't see and example of a config file with the flags. I mean if I need to specify all of the flags for hyperv and mscluster...I mean you can imagine that one liner command is going to span the globe a few times over.
msiexec /i <path-to-msi-file> --% ENABLED_COLLECTORS=os,service EXTRA_FLAGS="--collectors.exchange.enabled=""ADAccessProcesses""" 

So if anyone can maybe assist with an example of a config file and the included flags, that would be great, also why it seems my install is not referencing the config file I specified.

Thank you!

**Comment by jkroepke** [comment]
which version of windows_exporter you are using?

If you ran 

> msiexec /i --% CONFIG_FILE="D:\config.yaml"

Could you double check, what is the service config?

**Comment by fredericklessing** [comment]
Ok, so version is:
windows_exporter-0.30.0-beta.1-amd64.msi

And then I can see it is using the config file specified now after uninstall and reinstall. But hyperv and mscluster collectors are not enabled: both hyperv and mscluser = 0 (Also as extra measure, running the service with an domain admin account to make sure its not permission related)
# HELP windows_exporter_collector_success windows_exporter: Whether the collector was successful.
# TYPE windows_exporter_collector_success gauge
windows_exporter_collector_success{collector="cache"} 1
windows_exporter_collector_success{collector="cpu"} 1
windows_exporter_collector_success{collector="cpu_info"} 1
windows_exporter_collector_success{collector="diskdrive"} 1
windows_exporter_collector_success{collector="hyperv"} 0
windows_exporter_collector_success{collector="logical_disk"} 1
windows_exporter_collector_success{collector="logon"} 1
windows_exporter_collector_success{collector="memory"} 1
windows_exporter_collector_success{collector="mscluster"} 0
windows_exporter_collector_success{collector="net"} 1
windows_exporter_collector_success{collector="os"} 1
windows_exporter_collector_success{collector="process"} 1
windows_exporter_collector_success{collector="service"} 1
windows_exporter_collector_success{collector="system"} 1
windows_exporter_collector_success{collector="tcp"} 1
windows_exporter_collector_success{collector="terminal_services"} 1
windows_exporter_collector_success{collector="time"} 1
windows_exporter_collector_success{collector="udp"} 1

**Comment by jkroepke** [comment]
I expect that there are some messages in the event log?

Mention that https://github.com/prometheus-community/windows_exporter/releases/tag/v0.30.0-beta.4 includes a complete rewrite of the hyper-v collector. It make much more sense to test the new version.

For mscluster, there chances are high that the beta version has a bug.

**Comment by fredericklessing** [comment]
Yeah, sorry, should've said. That is if I browse http://<windows_exporter_host>:9182/metrics

Cool, let me try beta-4, I appreciate it.

**Comment by fredericklessing** [comment]
It doesnt look like beta-4 is working for me :( 
The service starts and then stops after a few seconds. 
This is the error in event logs:
time=2024-11-22T01:22:51.653+02:00 level=ERROR source=exporter.go:190 msg="Couldn't load collectors" err="error build collector hyperv: failed to build datastore collector: failed to create Hyper-V DataStore collector: failed to add counter \\Hyper-V DataStore(*)\\Fragmentation ratio: The specified object was not found on the computer.\r\n"

**Comment by fredericklessing** [comment]
Also, just been looking at some older event logs from earlier today, and see these entries:
ts=2024-11-20T07:45:09.038Z level=error caller=hyperv.go:762 msg="failed collecting hyperV health status metrics" collector=hyperv err="WMI query failed: WMI query failed: MI_RESULT_INVALID_QUERY: "

ts=2024-11-20T07:45:09.038Z level=error caller=prometheus.go:270 msg="collector hyperv failed after 30.5217ms, resulting in 0 metrics" err="WMI query failed: WMI query failed: MI_RESULT_INVALID_QUERY: "

ts=2024-11-20T07:45:09.417Z level=error caller=prometheus.go:270 msg="collector mscluster failed after 410.4318ms, resulting in 613 metrics" err="failed to collect cluster metrics: WMI query failed: WMI query failed: MI_RESULT_INVALID_QUERY: \nfailed to collect network metrics: WMI query failed: WMI query failed: MI_RESULT_INVALID_QUERY: "

Hope this helps you :)

**Comment by fredericklessing** [comment]
Yeah, it seems something is not working with this version and the hyperv collector. Runs fine if I remove the hyperv collector from the config.

Thanks for the great support so far! You rock!

**Comment by jkroepke** [comment]
Which windows server Version you are using?

**Comment by fredericklessing** [comment]
So yes, it seems 2019 does not contain the \Hyper-V DataStore metrics.
I can provide you with the export for both a 2019 and 2022 cluster, is there a way I can share the files privately with just you?

**Comment by jkroepke** [comment]
You can send me a mail to github@jkroepke.de

An export from 2019 and 2022 would be great!

MSCluster works differently. Its using WMI Query. I guess there is an issue in the code somewhere.

**Comment by fredericklessing** [comment]
Awesome, sent you the exports.

**Comment by jkroepke** [comment]
Cloud you test a snapshot build (#1756), if the resolve the Hyper-V issue on your system?

https://github.com/prometheus-community/windows_exporter/actions/runs/11976805136/artifacts/2225412028

**Comment by fredericklessing** [comment]
Hi, thank you! I will test it and let you know. Appreciate it.

**Comment by fredericklessing** [comment]
Sorry, it still the same results. On the 2019 Cluster, it doesn't start if I have the hyperv collector in the config, and mscluster still shows a 0.

On the 2022 Cluster, it works, but still a 0 at mscluster as well.

**Comment by fredericklessing** [comment]
Event logs for the mscluster collector on both 2019/2022

time=2024-11-23T18:54:09.344+02:00 level=ERROR source=prometheus.go:261 msg="collector mscluster failed after 360.5326ms, resulting in 575 metrics" err="failed to collect resource group metrics: WMI query failed: WMI query failed: failed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY"

And then on 2019 for hyperv:
time=2024-11-23T18:59:52.978+02:00 level=ERROR source=exporter.go:190 msg="Couldn't load collectors" err="error build collector hyperv: failed to build datastore collector: failed to create Hyper-V DataStore collector: failed to add counter \\Hyper-V DataStore(*)\\Fragmentation ratio: The specified object was not found on the computer.\r\n"

**Comment by jkroepke** [comment]
did you get, that I provide 2 different snapshot builds, distinct for each problem?

> time=2024-11-23T18:59:52.978+02:00 level=ERROR source=exporter.go:190 msg="Couldn't load collectors" err="error build collector hyperv: failed to build datastore collector: failed to create Hyper-V DataStore collector: failed to add counter \Hyper-V DataStore(*)\Fragmentation ratio: The specified object was not found on the computer.\r\n"

the error message did not match the PR changes.

**Comment by jkroepke** [comment]
> Event logs for the mscluster collector on both 2019/2022
> 
> time=2024-11-23T18:54:09.344+02:00 level=ERROR source=prometheus.go:261 msg="collector mscluster failed after 360.5326ms, resulting in 575 metrics" err="failed to collect resource group metrics: WMI query failed: WMI query failed: failed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY\nfailed to get element: MI_RESULT_NO_SUCH_PROPERTY"
> 
> And then on 2019 for hyperv: time=2024-11-23T18:59:52.978+02:00 level=ERROR source=exporter.go:190 msg="Couldn't load collectors" err="error build collector hyperv: failed to build datastore collector: failed to create Hyper-V DataStore collector: failed to add counter \Hyper-V DataStore(*)\Fragmentation ratio: The specified object was not found on the computer.\r\n"

I was able to reproduce the error related to mscluster, could you check, if snapshot build resolves that issue:

* https://github.com/prometheus-community/windows_exporter/actions/runs/11991311817/artifacts/2228701666

**Comment by fredericklessing** [comment]
Hi, sorry for the delay.
This time I tested the different PRs.

hyperv PR logs:
time=2024-11-25T18:30:31.375+02:00 level=ERROR source=exporter.go:190 msg="Couldn't load collectors" err="error build collector hyperv: failed to build datastore collector (err 3221228472): failed to create Hyper-V DataStore collector: failed to add counter \\Hyper-V DataStore(*)\\Fragmentation ratio: The specified object was not found on the computer.\r\n"
time=2024-11-25T18:30:37.934+02:00 level=INFO source=config.go:79 msg="Loading configuration file: C:\\Program Files\\windows_exporter\\config.yaml"
time=2024-11-25T18:30:37.946+02:00 level=WARN source=os.go:94 msg="The os collect holds a number of deprecated metrics and will be removed mid 2025. See https://github.com/prometheus-community/windows_exporter/pull/1596 for more information." collector=os
time=2024-11-25T18:30:39.582+02:00 level=ERROR source=exporter.go:190 msg="Couldn't load collectors" err="error build collector hyperv: failed to build datastore collector (err 3221228472): failed to create Hyper-V DataStore collector: failed to add counter \\Hyper-V DataStore(*)\\Fragmentation ratio: The specified object was not found on the computer.\r\n"

The latest mscluster PR you provided looks like it is working, I can see the mscluster_cluster and mscluster_network metrics, just not all of them, it seems there are some missing ones from what is documented, but it's a step closer! 

Thank you so much

**Comment by jkroepke** [comment]
A fix should be available in https://github.com/prometheus-community/windows_exporter/releases/tag/v0.30.0-beta.5
