### ISSUE TITLE
Please help us with Windows exporter installation steps to connect sql server(Named and default instance)

### ISSUE THREAD

**Issue by nareshdba333** [prometheus-community/windows_exporter#1754]
### Problem Statement

I have installed windows_exporter and can see Windows counters  but it is not connecting to the SQL Server instances

I want to monitor my SQL Server through Windows exporter.

Please help me with the steps to collect the stats for SQL Servers

### Environment

- windows_exporter Version:
- Windows Server Version:

**Comment by nareshdba333** [comment]
Facing below error

PS C:\Windows\system32> msiexec /i E:\software\windows_exporter-0.30.0-beta.3-amd64.msi --% ENABLED_COLLECTORS=mssql
msiexec : The term 'msiexec' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ msiexec /i E:\software\windows_exporter-0.30.0-beta.3-amd64.msi --% E ...
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (msiexec:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by jkroepke** [comment]
Try

```
C:\Windows\System32\msiexec.exe /i E:\software\windows_exporter-0.30.0-beta.3-amd64.msi --% ENABLED_COLLECTORS=mssql
```

**Comment by nareshdba333** [comment]
Now it is running and please help me with code on the .yaml file


![Uploading mssql.png…]()

**Comment by nareshdba333** [comment]
Unable to start windows exporter service and it giving below pop-up message

![image](https://github.com/user-attachments/assets/df6f391d-127f-454a-b2d3-09c56527c9ad)

**Comment by jkroepke** [comment]
Just open the event log

**Comment by nareshdba333** [comment]
time=2024-11-22T08:22:22.050-08:00 level=ERROR source=exporter.go:190 msg="Couldn't load collectors" err="error build collector mssql: failed to build accessmethods collector: failed to create AccessMethods collector for instance SQLRUNDECK: failed to add counter \\SQLServer:MSSQL$SQLRUNDECK:Access Methods\\AU cleanup batches/sec: The specified object was not found on the computer.\r\n"

**Comment by jkroepke** [comment]
Please use https://github.com/prometheus-community/windows_exporter/releases/tag/v0.29.2

**Comment by nareshdba333** [comment]
@jkroepke , Encoutering with below error message while trying to install. Please correct me if i am missing

![image](https://github.com/user-attachments/assets/ab3456be-ada2-46a1-beca-e9b0b9382dd0)

**Comment by nareshdba333** [comment]
Thank you now it working fine, for SQL Server as well, I am able to see SQL Server collectors

**Comment by nareshdba333** [comment]
If have multiple instances will it automatically captures all the instances info

**Comment by nareshdba333** [comment]
@jkroepke , Can we pull the long-running transactions history with this collector, if yes please give me one example query here to run on Prometheus classic UI
