### ISSUE TITLE
SQL Server prom sql

### ISSUE THREAD

**Issue by nareshdba333** [prometheus-community/windows_exporter#1757]
### Problem Statement

Please help me prom  sql, to check long running transaction on the SQL Server 

### Environment

- windows_exporter Version:
- Windows Server Version:

**Comment by jkroepke** [comment]
https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.mssql.md

search for transaction  maybe there is one that meets your expectation. If not, then windows_exporter isn't the correct tool for you.
