### ISSUE TITLE
Does it work with performance counters that are not in English?

### ISSUE THREAD

**Issue by ivanzzillo** [prometheus-community/windows_exporter#1780]
### Problem Statement

Before asking the question... I want you to know that I just started working with windows_exporter.

My doubt is that I have installed windows exporter on 4 machines with W2K16 (in Spanish) with an IIS server and when it comes to displaying the web service metrics it does display them but not with the correct data... 

I have reviewed the code a little, and I think it is because the collector (iis) attacks the corresponding performance counter(s) using its English name. 

Could this be the reason for not getting the correct metrics? If so... can you think of a solution?

NOTE: the same thing happens to me with the (mssql) collector.

Thank you very much in advance

### Environment

- windows_exporter 0.30.0.0
- Windows Server 2016

**Comment by jkroepke** [comment]
windows_exporter 0.30.0 uses a [language-neutral Win32 API](https://learn.microsoft.com/en-us/windows/win32/api/pdh/nf-pdh-pdhaddenglishcountera) to fetch data from Performance Counters on any localized system.

For example, my dev system is set to german and every think works as expected.

**Comment by jkroepke** [comment]
If you are using windows_exporter 0.30.0.0, double check that your are using latest version of windows_exporter 0.30.0.0. The version is not stable yet and error might be expectable.

**Comment by ivanzzillo** [comment]
First of all, thank you very much for your reply.

Secondly, indeed! Using the latest stable version, that is: v0.28.2, everything works perfectly and finally! I have achieved what I wanted, to monitor IIS and SQL Server. 

Greetings and thank you very much once again.
