### ISSUE TITLE
iis collector no longer fetching Default Web Site correctly (v0.30.0-rc.1)

### ISSUE THREAD

**Issue by aa-matthias** [prometheus-community/windows_exporter#1789]
### Current Behavior

When collecting metrics via iis collector the Default Web Site is now shown as "------" and stats are not shown correctly anymore.

(right -> before upgrade, left -> after upgrade)

![image](https://github.com/user-attachments/assets/1429339d-1e4c-4e78-8067-cc3bc1566f38)

### Expected Behavior

continue displaying metrics correctly

### Environment

- windows_exporter Version: 0.30.0-rc.1
- Windows Server Version: 2019

### windows_exporter logs

```shell
-
```

**Comment by jkroepke** [comment]
Could you check, if the transformation is done on Dashboard level? I count find any reference on the old code that empty is replaces by "Default Web Site"

**Comment by aa-matthias** [comment]
confirmed to be fixed with v0.30.0-rc.2
