### ISSUE TITLE
mssql sql errors no longer reported, collector shows success (v0.30.0-rc.1)

### ISSUE THREAD

**Issue by swiffer** [prometheus-community/windows_exporter#1790]
### Current Behavior

windows_mssql_sql_errors_total is no longer in the response but collector shows success.

![grafik](https://github.com/user-attachments/assets/512d40a2-aab7-4cea-aa9b-b1f333ab02e1)

### Expected Behavior

sql errors should still be part of the collected metrics

### Environment

- windows_exporter Version: 0.30.0-rc.1
- Windows Server Version: 2019

### windows_exporter logs

```shell
no logs in eventlog
```

**Comment by jkroepke** [comment]
Could you please run the collector with on debug log level and check for any logs?

**Comment by swiffer** [comment]
tried to set log level via config.yaml and restarted the service but nothing showing up in the event log...

**Comment by swiffer** [comment]
confirmed to be fixed with v0.30.0-rc.2
