### ISSUE TITLE
The current detected system for Windows 11 is Windows 10

### ISSUE THREAD

**Issue by jacbo0112** [prometheus-community/windows_exporter#1794]
### Problem Statement

# HELP windows_os_info Contains full product name & version in labels. Note that the "major_version" for Windows 11 is \\"10\\"; a build number greater than 22000 represents Windows 11.
# TYPE windows_os_info gauge
windows_os_info{build_number="22000",major_version="10",minor_version="0",product="Windows 10 Pro for Workstations",revision="2538",version="10.0.22000"} 1

**Comment by jkroepke** [comment]
Hi,

that correct.
