### ISSUE TITLE
mssql databases child collector fails in v0.30.0-rc.2

### ISSUE THREAD

**Issue by aa-matthias** [prometheus-community/windows_exporter#1795]
### Current Behavior

windows_mssql_collector_success{collector="databases",mssql_instance="MSSQLSERVER"} 0

having set log level to debug via config.yaml but nothing showing up in the eventlog currently.

### Expected Behavior

scrape should be successful

### Environment

- windows_exporter Version: v0.30.0-rc.2
- Windows Server Version: 2019 / MSSQL 14.0.3485.1

### windows_exporter logs

```shell
-
```

**Comment by jkroepke** [comment]
```
windows_mssql_collector_success{collector="databases",mssql_instance="MSSQLSERVER"} 1
windows_mssql_collector_success{collector="databases",mssql_instance="SQLTE2"} 1
```

I can't verify that on my dev machine.  

Idk, if there is an issue with the event log. Bug I would appricate if you could run the export from cmd.exe with --log.level=DEBUG

**Comment by aa-matthias** [comment]
🤔 i'm getting this:

2024/12/01 08:08:31 ERROR Failed to parse CLI args err="unrecognized log level DEBUG"

**Comment by jkroepke** [comment]
Ah, lowercase debug is correct.

**Comment by aa-matthias** [comment]
```
time=2024-12-01T12:22:16.057+01:00 level=DEBUG source=mssql.go:370 msg="detected MSSQL Instances: mssql.mssqlInstancesType{\"MSSQLSERVER\":\"MSSQL14.MSSQLSERVER\"}\n" collector=mssql
time=2024-12-01T12:22:16.804+01:00 level=WARN source=main.go:210 msg="couldn't initialize collector" err="error build collector mssql: failed to build databases collector: failed to create Databases collector for instance MSSQLSERVER: failed to initialize collector: failed to add counter \\SQLServer:Databases(*)\\Active parallel redo threads: Der angegebene Leistungsindikator wurde nicht gefunden.\r\n"
...
time=2024-12-01T12:22:38.470+01:00 level=DEBUG source=mssql.go:413 msg="mssql class collector databases for instance MSSQLSERVER failed after 511.1µs" collector=mssql err="failed to collect SQLServer:Databases metrics: performance counter not initialized"
```

**Comment by jkroepke** [comment]
> C:\Program Files\Microsoft SQL Server\MSSQL14
SQL Server 2017? 

Looking at https://github.com/microsoft/DiagManager/issues/41,  it sound like the Counter are available since SQL Server 2019

**Comment by aa-matthias** [comment]
I do agree that omitting them would be the preferred way to handle that.

**Comment by jkroepke** [comment]
Should be fixed in a upcoming release. 

You could also try an snapshot build to verify that: https://github.com/prometheus-community/windows_exporter/actions/runs/12107522322/artifacts/2258517864

**Comment by aa-matthias** [comment]
Hey - thanks addressing all the findings so quickly! tested the snapshot built successfully!
