### ISSUE TITLE
collector "logon" does not display metrics

### ISSUE THREAD

**Issue by vacili4** [prometheus-community/windows_exporter#1798]
### Problem Statement

hi
I enable the collector "logon"via the configuration file
`collectors:
  enabled: logon
collector:
  service:
    include: windows_exporter
log:
  level: warn`
but the expected metrics do not appear
[metrics.txt](https://github.com/user-attachments/files/17968453/metrics.txt)
What am I doing wrong?
how to get metrics "windows_logon_session_logon_timestamp_seconds"

### Environment

- windows_exporter Version:  0.29.0
- Windows Server Version: windows server 2019 10.0.17763

**Comment by jkroepke** [comment]
The metric is available on 0.30 https://github.com/prometheus-community/windows_exporter/releases/tag/v0.30.0-rc.2
