### ISSUE TITLE
Event logging errors every minute

### ISSUE THREAD

**Issue by pete-leese** [prometheus-community/windows_exporter#181]
It seems I deployed the MSI to machines that do not have MSMQ installed which is fine I guess, however every minute I get the following error in the event logs. 

Perhaps it would be better to have it log this message to the event viewer when the services starts as I think every minute is too much or if it can handle this better when a collector has been enabled.

I.E IIS not installed on all target devices, however I don't want to be deploying different exporters to cater for the role of a server. 

The description for Event ID 102 from source wmi_exporter cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

ERROR: msmq collector failed after 0.007022s: Exception occurred. (Invalid class )

**Comment by martinlindhe** [comment]
Patch is welcome, in the meantime you should configure your wmi_exporters to only include the collectors you are interested in.

Also FYI, msmq is not enabled by default.

**Comment by VR6Pete** [comment]
I know that but I’ve got over 500 servers and do not have an inventory of what components are installed on what server so makes it difficult to target specific collectors hence the request for the exporter to handle this scinario better.

**Comment by VR6Pete** [comment]
I know that but I’ve got over 500 servers and do not have an inventory of what components are installed on what server so makes it difficult to target specific collectors hence the request for the exporter to handle this scinario better.

**Comment by martinlindhe** [comment]
I think this is a valid issue, so I'm gonna reopen it. Thanks for your report @VR6Pete

**Comment by carlpett** [comment]
One potential improvement could be to check at start-up which collectors are possible to use and then disable them if the class is not present (after a clear log message).
On the other hand, I know of installations where the exporter is installed before all roles are guaranteed to be installed (parallel installations where the exporter and the roles are pushed simultaneously), so this approach would break those installs...

In general, it would be preferable to be able to assume that there is some form of configuration management present.

**Comment by brian-brazil** [comment]
How we handle this in the node exporter is that if a file in /proc is missing due to that functionality not being present, the collector logs a debug-level message and returns no metrics.

**Comment by VR6Pete** [comment]
Thanks. I don’t know why I closed it 🤔 too many beers I think !

Sounds like there are a couple of possible options to explore to make wmi exporter even better :)

**Comment by timweissenfels** [comment]
Did you guys fix it or came up with another solution ? @carlpett

**Comment by mcs** [comment]
Doesn't seem like that's fixed...

**Comment by ramachandrasuresh** [comment]
The application logs are filing up very quickly due to these errors every few seconds. @carlpett is this issue being considered?
