### ISSUE TITLE
`0.29.2` is missing on chocolatey

### ISSUE THREAD

**Issue by jonesbusy** [prometheus-community/windows_exporter#1812]
### Problem Statement

Hi,

I'm not sure if it's the correct repository for chocolatey packaging but the version `0.29.2` is missing on https://community.chocolatey.org/packages/prometheus-windows-exporter.install

The last published version is `0.27.2`

Thanks

### Environment

- windows_exporter Version: 0.27.2
- Windows Server Version: Windows 10, 20H2

**Comment by jkroepke** [comment]
Hi, chocolatey is not an official distribution channel. Please contact the maintainer of the package.
