### ISSUE TITLE
Get Drive of process I/O Writes in bytes

### ISSUE THREAD

**Issue by tekert** [prometheus-community/windows_exporter#1817]
### Problem Statement

It's there a way to get metrics like process write_bytes_total, but done per logical disk? Like the resource monitor but done to each disk. an extra_label with the disk name for example.

### Environment

- windows_exporter Version: v0.29.2
- Windows Server Version: 2019

**Comment by jkroepke** [comment]
From my standpoint: no. If there woulb be a known as known implementation path , it would be already integrated.

**Comment by tekert** [comment]
Guess ill have to code it then

**Comment by jkroepke** [comment]
Good luck!

It seems possible with ETW listener - https://learn.microsoft.com/en-us/windows/win32/etw/what-s-new-in-event-tracing.

**Comment by tekert** [comment]
Yes thanks, i was already studying the docs for ETW, it's entirey possible and more, seems nobody has done metrics for this, this can be really powerfull as an overview of kernel workings. I will beging working on this in the coming month.

**Comment by jkroepke** [comment]
> seems nobody has done metrics for this

I saw such metrcs at the Windows Performance Analyzer. But the Windows Performance Analyzer has todo some magic in order to correctly group the events to an process. 

It seems very complicated. Ref: https://stackoverflow.com/a/24080048/8087167

**Comment by tekert** [comment]
I meant, as a prometheus aggregated metric, 
Basically the process it's like this (from the command line)

`logman start "NT Kernel Logger" -p "Windows Kernel Trace" "(disk,process)" -o "mytest.etl" -ets`
> Starts dumping a trace using default buffer settings, more info at `logman -h`:
https://learn.microsoft.com/en-us/windows/win32/api/evntrace/ns-evntrace-event_trace_properties
(the settings from the code are the same as the commandline, yes.. microsoft docs... all over the place)

Im testing how the kernel provider `"Microsoft-Windows-Kernel-*"` works but i'm getting slight different field from the kernel trace `"NT Kernel Logger"` using provider `"Windows Kernel Trace"`

Basically the start done in code it's explained here https://learn.microsoft.com/en-us/windows/win32/api/evntrace/nf-evntrace-starttracea
A practical example to show it's like this: https://stackoverflow.com/questions/68646731/etw-realtime-consuming-of-event-trace

But for Kernel realtime dumps, we only have to open a collector, the overview of how all works is better explained here:
https://www.magicsplat.com/book/event_tracing.html

https://learn.microsoft.com/en-us/archive/msdn-magazine/2009/september/core-os-events-in-windows-7-part-1
https://learn.microsoft.com/en-us/archive/msdn-magazine/2009/october/core-instrumentation-events-in-windows-7-part-2

and here:
https://learn.microsoft.com/en-us/archive/msdn-magazine/2007/april/event-tracing-improve-debugging-and-performance-tuning-with-etw

Stop the dump with
`logman stop "NT Kernel Logger"`

To read the results, instead of using `tracerpt` i found it better to study the data using this: [perfview](https://github.com/microsoft/perfview)

Once i figure out the data rates, fields, performance, caveats, etc.
Im thinking of aggregating the dumps by fields:
`logman query providers "Windows Kernel Trace"`
every field it's explaned here:
`https://learn.microsoft.com/en-us/windows/win32/etw/msnt-systemtrace`
for example for disk read/writes:
`https://learn.microsoft.com/en-us/windows/win32/etw/diskio-typegroup1`

Any field that seems reasonable to make a metric from, we aggregate them, counters to sum, gauges to avg. It's better i thinkg to do that in memory instead to aggregate all the data on something like vmagent.
