### ISSUE TITLE
monitoring memory on machine

### ISSUE THREAD

**Issue by Itaysh9** [prometheus-community/windows_exporter#187]
Hey,
I want to set a reasonable monitoring on my windows machines, which run loaded applications.
As i read the the metrics you should watch are pages/sec and available bytes.
Those metrics can be exported from the class Win32_PerfFormattedData_PerfOS_Memory.  but as far as i see this class is not exported for now from wmi exporter. 
Is there any other way i can get those metrics? or maybe there is another suggestion for how to set a proper memory monitoring?
Cheers

**Comment by carlpett** [comment]
Hi!
We expose some of this via the `Win32_OperatingSystem` class [here](https://github.com/martinlindhe/wmi_exporter/blob/041ff0351d50b3022c0d431aca571ea2725ae8c4/collector/os.go#L19), you get PhysicalMemoryFreeBytes, VirtualMemoryFreeBytes and PagingFreeBytes (free space in page files), among others. Is this sufficient?

**Comment by Itaysh9** [comment]
Not exactly...
I am looking for monitoring on pages/sec. this metrics show how many swaps-in/out rate of the system.

**Comment by carlpett** [comment]
Ah, right. This would need to be implemented, then.
As a interim solution, we do expose this on a per-process level from the Process collector (`wmi_process_page_faults_total`), perhaps that could be useful?

**Comment by Itaysh9** [comment]
Maybe, i'll check.
Is the think i asked would be implement in the future? or i have to find another solution?

**Comment by carlpett** [comment]
It could definitely be implemented in the future, it seems like a reasonable class to include

**Comment by carlpett** [comment]
@aswhit1 We're happy to help with code reviews and such :) 
There is a code generator in tools/collector-generator that will do most of the boilerplate for you, I'd suggest starting there.
General steps for setting up a golang dev environment are [here](https://golang.org/doc/install#windows)

Let me know if you need any additional help!

**Comment by aswhit1** [comment]
I got 'go' downloaded and set up.

I downloaded Atom for an editor.

Ran the generator and os_memory.go was the resultant file

Ran 'go build'

Executed 'wmi_exporter' with os_memory enabled.

Hit "localhost:9182" with a browser

Runtime error.

Tried installing Delve for debugger, but hopelessly lost.

Suggestions?

**Comment by aswhit1** [comment]
How should I share the code and runtime error with you?

I've gotten a little better with delve, but still no success with resolving error.

**Comment by carlpett** [comment]
I would suggest opening a pull request on this repo with your changes, and additionally include the error message there.

**Comment by aswhit1** [comment]
Please double check my activities:

1. created repo aswhit1/wmi_exporter as fork from martinlindhe/wmi_exporter
2. created branch "os_memory"
3. checked in collector/os_memory.go
4. created pull request #266 and included runtime errors in the commit
comments.

I'm trying to be very careful as this is the first time I've used github.

Thank you for your patience!!

**Comment by carlpett** [comment]
Sorry, didn't realize that, or I would have been more detailed!
You did it all correct, though, so well done on opening your first PR :) Let's continue there!
