### ISSUE TITLE
wmi_exporter crashed on window10 VM

### ISSUE THREAD

**Issue by jinh-dk** [prometheus-community/windows_exporter#188]
I have a few windows 10 VM,  I have seen wmi_exporter crashed on a couple of machine 

I have seen collector failed because of **Invalid query** , **Invalid class**,  **Access denied** ,  and **Out of memory** .   for instance:  this is the event log of one crash.    

> The description for Event ID 102 from source wmi_exporter cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.
> 
> If the event originated on another computer, the display information had to be saved with the event.
> 
> The following information was included with the event: 
> 
> ERROR: logical_disk collector failed after 0.128710s: Exception occurred. (Invalid query )
>

**Comment by carlpett** [comment]
Hi @jinh-dk,
Hm, that is odd, even if the query does not succeed, it should absolutely not _crash_ in this circumstance. Do you get some exit code when this happens?
"Invalid query" and "Invalid class" would suggest that there are collectors which try to access counters which for some reason are not present on your system, or present with another set of data points than we try to access.
"Access denied" would suggest you are not running the exporter as an administrative account, something which is sadly required.
"Out of memory" would mean just that. What specs does your VMs have? Anything else running there which uses a lot of memory? The exporter normally consumes ~15 MB of memory. There have been some memory leaks previously, but the latest version does not have any known such issues.

Could you share some information about your setup? What is the sizing of the machines which have these issues, what version of Windows 10 are you running, which version of the exporter, and how did you install it?

Thanks!

**Comment by carlpett** [comment]
Hm, that's odd. Did it work to start it manually?

**Comment by jinh-dk** [comment]
Yes, I can start the service manually.

**Comment by carlpett** [comment]
Did the exporter log anything around that time? I don't see how this could happen unless the exporter was crashing on start, but if it works to start it manually, then that seems to be not the case.

**Comment by breed808** [comment]
Closing due to a lack of activity
