### ISSUE TITLE
Unable to determine relationship between Hyper-V CPU usage metrics and VM CPU usage %

### ISSUE THREAD

**Issue by sandersaares** [prometheus-community/windows_exporter#205]
I see that regular CPU usage is measured in seconds. This does not include time spent in VMs, however (it is counter under idle as per #101).

In recent versions various `wmi_hyperv_` metrics have been added, including CPU. However, these appear to be completely unitless numbers that bear little to no relation to the regular CPU usage.

For example:

```
wmi_cpu_time_total{core="0",mode="dpc"} 1375.328125
wmi_cpu_time_total{core="0",mode="idle"} 71868.5137236
wmi_cpu_time_total{core="0",mode="interrupt"} 830.953125
wmi_cpu_time_total{core="0",mode="privileged"} 9764.828125
wmi_cpu_time_total{core="0",mode="user"} 9109.40625
```

You can see 70K seconds idle and a little on top in the other states for this core. But Hyper-V has this:

```
wmi_hyperv_host_cpu_guest_run_time{core="0"} 2.62050994672e+11
wmi_hyperv_host_cpu_hypervisor_run_time{core="0"} 1.2303137851e+10
wmi_hyperv_host_cpu_remote_run_time{core="0"} 0
wmi_hyperv_host_cpu_total_run_time{core="0"} 2.74354132523e+11
```

I see no relation here to any other metrics. I also do not see how I can actually get some usage % out of these metrics - "total run time" is not the same as "capacity" and seems to be more correlated with "guest" than anything else. There is no number to divide by to get a %.

Am I missing something? How do I get CPU % used by Hyper-V virtual machines?

**Comment by sandersaares** [comment]
This article seems to be potentially relevant: https://blogs.msdn.microsoft.com/tvoellm/2008/07/14/how-to-get-processor-utilization-for-hyper-v-via-wmi/

It references some metrics that are not exposed by WMI exporter. I request that sufficient metrics be exposed to be able to get "Hyper-V VM CPU usage %". Ideally, I would also like to see all measurements in seconds instead of nameless units.

**Comment by shamsalmon** [comment]
In case anyone is wondering... based on that article you can do the following: 
`avg(irate(wmi_hyperv_vm_cpu_hypervisor_run_time[5m])) by (instance,vm) / 10000 / on (instance) group_left wmi_hyperv_hypervisor_logical_processors`

**Comment by shamsalmon** [comment]
That calculated percentage seems 10% off perfmon counters so who knows...
