### ISSUE TITLE
Wrong Metric Type for `process_start_time_seconds`

### ISSUE THREAD

**Issue by themontem** [prometheus-community/windows_exporter#206]
Metric type of `process_start_time_seconds` must be Gauge, as checked from official supported exporters.

Refer: https://github.com/prometheus/node_exporter/blob/dd98a09bb27b4eca4fd8c67189afbb5e0d8b2920/collector/fixtures/e2e-64k-page-output.txt#L3147

**Comment by breed808** [comment]
Resolved as per #669
