### ISSUE TITLE
Feature request: timestamp of last Windows Update run

### ISSUE THREAD

**Issue by avonwyss** [prometheus-community/windows_exporter#211]
This is nicely queryable via WMI (other methods no longer seem to work in Server 2016), as described here:
https://serverfault.com/questions/835490/how-to-determine-the-date-and-time-of-most-recent-successful-windows-update-run

**Comment by carlpett** [comment]
Hi @avonwyss!
Thanks for the suggestion. I recall looking into this a while back, and having problems finding a good class for it. This seems quite nice (it only seems to go back to 2008R2, but that might be sufficient in the year 2018...), but I'm somewhat worried about this note in the docs:

>To access information from this WMI class, the group policy Configure Reliability WMI Providers must be enabled. On Windows client systems, the policy is enabled by default. On Windows server systems, the policy is disabled by default. Disabling the policy will clear existing data within one hour.

On my local machine, it seems to have more than 1 hour of data, but this seems like something which could be brittle.

**Comment by avonwyss** [comment]
Good find, I did not dig that deep. Enabling the GPO can be done through documentation, but it is more complicated than that... Indeed it seems to be even more brittle since it also requires some scheduled tasks to run, see https://www.myotherpcisacloud.com/post/Enabling-Win32_Reliability-WMI-Classes-for-Windows-Server

Still I think it would be great to offer the info through wmi_exporter as collector which is disabled by default, and document the requirements for this to run (somewhat similar to IIS which needs to be installed).
