### ISSUE TITLE
About every 15 minutes of data loss

### ISSUE THREAD

**Issue by zhenglisai** [prometheus-community/windows_exporter#222]
![image](https://user-images.githubusercontent.com/32353492/42426356-fd8bebbe-8359-11e8-94d6-6732138b9f13.png)
i deployed three prometheus systems to monitor windows system. all of them loss data about every 15min
windows 2012r2
wim_exporter version: wmi_exporter-0.3.3-amd64
prometheus version: 2.3.1

**Comment by Teriand** [comment]
On us servers we fixed it when uninstall WMI STAT component in VmWare tools.

**Comment by zhenglisai** [comment]
my problem haven't been solved, my servers run on aws ec2, i'm thinking if this problem can't solved , i'll change my alert rules to ignore the data loss.

**Comment by FLeven** [comment]
@Teriand tried it, no change.
