### ISSUE TITLE
Expose Latency on Windows process

### ISSUE THREAD

**Issue by pete-leese** [prometheus-community/windows_exporter#228]
I'm  not sure if this can be exposed, but if you drill down into Resource Monitor from task manager and drill down to "Network" you see Latency against each windows process. 

I think this would be a good performance metric to capture if it is exposed through WMI.

**Comment by carlpett** [comment]
Could you figure out which class provides this data? Also, what does Perfmon say it means? It is not clear to me what a single latency number would mean...
