### ISSUE TITLE
Collect Process/Service Connection metrics with port and number of connections.

### ISSUE THREAD

**Issue by muralikanagala** [prometheus-community/windows_exporter#242]
I have came across an interesting connection metric on Azure OMS with the below details
`<Service> <Source IP> <Source port> <Dest IP> <Dest Port> <Number of connections>`

I have tried implementing this by running a PS script and pushing to Pushgateway but it's taking a lot of CPU/memory resources.

Is there a possibility to add those metrics to WMI exporter?

**Comment by muralikanagala** [comment]
Hi @carlpett - Thanks for the quick response.
We are not using Azure. I am just referring it as i have used it in the past. 
I am trying to get some more details on open connections in the physical infrastructure i am working on.

Essentially I am looking for a metric like this. 
`wmi_current_connections{instance="myserver",job="wmi_metrics", source_ip= "10.0.33.2", source_port="7879", dest_ip="10.0.33.4", dest_port="7676", source_service="myservice"}  23`

**Comment by carlpett** [comment]
Ah, I see. I see two issues with this:
1. This would turn out to be quite a lot of series in Prometheus, which will be bad for your performance.
2. I do not think this data is directly exposed over WMI.

So, this will likely not be implemented in the wmi_exporter directly. If you want to do this anyway (in which case I'd recommend heavily filtering the data to drill down to the interesting bits), I'd suggest having a script which dumps the data to a file on disk and using the textfile collector.

**Comment by muralikanagala** [comment]
Makes sense. Text file collector seems to be a good idea. I will give a try. 
Thank you @carlpett !
