### ISSUE TITLE
wmi_logical_disk_size_bytes

### ISSUE THREAD

**Issue by supertwister** [prometheus-community/windows_exporter#248]
Recently i have installed wmi_exporter in my Windows servers. I have noticed that the value of the wmi_logical_disk_size_bytes is not correct. Both of my C and E drives has the same value in Prometheus, While they are not on the same size.

Please see the attached screenshots. 

What could be the issue? 
Please advise.

![1](https://user-images.githubusercontent.com/37807214/44392297-8867f280-a53a-11e8-864f-5d8bec1497b2.png)
![2](https://user-images.githubusercontent.com/37807214/44392298-8867f280-a53a-11e8-9666-c4b52cb1896f.png)

**Comment by szook** [comment]
can you open a powershell window and run the following:
```
Get-WmiObject -Query "select * from Win32_PerfRawData_PerfDisk_LogicalDisk" | ft Name, PercentFreeSpace, PercentFreeSpace_Base
```

**Comment by supertwister** [comment]
Done. Please see the attached screenshot.

What could be the issue?
![3](https://user-images.githubusercontent.com/37807214/44403228-8d3d9e00-a55c-11e8-99ad-968a34eb55ea.png)

**Comment by szook** [comment]
the wmi_exporter is using the same wmi query as above to get the metrics and provides that for prometheus.  Your issue is not with wmi_exporter, per se, but something is not correct on that server.  

If that OS is Windows 2003 or 2008, it might be related to this:
http://ossmall.ro/the-win32perfrawdataperfdisklogicaldisk-wmi-class-returns-an-incorrect-percentage-of-free-disk-space-in-windows-vista-and-in-windows-server-2008/

**Comment by supertwister** [comment]
OK. Thanks!

**Comment by carlpett** [comment]
@supertwister Did this resolve your problem?

**Comment by supertwister** [comment]
I still have the issue with the wrong values of the drives size, But this issue is not related the exporter. It seems like a bug in Windows.

In order to workaround this issue, I have added in Prometheus the drive sizes (hard coded), And now i can monitor the drives's free space as i wanted.

**Comment by withqingshao** [comment]
> I still have the issue with the wrong values of the drives size, But this issue is not related to the exporter. It seems like a bug in Windows.
> 
> In order to workaround this issue, I have added in Prometheus the drive sizes (hard coded), And now i can monitor the drives's free space as i wanted.

how do you deal with the problem

**Comment by avonwyss** [comment]
The link explaining the issue is dead. This link here might help though:
https://support.microsoft.com/en-us/help/961435/some-base-values-are-not-updated-when-you-use-the-win32-perfrawdata-pe
