### ISSUE TITLE
Question: mssql collector - DB offline 

### ISSUE THREAD

**Issue by pete-leese** [prometheus-community/windows_exporter#251]
I’m running high availability on sql and recently one of the servers blue screened during the night and some databases were no longer synchronising (preventing failover) and some were offline whixh resulted in customer outage.

What I’m looking to do is to create an alert to inform me that this has occurred. 

Is it possible to determine which DB’s are not online and which DBS are not synchronised etc... with metrics currently being captured with the sql exporter?

Cheers

Pete

**Comment by carlpett** [comment]
@szook is probably the expert to hope for here :)
I don't have access to a mssql cluster to check, but I'd suggest looking at the `wmi_mssql_availreplica_*` and `wmi_mssql_dbreplica_*` metrics, depending on which type of replication you have set up.

**Comment by VR6Pete** [comment]
I will take a closer look but difficult to reproduce without it impacting customers so if anyone has created an alert rule already that would be amazing

**Comment by carlpett** [comment]
Oh, I wasn't suggesting that you'd provoke a new blue screen :) What I meant was that you should be able to look at the historical data for the outage in Prometheus and see if there's something useful there.
