### ISSUE TITLE
Support to check certificate details

### ISSUE THREAD

**Issue by SGTGunner** [prometheus-community/windows_exporter#273]
Would like to use the wmi exporter to check certificates on expiry etc. Is that possible?

**Comment by carlpett** [comment]
You can use the [blackbox_exporter](https://github.com/prometheus/blackbox_exporter) to check this, would that be sufficient?

**Comment by VR6Pete** [comment]
I was going to raise an issue on this topic, it would  be really neat if this can be pulled with the IIS collector.

Whilst blackbox can do this, it doesn't really scale when you have over 300 URL's to manage - and I think some people would struggle if no slick config management tooling is in place to manage and maintain this.

**Comment by brian-brazil** [comment]
The blackbox exporter should have no problems with 300 HTTP targets.

**Comment by VR6Pete** [comment]
My use case here is that I have really quirky apps that uses a combination of SSL and self signed certificates, but these are not reachable using black box in my environment. 

Therefore it would be really useful if there was a way of wmi exporter being able to pull the expiry date from the self signed certs installed in IIS.

I have upwards of 600 servers where wmi exporter is installed and would be ideal if something can be incorporated into this exporter.

**Comment by brian-brazil** [comment]
If the blackbox exporter can't get to it, how would the WMI exporter?
