### ISSUE TITLE
Documentation for Hyperv metrics

### ISSUE THREAD

**Issue by nelsonfassis** [prometheus-community/windows_exporter#282]
Are there any plans to add documentation and description for HyperV metrics? I'm trying to build dashboards and analyze those values but the units don't add up to node values nad they currently only give me an idea of what I am seeing.

**Comment by nelsonfassis** [comment]
@carlpett I would say I don't know what I'm looking at. I'm trying to build a dashboard comparing how much of CPU is being requested by each VM and how much of the requested CPU is being used by this VM, but all the metrics I get from hyperv, when I compare to what I see in Windows, they don't match. So, I know my question is super vague, but I got so lost on using them that I can't formulate a better one :(

**Comment by carlpett** [comment]
Going back to this, the documentation structure is now in place, and although we still haven't fleshed it out, here is the the Hyper-V section: [docs](https://github.com/martinlindhe/wmi_exporter/blob/master/docs/collector.hyperv.md)
We'd be very happy to accept any contributions there from Hyper-V users!

**Comment by JDA88** [comment]
Trying to add some example in Pull Request #556 but still learning to use Github...
No idea on how to restart the DCO checks
