### ISSUE TITLE
Metric name spelling error: wmi_os_process_memory_limix_bytes

### ISSUE THREAD

**Issue by carlpett** [prometheus-community/windows_exporter#283]
The os collector has a misspelled metric: `wmi_os_process_memory_limix_bytes`.
Should probably be duplicated with the correct spelling for a while.

**Comment by dylan-ferreira** [comment]
We can update the exporter to produce to both `wmi_os_process_memory_limix_bytes` and the corrected metric name `wmi_os_process_memory_limit_bytes`, or we could correct the metric name and include a Prometheus recording rule example to the documentation that would duplicate the data from the new correct metric name to the older incorrect name so users have a choice of if/when to make the change:

`---
groups:
  - name: wmi-rules
    rules:
    - record: wmi_os_process_memory_limix_bytes
      expr: wmi_os_process_memory_limit_bytes`

**Comment by Mario-Hofstaetter** [comment]
Just found this issues after searching for this. Any chance the misspelling will be fixed in `v1.0` ?

**Comment by carlpett** [comment]
Hey all,
Yes, we should just fix this in the next release. I like @dylan-ferreira's suggestion of hinting at a recording rule to handle backwards compat for those who might be using the old spelling.
