### ISSUE TITLE
Getting over 100% in a time counter irate

### ISSUE THREAD

**Issue by gabriel4567** [prometheus-community/windows_exporter#297]
I magine delta_time_idle / delta_time couldn't be greater than 1. But thats what I'm getting sometimes. Scraping interval is 15s.

Example: irate(wmi_logical_disk_idle_seconds_total[1m])

{group="desenv",instance="10.139.34.175:1433",job="hw_os",volume="C:"}	0.9652800000001055
{group="desenv",instance="10.139.34.175:1433",job="hw_os",volume="E:"}	0.9654999999998836
{group="desenv",instance="10.139.34.175:1433",job="hw_os",volume="HarddiskVolume1"}	0.9654999999998836
{group="desenv",instance="10.139.52.128:8443",job="hw_os",volume="C:"}	1.0006800000000415
{group="desenv",instance="10.139.52.128:8443",job="hw_os",volume="E:"}	1.0006866666665397
{group="desenv",instance="10.139.52.128:8443",job="hw_os",volume="HarddiskVolume1"}	1.0006866666665397

An example of range vector. On the second time series, see that  103360.3777s-103344.8217s= 15.556s >15s

wmi_logical_disk_idle_seconds_total[30s]

wmi_logical_disk_idle_seconds_total{group="desenv",instance="10.139.34.175:1433",job="hw_os",volume="C:"}	141104.47449999998 @1544116418.577
141120.0257 @1544116433.577
wmi_logical_disk_idle_seconds_total{group="desenv",instance="10.139.34.175:1433",job="hw_os",volume="E:"}	103344.8217 @1544116418.577
103360.3777 @1544116433.577
wmi_logical_disk_idle_seconds_total{group="desenv",instance="10.139.34.175:1433",job="hw_os",volume="HarddiskVolume1"}	103370.72219999999 @1544116418.577
103386.2782 @1544116433.577
wmi_logical_disk_idle_seconds_total{group="desenv",instance="10.139.52.128:8443",job="hw_os",volume="C:"}	107028.77519999999 @1544116419.7
107043.30159999999 @1544116434.7
wmi_logical_disk_idle_seconds_total{group="desenv",instance="10.139.52.128:8443",job="hw_os",volume="E:"}	104524.9086 @1544116419.7
104539.4372 @1544116434.7
wmi_logical_disk_idle_seconds_total{group="desenv",instance="10.139.52.128:8443",job="hw_os",volume="HarddiskVolume1"}	104431.5907 @1544116419.7
104446.11929999999 @1544116434.7

Can anyone guess whats happening? Forgive me for any mistakes

**Comment by carlpett** [comment]
We've seen this for some other similar cases too before, unfortunately. There are two theories at this time:
1. The data from WMI isn't that good in precision (somewhat unlikely, and Windows internal tooling should show some artifacts from this too)
2. When some WMI queries take longer than others, the data will be "smeared", since different collectors will deliverer snapshots at different times. Prometheus will still associate them with a single timestamp, however (when the last query was completed)

So at the moment, we're aware of this imprecision (which is more noticable under higher loads), but do not have a clear and simple fix proposed, I'm afraid.

**Comment by kworr** [comment]
As for me, I'm graphing this inside Grafana nailing it to a percent scale. This gives a shiny look to the graph.

Shiny look is a thing. When the graph is shiny you will notice things you need to notice on the graph, leaving time smearing aside.

And if you want to limit smearing you need to understand that:

1. Time doesn't flow the same way on any two hosts. They just try to keep up with it, but 15s at one host will just be roughly equivalent to 15s on another host.

2. In Prometheus world, nothing except scraping triggers a snapshot. This means that any network delays, any server bottlenecks, any packet drops - everything will have an impact on scraping delays adding to the total precision errors.
