### ISSUE TITLE
Support for ADO.NET metrics

### ISSUE THREAD

**Issue by amitsaha** [prometheus-community/windows_exporter#301]
Would you be willing to accept a PR for adding ADO.NET metrics as documented [here](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/performance-counters) - `System.Data.SqlClient` for now?

**Comment by carlpett** [comment]
Hi @amitsaha,
Thanks for asking! And yes, this looks like it would reasonably be in scope, I'd say. Would this fall under the general dotnet collectors, or is it separate, you think?

**Comment by amitsaha** [comment]
thanks @carlpett  - i was thinking perhaps a separate collector to add to the existing `netframework_*` collectors.  If there's a certain way you want me to implement it in light of https://github.com/martinlindhe/wmi_exporter/issues/300 - please let me know. 

I was thinking of naming it as  `netframework_adonet`.

**Comment by theimdal** [comment]
+1

**Comment by teonivalois** [comment]
+1

**Comment by amitsaha** [comment]
hey folks sorry, i will not be able to look into it :-(
