### ISSUE TITLE
wmi_exporter 0.5.0 duplicate errors in event viewer

### ISSUE THREAD

**Issue by kworr** [prometheus-community/windows_exporter#304]
Hello.

I'm trying to get a hand on setting this up on a few hosts. However, I have some troubles unifying setup.

Imagine you have like a 100 of hosts. Some do DNS, some MSSQL, some IIS, some are VMWare guests and so on. Setting everything to set up each host in a unique way is another huge task, it's easier to just enable all required collectors globally on all hosts. One giant Pro is that I will not manage all of this stuff, I have to configure them once and handle this to the people who will manage installs/updates later on. This means everything should be trivial.

But when I'm throwing one global config to all hosts each of them starts generating a huge stream of logs in Event Viewer. For each query, I get 8 MSSQL errors and 2 DNS errors.

My question is, can service reports this errors only once, when it detects that no MSSQL/DNS is present on the server, instead of screaming in the logs all the time?

Thanks in advance.

**Comment by carlpett** [comment]
Actually @VR6Pete. it would be greatly appreciated if you could submit that script as a PR to the contrib directory, too!

**Comment by VR6Pete** [comment]
I’ll get a PR submitted tomorrow :)

**Comment by VR6Pete** [comment]
PR #305 submitted.
