### ISSUE TITLE
Specifying .NET metrics lists all .NET processes

### ISSUE THREAD

**Issue by chester89** [prometheus-community/windows_exporter#319]
Hello. 
My task is to monitor IIS process for many metrics, including .NET related ones. 
But when I run this command `wmi_exporter-0.6.0-amd64.exe --collectors.enabled netframework_clrexceptions,netframework_clrinterop,netframework_clrjit,netframework_clrloading,netframework_clrlocksandthreads,netframework_clrmemory,net,process,iis--collector.process.processes-where "Name LIKE '%%w3wp%%'"`, all of the processes on my machine that run .NET framework are shown, including various developer tools.
What did I do wrong?
If I specify just the process collector, it works as expected

**Comment by carlpett** [comment]
Hi @chester89,
The `netframework_*` collectors does not yet have support for filtering processes, so while your command will filter the output of the process collector, the dotnet ones currently grabs everything.
If you'd like to contribute filtering support for the dotnet ones, it'd be much appreciated!

**Comment by chester89** [comment]
@carlpett understood. I'll take a look - it would be very useful for my tasks
