### ISSUE TITLE
new collector generation

### ISSUE THREAD

**Issue by siddu108** [prometheus-community/windows_exporter#328]
How do I create a new collector to get a metric from a class say, root/microsoft

**Comment by kaffarell** [comment]
I think we can close this @breed808

**Comment by breed808** [comment]
For anyone viewing this in the future, there's a [collector generator](https://github.com/prometheus-community/windows_exporter/tree/63800b5c6a1d576617468516de8d7e078e15acec/tools/collector-generator) tool available for anyone needing to create a collector sourcing metrics from WMI.

For Perflib, feel free to copy one of the existing Perflib collectors and amend for the new Perflib class. Alternatively we're open to a PR that introduces a Perflib template.
