### ISSUE TITLE
ENABLED_COLLECTORS flags for msi installer doesn't filter 

### ISSUE THREAD

**Issue by Jacko50** [prometheus-community/windows_exporter#332]
`msiexec /i wmi_exporter-0.7.0-386.msi ENABLED_COLLECTORS=os` still outputs all metrics whereas running `wmi_exporter-0.7.0-386.exe --collectors.enabled "os"` filters as expected when curling `http://localhost:9182/metrics`

**Comment by carlpett** [comment]
Hi @Jacko50,
That is odd. Could you check what arguments the installed service gets (by opening properties in the Services management console)?

**Comment by ericterpstra** [comment]
I tried this twice. First time I installed, all thet default collectors were enabled. Second time, I put quotes around the enabled collectors (e.g. `ENABLED_COLLECTORS="cpu,memory"`) and it worked. YMMV.
