### ISSUE TITLE
IIS Response Time

### ISSUE THREAD

**Issue by VoidMonk** [prometheus-community/windows_exporter#347]
Hi, it'll be great if the IIS collector could get or calculate the response time (by App Pool or site). I couldn't find a way to get this metric into Prometheus.

**Comment by carlpett** [comment]
Hi @VoidMonk,
I do not believe this is exposed by IIS as counters, sadly. You'll need to extract metrics from the IIS logs instead.
I've used [stream_exporter](https://github.com/carlpett/stream_exporter) for this at a couple of clients, and I also know of [mtail](https://github.com/google/mtail) which allows similar extraction.
