### ISSUE TITLE
Process collector return error when collect same name and label values

### ISSUE THREAD

**Issue by vidalsysadmin** [prometheus-community/windows_exporter#379]
Hello,

We start to deploy wmi_exporter on  Windows Server 2012, we have this issue on our w2k12 server:

 

> An error has occurred during metrics gathering:
> 
> 266 error(s) occurred:
> * collected metric wmi_process_start_time label:<name:"creating_process_id" value:"660" > label:<name:"process" value:"svchost" > label:<name:"process_id" value:"0" > gauge:<value:1.5653378012614076e+09 >  was collected before with the same name and label values
> * collected metric wmi_process_handle_count label:<name:"creating_process_id" value:"660" > label:<name:"process" value:"svchost" > label:<name:"process_id" value:"0" > gauge:<value:450 >  was collected before with the same name and label values
> * collected metric wmi_process_cpu_time_total label:<name:"creating_process_id" value:"660" > label:<name:"mode" value:"privileged" > label:<name:"process" value:"svchost" > label:<name:"process_id" value:"0" > counter:<value:0.28125 >  was collected before with the same name and label values

Os: Windows Server 2012 R2
wmi_exporter version: 0.8.0
Enabled collectors: cpu, logical_disk, net, os, textfile, process, tcp, cs, memory, system, service

We don't have this issue on Windows Server 2008 R2 ...

We try to rollback to version 0.7.0 but we have same  issue. We have read this issue #272, we have try to disable textfile but we have the same error.  We find that could be the process collector which make this error so we have tried to disable it , it's works now but we want to user the process collector :(

Thanks..

**Comment by carlpett** [comment]
Hi @vidalsysadmin,
Thanks for reporting! The complaint from the exporter here is that there are processes which result in duplicate metrics. It looks like you get several processes which either report their process_id to be zero, or does not report a process id at all. 
Could you check in Powershell with `gwmi Win32_PerfRawData_PerfProc_Process` if you get any processes which has `IDProcess` zero?

**Comment by vidalsysadmin** [comment]
Hi @carlpett do you mean `ProcessID` , if yes we have run the gwmi command and have this:

> Name                                                                                                          ProcessID
> ----                                                                                                          ---------
> Idle                                                                                                                  0
> System                                                                                                                0
> smss                                                                                                                  0
> csrss                                                                                                                 0
> csrss#1                                                                                                               0
> wininit                                                                                                               0
> winlogon                                                                                                              0
> services                                                                                                              0
> lsass                                                                                                                 0
> svchost                                                                                                               0
> svchost#1                                                                                                             0
> LogonUI                                                                                                               0
> dwm                                                                                                                   0
> svchost#2                                                                                                             0
> svchost#3                                                                                                             0
> svchost#4                                                                                                             0
> svchost#5                                                                                                             0
> svchost#6                                                                                                             0
> spoolsv                                                                                                               0
> svchost#7                                                                                                             0
> klnagent                                                                                                              0
> MsDtsSrvr                                                                                                             0
> sqlservr                                                                                                              0
> mysqld                                                                                                                0
> sqlbrowser                                                                                                            0
> sqlceip                                                                                                               0
> sqlwriter                                                                                                             0
> sqlceip#1                                                                                                             0
> svchost#8                                                                                                             0
> VGAuthService                                                                                                         0
> vmtoolsd                                                                                                              0
> ManagementAgentHost                                                                                                   0
> avp                                                                                                                   0
> WmiPrvSE                                                                                                              0
> SQLAGENT                                                                                                              0
> conhost                                                                                                               0
> svchost#9                                                                                                             0
> svchost#10                                                                                                            0
> WmiApSrv                                                                                                              0
> dllhost                                                                                                               0
> WmiPrvSE#1                                                                                                            0
> msdtc                                                                                                                 0
> csrss#2                                                                                                               0
> winlogon#1                                                                                                            0
> dwm#1                                                                                                                 0
> avp#1                                                                                                                 0
> taskhostex                                                                                                            0
> rdpclip                                                                                                               0
> explorer                                                                                                              0
> vmtoolsd#1                                                                                                            0
> vapm                                                                                                                  0
> unsecapp                                                                                                              0
> WmiPrvSE#2                                                                                                            0
> WmiPrvSE#3                                                                                                            0
> mmc                                                                                                                   0
> wmi_exporter                                                                                                          0
> DTExec                                                                                                                0
> conhost#1                                                                                                             0
> ISServerExec                                                                                                          0
> conhost#2                                                                                                             0
> powershell                                                                                                            0
> conhost#3                                                                                                             0
> notepad                                                                                                               0
> msiexec                                                                                                               0
> _Total                                                                                                                0

**Comment by carlpett** [comment]
Huh, that looks strange. Do they show up as PID 0 in Task Manager as well?

**Comment by vidalsysadmin** [comment]
No, I have already checked this when you said that we have process with PID 0 :joy:  In the task Manager the pid are good , so I try to understand why on task manager and gwmi command we don't have same result... but the wmi documentation about IDProcess/ProcessID is crap! Nobody seems have an ID process that return zero :-1:

**Comment by carlpett** [comment]
Ok, that's probably good at least :) Then it seems you might have some issue with the performance counters on your server. You can rebuild them by running `lodctr.exe /r`.
Let me know if that fixes it for you!

**Comment by vidalsysadmin** [comment]
Thank you for your help!
The command `lodctr.exe /r` was run successfully but we have the same issue when i run the command `gwmi` again :(

**Comment by vidalsysadmin** [comment]
So We have follow your way to rebuild/reset perf counter, after many search on Google we find the right solution,  the command `gwmi` return the true PID  and the wmi_exporter works  now ! Thank you for your help .. 

The solution to reset wmi counter:

> Click Start , click Run, type cmd, and then click OK.
> Stop the Windows Management Instrumentation service or at the command prompt, type net stop winmgmt, and then press ENTER.
> At the command prompt, type winmgmt /resyncperf, and then press ENTER.
> At the command prompt, type wmiadap.exe /f, and then press ENTER.
> Start the Windows Management Instrumentation service or at the command prompt, type net start winmgmt, and then press ENTER.

Source link: [here](https://lizardsystems.com/remote-process-explorer/articles/wmi-troubleshooting/)

**Comment by carlpett** [comment]
Nice! Thanks for documenting the steps!

**Comment by vidalsysadmin** [comment]
Hi,

The steps i have done before worked with a part of our servers on windows 2012 r2 but not for all of them.

We have tried  this procedure to resolve the issue on problematic servers: 

sc config winmgmt start= disabled
net stop wmi_exporter
net stop winmgmt
lodctr /r
cd %systemroot%\system32\wbem
rd /S /Q repository
regsvr32 /s %systemroot%\system32\scecli.dll
regsvr32 /s %systemroot%\system32\userenv.dll
sc config winmgmt start= auto
for %i in (*.mof, *.mfl) do Mofcomp %i
winmgmt /salvagerepository
winmgmt /verifyrepository
net start wmi_exporter

The are two parameters:
- IDProcess: give the ID of the Process (PID)
- ProcessID: give 0 if the Process is ok

In fact, we suppose WMI on server change the value "IDProcess" parameter (which is good, with the good ID of all Processes) to "ProcessID" parameter (which all values of them are to 0 = the process is OK for Windows) and the exporter read both value (if IDProcess is not present it takes ProcessID). Both value are not present at the same time (only one at a time).

We don't know why this value change all time on some servers...
Our server are Windows 2012 R2 on French Language, we don't know if this is an issue only on this type of server. 
We are investigating  but we are blocked for the moment :'( , we have created a topic on technet too: 

https://social.technet.microsoft.com/Forums/office/fr-FR/4a194ef5-1590-48dc-8ff2-ef98664303a1/wmi-processididprocess-0?forum=windowsserver8fr

**Comment by vidalsysadmin** [comment]
no ideas ?

**Comment by vidalsysadmin** [comment]
We have resolved that issue on a large part on our servers. We have exported wmi configuration (from a server which works) on a REC file and we have imported it on the server which have the problem. After that, we already have to do all the  steps i have done before (on my previous post) but it seems working randomly.

**Comment by da77a** [comment]
I'm getting the same error, but in my case its about USB docking hub network adapters that appear to be enumerated as the same (so far as wmi_exporter is concerned) but are actually different (identical) units - joys of hotdesking a laptop...
I'm considering raising a separate issue about the specifics when I have data collected, but it isn't important to me - I don't anticipate the same problem with things other than my development system... What I do anticipate is "stuff happens" (be it weird PID 0 or duplicate network adapters or... and stops ALL metrics being collected. If the "error" were returned as a metric AND the dup metrics suppresses AND all other metrics NOT suppressed THEN I would not lose all visibility when one thing (processes, network adapter, whatever) has a problem AND I could diagnose, alert etc from the metrics collected NOT by trawling logs...

**Comment by da77a** [comment]
Hi, why is my comment deleted? Do you want me to raise it as a separate issue?

**Comment by martinlindhe** [comment]
@da77a yes, please do

**Comment by da77a** [comment]
Ah - ok.
