### ISSUE TITLE
Logical_disk collectors for Disk Read latency and Write latency

### ISSUE THREAD

**Issue by manohrn** [prometheus-community/windows_exporter#380]
Do you have the repo which has the Logical_disk collectors for Disk Read latency and Write latency.
Can anyone help me to get the updated Logical _disk collectors MSI file as it is very much needed for our clients.

Please help me ASAP

**Comment by breed808** [comment]
This should be resolved as of 853d615

**Comment by robodair** [comment]
Looks like the metrics added in 853d615 weren't multiplied by `ticksToSecondsScaleFactor` but this should be fixed in https://github.com/martinlindhe/wmi_exporter/pull/400.

For now I'm using `rate(wmi_logical_disk_read_latency_seconds_total[1m]) / 1e7` to get disk latency in seconds.

**Comment by cameronkerrnz** [comment]
@robodair You shouldn't use rate() on a gauge. What you probably want is instead something like the following:

```
wmi_logical_disk_read_latency_seconds_total{volume=~".:"} / 1e7
```

**Comment by cameronkerrnz** [comment]
I don't understand why wmi_logical_disk_read_latency_seconds_total is a counter and not a gauge.

```
# HELP wmi_logical_disk_read_latency_seconds_total Shows the average time, in seconds, of a read operation from the disk (LogicalDisk.AvgDiskSecPerRead)
# TYPE wmi_logical_disk_read_latency_seconds_total counter
wmi_logical_disk_read_latency_seconds_total{volume="C:"} 636.2798569
wmi_logical_disk_read_latency_seconds_total{volume="D:"} 184.26475879999998
wmi_logical_disk_read_latency_seconds_total{volume="HarddiskVolume1"} 0.004719
wmi_logical_disk_read_latency_seconds_total{volume="HarddiskVolume2"} 0.015182699999999999
```

Installed today, version is:
```
wmi_exporter_build_info{branch="master",goversion="go1.12.3",revision="012b938b5451e5d10e2bb364876aac66cd85c54e",version="0.9.0"} 1
```

If this is really meant to be a counter, then how does it compare to wmi_logical_disk_read_seconds_total, which would make sence as rate() would be essentially dividing that over the time difference, and you would have an average. eg. compare the following

```
rate(wmi_logical_disk_read_seconds_total[1m])
rate(wmi_logical_disk_read_latency_seconds_total[1m])
```

Perhaps worthy of a note in the docs at least.

Thanks,
Cameron

**Comment by breed808** [comment]
Good spot Cameron!

My understanding is that the `wmi_logical_disk_read_seconds_total` metric is the total number of seconds the disk has spent _reading_, while the `wmi_logical_disk_read_latency_seconds_total` metric is the total number of seconds the disk has spent _waiting_ to perform a read operation.

This does not appear to be the case as both metrics are returning the same value.

**Comment by breed808** [comment]
Looking at the values returned directly by Perflib via `Get-Counter`, it looks like the `Avg. Disk sec/Read` metric should be a gauge type, returning the average read request latency.
The `% Disk Read Time` should also be a gauge type returning a percentage. There doesn't appear to be a `read_seconds_total` value returned at all.

I think the underlying `perflib` values need to be fixed, and the `wmi_logical_disk_read_seconds_total` needs to be re-named to `wmi_logical_disk_read_percentage`.

The above would also need to be applied to the `wmi_logical_disk_write_seconds_total` and `wmi_logical_disk_write_latency_seconds_total` metrics.

**Comment by carlpett** [comment]
@breed808 When we pulled the data with WMI, I'm fairly sure the values were seconds. Could it be the perflib data has a _base value corresponding to it?
It would be preferable to keep the seconds-counter rather than a percentage gauge (if possible, of course!), and it seems strange WMI and perflib would differ here.

**Comment by breed808** [comment]
@carlpett It's been a while so I'll need to check that the counters were returning the same value prior to the perflib rewrite (I.E. v0.8.3 or older). My testing during the perflib rewrite was to ensure that the perflib metrics returned the same value as the WMI metrics.

I'll check the above and also see if there are any base perflib counters that could be used.

**Comment by breed808** [comment]
Ok, I've checked both `v0.8.3` and `master` and there is a discrepancy with `wmi_logical_disk_read_latency_seconds_total`. Note that `192.168.88.43:9182` is `v0.8.3`.
![logical_disk_metrics](https://user-images.githubusercontent.com/3103817/72152354-9eca5480-33a2-11ea-8aae-7a9c53669c7a.png)

I see two issues:

1) The WMI version (`v0.8.3`) reports an incredible large value for the `wmi_logical_disk_latency_seconds_total` metric.

2) The Perflib version reports the same value for both metrics.

`wmi_logical_disk_read_seconds_total` is sourced from the perflib `PercentDiskReadTime` counter, while `wmi_logical_disk_read_latency_seconds_total` is sourced from the perflib `AvgDiskSecPerRead` counter.

I will look to see if another perflib counter/base counter may be used or is applicable for either of these two metrics.

**Comment by breed808** [comment]
I've checked the base counter for `perflib:Avg. Disk sec/Read"` and `perflib:Avg. Disk sec/Read"` with no luck, results are still the same.

Perhaps we should consider retiring one of the two identical metrics?
