### ISSUE TITLE
How to exclude/disable logical disk monitoring?

### ISSUE THREAD

**Issue by hizamilatip** [prometheus-community/windows_exporter#383]
Can anyone advise me on how to disable the logical disk from monitoring? I am doing the housekeeping for this by routine.

**Comment by breed808** [comment]
Do you mean to prevent exporting of metrics for specific logical volumes? This can be done with the `--collector.logical_disk.volume-whitelist` and `--collector.logical_disk.volume-blacklist` flags.
See the [logical_disk collector documentation](https://github.com/martinlindhe/wmi_exporter/blob/master/docs/collector.logical_disk.md).

All logical volume monitoring for a host can be disabled by excluding the `logical_disk` collector.

**Comment by vidalsysadmin** [comment]
Hi  @breed808 can you tell me how I can disable only one logical disk ( in my case i want to disable the T logical volume) i have tried --collector.logical_disk.volume-blacklist=T but it didn't work.

**Comment by breed808** [comment]
@vidalsysadmin I believe you need to add a colon after the drive letter.

E.G. to blacklist C: drive:
```powershell
.\wmi_exporter-0.8.3-amd64.exe --collector.logical_disk.volume-blacklist="C:"
```

**Comment by vidalsysadmin** [comment]
@breed808 Thank you ! It works ! ;)

**Comment by zuosc** [comment]
if i have many logical  need ignore,how to use it? @breed808   thanks.

```
C:
C:\ProgramData\Microsoft\Windows\Containers\BaseImages\9dbce7ba-98d5-4caa-a065-e0506214426d\BaseLayer
D:
HarddiskVolume1
HarddiskVolume5
```

I just want exclude C: D: E: F: ......

**Comment by akunzai** [comment]
Hi @zuosc 

in regexp,

you should use `HarddiskVolume.*` instead of `HarddiskVolume*`

**Comment by zuosc** [comment]
@akunzai  thanks!

`\windows_exporter.exe --collector.logical_disk.volume-blacklist="HarddiskVolume.*|.*Containers.*" `

**Comment by zuosc** [comment]
`sc create window_exporter binPath= `"D:\windows_exporter\windows_exporter.exe"`
