### ISSUE TITLE
How do I add metrics for services specific to my machine?

### ISSUE THREAD

**Issue by AmishRanjan** [prometheus-community/windows_exporter#385]
Suppose I use a service that is not generic, it is some specific service running on my system. How do I add metric for that service? @carlpett

**Comment by carlpett** [comment]
Hi @AmishRanjan,
If it is a service you are writing the code for yourself and you can change it, your best option is to add instrumentation to it directly, see [client libraries](https://prometheus.io/docs/instrumenting/clientlibs/) to find one for your application. This is always the prefered alternative when possible.

If it is a third-party application, or one you cannot change, but you have some way to get metrics from it, you can build a script to extract them and use the [textfile collector](https://github.com/martinlindhe/wmi_exporter/blob/master/docs/collector.textfile.md).

**Comment by xuanyuanaosheng** [comment]
@carlpett If use the textfile collector,  how the windows server perform the file by scheduled tasks? Any good suggestions?

**Comment by carlpett** [comment]
@xuanyuanaosheng The usual approach is to invoke a Powershell script in the scheduled task, which then writes the file that the textfile collector reads. For example,
```ps1
echo @"
#TYPE my_metric counter
my_metric 5
"@ | out-file -Encoding utf8 C:\Program Files\wmi_exporter\textfile_inputs\my-test.prom
```
