### ISSUE TITLE
How do I calculate the individual process cpu utilization in percentage?

### ISSUE THREAD

**Issue by xudong321p** [prometheus-community/windows_exporter#386]
Can anyone tell me on how to calculate the single process cpu utilization in percentage? I think it may uses the matrices wmi_process_cpu_total{process="my process"} but I have no idea how  to use it.

**Comment by carlpett** [comment]
Hi @xudong321p,
If you run `sum(rate(wmi_process_cpu_total{process="my process"}[5m]))` you will get a number 0-(number of cores), showing the ratio of time your process was running.
If you want a 0-1 instead, you can divide by `wmi_cs_logical_processors`.
