### ISSUE TITLE
IIS Grafana Dashboard

### ISSUE THREAD

**Issue by mango19b** [prometheus-community/windows_exporter#397]
I wanted a full dashboard for iis collector wmi prometheus  If possible please have a sample available for my servant

**Comment by carlpett** [comment]
Hi @mango19b,
I don't personally have one, hopefully someone in the community has one to share!

**Comment by mango19b** [comment]
> Hi @mango19b,
> I don't personally have one, hopefully someone in the community has one to share!

Thankful

**Comment by alekssako** [comment]
@mango19b I have one for SQL Server you can have a look : https://github.com/alekssako/grafana-dashboards/blob/master/Prometheus-Windows/SQL-Server-Monitoring.json

**Comment by alekssako** [comment]
@mango19b this one is for Windows IIS : https://github.com/alekssako/grafana-dashboards/blob/master/Prometheus-Windows/Windows-IIS-Server.json

You probably will need to modify as your specific needs... but is a good start.
