### ISSUE TITLE
How can I monitor multiple services?

### ISSUE THREAD

**Issue by kerven88** [prometheus-community/windows_exporter#398]
Hello!
I want to monitor multiple services, how do I implement them?
I tried the following method：
./wmi_exporter.exe --telemetry.addr=":9183"  --collectors.enabled="cpu,cs,logical_disk,net,os,service,system,textfile,process" --collector.service.services-where="Name='RemoteRegistry'" --collector.service.services-where="Name='W32Time'"

But throw an error：
wmi_exporter.exe: error: flag 'collector.service.services-where' cannot be repeated, try --help
![error](https://user-images.githubusercontent.com/51351006/65005996-5b9c2f80-d934-11e9-85cd-b1e0c9e83160.png)

**Comment by breed808** [comment]
@kerven88 you need to use a single WMI filter:

`.\wmi_exporter-0.8.3-amd64.exe --telemetry.addr=":9183" --collectors.enabled="cpu,cs,logical_disk,net,os,service,system,textfile,process" --collector.service.services-where="Name='W32Time' or Name='RemoteRegistry'"`

**Comment by reformc** [comment]
How to wirte the yml?

**Comment by breed808** [comment]
Hi @reformc, are you referring to the recent configuration file support? It would be worth opening a separate issue with some more detail on your problem.
