### ISSUE TITLE
How can I setting mssql multiple instance name?

### ISSUE THREAD

**Issue by csinghans** [prometheus-community/windows_exporter#408]
My mssql server has multiple instance name, but I start service just find default instance name, it's "MSSQLSERVER", How can I setting mssql multiple instance name?

**Comment by alekssako** [comment]
If you need to use it in grafana, you can achieve it using global variables like : 
`$server` defined in another variable
`label_values(wmi_mssql_genstats_logical_connections{job=~"$server.*"}, exported_instance)`
`exported_instance` is what you looking for.

**Comment by csinghans** [comment]
thank for answer , I mean  I can't find another instance name on "localhost:9182/metrics".
 I just find this `{instance="MSSQLSERVER"}`

**Comment by rajacoast** [comment]
Hi Alex,

exported_instance is what I am looking for. I am getting it as MSSQLSERVER, if I have 2 or more sql server instances running on same windows server, how to differentiate b/w them. There should be a way to get the sql server instance name.
