### ISSUE TITLE
Export TCP connections

### ISSUE THREAD

**Issue by felipsilva2** [prometheus-community/windows_exporter#414]
How to export the number of TCP connections

**Comment by breed808** [comment]
Are you looking for the total number of active TCP connections? WMI exposes TCP connections as counters so this would be fairly difficult.

You could view the number of TCP connections over time using `rate`/`irate`. E.G.
```
irate(wmi_tcp_connections_active{instance="example.com"}[2m]) + irate(wmi_tcp_connections_established{instance="example.com"}[2m]) + irate(wmi_tcp_connections_passive{instance="example.com"}[2m])
```

**Comment by carlpett** [comment]
Interestingly, it seems `wmi_tcp_connections_established` is actually a gauge (and then both our docs and code is wrong). The _active and _reset ones *are* counters, however. _passive is unclear, I don't see it moving on my machine at all, so hard to tell.
