### ISSUE TITLE
Is "HTTP Service Request Queues" metric for IIS Available?

### ISSUE THREAD

**Issue by basilmusa** [prometheus-community/windows_exporter#417]
One important metric for IIS is the current requests in the Queue. But it seems I can't find this exported in the IIS collector anywhere?

**Comment by carlpett** [comment]
Hi @basilmusa,
Sorry for the late reply! I believe that it is not exposed since it was not available. Do you have an example query which shows it? It may very well have been added since the initial implementation.

**Comment by basilmusa** [comment]
> Hi @basilmusa,
> Sorry for the late reply! I believe that it is not exposed since it was not available. Do you have an example query which shows it? It may very well have been added since the initial implementation.

It's been some time. I'll check again when i get some time. Thanks.
