### ISSUE TITLE
WMI Exporter not pulling wmi_service metrics

### ISSUE THREAD

**Issue by Kidd-Sisco** [prometheus-community/windows_exporter#419]
OS: Windows Server 2012 R2
WMI version: Both 0.9.0 & 0.3.4

I'm seeing the the following error in Event viewer:

- System 
  - Provider 
   [ Name]  wmi_exporter 

  - EventID 102 
   [ Qualifiers]  0 
   Level 2 
   Task 0 
   Keywords 0x80000000000000 
 
  - TimeCreated 
   [ SystemTime]  2019-10-18T18:39:10.000000000Z 
   EventRecordID 1982695 
   Channel Application 
   Computer somecomputer.domain 
   Security 

- EventData 
   failed collecting service metrics:<nil> wmi: cannot load field "State" into a "string": unsupported type (<nil>) 

Any way to fix this or see what is causing this on the system. I have WMI exporter running in other environments and it's working fine.

**Comment by carlpett** [comment]
Hi @Kidd-Sisco,
This sounds like the machine is returning the Service counters in an unexpected format. You could try running `gwmi Win32_Service` and check if the `State` field looks corrupted or is missing?

**Comment by Kidd-Sisco** [comment]
Hi @carlpett,
Thank you for the reply. The `gmi Win32_Service` returned the State field as OK. The exporter is publishing metrics but not the wmi_service ones. I'm not sure what the issue is, whether it's the install or the how the server is locked down. Any other ideas?

**Comment by SovietFrontier** [comment]
@Kidd-Sisco I know this is years later, but did you ever get it to work? I am running into the same issue.
