### ISSUE TITLE
Network Adapter Status

### ISSUE THREAD

**Issue by tompal3** [prometheus-community/windows_exporter#424]
Hi
we want to list all network adapters on machine and to have their status . Currently this can be achieved by running:  
`Get-WmiObject Win32_NetworkAdapter `
but this is not a part of `Win32_PerfRawData` and seems not to work with `.\New-Collector.ps1` out of the box . Can you suggest any way to have it as a part of wmi_exporter?

**Comment by breed808** [comment]
@tompal3 which field are you using to determine interface status?

`Get-WmiObject Win32_NetworkAdapter` is returning the following for me:

```
ServiceName      : E1G60
MACAddress       : 01:23:45:67:89:AB
AdapterType      : Ethernet 802.3
DeviceID         : 4
Name             : Intel(R) PRO/1000 MT Desktop Adapter
NetworkAddresses :
Speed            : 1000000000
```

**Comment by tompal3** [comment]
it is netconnectionstatus:
`get-wmiobject win32_networkadapter -filter "netconnectionstatus = 2" | select netconnectionid, name, InterfaceIndex, netconnectionstatus`

**NetConnectionStatus**

Data type: uint16

Access type: Read-only

State of the network adapter connection to the network.


Disconnected (0)


Connecting (1)


Connected (2)


Disconnecting (3)


Hardware Not Present (4)


Hardware Disabled (5)


Hardware Malfunction (6)


Media Disconnected (7)


Authenticating (8)


Authentication Succeeded (9)


Authentication Failed (10)


Invalid Address (11)


Credentials Required (12)

source:
https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-networkadapter?redirectedfrom=MSDN

**Comment by martinlindhe** [comment]
@breed808 powershell is not always intuitive, your command just show the default presentation of the result.

Try

    Get-WmiObject Win32_NetworkAdapter | Format-List *

**Comment by breed808** [comment]
@tompal3 @martinlindhe thanks all, didn't realise the command was hiding object fields by default :frowning_face:

**Comment by breed808** [comment]
Doesn't look like perflib exposes any form of interface status. Perhaps querying `Win32_NetworkAdapter` in `collector/net.go` alongside the current perflib metrics would be a solution?

**Comment by wizardmatas** [comment]
Hi, do we have any other collector which execute poweshell to get metrics instead of using perflib for it ?If yes please note which one. Thank you.

On the other hand, is it realy good practice to mix such a different ways in performance perspective(assume that perf lib is much faster than powershell) to collect metrics? Maybe @martinlindhe or @carlpett  can comment on this ?

**Comment by carlpett** [comment]
You always have the option of using the textfile collector to get metrics you generate yourself. There's an example [in the docs](https://github.com/martinlindhe/wmi_exporter/blob/master/docs/collector.textfile.md) of using Powershell for this.
So this could be a workaround when we cannot access the data for some reason.

**Comment by wizardmatas** [comment]
Ok, lets make it clear, if we will include some part of code in collector/net.go which gathers metrics using powershell, can we expect it will be merged into master ? or it should be separate collector ?  what would be your advice? Thank you

**Comment by carlpett** [comment]
@wizardmatas No, code shelling out to powershell will not be merged into the Go collectors. What I meant was that if you need this _today_, you can get it by writing a Powershell script that you schedule on your machines and which writes files the textfile collector can use.
If we determine that the adapter status is something we should support, but it is not available with perflib, we could fall back to using the same WMI code we have been using previously. Such a PR would possibly be merged, at least.

**Comment by wizardmatas** [comment]
Thanks, @carlpett, that is what I expected. We will try to dig into this.  I assume we can close this one?
