### ISSUE TITLE
failed collecting metrics

### ISSUE THREAD

**Issue by roiromanoclick** [prometheus-community/windows_exporter#427]
Hi, 
I'm using win server 2012 r2 
-wmi version 0.6.0 
- Getting error in event viewer - failed collecting metrics ( for all metrics ) 
- installation command - 
c:\temp\wmi_exporter-0.6.0-amd64.msi ENABLED_COLLECTORS=os,iis,cpu,dns,net,system,process,logical_disk,service,os,ad,cs LISTEN_PORT=9182
-wmi service is running.
-Rebooted and reinstall didn't help.

Please suggest how to fix it.

 Thanks!

**Comment by roiromanoclick** [comment]
http://localhost:9182/metrics
The page loads a lot of time.

**Comment by khomich-vlad** [comment]
Try to limit the process metrics via `--collector.process.processes-where "Name LIKE 'firefox%'"`

**Comment by carlpett** [comment]
Hi @roiromanoclick,
Could you paste the exact error message you are seeing in the event log? Also, note that the version you are running is pretty old, is there a reason not using 0.9?

**Comment by breed808** [comment]
Closing due to a lack of activity
