### ISSUE TITLE
wmi_hyperv_health_critical Questions

### ISSUE THREAD

**Issue by ampieka** [prometheus-community/windows_exporter#432]
My assumption with this metric was that it reported on the replication health of VM's on the machine.  this morning when i walked in the VM's replication health was at critical, but the exporter was saying that all the machines were healthy.  Do i have the wrong assumption of this metric or is it not working for one reason or another.

Environment:
HP ProLiant DL385p Gen8
running 8 VMs

![image](https://user-images.githubusercontent.com/57642439/68623408-70afbd80-04a2-11ea-9650-eb2af8989124.png)

**Comment by carlpett** [comment]
Hi @ampieka,
This metric exposes data from the WMI class `Win32_PerfRawData_VmmsVirtualMachineStats_HyperVVirtualMachineHealthSummary`. This *should* be the same that the Hyper-V management console exposes, I believe. I don't have a Hyper-V machine available to see what this does and does not consider critical, however.
I assume it is now a bit late for you to investigate the machine? It would be helpful if we could determine what it covers and not.
