### ISSUE TITLE
issues with thermalzone collector 

### ISSUE THREAD

**Issue by czepesch** [prometheus-community/windows_exporter#443]
Hello,
I have Win2k8 R2 and have installed v0.9.0 wmi exporter.
Thermalzone collector dont work:
```
wmi_exporter_collector_success{collector="cpu"} 1
wmi_exporter_collector_success{collector="cs"} 1
wmi_exporter_collector_success{collector="logical_disk"} 1
wmi_exporter_collector_success{collector="memory"} 1
wmi_exporter_collector_success{collector="mssql"} 1
wmi_exporter_collector_success{collector="net"} 1
wmi_exporter_collector_success{collector="os"} 1
wmi_exporter_collector_success{collector="system"} 1
wmi_exporter_collector_success{collector="thermalzone"} 0
```
In properties of WMI exporter service:
```
"c:\Program Files\wmi_exporter\wmi_exporter.exe" --log.format logger:eventlog?name=wmi_exporter --collectors.enabled os,cpu,cs,logical_disk,memory,thermalzone,net,system,mssql --telemetry.addr :9182  
```
This is a bug or there is a things I can do to make thermalzone work?

thank You.

**Comment by carlpett** [comment]
Hi @czepesch,
Do you get any indication in the event viewer what the error is?
You can try to run this in Powershell:
```powershell
Get-WMIObject Win32_PerfRawData_Counters_ThermalZoneInformation 
```
Do you get any results back?

**Comment by czepesch** [comment]
@carlpett hi,
I have a lot of errors in event viewer (almost every second):
```
failed collecting thermalzone metrics:<nil> Ошибка. (Invalid class )
```
```
collector thermalzone failed after 0.187006s: Ошибка. (Invalid class )
```
seems like no results back by this command:
```
Get-WmiObject : Invalid class
строка:1 знак:14
+ Get-WMIObject <<<<  Win32_PerfRawData_Counters_T
    + CategoryInfo          : InvalidOperation: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand
```

**Comment by carlpett** [comment]
I see, in that case it seems like your computer does not have the necessary counters installed. I cannot say exactly when those are installed I'm afraid, but I can see two possibilities:
- It could be that your system simply does not have supported hardware
- They may not be supported on Windows 2008R2

Microsoft sadly doesn't seem to have any public documentation on this class, so I cannot determine much more. If possible, upgrading to a more recent Windows release *might* help, although I understand that it is likely quite out-of-scope for just fixing this problem (although there's just three weeks until 2008R2 goes end-of-life, so you might want to look at it anyway...).

**Comment by oblalex** [comment]
Same situation for Server 2012.
