### ISSUE TITLE
Add commandline information to process collector

### ISSUE THREAD

**Issue by MarcoJ-CID** [prometheus-community/windows_exporter#445]
We host several DotNet Core Applications on one server. The WMI Exporter shows all processes, but we can't assign the processes to the respective application because we only have the ProcessID. 

```
wmi_process_cpu_time_total{creating_process_id="19760",mode="privileged",process="dotnet",process_id="76324"} 122
wmi_process_cpu_time_total{creating_process_id="19880",mode="privileged",process="dotnet",process_id="38168"} 127.234375
wmi_process_cpu_time_total{creating_process_id="21320",mode="privileged",process="dotnet",process_id="73952"} 115.5
wmi_process_cpu_time_total{creating_process_id="21668",mode="privileged",process="dotnet",process_id="56404"} 0.75
wmi_process_cpu_time_total{creating_process_id="24172",mode="privileged",process="dotnet",process_id="34688"} 976.734375
wmi_process_cpu_time_total{creating_process_id="25532",mode="privileged",process="dotnet",process_id="17700"} 29.375
wmi_process_cpu_time_total{creating_process_id="3024",mode="privileged",process="dotnet",process_id="15372"} 118.265625
wmi_process_cpu_time_total{creating_process_id="32656",mode="privileged",process="dotnet",process_id="18596"} 115.15625
```

However, we would have liked to assign the process information based on the started dll. In the Windows TaskManager, under 'Details', you can display the command line and see to which app the process belongs. Unfortunately the info is not provided with the class `Win32_PerfRawData_PerfProc_Process` but the class `Win32_Process` could provide this information.

```
PS C:\> $processInformation = Get-WmiObject Win32_Process -Filter "processid = '76324'"
PS C:\> $processInformation | Select CommandLine, ProcessId

CommandLine                                                                   ProcessId
-----------                                                                   ---------
dotnet .\Dotnet.Core.Test.Three.dll                                               76324
```

**Comment by carlpett** [comment]
Hi @MarcoJ-CID,
This has been discussed before, for example #134. Due to the cost involved, both on the prometheus storage side, as well as issuing extra WMI queries, this will likely not be implemented.
Since you control these applications yourself, the suggestion would be to instrument them directly instead, eg via [the dotnet client library](https://github.com/prometheus-net/prometheus-net).
