### ISSUE TITLE
inconsistent label dimensions in multiple textfiles causes HTTP 500

### ISSUE THREAD

**Issue by kl-gh** [prometheus-community/windows_exporter#448]
http://localhost:/metrics returns HTTP 500 internal server error, when there are two textfiles with same metric with different labels

Expected behaviour:
* wmi_exporter should export both metrics
* with node_exporter I have no problems to do similar things
* According to https://github.com/prometheus/client_golang/commit/c06fb788be8a05442219295095ee0e51523802f0 this should be possible 

Steps to reproduce:
1. Create `file1.prom` with `label_a`:
```
# HELP foo bar
# TYPE foo gauge
foo{label_a = "bar"} 1
```
2. Create `file2.prom` with `label_b`:
```
# HELP foo bar
# TYPE foo gauge
foo{label_b = "bar"} 1
```
3. Try to scrape it via textfile collector http://localhost:/metrics

**Comment by carlpett** [comment]
We need to update our dependency on client_golang, which will fix this. #420 should be done first, but then it should be simple.

**Comment by lapo-luchini** [comment]
This also stops in error 500 if there is a duplicate value in a single file, and breaks all other metrics; I'd suggest rather at worst ignore that single Prom file and keep exporting other metrics.
