### ISSUE TITLE
How do I get tcp time_wait?

### ISSUE THREAD

**Issue by for-mat** [prometheus-community/windows_exporter#449]
I want to get the time_wait information in Windows, but only wmi_tcp_connections_established is used to get the established and close_wait data.How do I get time_wait?

**Comment by for-mat** [comment]
https://github.com/martinlindhe/wmi_exporter/issues/414#issuecomment-541979162
An attempt was made to obtain the total number of TCP connections, but the results were incorrect based on the above

**Comment by for-mat** [comment]
![image](https://user-images.githubusercontent.com/43637488/71504123-21d3b100-28b3-11ea-89f3-7e888f6de163.png)
![image](https://user-images.githubusercontent.com/43637488/71504134-30ba6380-28b3-11ea-94f3-05d3e5ff55d6.png)
Using wmi_tcp_connections_established{instance="10.0.10.162:9182" without irate is correct, but I also need time_wait data

**Comment by carlpett** [comment]
Hi @for-mat,
I'm afraid Windows doesn't expose time_wait as part of their WMI counters. If you could find a class which does contain this information, we could look into adding it, but with the current ones, it is not possible.

**Comment by for-mat** [comment]
> @ for-mat，您好，
> 恐怕Windows不会在其WMI计数器中公开time_wait。如果您找到一个确实包含此信息的类，我们可以考虑添加它，但是对于当前的类，这是不可能的。

In zabbbix's monitor, time_wait can be displayed.You can also view this value in windowsd CMD via netstat . anyway,thanks

**Comment by carlpett** [comment]
I assume zabbix would then be parsing the output of netstat or similar. We do not support (nor want to support) collecting metrics by exec:ing other binaries and parsing their output. If you need something which is only available by that method, you should look into using the [textfile collector](https://github.com/martinlindhe/wmi_exporter/blob/master/docs/collector.textfile.md) in combination with eg a scheduled task to write the necessary data to disk.
