### ISSUE TITLE
GPU metrics (NVIDIA specifically)

### ISSUE THREAD

**Issue by zhenisduissekov** [prometheus-community/windows_exporter#457]
Hello!

Thank you very much for the wmi_exporter. I have been using it for almost two months and its been very useful. I wonder if there is any possibility to get GPU metrics? I have NVIDIA card and really want to monitor it. NVIDIA offers an extension NVIDIA WMI. Is it possible to scrape these parameters?

source: https://www.nvidia.com/content/quadro_fx_product_literature/wp-06953-001-v02.pdf

regards
Zhenis

**Comment by carlpett** [comment]
Hi @zhenisduissekov,
Thanks for the suggestion! From a quick look at the linked document, it seems we should be able to read parts of it, at least. Some of their examples include invoking methods on WMI objects, which we don't support, but anything that is possible to show in perfmon should be possible in the exporter!
I personally do not have an environment with a supported GPU, however, so we'd need someone to contribute the code.

**Comment by zhenisduissekov** [comment]
Hello Martin!

thank you for your reply. In fact, I can create a remote access to workstation with GPU (NVIDIA) and will be happy to contribute some money for your help.

regards
Zhenis.

**Comment by zhenisduissekov** [comment]
Hi
If you like we can chat over email or whatsapp
my email is zduissekov@gmail.com
whatsapp +77017539889

**Comment by elurex** [comment]
In current Windows 10 Pro 1909, it is capable showing gpu usage via wmi (which is built into windows already)

![image](https://user-images.githubusercontent.com/15149930/74299974-49aaa580-4d89-11ea-94df-a09de84d74b4.png)
