### ISSUE TITLE
promu build -v . fails

### ISSUE THREAD

**Issue by shivakumargn** [prometheus-community/windows_exporter#458]
promu build -v . fails.

> cd %GOPATH%\github.com\martinlindhe\wmi_exporter
> promu build -v .
Using config file: .promu.yml
Running command: build [-v .]
!! binary . not found in config
validation of given binary names for build command failed
github.com/prometheus/promu/cmd.runBuild
        <gopath>/src/github.com/prometheus/promu/cmd/build.go:137
github.com/prometheus/promu/cmd.Execute
        <gopath>/src/github.com/prometheus/promu/cmd/promu.go:125
main.main
        <gopath>/src/github.com/prometheus/promu/main.go:20
runtime.main
        c:/go/src/runtime/proc.go:203
runtime.goexit
        c:/go/src/runtime/asm_amd64.s:1357

Seems similar to https://github.com/martinlindhe/wmi_exporter/issues/119

**Comment by breed808** [comment]
Have you set `GOOS=windows`? Try omitting the local dir in the `promu` command.

E.G. `GOOS=windows promu build -v`
