### ISSUE TITLE
collection time out 

### ISSUE THREAD

**Issue by pechettibhaskar** [prometheus-community/windows_exporter#469]
1. It showing collection time out error
![image](https://user-images.githubusercontent.com/55787564/75145895-ebce7400-571f-11ea-8d0f-23fdee6d681b.png)
2. CPU memory load very less but we are getting timeout for collection.
3.How to find what power shell modules are used in backend for collecting these metrics,Can you find the solution for this.

**Comment by carlpett** [comment]
Hi @pechettibhaskar,
First a sidenote: I see that you are getting the events every five seconds. Note that this is a pretty intense scrape frequency, and you should evaluate if you really need it. It will increase the impact of your montoring significantly over the Prometheus default of 60s.

For your questions - what is your `scrape_timeout` configuration in Prometheus? The message will be logged if we were not able to complete a scrape before this period expires. WMI queries can take a few seconds to complete.

There are no Powershell modules involved in collecting the metrics. It is just Go code.

**Comment by pechettibhaskar** [comment]
Hi @carlpett ,
How can set at scrape_timeout level in at expoter level, i have seen scrape_timeout in Prometheus server level. I want set in Prometheus expoter level. In the above I did nt set any scrape_timeout level, that is working on default >> 1 .  For exe file: .\wmi_exporter-0.9.0-amd64.exe --collectors.enabled="os,cpu,cs,dns,logical_disk,memory,net,process,service,system,tcp,iis,mssql" 2.  For msi file : msiexec /i C:\Users\Administrator\Downloads\wmi_exporter-0.9.0-amd64.msi  ENABLED_COLLECTORS=os,cpu,cs,dns,logical_disk,memory,net,process,service,system,tcp,iis,mssql LISTEN_PORT=9182 <<

**Comment by alekssako** [comment]
Hi @pechettibhaskar 

> "Seconds to subtract from the timeout allowed by the client. Tune to allow for overhead or high loads."

You can set `--% EXTRA_FLAGS="--scrape.timeout-margin=20"` to 20 seconds.

**Comment by carlpett** [comment]
The scrape timeout is set on the Prometheus server, the exporter cannot tell Prometheus to have a longer timeout. You can tune the timeout per job in Prometheus configuration, however, if that helps, see [`scrape_config` docs](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#scrape_config).

Could you check the value of the metric `scrape_duration_seconds` for the wmi_exporter job in your Prometheus server?

@alekssako That config would mean that the exporter would try to get results in 20 seconds _less_ than the timeout. With the default 10 second timeout, that would mean that we'd abort immediately.

**Comment by alekssako** [comment]
@carlpett yes but is possible to tune `scrape.timeout-margin` based on prometheus `scrape_config` for high server loads.

**Comment by pechettibhaskar** [comment]
@carlpett @alekssako We are not using the Prometheus server. We are taking the URL data of the exporter. 
We are getting the timeout error after adding the scrape-timeout
![image](https://user-images.githubusercontent.com/55787564/75246169-3968e080-57f5-11ea-8d33-25558a7b36c4.png)

error:
extfile.go:222"
WARN[0013] Collection timed out, still waiting for [logical_disk net os service system textfile cpu cs]  source="exporter.go:186"
ERRO[0013] Error reading textfile collector directory "C:\\Program Files\\wmi_exporter\\textfile_inputs": open C:\Program Files\wmi_exporter\textfile_inputs: The system cannot find the path specified.  source="t
extfile.go:222"

**Comment by carlpett** [comment]
As I mentioned in my previous reply, setting the suggested `scrape.timeout-margin` will effectively set the timeout to zero, which will immediately time out, unless you also pass a header with a larger timeout value.
But you are scraping the data and inserting it into some other system, without using Prometheus at all? That is an interesting use-case, but will make it harder for us to support.

**Comment by pechettibhaskar** [comment]
Hello, @carlpett, As you said that I have tried by keeping the --scrape.timeout-margin=0.5, 20, 60, 120. Still, we are getting the timeout errors. The below image is the outputs of different Scarpe-timeout-margins.
![image](https://user-images.githubusercontent.com/55787564/75315975-26542000-588a-11ea-9048-13aac778bcd5.png)
![image](https://user-images.githubusercontent.com/55787564/75315989-2fdd8800-588a-11ea-928e-a5e5f1913147.png)
![image](https://user-images.githubusercontent.com/55787564/75316006-37049600-588a-11ea-9afd-3d1e728b91ef.png)

We are taking the data of the exporter URL, in the Prometheus server also we don't get data in the exporter URL(http://ip:9182/metrics). Due to this timeout issue.
![image](https://user-images.githubusercontent.com/55787564/75316093-6915f800-588a-11ea-823a-9a4ed4577585.png)
I understood that if I increase timeout it will work, but I am unable to figure out how to increase the timeout value. Can you provide the full command of that?

Suggest me a way to get the data without using scrape.timeout-margin.

**Comment by alekssako** [comment]
@pechettibhaskar you can add collectors one by one to check from which one you are getting timeout. (or leave it blank to see whether the defaults do not give timeout)

**Comment by pechettibhaskar** [comment]
@alekssako Thank you for a suggestion 

when I giving this command = .\wmi_exporter-0.9.0-amd64.exe --collectors.enabled="[defulat],iis" , I getting data.
![image](https://user-images.githubusercontent.com/55787564/75368258-744b4100-58e7-11ea-96d8-a80a60273c21.png)
But when i given the complete command = .\wmi_exporter-0.9.0-amd64.exe --collectors.enabled="os,cpu,cs,dns,logical_disk,memory,net,process,service,system,tcp,iis,mssql" i am getting collection time out.

**Comment by carlpett** [comment]
@pechettibhaskar The timeout configuration is on the Prometheus server side. What does your job configuration for the exporter look like there?
From looking at your screenshots, it seems all WMI-based collectors are timing out, while the ones that succeed are perflib-based. This suggests that something is not working with the WMI subsystem on your machine, could you try running `Get-WmiObject Win32_ComputerSystem` in Powershell?

**Comment by carlpett** [comment]
Closing for lack of response. If this is still an issue, please update and we can reopen.
