### ISSUE TITLE
For some reason wmi_ad_replication_pending_synchronizations is not 0

### ISSUE THREAD

**Issue by eligosfx** [prometheus-community/windows_exporter#478]
What does it mean wmi_ad_replication_pending_synchronizations > 0, i can't see any error in my active directory.
Please explain to me , how can I check with wmi command to check my value.

**Comment by eligosfx** [comment]
From perf monitor i getting 0, from wmi exporter the number is not 0, trying to understand where is the issue.

**Comment by carlpett** [comment]
Hi @eligosfx,
That's odd. What value are you getting?
You can see the data we are fetching by running `gwmi Win32_PerfRawData_DirectoryServices_DirectoryServices` in Powershell

**Comment by eligosfx** [comment]
Get-WmiObject -Query "select * from Win32_PerfFormattedData_DirectoryServices_DirectoryServices"


__GENUS                                                          : 2
__CLASS                                                          : Win32_PerfFormattedData_DirectoryServices_DirectoryServices
__SUPERCLASS                                                     : Win32_PerfFormattedData
__DYNASTY                                                        : CIM_StatisticalInformation
__RELPATH                                                        : Win32_PerfFormattedData_DirectoryServices_DirectoryServices.Name="NTDS"
__PROPERTY_COUNT                                                 : 175
__DERIVATION                                                     : {Win32_PerfFormattedData, Win32_Perf, CIM_StatisticalInformation}
__SERVER                                                         : RMPR-MNG01
__NAMESPACE                                                      : root\cimv2
__PATH                                                           : \\RMPR-MNG01\root\cimv2:Win32_PerfFormattedData_DirectoryServices_DirectoryServices.Name="NTDS"
ABANRPersec                                                      : 0
ABBrowsesPersec                                                  : 0
ABClientSessions                                                 : 0
ABMatchesPersec                                                  : 0
ABPropertyReadsPersec                                            : 0
ABProxyLookupsPersec                                             : 0
ABSearchesPersec                                                 : 0
ApproximatehighestDNT                                            : 57471
ATQEstimatedQueueDelay                                           : 0
ATQOutstandingQueuedRequests                                     : 0
ATQQueueLatency                                                  : 0
ATQRequestLatency                                                : 1
ATQThreadsLDAP                                                   : 0
ATQThreadsOther                                                  : 0
ATQThreadsTotal                                                  : 18
BasesearchesPersec                                               : 0
Caption                                                          : 
DatabaseaddsPersec                                               : 0
DatabasedeletesPersec                                            : 0
DatabasemodifysPersec                                            : 0
DatabaserecyclesPersec                                           : 0
Description                                                      : 
DigestBindsPersec                                                : 0
DirSyncsessionsinprogress                                        : 0
DirSyncsessionthrottlingrate                                     : 0
DRAHighestUSNCommittedHighpart                                   : 0
DRAHighestUSNCommittedLowpart                                    : 488924
DRAHighestUSNIssuedHighpart                                      : 0
DRAHighestUSNIssuedLowpart                                       : 488925
DRAInboundBytesCompressedBetweenSitesAfterCompressionPersec      : 0
DRAInboundBytesCompressedBetweenSitesAfterCompressionSinceBoot   : 7394965
DRAInboundBytesCompressedBetweenSitesBeforeCompressionPersec     : 0
DRAInboundBytesCompressedBetweenSitesBeforeCompressionSinceBoot  : 10337952
DRAInboundBytesNotCompressedWithinSitePersec                     : 0
DRAInboundBytesNotCompressedWithinSiteSinceBoot                  : 23638432
DRAInboundBytesTotalPersec                                       : 0
DRAInboundBytesTotalSinceBoot                                    : 31033397
DRAInboundFullSyncObjectsRemaining                               : 0
DRAInboundLinkValuesPersec                                       : 0
DRAInboundLinkValueUpdatesRemaininginPacket                      : 0
DRAInboundObjectsAppliedPersec                                   : 0
DRAInboundObjectsFilteredPersec                                  : 0
DRAInboundObjectsPersec                                          : 0
DRAInboundObjectUpdatesRemaininginPacket                         : 0
DRAInboundPropertiesAppliedPersec                                : 0
DRAInboundPropertiesFilteredPersec                               : 0
DRAInboundPropertiesTotalPersec                                  : 0
DRAInboundSyncLinkDeletionPersec                                 : 0
DRAInboundTotalUpdatesRemaininginPacket                          : 0
DRAInboundValuesDNsonlyPersec                                    : 0
DRAInboundValuesTotalPersec                                      : 0
DRAnumberofNCreplicationcallssinceboot                           : 9983
DRAnumberofsuccessfulNCreplicationcallssinceboot                 : 9700
DRAOutboundBytesCompressedBetweenSitesAfterCompressionPersec     : 0
DRAOutboundBytesCompressedBetweenSitesAfterCompressionSinceBoot  : 0
DRAOutboundBytesCompressedBetweenSitesBeforeCompressionPersec    : 0
DRAOutboundBytesCompressedBetweenSitesBeforeCompressionSinceBoot : 0
DRAOutboundBytesNotCompressedWithinSitePersec                    : 0
DRAOutboundBytesNotCompressedWithinSiteSinceBoot                 : 20167416
DRAOutboundBytesTotalPersec                                      : 0
DRAOutboundBytesTotalSinceBoot                                   : 20167416
DRAOutboundObjectsFilteredPersec                                 : 0
DRAOutboundObjectsPersec                                         : 0
DRAOutboundPropertiesPersec                                      : 0
DRAOutboundValuesDNsonlyPersec                                   : 0
DRAOutboundValuesTotalPersec                                     : 0
DRAPendingReplicationOperations                                  : 0
DRAPendingReplicationSynchronizations                            : 0
DRASyncFailuresonSchemaMismatch                                  : 0
DRASyncRequestsMade                                              : 9983
DRASyncRequestsSuccessful                                        : 9700
DRAThreadsGettingNCChanges                                       : 0
DRAThreadsGettingNCChangesHoldingSemaphore                       : 0
DRAtotalnumberofBusyfailuressinceboot                            : 0
DRAtotalnumberofMissingParentfailuressinceboot                   : 0
DRAtotalnumberofNotEnoughAttrsPerMissingObjectfailuressinceboot  : 0
DRAtotalnumberofPreemptedfailuressinceboot                       : 0
DRAtotaltimeofapplyingreplicationpackagesinceboot                : 972
DRAtotaltimeofNCreplicationcallssinceboot                        : 1078746
DRAtotaltimeofsuccessfullyapplyingreplicationpackagesinceboot    : 972
DRAtotaltimeofsuccessfulNCreplicationcallssinceboot              : 1003344
DRAtotaltimeonwaitingasyncreplicationpackagessinceboot           : 0
DRAtotaltimeonwaitingsyncreplicationpackagessinceboot            : 634580
DSClientBindsPersec                                              : 0
DSClientNameTranslationsPersec                                   : 0
DSDirectoryReadsPersec                                           : 0
DSDirectorySearchesPersec                                        : 0
DSDirectoryWritesPersec                                          : 0
DSMonitorListSize                                                : 21
DSNameCachehitrate                                               : 0
DSNotifyQueueSize                                                : 0
DSPercentReadsfromDRA                                            : 1
DSPercentReadsfromKCC                                            : 2
DSPercentReadsfromLSA                                            : 0
DSPercentReadsfromNSPI                                           : 0
DSPercentReadsfromNTDSAPI                                        : 0
DSPercentReadsfromSAM                                            : 96
DSPercentReadsOther                                              : 0
DSPercentSearchesfromDRA                                         : 0
DSPercentSearchesfromKCC                                         : 0
DSPercentSearchesfromLDAP                                        : 88
DSPercentSearchesfromLSA                                         : 0
DSPercentSearchesfromNSPI                                        : 0
DSPercentSearchesfromNTDSAPI                                     : 10
DSPercentSearchesfromSAM                                         : 0
DSPercentSearchesOther                                           : 0
DSPercentWritesfromDRA                                           : 26
DSPercentWritesfromKCC                                           : 0
DSPercentWritesfromLDAP                                          : 2
DSPercentWritesfromLSA                                           : 0
DSPercentWritesfromNSPI                                          : 0
DSPercentWritesfromNTDSAPI                                       : 0
DSPercentWritesfromSAM                                           : 70
DSPercentWritesOther                                             : 0
DSSearchsuboperationsPersec                                      : 0
DSSecurityDescriptorPropagationsEvents                           : 0
DSSecurityDescriptorPropagatorAverageExclusionTime               : 0
DSSecurityDescriptorPropagatorRuntimeQueue                       : 0
DSSecurityDescriptorsuboperationsPersec                          : 0
DSServerBindsPersec                                              : 0
DSServerNameTranslationsPersec                                   : 0
DSThreadsinUse                                                   : 0
ExternalBindsPersec                                              : 0
FastBindsPersec                                                  : 0
Frequency_Object                                                 : 
Frequency_PerfTime                                               : 
Frequency_Sys100NS                                               : 
LDAPActiveThreads                                                : 0
LDAPBindTime                                                     : 0
LDAPClientSessions                                               : 7
LDAPClosedConnectionsPersec                                      : 0
LDAPNewConnectionsPersec                                         : 0
LDAPNewSSLConnectionsPersec                                      : 0
LDAPPageSearchCacheentriescount                                  : 0
LDAPPageSearchCachesize                                          : 0
LDAPSearchesPersec                                               : 0
LDAPSuccessfulBindsPersec                                        : 0
LDAPUDPoperationsPersec                                          : 0
LDAPWritesPersec                                                 : 0
LinkValuesCleanedPersec                                          : 0
Name                                                             : NTDS
NegotiatedBindsPersec                                            : 0
NTLMBindsPersec                                                  : 0
OnelevelsearchesPersec                                           : 0
PhantomsCleanedPersec                                            : 0
PhantomsVisitedPersec                                            : 0
RIDPoolinvalidationssinceboot                                    : 0
RIDPoolrequestfailuressinceboot                                  : 0
RIDPoolrequestsuccessessinceboot                                 : 0
SAMAccountGroupEvaluationLatency                                 : 324
SAMDisplayInformationQueriesPersec                               : 0
SAMDomainLocalGroupMembershipEvaluationsPersec                   : 0
SAMEnumerationsPersec                                            : 0
SAMGCEvaluationsPersec                                           : 0
SAMGlobalGroupMembershipEvaluationsPersec                        : 0
SAMMachineCreationAttemptsPersec                                 : 0
SAMMembershipChangesPersec                                       : 0
SAMNonTransitiveMembershipEvaluationsPersec                      : 0
SAMPasswordChangesPersec                                         : 0
SAMResourceGroupEvaluationLatency                                : 0
SAMSuccessfulComputerCreationsPersecIncludesallrequests          : 0
SAMSuccessfulUserCreationsPersec                                 : 0
SAMTransitiveMembershipEvaluationsPersec                         : 0
SAMUniversalGroupMembershipEvaluationsPersec                     : 0
SAMUserCreationAttemptsPersec                                    : 0
SimpleBindsPersec                                                : 0
SubtreesearchesPersec                                            : 0
Timestamp_Object                                                 : 
Timestamp_PerfTime                                               : 
Timestamp_Sys100NS                                               : 
TombstonesGarbageCollectedPersec                                 : 0
TombstonesVisitedPersec                                          : 0
Transitiveoperationsmillisecondsrun                              : 0
TransitiveoperationsPersec                                       : 0
TransitivesuboperationsPersec                                    : 0

**Comment by eligosfx** [comment]
from wmi i getting 0
and from wmi_exporter is not 0

**Comment by carlpett** [comment]
This look odd. The value we read is zero, and we don't do any manipulations at all of this number. What is the exact value you get if you go to the /metrics endpoint of the exporter?

**Comment by eligosfx** [comment]
About 2000 and increasing every few minutes.

**Comment by breed808** [comment]
Is this exposed by WMI as a counter? That would explain the constantly increasing value.

![image](https://user-images.githubusercontent.com/3103817/76261894-be98ce80-62a6-11ea-8034-f944c8aae5a3.png)

**Comment by carlpett** [comment]
Yes, I would guess that we get the total number of synchronizations queued. It's been a few years since I worked on the AD environment for which I initially added the collector, but I guess it didn't queue up for some reason there.
So we should rename this to something like `wmi_ad_replication_synchronizations_queued_total` and change it to a counter. Is there a matching `_Base` counter? We'd need to know how many items have been dequeued as well for this to be useful.

**Comment by breed808** [comment]
I've had a look at the perflib side of things, and the `dra_pending_replication_synchronizations` metrics appears to be a gauge. I checked it on 4 domain controllers and it was 0 on all.
Moving the collector to perflib could be an option, though we'd need to confirm that perflib provides the same metrics.

Separate to this, I think there's something off here: the AD collector queries the `Win32_PerfRawData_DirectoryServices_DirectoryServices` (*raw*) class, while @eligosfx has provided us with output of `Win32_PerfFormattedData_DirectoryServices_DirectoryServices` (*formatted*).
I suspect the raw class is returning the raw counter, while the formatted class is returning a gauge.
I also suspect the formatted class isn't returning a "true" gauge, merely an increase() of the underlying counter for an unknown interval. If this is the case, the perflib metric would behave similarly.

@eligosfx can you query both classes and let us know if the output of each class matches?
