### ISSUE TITLE
Allow filtering via query parameters

### ISSUE THREAD

**Issue by finkr** [prometheus-community/windows_exporter#479]
Adds a collect[] URL parameter to filter currently enabled collectors.

node_exporter has this feature, see pull request => https://github.com/prometheus/node_exporter/pull/699 (and documentation [PR](https://github.com/prometheus/node_exporter/pull/784))

There was an attempt to provide a solution in prometheus/client_golang, but that's stalled => [https://github.com/prometheus/client_golang/issues/135](https://github.com/prometheus/client_golang/issues/135)

**Comment by breed808** [comment]
This has been resolved in #640 and is present in the [v0.15.0 release](https://github.com/prometheus-community/windows_exporter/releases/tag/v0.15.0).
