### ISSUE TITLE
collector_error

### ISSUE THREAD

**Issue by geldarr** [prometheus-community/windows_exporter#482]
Good afternoon.
I get this error when running \ wmi_exporter-0.10.2-amd64.exe --collectors.enabled = "logical_disk"
Windows server 2019 on KVM virt

time="2020-03-17T09:25:02+03:00" level=info msg="Build context (go=go1.13.3, user=appvyr-win\\appveyor@APPVYR-WIN, date=20200305-20:33:23)" source="exporter.go:342"
time="2020-03-17T09:25:02+03:00" level=info msg="Starting server on :9182" source="exporter.go:345"
time="2020-03-17T09:25:17+03:00" level=error msg="failed collecting logical_disk metrics:<nil> counter not found" source="logical_disk.go:162"
time="2020-03-17T09:25:17+03:00" level=error msg="collector logical_disk failed after 0.000000s: counter not found" source="exporter.go:207"
time="2020-03-17T09:25:32+03:00" level=error msg="failed collecting logical_disk metrics:<nil> counter not found" source="logical_disk.go:162"
time="2020-03-17T09:25:32+03:00" level=error msg="collector logical_disk failed after 0.001050s: counter not found" source="exporter.go:207"

**Comment by geldarr** [comment]
After running these commands, the error with the disk disappeared, but now a similar error with 'cs' and 'os'
lodctr /R
winmgmt.exe /RESYNCPERF

**Comment by carlpett** [comment]
Hi @geldarr,
These issues are very hard for us to troubleshoot, unfortunetely, but here's a step that worked for a previous reporter in addition to what you've already done:
>Try running regsvr32 wmisvc.dll at the command prompt, followed by winmgmt /resyncperf, and then reboot.
