### ISSUE TITLE
Show service name for process metrics

### ISSUE THREAD

**Issue by nvasudevan** [prometheus-community/windows_exporter#483]
Hello,

When a process is started via a service with `path to executable` set to `svchost.exe -k <service name> ...`, the process metrics such as `wmi_process_cpu_time_total` show the `process` attribute as `svchost`, is it possible to include/show the _service name_ (or even the _display name_) in the metric, rather than `svchost` for the process attribute? At present, it is quite difficult to work out which svchost entry maps to the service.

For e.g.: For the `Remote Desktop Services` service, the entry for `wmi_process_cpu_time_total` looks as follows:

`wmi_process_cpu_time_total{creating_process_id="788",mode="privileged",process="svchost",process_id="5044"} 6932.28125`

Can this be shown as:

`wmi_process_cpu_time_total{creating_process_id="788",mode="privileged",process="termsvcs",process_id="5044"} 6932.28125`

**Comment by carlpett** [comment]
Hi @nvasudevan,
Thanks for the suggestion! We actually do something similar for IIS worker processes, so seems reasonable to extend that for services too.
It would be useful if you could figure out how to correlate these, though. The data in `Win32_PerfRawData_PerfProc_Process` doesn't contain the commandline, so there's a need to make another query which gives the required info.

**Comment by nvasudevan** [comment]
Thanks @carlpett Let me see if I can figure out how to obtain the command line.

**Comment by BongoEADGC6** [comment]
@nvasudevan @carlpett 
I've added a pull request here that adds the service name as a label for the process collector. Matches the pid to the Service if it exists and adds it as a label.
