### ISSUE TITLE
wmi_thermalzone_temperature_celsius get -273.15

### ISSUE THREAD

**Issue by CasparChou** [prometheus-community/windows_exporter#495]
![image](https://user-images.githubusercontent.com/10682620/78058838-78252400-73bb-11ea-90e8-e51729ec85a0.png)

issue as title

[V] Powershell check
    powershell > Get-WMIObject Win32_PerfRawData_Counters_ThermalZoneInformation
    (return Temperature: 301)

[V] reinstall service
[V] restart service
[V] Administrator permission

**Comment by carlpett** [comment]
Hey @CasparChou,
The field we use is `HighPrecisionTemperature`, rather than `Temperature`. Do you get a value there?
In general, the thermalzone collector is dependent on good drivers to report correctly, so absent that there will be issues (although we might want to thinking about if we should just return an error if this field is not initialized, rather than reporting a very cold temperature...)

**Comment by CasparChou** [comment]
it seems no field named `HighPrecisionTemperature`, so it might be sensor not support or driver issues..

**Comment by carlpett** [comment]
Yes, if you don't get that field, it is not supported by the hardware/driver. We should fail instead of reporting -273.15, though.

**Comment by zhongxinlei** [comment]
Hey @carlpett , about the windows_thermalzone_temperature_celsius metrics, in description it says "Temperature of the thermal zone, in degrees Celsius.", could I understand the thermal zone is cpu or ti's something else? and I also could only get value of -237.15, may I ask what specific hardware/driver do I need to have it report right?

**Comment by carlpett** [comment]
Your hardware may support many thermal zones, which may or may not include the CPU. I've seen systems with temperature readings from memory and hard drives, for example.
It is very hard to give recommendations on what may be missing when the temperature is not reported, it depends on so very many factors. I would advice you to contact your hardware manufacturer.
