### ISSUE TITLE
Anyway to dump the metrics database out for analysis

### ISSUE THREAD

**Issue by YangLu1031** [prometheus-community/windows_exporter#502]
I guess all the metrics may be stored in local database, so just wondering if we could dump all the metrics database out and make complex query for analysis later?

**Comment by YangLu1031** [comment]
cc @pjh

**Comment by carlpett** [comment]
Hi @YangLu1031,
The exporter doesn't store anything in itself, it merely exposes the current values so that Prometheus can fetch them. Prometheus should be the query and analysis tool you need?
