### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by Daly123456** [prometheus-community/windows_exporter#505]
i'am monitoring my windows 10 VM i got a context deadline exceeded even after increasing my scrape timeout , evaluation interval and scrape interval ?? 
i just increased  time from 15s to 5m and i got the same error ! 
when i set time > then 5m i got service unavailable !!!
Some help please !

**Comment by carlpett** [comment]
Hi @Daly123456,
This isn't much to go on, I'm afraid. What version of the exporter are you using? What collectors are enabled? Are there any logs?

**Comment by Daly123456** [comment]
WMI V 0.11.1  and no logs

**Comment by carlpett** [comment]
Ok, and what collectors are enabled? Did you try disabling different combination in order to see if there is a particular one which is locking up?

**Comment by Daly123456** [comment]
How can i access to all collectors ! ?

Le lun. 20 avr. 2020 à 09:26, Calle Pettersson <notifications@github.com> a
écrit :

**Comment by carlpett** [comment]
I'm not sure I understand what you mean? You control the enabled collectors with the `--collectors.enabled` flag. See the [examples section](https://github.com/martinlindhe/wmi_exporter#examples) of the readme, or start the exporter with `--help` for some more details.

**Comment by Daly123456** [comment]
i thought mybe i got that error because i have to many metrics to collect !
so whynot reducing the number of metrics ?
Shall i set ''.\wmi_exporter.exe --collectors.enabled "process" " on my
windows powershell ?

Le lun. 20 avr. 2020 à 10:44, Calle Pettersson <notifications@github.com> a
écrit :

**Comment by carlpett** [comment]
Yes, and please try some combinations to see if you can identify which collector leads to the problem, or if it happens for all of them.

**Comment by Daly123456** [comment]
I got problem after installing WMI exporter i couldn't find it as a service
on my services list !

Le lun. 20 avr. 2020 à 15:31, Calle Pettersson <notifications@github.com> a
écrit :

**Comment by Daly123456** [comment]
[image: image.png]
this is problem i got while running it

**Comment by carlpett** [comment]
@Daly123456 the image does not show.
Also, this issue is getting a bit fragmented. Could you explain clearly what you've done, what works, and what does not?

**Comment by Daly123456** [comment]
I downloaded wmi exporter on my windows server ! I did that command to
install it as a service but i doesn't worked for me i even followed your
steps and while oppenning "services" i could'nt find WMI as a service

Le mer. 22 avr. 2020 à 08:27, Calle Pettersson <notifications@github.com> a
écrit :

**Comment by carlpett** [comment]
I'm sorry, but this is not very clear. 
Please state which file you downloaded, exactly what commands you've run and what you expected to happen at that point. Copy and paste any error messages.
Is the initial report of timeouts still valid, or is your issue actually in getting the exporter installed?

**Comment by Daly123456** [comment]
Hi i donwloaded ''wmi_exporter-0.11.0-amd64" on my windows server Active
directory
[image: image.png]

Le mer. 22 avr. 2020 à 22:16, Calle Pettersson <notifications@github.com> a
écrit :

**Comment by Daly123456** [comment]
[image: image.png]

**Comment by carlpett** [comment]
The images still don't work, could you please try using the Github interface instead of sending them via email?

**Comment by Mrlinux-yyds** [comment]
--collectors.enabled Do not open “textfile”
