### ISSUE TITLE
windows core compatibility issues

### ISSUE THREAD

**Issue by pathcl** [prometheus-community/windows_exporter#512]
Hello there!

First thank you for the exporter :) 

Im trying to get it up and running on Microsoft Windows Server 2016 (64-bit) core. But Im getting this meessage:

This version of wmi_exporter.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

I already checked about the OS architecture and its fine. Any suggestions will be appreciated.

**Comment by carlpett** [comment]
Hi @pathcl!
Interesting. And you are running the binary directly, not installing via the msi? I can't find exactly what pieces are not present on core, but here's a list of dll:s that appear to be loaded when I run the binary - could you see if any of them are missing on a core install?

```
C:\WINDOWS\System32\advapi32.dll
C:\WINDOWS\System32\bcrypt.dll
C:\WINDOWS\System32\bcryptPrimitives.dll
C:\WINDOWS\System32\cfgmgr32.dll
C:\WINDOWS\System32\clbcatq.dll
C:\WINDOWS\System32\combase.dll
C:\WINDOWS\SYSTEM32\CRYPTBASE.DLL
C:\WINDOWS\System32\GDI32.dll
C:\WINDOWS\System32\gdi32full.dll
C:\WINDOWS\System32\IMM32.DLL
C:\WINDOWS\System32\kernel.appcore.dll
C:\WINDOWS\System32\KERNEL32.DLL
C:\WINDOWS\System32\KERNELBASE.dll
C:\WINDOWS\System32\msvcp_win.dll
C:\WINDOWS\System32\msvcrt.dll
C:\WINDOWS\system32\mswsock.dll
C:\WINDOWS\SYSTEM32\ntdll.dll
C:\WINDOWS\System32\ole32.dll
C:\WINDOWS\System32\oleaut32.dll
C:\WINDOWS\System32\powrprof.dll
C:\WINDOWS\System32\RPCRT4.dll
C:\WINDOWS\System32\sechost.dll
C:\WINDOWS\System32\ucrtbase.dll
C:\WINDOWS\System32\UMPDC.dll
C:\WINDOWS\System32\USER32.dll
C:\WINDOWS\system32\uxtheme.dll
C:\WINDOWS\system32\wbem\wbemdisp.dll
C:\WINDOWS\system32\wbem\wbemprox.dll
C:\WINDOWS\SYSTEM32\wbemcomn.dll
C:\WINDOWS\System32\win32u.dll
C:\WINDOWS\SYSTEM32\winmm.dll
C:\WINDOWS\SYSTEM32\WINMMBASE.dll
C:\WINDOWS\System32\ws2_32.dll
```

**Comment by JDA88** [comment]
Hi,

Tested on a fresh Windows 2019 Core, this is the DLL missing
`C:\WINDOWS\System32\UMPDC.dll`
