### ISSUE TITLE
Allow to disable firewall configuration

### ISSUE THREAD

**Issue by thyn** [prometheus-community/windows_exporter#513]
Please add ability to skip firewall configuration. Every time after installation I'm deleting that record. We have our own firewall rules.

Also it's not secure

**Comment by c5395348** [comment]
I have the same problem,  windows disable the firewall. The installer throw error "ExecFirewallExceptions Installing firewall exception2 windows_exporter"

**Comment by PauloFernandoPires** [comment]
> I have the same problem, windows disable the firewall. The installer throw error "ExecFirewallExceptions Installing firewall exception2 windows_exporter"

Same problem here.

**Comment by breed808** [comment]
I think there's an argument for removing the firewall entry, or at least making it a non-default option.
Most environments where the exporter is installed via MSI will have some capability to manage firewall rules (GPO, config management tool, etc).

@carlpett could the firewall exception be placed behind a `<? if ?>` guard in the wxs file?

**Comment by FLeven** [comment]
> Please add ability to skip firewall configuration. Every time after installation I'm deleting that record. We have our own firewall rules.

Same problem here.

**Comment by tradiuz** [comment]
Either setting the firewall to non-default or adding a simple way to disable it would go a long way.  Currently, I have to go in afterwards and delete the spurious rule, since it defaults to "All Networks", and really should be something like "Domain, Private" and/or "Local Subnet"/"Intranet"

**Comment by jkroepke** [comment]
@breed808 I would also flip the toggle. Users should explicit opt-in to have firewall rules.
