### ISSUE TITLE
Missing some key metrics in Hyper-V collector

### ISSUE THREAD

**Issue by theelog** [prometheus-community/windows_exporter#517]
In order to monitor VM memory and host storage I propose to add the following performance counters.

*Cluster CSV File System*
```
Path = "Cluster_CSV_File_System"
Counters = [
    "IO Read Bytes/sec",
    "IO Read Latency",
    "IO Read Queue Lenght",
    "IO Reads/sec",
    "IO Write Bytes/sec",
    "IO Write Latency",
    "IO Write Queue Lenght",
    "IO Writes/sec"
]
```

*Hyper-V Dynamic Memory VM*
```
Path = "Hyper-V_Dynamic_Memory_VM"
Counters = [
    "Average Pressure",
    "Current Pressure",
    "Maximum Pressure",
    "Guest Visible Physical Memory"
]
```

Also a major one which I previously thought could only be queried via Powershell:
*Hyper-V Cluster Shared Volume (Cluster Disk Partition)*
```
NameSpace = root\MSCluster
Class == MSCluster_ClusterDiskPartition
Metrics = [
    "FreeSpace"
    "TotalSize"
]
Labels = [
    "MountPoints"
]
```

Documentation on this can be found here: https://docs.microsoft.com/en-us/previous-versions/windows/desktop/cluswmi/mscluster-clusterdiskpartition

**Comment by JDA88** [comment]
I agree with the previous request and I think followinf counter could be usefull to

```
Path = "Hyper-V_Dynamic_Memory_Balancer"
Counters = [
    "Available Memory",
    "Available Memory For Balancing",
    "Average Pressure"
]
```

**Comment by basroovers** [comment]
We should also add this metric, which is the equivalent of CPU Ready metric in VMware:
```
Hyper-V Hypervisor Virtual Processor\CPU Wait Time Per Dispatch
```
