### ISSUE TITLE
Adding hostname in service collector

### ISSUE THREAD

**Issue by veenone** [prometheus-community/windows_exporter#518]
Hi,

Is it possible to add a hostname label from the node on service collectors? 

So for example  metric wmi_service_status, will have the hostname of the node. I think this could be useful for aggregation process.

**Comment by carlpett** [comment]
Hi @veenone,
That would typically be handled via relabelling in your Prometheus server. I assume you currently get an `instance` label which is an IP address?

**Comment by veenone** [comment]
Hi @carlpett,

I was thinking to get the hostname information from cs collector wmi_cs_hostname.

I don't know what is the best way to include this information on each wmi_service_status metrics.

I think it's not really common, but if you can help me informing a way to do that, it would be great. 

What I want to achieve actually to display specifi service state for each scraped nodes in grafana to monitor them altogether.

I'm quite a learner here so pardon my basic question

**Comment by carlpett** [comment]
You'll probably want to look at [`relabel_config`](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) at some point, but it might not be the easiest way to solve your immediate problem.
If you just want to have the hostname available on a dashboard, you can join labels at query time using multiplication. Something like this:
```
wmi_service_status
 * on (instance) group_left(hostname)
wmi_cs_hostname
```
