### ISSUE TITLE
Collector generator panics because of BOM

### ISSUE THREAD

**Issue by theelog** [prometheus-community/windows_exporter#522]
I was trying to generate a collector but didn't get very far. Right after running it I run into the following message:

```
.\New-Collector.ps1 -Class Win32_PerfRawData_PerfOS_Processor
panic: invalid character 'ï' looking for beginning of value

goroutine 1 [running]:
main.main()
        C:/basroovers/wmi_exporter/tools/collector-generator/generate-collector.go:29 +0x4bd
can't load package: package main:
..\..\collector\os_processor.go:1:1: expected 'package', found 'EOF'
```

Some research let's me to believe it is bumping into a BOM character which trips a panic.

I'm running on Windows 10 1909 with GoLang 1.14.3.

**Comment by basroovers** [comment]
I just ran it from the new Windows Terminal 1.0 with Powershell 7.0.1 with a small fix because it is missing the Get-WMIObject (replaced it with Get-CimInstance).

This ran perfectly fine.

**Comment by carlpett** [comment]
Can we close this after your fix @basroovers?

**Comment by basroovers** [comment]
Since it’s not working anymore for Powershell 5 we might need to look into a solution for that.
