### ISSUE TITLE
Error 0x800706d9 while installing wmi_exporter from docker file

### ISSUE THREAD

**Issue by sikasam** [prometheus-community/windows_exporter#524]
i am trying to install wmi_exporter from the docker file using below command. 
**Command Used:**
```
RUN powershell -Command `
    $ErrorActionPreference = 'Stop'; `
    msiexec /i "c:\tools\wmi_exporter.msi" ENABLED_COLLECTORS=os,memory,netframework_clrexceptions,netframework_clrinterop,netframework_clrjit,netframework_clrloading,netframework_clrlocksandthreads,netframework_clrmemory,netframework_clrremoting,netframework_clrsecurity,process,tcp,system,service,logical_disk,cpu,cs,net LISTEN_PORT=50505
```
 **Log Snippet:**
MSI (s) (BC:F4) [13:50:29:720]: Executing op: FileCopy(SourceName=blenxdzx.exe|wmi_exporter.exe,SourceCabKey=wmi_exporter.exe,DestName=wmi_exporter.exe,Attributes=512,FileSize=18258320,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,,,InstallMode=58982400,HashOptions=0,HashPart1=903693586,HashPart2=1905883247,HashPart3=411733759,HashPart4=108971866,,)
MSI (s) (BC:F4) [13:50:29:720]: File: c:\Program Files\wmi_exporter\wmi_exporter.exe;	To be installed;	Won't patch;	No existing file
MSI (s) (BC:F4) [13:50:29:720]: Source for file 'wmi_exporter.exe' is compressed
MSI (s) (BC:F4) [13:50:29:923]: Executing op: CacheSizeFlush(,)
MSI (s) (BC:F4) [13:50:29:923]: Executing op: ActionStart(Name=WixRollbackFirewallExceptionsInstall,Description=Rolling back Windows Firewall configuration,)
MSI (s) (BC:F4) [13:50:29:923]: Executing op: CustomActionSchedule(Action=WixRollbackFirewallExceptionsInstall,ActionType=3329,Source=BinaryData,Target=ExecFirewallExceptions,CustomActionData=1WMI Exporter (HTTP 50505)2147483647*12c:\Program Files\wmi_exporter\wmi_exporter.exe505056WMI Exporter HTTP endpoint)
MSI (s) (BC:F4) [13:50:29:923]: Executing op: ActionStart(Name=WixExecFirewallExceptionsInstall,Description=Installing Windows Firewall configuration,)
MSI (s) (BC:F4) [13:50:29:923]: Executing op: CustomActionSchedule(Action=WixExecFirewallExceptionsInstall,ActionType=3073,Source=BinaryData,Target=ExecFirewallExceptions,CustomActionData=1WMI Exporter (HTTP 50505)2147483647*12c:\Program Files\wmi_exporter\wmi_exporter.exe505056WMI Exporter HTTP endpoint)
MSI (s) (BC:04) [13:50:29:923]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI2000.tmp, Entrypoint: ExecFirewallExceptions
MSI (s) (BC:FC) [13:50:29:923]: Generating random cookie.
MSI (s) (BC:FC) [13:50:29:923]: Created Custom Action Server with PID 1496 (0x5D8).
MSI (s) (BC:08) [13:50:29:954]: Running as a service.
MSI (s) (BC:EC) [13:50:29:970]: Hello, I'm your 32bit Elevated Non-remapped custom action server.
ExecFirewallExceptions:  Installing firewall exception2 WMI Exporter (HTTP 50505) (c:\Program Files\wmi_exporter\wmi_exporter.exe)
MSI (s) (BC:F4) [13:50:30:001]: Executing op: ActionStart(Name=InstallServices,Description=Installing new services,Template=Service: [2])
ExecFirewallExceptions:  Error 0x800706d9: failed trying to find existing app
MSI (s) (BC:F4) [13:50:30:001]: Executing op: ProgressTotal(Total=1,Type=1,ByteEquivalent=1300000)
MSI (s) (BC:F4) [13:50:30:001]: Executing op: ServiceInstall(Name=wmi_exporter,DisplayName=WMI exporter,ImagePath="c:\Program Files\wmi_exporter\wmi_exporter.exe" --log.format logger:eventlog?name=wmi_exporter --collectors.enabled os,memory,netframework_clrexceptions,netframework_clrinterop,netframework_clrjit,netframework_clrloading,netframework_clrlocksandthreads,netframework_clrmemory,netframework_clrremoting,netframework_clrsecurity,process,tcp,system,service,logical_disk,cpu,cs,net --telemetry.addr :50505  ,ServiceType=16,StartType=2,ErrorControl=1,,Dependencies=[~],,,Password=**********,Description=Exports Prometheus metrics from WMI queries,,)
MSI (s) (BC:F4) [13:50:30:001]: Executing op: ActionStart(Name=RollbackServiceConfig,,)
MSI (s) (BC:F4) [13:50:30:001]: Executing op: CustomActionSchedule(Action=RollbackServiceConfig,ActionType=3329,Source=BinaryData,Target=RollbackServiceConfig,CustomActionData=SchedServiceConfig)
MSI (s) (BC:F4) [13:50:30:017]: Executing op: ActionStart(Name=ExecServiceConfig,,)
MSI (s) (BC:F4) [13:50:30:017]: Executing op: CustomActionSchedule(Action=ExecServiceConfig,ActionType=3073,Source=BinaryData,Target=ExecServiceConfig,CustomActionData=SchedServiceConfigwmi_exporter1restartrestartrestart05)
MSI (s) (BC:38) [13:50:30:017]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI205F.tmp, Entrypoint: ExecServiceConfig
MSI (s) (BC:F4) [13:50:30:017]: Executing op: ActionStart(Name=StartServices,Description=Starting services,Template=Service: [1])
MSI (s) (BC:F4) [13:50:30:017]: Executing op: ProgressTotal(Total=1,Type=1,ByteEquivalent=1300000)
MSI (s) (BC:F4) [13:50:30:017]: Executing op: ServiceControl(,Name=wmi_exporter,Action=1,,)
MSI (s) (BC:F4) [13:51:00:301]: Product: WMI Exporter -- Error 1920. Service 'WMI exporter' (wmi_exporter) failed to start.  Verify that you have sufficient privileges to start system services.

Error 1920. Service 'WMI exporter' (wmi_exporter) failed to start.  Verify that you have sufficient privileges to start system services.
MSI (s) (BC:F4) [13:51:00:301]: Note: 1: 2265 2:  3: -2147287035 
MSI (s) (BC:F4) [13:51:00:317]: User policy value 'DisableRollback' is 0
MSI (s) (BC:F4) [13:51:00:317]: Machine policy value 'DisableRollback' is 0
Action ended 13:51:00: InstallExecute. Return value 3.
MSI (s) (BC:F4) [13:51:00:317]: Note: 1: 2318 2:  
MSI (s) (BC:F4) [13:51:00:317]: Executing op: Header(Signature=1397708873,Version=500,Timestamp=1353870927,LangId=1033,Platform=589824,ScriptType=2,ScriptMajorVersion=21,ScriptMinorVersion=4,ScriptAttributes=1)
MSI (s) (BC:F4) [13:51:00:317]: Executing op: DialogInfo(Type=0,Argument=1033)
MSI (s) (BC:F4) [13:51:00:317]: Executing op: DialogInfo(Type=1,Argument=WMI Exporter)
MSI (s) (BC:F4) [13:51:00:317]: Executing op: RollbackInfo(,RollbackAction=Rollback,RollbackDescription=Rolling back action:,RollbackTemplate=[1],CleanupAction=RollbackCleanup,CleanupDescription=Removing backup files,CleanupTemplate=File: [1])
MSI (s) (BC:F4) [13:51:00:317]: Executing op: ActionStart(Name=StartServices,Description=Starting services,Template=Service: [1])
MSI (s) (BC:F4) [13:51:00:317]: Executing op: ProductInfo(ProductKey={29B58657-70D1-49AF-BE39-EBEE99216903},ProductName=WMI Exporter,PackageName=wmi_exporter.msi,Language=1033,Version=327680,Assignment=1,ObsoleteArg=0,,,PackageCode={708EE6CE-3755-4CB2-BD2C-FC3D2CBD40A8},,,InstanceType=0,LUASetting=0,RemoteURTInstalls=0,ProductDeploymentFlags=3)
MSI (s) (BC:F4) [13:51:00:317]: Executing op: ActionStart(Name=ExecServiceConfig,,)
MSI (s) (BC:F4) [13:51:00:317]: Executing op: ActionStart(Name=RollbackServiceConfig,,)
MSI (s) (BC:F4) [13:51:00:317]: Executing op: CustomActionRollback(Action=RollbackServiceConfig,ActionType=3329,Source=BinaryData,Target=RollbackServiceConfig,CustomActionData=SchedServiceConfig)
MSI (s) (BC:D4) [13:51:00:335]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI96B9.tmp, Entrypoint: RollbackServiceConfig
MSI (s) (BC:F4) [13:51:00:353]: Executing op: ActionStart(Name=InstallServices,Description=Installing new services,Template=Service: [2])
MSI (s) (BC:F4) [13:51:00:353]: Executing op: ServiceControl(,Name=wmi_exporter,Action=8,,)
MSI (s) (BC:F4) [13:51:00:353]: Executing op: ActionStart(Name=WixExecFirewallExceptionsInstall,Description=Installing Windows Firewall configuration,)
MSI (s) (BC:F4) [13:51:00:353]: Executing op: ActionStart(Name=WixRollbackFirewallExceptionsInstall,Description=Rolling back Windows Firewall configuration,)
MSI (s) (BC:F4) [13:51:00:353]: Executing op: CustomActionRollback(Action=WixRollbackFirewallExceptionsInstall,ActionType=3329,Source=BinaryData,Target=ExecFirewallExceptions,CustomActionData=1WMI Exporter (HTTP 50505)2147483647*12c:\Program Files\wmi_exporter\wmi_exporter.exe505056WMI Exporter HTTP endpoint)
MSI (s) (BC:38) [13:51:00:360]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI96D9.tmp, Entrypoint: ExecFirewallExceptions
ExecFirewallExceptions:  Uninstalling firewall exception2 WMI Exporter (HTTP 50505) (c:\Program Files\wmi_exporter\wmi_exporter.exe)
ExecFirewallExceptions:  Error 0x800706d9: failed to remove authorized app
MSI (s) (BC:F4) [13:51:00:362]: Executing op: ActionStart(Name=InstallFiles,Description=Copying new files,Template=File: [1],  Directory: [9],  Size: [6])
MSI (s) (BC:F4) [13:51:00:362]: Executing op: SetTargetFolder(Folder=c:\Program Files\wmi_exporter\)
MSI (s) (BC:F4) [13:51:00:362]: Executing op: FileRemove(,FileName=c:\Program Files\wmi_exporter\wmi_exporter.exe,,)
MSI (s) (BC:F4) [13:51:00:380]: Executing op: ActionStart(Name=CreateFolders,Description=Creating folders,Template=Folder: [1])
MSI (s) (BC:F4) [13:51:00:380]: Executing op: FolderRemove(Folder=c:\Program Files\wmi_exporter\textfile_inputs\,Foreign=0)
MSI (s) (BC:F4) [13:51:00:380]: Note: 1: 2318 2:  
MSI (s) (BC:F4) [13:51:00:380]: Note: 1: 2318 2:  
MSI (s) (BC:F4) [13:51:00:380]: Executing op: ActionStart(Name=StopServices,Description=Stopping services,Template=Service: [1])
MSI (s) (BC:F4) [13:51:00:380]: Executing op: ActionStart(Name=ProcessComponents,Description=Updating component registration,)
MSI (s) (BC:F4) [13:51:00:380]: Executing op: ComponentUnregister(ComponentId={D03EF58A-9CBF-4165-AD39-D143E9B27E14},ProductKey={29B58657-70D1-49AF-BE39-EBEE99216903},BinaryType=1,)
MSI (s) (BC:F4) [13:51:00:380]: Executing op: ComponentUnregister(ComponentId={2FE201A9-D958-521C-AD6A-4CB78D4F222E},ProductKey={29B58657-70D1-49AF-BE39-EBEE99216903},BinaryType=1,)
MSI (s) (BC:F4) [13:51:00:380]: Executing op: End(Checksum=0,ProgressTotalHDWord=0,ProgressTotalLDWord=0)
MSI (s) (BC:F4) [13:51:00:380]: Error in rollback skipped.	Return: 5
MSI (s) (BC:F4) [13:51:00:395]: Note: 1: 2318 2:  
MSI (s) (BC:F4) [13:51:00:395]: No System Restore sequence number for this installation.
MSI (s) (BC:F4) [13:51:00:395]: Unlocking Server
MSI (s) (BC:F4) [13:51:00:401]: PROPERTY CHANGE: Deleting UpdateStarted property. Its current value is '1'.
Action ended 13:51:00: INSTALL. Return value 3.
Property(S): UpgradeCode = {66A6EB5B-1FC2-4B14-A362-5CEEC6413308}
Property(S): WixRollbackFirewallExceptionsInstall = 1WMI Exporter (HTTP 50505)2147483647*12c:\Program Files\wmi_exporter\wmi_exporter.exe505056WMI Exporter HTTP endpoint
Property(S): WixExecFirewallExceptionsInstall = 1WMI Exporter (HTTP 50505)2147483647*12c:\Program Files\wmi_exporter\wmi_exporter.exe505056WMI Exporter HTTP endpoint
........
MSI (s) (BC:F4) [13:51:00:438]: Note: 1: 1708 
MSI (s) (BC:F4) [13:51:00:438]: Product: WMI Exporter -- Installation failed.

MSI (s) (BC:F4) [13:51:00:438]: Windows Installer installed the product. Product Name: WMI Exporter. Product Version: 0.5.0. Product Language: 1033. Manufacturer: Martin Lindhe. Installation success or error status: 1603.

**Comment by carlpett** [comment]
Hi @sikasam,
I am not certain, but I do not believe the Windows Installer is supported within containers, unfortunately. I would recommend trying to add the executable instead.

**Comment by sikasam** [comment]
Hi @carlpett,
I can try this but the error looks like it is fiddling with firewall when it is trying to install wmi_exporter.exe only. So i am just guessing that it would not make any difference if i install the msi or exe.

**Comment by carlpett** [comment]
The .exe doesn't do any installation steps at all, it is just the exporter binary. So it will not try to touch any firewall settings etc.
