### ISSUE TITLE
DHCP Collector error

### ISSUE THREAD

**Issue by Pamalosebi** [prometheus-community/windows_exporter#531]
Hey, I wanted to check out the latest version of Windows_exporter (WMI_exporter) 0.12.0 on a Windows Server 2012 R2 with the new dhcp collector enabled. Unfortunately it throws the following message:

```
An error has occurred while serving metrics:

collected metric wmi_dhcp_denied_due_to_match_total counter:<value:0 >  has help "Total number of DHCP requests denied, based on non-matches from the Allow list (DeniedDueToNonMatch)" but should have "Total number of DHCP requests denied, based on matches from the Deny list (DeniedDueToMatch)"
```

Any tips how to resolve this?

**Comment by carlpett** [comment]
Hey @Pamalosebi,
Thanks for reporting! That looks like a bug.
@breed808 do you have time to take a look?

**Comment by breed808** [comment]
Sure, I'll have a look at this in the next couple days. I'll see if I can reproduce it on our DHCP servers (Windows Server 2016).

**Comment by BongoEADGC6** [comment]
Good morning, @carlpett 

This is still an issue on Server 2012 on v0.13

An error has occurred while serving metrics:

collected metric windows_dhcp_denied_due_to_match_total counter:<value:0 >  has help "Total number of DHCP requests denied, based on non-matches from the Allow list (DeniedDueToNonMatch)" but should have "Total number of DHCP requests denied, based on matches from the Deny list (DeniedDueToMatch)"
