### ISSUE TITLE
no temperature metrics exposed from wmi_exporter when enabled thermalzone in Windows Server 2016

### ISSUE THREAD

**Issue by godocean** [prometheus-community/windows_exporter#539]
I downloaded wmi_exporter-0.9.0-amd64.exe in my server which is Windows Server 2016, and started it as below:
./wmi_exporter-0.9.0-amd64.exe --collectors.enabled "thermalzone"
when I request from http://localhost:9182/metrics, it didn't return any temperature metrics.

And then I open powershell with administrator privilege in this server, and run command as below:
![image](https://user-images.githubusercontent.com/17870432/83869994-0ae99280-a760-11ea-81dd-b987a6f936d9.png)

So my question is if "thermalzone" is supported in Windows Server 2016? or should I do some work to open the feature gate in Server 2016? can anyone give some feedback? Thanks ahead.

**Comment by carlpett** [comment]
Hi @godocean,
First off, I'd suggest running the latest version (0.13) rather than 0.9. Regarding the thermalzone collector, is is dependent on both compatible hardware and drivers being installed. As long as that is in place, the metrics will work.

**Comment by godocean** [comment]
> Hi @godocean,
> First off, I'd suggest running the latest version (0.13) rather than 0.9. Regarding the thermalzone collector, is is dependent on both compatible hardware and drivers being installed. As long as that is in place, the metrics will work.

**Comment by godocean** [comment]
@carlpett 
Thanks for your reply!

I've followed your advice and tried latest version(0.13) in Windows Server 2016, but it returned the same result without any temperature metrics,

You mentioned that for thermalzone collector, "it is dependent on both compatible hardware and drivers being installed", what kind of compatible hardware and drivers should be installed? Could you give me more details about it? 

Because I've tried this windows exporter in my PC whose OS is Windows 10 Enterprise, and it worked out temperature metrics. So I'm little confused about it, maybe there should be some feature gate is open by default in Windows 10 Enterprise but not in Windows Server 2016, I'm looking forward to your kindly guidance. Thanks ahead!

**Comment by carlpett** [comment]
Hi,
>You mentioned that for thermalzone collector, "it is dependent on both compatible hardware and drivers being installed", what kind of compatible hardware and drivers should be installed? Could you give me more details about it?

The temperature needs to be measured by the hardware, and there needs to be drivers installed to interpret it. This will be very dependent on your system setup. And, just to be very clear, if the server is a virtual machine, there are no temperature metrics (this is the most common case where it doesn't work).

>Because I've tried this windows exporter in my PC whose OS is Windows 10 Enterprise, and it worked out temperature metrics. So I'm little confused about it, maybe there should be some feature gate is open by default in Windows 10 Enterprise but not in Windows Server 2016

There's no difference in this regard between Windows 10 and Server 2016. Did you try this on the same hardware?

**Comment by godocean** [comment]
Hi, @carlpett 
> The temperature needs to be measured by the hardware, and there needs to be drivers installed to interpret it. This will be very dependent on your system setup. And, just to be very clear, if the server is a virtual machine, there are no temperature metrics (this is the most common case where it doesn't work).
>
Which driver need to be installed to interpret it? could you provide more information?
BTW, my server is a physical machine, not a virtual machine.

> There's no difference in this regard between Windows 10 and Server 2016. Did you try this on the same hardware?
>
Windows 10 is my PC, and Server 2016 is my physical server.

**Comment by carlpett** [comment]
I'm afraid I cannot help you there, it all depends on your hardware. So I'd suggest checking with your motherboard supplier.

**Comment by godocean** [comment]
@carlpett Thanks for your help, 
I've written a tool with openhardwaremonitor to get its CPU temperature, so I'll close this issue.

**Comment by sharkoz** [comment]
> @carlpett Thanks for your help, I've written a tool with openhardwaremonitor to get its CPU temperature, so I'll close this issue.

Hello @godocean , I am interested in doing the same thing, and using openhardwaremonitor looks primising. Can you share what you did to make it work ?

**Comment by sharkoz** [comment]
Never mind, I found a way with https://github.com/nickbabcock/OhmGraphite
