### ISSUE TITLE
Question about monitoring gaming metrics.

### ISSUE THREAD

**Issue by BeastlyPixels** [prometheus-community/windows_exporter#541]
Hello, I was wondering if there were any wmi calls for realtime FPS, frametimes, FPS min/max, latency, etc? I would like to have a full set of metrics that are logged and use Ansible to change settings based on parameters to improve said metrics. I appreciate your input.

**Comment by avonwyss** [comment]
I don't think there are WMI calls or standard performance counters for these, but you may want to look into https://github.com/GameTechDev/PresentMon which does produce some of the wanted metrics.

**Comment by BeastlyPixels** [comment]
@avonwyss This looks perfect, thank you!
