### ISSUE TITLE
Service failed to start - 32bit Install 

### ISSUE THREAD

**Issue by babunatarajan** [prometheus-community/windows_exporter#544]
**Overview**
windows_exporter service failed to start

Error reading textfile collector directory "C:\\Program Files\\windows_exporter\\textfile_inputs": open C:\Program Files\windows_exporter\textfile_inputs: The system cannot find the path specified.

**Expected Behavior**
When rebooting the server, the service failed to start.
Event viewer error: "Error reading textfile collector directory "C:\\Program Files\\windows_exporter\\textfile_inputs": open C:\Program Files\windows_exporter\textfile_inputs: The system cannot find the path specified."

**Workaround**
The build is installed in the 32bit path [C:\Program Files (x86)\windows_exporter\] and its looking for textfile_inputs directory under 64bit path ["C:\Program Files\windows_exporter\textfile_inputs"]
Create the textfile_inputs directory under the 64bit path
["C:\Program Files\windows_exporter\textfile_inputs"]

**Environment**
OS Product: Windows 2016 Datacenter (64bit)
OS Version: 10.0.14393
**windows_exporter version: windows_exporter-0.13.0-386.msi. (32bit)**

**Comment by carlpett** [comment]
Hi @babunatarajan,
That error will not prevent the exporter from starting, so there must be some other error too?
Regarding 32 bit vs 64 bit installations, I would really recommend using the 64-bit version on a 64-bit OS. Is there a reason that you are not doing so?

**Comment by babunatarajan** [comment]
I used 64bit build (windows_exporter-0.13.0-amd64.exe) to install the product, not sure why its created the program directory under the 32bit path.
I didn't have issues when installing the product, it occurs when rebooting the server.

**Comment by babunatarajan** [comment]
I do have one more Warning error "No where-clause specified for service collector. This will generate a very large number of metrics!"

**Comment by carlpett** [comment]
>I used 64bit build (windows_exporter-0.13.0-amd64.exe) to install the product, not sure why its created the program directory under the 32bit path.

Hm, the .exe will not do any installation at all, did you mean the .msi? Or did you do some manual installation?

>I do have one more Warning error "No where-clause specified for service collector. This will generate a very large number of metrics!"

Both these warnings will only be logged when the service has successfully started, so I'm confused about the "failed to start". I would suspect there is something deeper going on.
Can you try starting it from the commandline instead so logs are written directly to terminal, and we can see if it even crashes?

**Comment by babunatarajan** [comment]
My bad, I used the 32bit installer, not the 64bit to install the product.
I've updated the issue.
Thanks Carl.

**Comment by carlpett** [comment]
Right, but is there a reason to not use the 64-bit installer, since it is a 64-bit system?
And again, none of the errors mentioned so far prevent the exporter from starting, so please try launching it from the commandline so we can get all the logs.

**Comment by babunatarajan** [comment]
No it was a mistake that my team have installed the 32bit setup. If someone have this use case to install the 32bit product in 64bit OS they should be aware that service wont start when rebooting the server and it requires 64bit folder structure.

**Comment by carlpett** [comment]
As I mentioned, the errors you've posted so far will **not** prevent the exporter from starting (in fact, they require that it has both started and received a scrape request from Prometheus), so there must be something else going on.
