### ISSUE TITLE
Windows Metrics for Grafana Dashboard

### ISSUE THREAD

**Issue by Zayan1221** [prometheus-community/windows_exporter#545]
Hello,
Can I have scripts for these Metrics  Windows client.
§ CPU utilization                                                       
§ File System utilization                   
§ System messages (ex. Errors in /var/log/messages)         Any critical errors reported in logs
§ Disk INODE utilization                   
§ System process monitoring (ex. Set of services on a server if they are running or not) Alarm if services are not running.

For Memory I got this executed fine :
100 * (windows_os_physical_memory_free_bytes{instance=~"$instance"}) / windows_cs_physical_memory_bytes{instance=~"$instance"}

**Comment by carlpett** [comment]
Hi @Zayan1221,
The issue tracker is mainly intended for bug reports and discussions on new features. Please see the documentation for [the exporter](https://github.com/prometheus-community/windows_exporter/tree/master/docs) and [Prometheus](https://prometheus.io/docs/prometheus/latest/querying/basics/) to get started. If you have additional usage questions, I'd suggest using the resources listed under [Prometheus Community](https://prometheus.io/community/), such as the users-mailing list.
