### ISSUE TITLE
new install windows_exporter, normal jumping to 11% cpu load

### ISSUE THREAD

**Issue by f1-outsourcing** [prometheus-community/windows_exporter#549]
I am new with the use of windows_exporter. Is it normal it constantly jumps to 11% cpu use? Is that not a bit to much for exporting some metrics?

**Comment by carlpett** [comment]
Hi @f1-outsourcing,
That sounds excessive, but is lacking a lot of information. Eg how often does it consume 11% cpu when you say "constantly jumps"? How do you measure this, using the exposed metrics?
What collectors do you have enabled? Check the `windows_exporter_collector_duration_seconds` metric to see if any of them are taking a long time.

**Comment by f1-outsourcing** [comment]
It looks like it jumps to 11% every time prometheus scrapes, 8s-10s. I am seeing this in the task manager running on the windows vm, sorting on cpu%
I have a default setup, so I guess have those collectors enabled.
I don't know if these values are high or normal.

```
windows_exporter_collector_duration_seconds{collector="cpu", instance="ad2.local:9182", job="windows"}
	0
windows_exporter_collector_duration_seconds{collector="cs", instance="ad2.local:9182", job="windows"}
	0.5214729
windows_exporter_collector_duration_seconds{collector="logical_disk", instance="ad2.local:9182", job="windows"}
	0
windows_exporter_collector_duration_seconds{collector="net", instance="ad2.local:9182", job="windows"}
	0.0009732
windows_exporter_collector_duration_seconds{collector="os", instance="ad2.local:9182", job="windows"}
	0.0468775
windows_exporter_collector_duration_seconds{collector="service", instance="ad2.local:9182", job="windows"}
	0.5068291
windows_exporter_collector_duration_seconds{collector="system", instance="ad2.local:9182", job="windows"}
	0
windows_exporter_collector_duration_seconds{collector="textfile", instance="ad2.local:9182", job="windows"}
	0
```

**Comment by xmapst** [comment]
os build: `Microsoft Windows [Version 10.0.19041.928]`
windows_exporter version: `0.16.0`
Only one collector is open, and no containers are running. cpu utilization rate reached 33.5%
@carlpett Can you help me solve it
![3DF2254A-108F-4d40-B3F1-E846B5EA036B](https://user-images.githubusercontent.com/36829716/117628947-3fee3880-b1ac-11eb-8751-602ffd59f590.png)
![9E66667A-2272-4adc-B7CF-C738F3540F78](https://user-images.githubusercontent.com/36829716/117629026-54323580-b1ac-11eb-83bc-f062429e76da.png)

**Comment by xmapst** [comment]
> > os build: `Microsoft Windows [Version 10.0.19041.928]` windows_exporter version: `0.16.0` Only one collector is open, and no containers are running. cpu utilization rate reached 33.5% @carlpett Can you help me solve it ![3DF2254A-108F-4d40-B3F1-E846B5EA036B](https://user-images.githubusercontent.com/36829716/117628947-3fee3880-b1ac-11eb-8751-602ffd59f590.png) ![9E66667A-2272-4adc-B7CF-C738F3540F78](https://user-images.githubusercontent.com/36829716/117629026-54323580-b1ac-11eb-83bc-f062429e76da.png)
> 
> yes crazy, probably bad design / bad programming. I guess this is the standard for current times, even Microsoft produces lots of crap.

@f1-outsourcing You can try to use docker api to implement the container indicator collector yourself.
