### ISSUE TITLE
wmi_exporter  VS windows_exporter - BUG

### ISSUE THREAD

**Issue by Zayan1221** [prometheus-community/windows_exporter#550]
I have an issue with the Metrics in Grafana with windows_exporter.
100 - (avg (irate(windows_cpu_time_total{mode="idle"}[2m])) * 100) 
The output for this one showing CPU of One server as same to all other servers.
100 - (avg (irate(windows_cpu_time_total{instance=~"$instance",mode="idle"}[2m])) * 100)
shows No data error in windows_exporter where as in wmi_exporter it works fine.

Same issue with Filesystem output
100.0 - 100 * ((windows_logical_disk_free_bytes {} / 1024 / 1024 ) / (windows_logical_disk_size_bytes {} / 1024 / 1024))
The output for this one showing Filesystem of One server as same to all other servers.
100.0 - 100 * ((windows_logical_disk_free_bytes {instance=~"$instance"} / 1024 / 1024 ) / (windows_logical_disk_size_bytes {instance=~"$instance"} / 1024 / 1024))
shows No data error in windows_exporter where as in wmi_exporter it works fine.

And for Memory it works fine with windows_exporter:
100 * (windows_os_physical_memory_free_bytes{instance=~"$instance"}) / windows_cs_physical_memory_bytes{instance=~"$instance"}

**Comment by carlpett** [comment]
Hi @Zayan1221,
This report isn't really clear to me, I'm afraid. 
>100 - (avg (irate(windows_cpu_time_total{mode="idle"}[2m])) * 100)
>showing CPU of One server as same to all other servers

Are you running this query, and changing the variable `$instance` does not change the output? That seems to be expected, in that case, since you are not actually including that label in the query, and it will aggregate across all instances.

If you get no data when including the instance label, I would suspect your variable are not correctly set up in Grafana.

**Comment by Zayan1221** [comment]
I have a variable for this Dashboard as:
instance | label_values(up, instance)
And this works for Memory but not for CPU and Filesystem.

**Comment by Zayan1221** [comment]
I have fixed the issue now:Someone helped me with this statement which I have followed and it is fixed now.

Basically all you need to do is to go into the prometheus console, look at your metrics like "windows_cpu_time_total" and the full set of labels, check they have an "instance" label, and check the Grafana dashboard variable is generating the correct value.

If it's working for Linux but not for Windows it may be because your dashboard variable is querying a metric which only exists for Linux instances.  Try making a dashboard variable like this:

Name: instance
Data source: prometheus
Query: label_values(windows_cpu_time_total, instance)

**Comment by carlpett** [comment]
`label_values(windows_cpu_time_total, instance)` should work for all `windows_*` metrics, under the assumption that you do not disable the cpu collector. 
`label_values(up, instance)` will _technically_ work, although you would of course then get `$instance` values which are not in fact windows_exporter instances, and will be confusing.
I'd suggest a middle ground of `label_values(up{job="windows_exporter"}, instance)` (checking first that your job label is indeed windows_exporter, of course), which will give you all the windows_exporter instances regardless of enabled collectors.

**Comment by Zayan1221** [comment]
How to get system messages for windows on Grafana with Prometheus data source
Does Windows has SystemD ?
Server Network Interface Up or Down     (Alarm if server doesn’t respond)

**Comment by Zayan1221** [comment]
Hello Calle- Appreciate your help - That works better and solved some issues.

How to get system messages for windows on Grafana with Prometheus data source
Does Windows has SystemD ?
Server Network Interface Up or Down (Alarm if server doesn’t respond)
Fislesystem/Disk Usage:This Syntax shows more Drives then the server exist also want to know which Drives(example A,B,C,D)
100.0 - 100 * ((windows_logical_disk_free_bytes {instance="$instance"} / 1024 / 1024 ) / (windows_logical_disk_size_bytes {instance="$instance"} / 1024 / 1024))

**Comment by carlpett** [comment]
To answer some of your questions, Windows does not use Systemd, and Prometheus is fundamentally not a event logging tool, so this is not something we'll handle in this exporter. 

But as I mentioned in the other issue you opened, the issue tracker is not the right place for these "how to"-questions. Please use the prometheus-users mailing list or one of the chat groups instead.
