### ISSUE TITLE
Add /version endpoint

### ISSUE THREAD

**Issue by zlepper** [prometheus-community/windows_exporter#553]
We are working on some automatic scripts for installing and upgrading our servers. For that we need some way of checking the version of the running service, so we know if we need to upgrade it or not. 

Prometheus itself has a /version endpoint that just returns a json object, with amongst other, the version of Prometheus. 

If this has any interest, i'll be happy to PR it myself :)

**Comment by carlpett** [comment]
Hey @zlepper,
Sounds like a reasonable thing, a PR would be much appreciated! :slightly_smiling_face:
