### ISSUE TITLE
MSSQL Database Data File Size Incorrect

### ISSUE THREAD

**Issue by bpickhardt** [prometheus-community/windows_exporter#557]
I have been using the WMI_Exporter, now Windows_Exporter, for a few years now and this morning I noticed something odd with my database sizes in Grafana.  There is one of our databases that has grown too large for the reporting to correctly report the value.  According to the metric wmi_mssql_databases_data_files_size_bytes collected by Prometheus the database size dropped from 4470184148992 to 72137637888 suddenly in May.  That is not true though because I looked up the size of the data file for that database in SQL and the result comes back correct with 4525753761792.  I suspect some kind of overflow is occurring to truncate my file size because it is over 4096GB.  the machine is running version 0.9.0 and I have not tried running a newer version yet but I reviewed the patch notes and noticed nothing that appears like it would fix this problem.  I'm not sure if the problem is in the Windows counters itself that are being read of WMI_Exporter either. It should be fairly easy to test though if you have a large enough drive.

System Info: SQL Server 2016 Enterprise running on Windows 2012 R2 with WMI_Exporter 0.9.0 reporting to Prometheus version 2.17.2.

**Comment by carlpett** [comment]
Hi @bpickhardt,
Could you check if `gwmi win32PerfRawDataSQLServerDatabases` gives the correct result? The collector code _looks_ like this should work correctly, given that the data we read is correct.

**Comment by bpickhardt** [comment]
I couldn't figure out exactly how to get that counter via the command line but when I used performance monitor and selected the SQL Server Data files size in KB and then multiplied that by 1024 to get it in bytes I get the result the WMI_Exporter is showing me.  Does that mean this is a Windows 32 bit counter issue that cannot be fixed?  It makes some sense I guess that as it went above 4096GB it hit the integer limit for a 32-bit unsigned int in KB so this counter would have messed up.

**Comment by carlpett** [comment]
Yeah, then I would guess there's a limitation in SQL Server in how they chose to expose the counters, unfortunately, and there's not much we can do in the exporter to fix it.

**Comment by bpickhardt** [comment]
Thanks for looking.  I confirmed that even via the Get-Counter PowerShell I get the same response so I believe it to be A MSSQL issue.
