### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by r8or0pz** [prometheus-community/windows_exporter#559]
Hi! 

What Grafana Dashboard can I use with it? It is not shown up with Node Exporter

**Comment by NosIreland** [comment]
There are multiple dashboards
[](https://grafana.com/grafana/dashboards/10467)
[](https://grafana.com/grafana/dashboards/10171)
Just make sure to modify metrics in dashboards from wmi_metric to windows_metric

**Comment by MHZarei** [comment]
I found this dashboard that work with version v0.13.0+

https://grafana.com/grafana/dashboards/12422

**Comment by mucahidk** [comment]
This is my new Dashbord for IIS Perfmon Metrics : https://grafana.com/grafana/dashboards/12495

**Comment by nguyenngokhuong** [comment]
how to add start file windows_exporter on prometheus

**Comment by vSakun** [comment]
Maybe there is a dashboard for MS SQL?

**Comment by pauloligorio** [comment]
@mucahidk 
Hello, I have a panel similar to this one , regarding IIS, but I would like some way to display the source ip of the connection, do you think it is possible? Are there any metrics that export this today?
