### ISSUE TITLE
thermalzone does not seem to work properly for me

### ISSUE THREAD

**Issue by Jared87** [prometheus-community/windows_exporter#560]
I installed the exporter because my CPU fan was really bad in cooling, i activated the thermalzone plugin, but it shows constantly `16.850000000000023` in the `windows_thermalzone_temperature_celsius` field.
```
# HELP windows_thermalzone_percent_passive_limit (PercentPassiveLimit)
# TYPE windows_thermalzone_percent_passive_limit gauge
windows_thermalzone_percent_passive_limit{name="\\_TZ.TZ10"} 100
windows_thermalzone_percent_passive_limit{name="\\_TZ.X570"} 100
# HELP windows_thermalzone_temperature_celsius (Temperature)
# TYPE windows_thermalzone_temperature_celsius gauge
windows_thermalzone_temperature_celsius{name="\\_TZ.TZ10"} 16.850000000000023
windows_thermalzone_temperature_celsius{name="\\_TZ.X570"} 16.850000000000023
# HELP windows_thermalzone_throttle_reasons (ThrottleReasons)
# TYPE windows_thermalzone_throttle_reasons gauge
windows_thermalzone_throttle_reasons{name="\\_TZ.TZ10"} 1
windows_thermalzone_throttle_reasons{name="\\_TZ.X570"} 1
```

The system is running a Ryzen 7 3700X on a GIGABYTE X570 AORUS ELITE, other Tools like CoreTemp showing the correct temperatures.

Did i do something wrong or am i completly on the wrong way?

**Comment by carlpett** [comment]
Hi @Jared87,
The driver support for WMI (which is how we're reading the temperatures) is quite mixed, and we've seen many questions on lack of data, or like your case, incorrect data. The only advice we can give unfortunately is checking with your vendor if they have better drivers available.
I haven't used CoreTemp, but I would expect such tools to use some other mechanism to read the data. We'd be very open to help improving the collector if that mechanism is possible to use for us.

**Comment by Jared87** [comment]
Thank you for the explanation. They habe a super short description how they get  the temperatures on their website, but nothing technical. Changing drivers seems Not to ne an option for me, it was just a try to geht the numbers from my desktop in a crashsafe way.
