### ISSUE TITLE
File version missing on the EXE

### ISSUE THREAD

**Issue by JDA88** [prometheus-community/windows_exporter#561]
Hi,

The file version, and product name are missing from the EXE. It makes reporting, deployment and patching livecycle with corporate tools like SCCM sub optimal. 
Does anyone know an easy way to add that on the build process?

**Comment by carlpett** [comment]
Hi @JDA88,
Thanks for the suggestion, it is a really good idea! I found some tooling for building the necessary blobs into the executable. After testing around a bit, this is what it looks like:
![image](https://user-images.githubusercontent.com/214867/86464414-bec64980-bd2f-11ea-898d-1e1c80a0ced0.png)

Does that cover all the info you need? The product version will be the output of `git describe --tags`, so for normal released versions you'd get `v0.13.0`, not the bits at the end I have with a local build. Alternatively, we could set this to the git revision, not sure what is most helpful.

**Comment by JDA88** [comment]
That's perfect! Thank you very much 👍

**Comment by JDA88** [comment]
When does this change will be merged? It's hard to do inventory on windows without this information.
