### ISSUE TITLE
system_up_time metrics

### ISSUE THREAD

**Issue by mucahidk** [prometheus-community/windows_exporter#567]
Hi,
First off all thank you for this application. I was using wmi exporter 0.9 version, now I installed windows_exporter 0.13 version.

There was wmi_system_system_up_time in the old version, but not in the new verison. I was using this frequently. 

the query i use: wmi_os_time{instance=~"$host"} - wmi_system_system_up_time{instance=~"$host"}

There is windows_os_time but not windows_system_system_up_time. I request your valuable help.

**Comment by arnepluhar** [comment]
Hi,
do you see any windows_system_*-metrics? If not, did you do a custom install? In a custom install you need to include all exporters you like to use because you override the default list of exporters to be installed.

**Comment by carlpett** [comment]
In addition to what @arnepluhar points out, I'd like to mention that you can use the shorthand `[defaults]` to expand to all the default collectors if you are just adding additional ones (ie not want to disable any of the default ones).
So `--collectors.enabled=[defaults],iis` to keep the defaults and just add the `iis` collector. This appears to have disappeared from the documentation for some reason, I'll add it back.

**Comment by mucahidk** [comment]
Hi,
I'm installing default and others: ENABLED_COLLECTORS="cpu,cs,iis,logical_disk,memory,net,os,service,textfile,process,netframework_clrmemory,netframework_clrexceptions" 

@carlpett I wait you to add again.Thank you very much for your support :)

This is my new Dashbord for IIS Perfmon Metrics : https://grafana.com/grafana/dashboards/12495

**Comment by carlpett** [comment]
Flags are now documented in the readme. The reason you're not seeing the system metrics is that you do not actually have `system` in your list of enabled collectors.
I'd suggest changing your line to `ENABLED_COLLECTORS=[defaults],iis,memory,netframework_clrmemory,netframework_clrexceptions`.
