### ISSUE TITLE
Windows Exporter Won't Start as Service on Windows Server 2016

### ISSUE THREAD

**Issue by james-m-tubbs** [prometheus-community/windows_exporter#568]
Hi All,

I'm having an issue where Windows Server 2016 where I can't start wmi_exporter as a service. This happens both via the MSI installer and creating the service manually via cmd line. When manual create from cmd line service start fails with 1067 error. I am not passing any options to the command line.
 
Starting the exporter exe manually works as expected. It's just for some reason failing when starting as a service. Also, even more weirdly, if I reboot the box the service works! At that point if I do a manual start/stop i get the above error.

Versions tested:
- 0.11.0
- 0.12.0

Also, if it helps, I'm running on hardened enterprise windows servers. If there are hardening services running that may impact the service starting I can investigate that as well.

**Comment by carlpett** [comment]
Hi @james-m-tubbs,
We haven't heard anything specific about hardening services impacting the exporter, but it sounds plausible. If you have any way of getting logs from those, that would seem like a good place to start. By default we'll run as a system account, which might be blocked?
That it works on boot would indicate that it is allowed until "something else" (GPOs, other serives) steps in to block it.

There isn't a good set of built-in privileges to grant which allows all the calls used by the exporter, as far as we know, but perhaps your security team has some ideas?

**Comment by rkuksa** [comment]
Hello @james-m-tubbs @carlpett !
Look at https://github.com/prometheus-community/windows_exporter/issues/551#issuecomment-655732294
I had the same problem on Windows 7 Pro and `sc config / sc failure` solution work.

**Comment by aymericDD** [comment]
Hi all ! 
Thanks @james-m-tubbs  for the issue :+1:  And @rkuksa for the patch, but it didn't work for us...
We have the same issue on server 2012 and 2016 too ! The service starting and stopped endlessly...

**Comment by james-m-tubbs** [comment]
The issue was due to a policy configuration - this can be closed

**Comment by james-m-tubbs** [comment]
We found the root cause and it was unrelated to the binary - this can be closed.

**Comment by aymericDD** [comment]
Hi @james-m-tubbs 
Can you explain your issue? Maybe ours is related.
