### ISSUE TITLE
GPU load Collector

### ISSUE THREAD

**Issue by andryrus** [prometheus-community/windows_exporter#573]
Is it posible to add GPU load Collector?

Same info that we got on Task Manager - Perfomance
 - GPU 3D
 - GPU Copy
 - GPU Video Encode
 - GPU Video Decode
 - GPU Dedicated GPU memeory usage
 - GPU Shared GPU memeory usage

It will be great to have Fan speed and Temp, but as i understand Nvidia or AMD software should be installed.

**Comment by carlpett** [comment]
Hi @andryrus,
I'm not sure from where Windows collects that data, but if you can find out, it can most likely be added. Contributions are very welcome!

**Comment by andryrus** [comment]
Hi @carlpett 
So there are  several  posible ways - all using perfmon.

1st is perfmon build in metrics, they were added to win 10, i thinck with **17 or **18 update.
Minimum servers versison - 2019

\GPU Local Adapter Memory(*)\Local Usage
\GPU Engine(*)\Utilization Percentage
\GPU Engine(*)\Running Time
\GPU Adapter Memory(*)\Shared Usage
\GPU Adapter Memory(*)\Dedicated Usage
\GPU Adapter Memory(*)\Total Committed
\GPU Process Memory(*)\Shared Usage
\GPU Process Memory(*)\Dedicated Usage
\GPU Process Memory(*)\Non Local Usage
\GPU Process Memory(*)\Local Usage
\GPU Process Memory(*)\Total Committed
\GPU Non Local Adapter Memory(*)\Non Local Usage

2nd way is metrics added with GPU drivers.
I don't have info about Intel and AMD, but Nvidia metrics are
\NVIDIA GPU(*)\% Video Decoder Usage
\NVIDIA GPU(*)\% Video Encoder Usage
\NVIDIA GPU(*)\PCI-E current speed to GPU Mbps
\NVIDIA GPU(*)\PCI-E current width to GPU
\NVIDIA GPU(*)\PCI-E downstream width to GPU
\NVIDIA GPU(*)\% FB Usage
\NVIDIA GPU(*)\% Video Usage
\NVIDIA GPU(*)\% Bus Usage
\NVIDIA GPU(*)\Fan Speed
\NVIDIA GPU(*)\% GPU Memory Usage
\NVIDIA GPU(*)\% GPU Usage
\NVIDIA GPU(*)\Power Consumption mW
\NVIDIA GPU(*)\Available Memory MB
\NVIDIA GPU(*)\Total Memory MB
\NVIDIA GPU(*)\Virtual Memory MB
\NVIDIA GPU(*)\Memory Clock MHz
\NVIDIA GPU(*)\Core Clock MHz
\NVIDIA GPU(*)\% Cooler rate
\NVIDIA GPU(*)\Temperature C

So, not sure wich one is best...

I try to take disk collection as exemple, but i am not so good in Go :(

**Comment by carlpett** [comment]
That's already very useful! Last time this came up nothing was found outside of using vendor drivers. 
Looking at the generic GPU counters, they seem to have instances like `pid_680_luid_0x00000000_0x0000877D_phys_0_eng_8_engtype_VideoEncode`. So we could extract labels for the pid and engine type (if that's useful?).
Do you have access to a multi-GPU machine to see how the other parameters vary when running across different cards? `phys` could be some index of the cards, perhaps? Or the hexadecimals.

**Comment by andryrus** [comment]
Nvidia Counters...
On my home Desktop i got 1050 with default driver and nvidia experience - and no couters.
On my PROD server i got Win10 and SRV19 with Grid and Quadro - and i got couters on both.
I am a bit confused as both use nvidia-smi...

Generic GPU
**phys_0** is always **phys_0**
And is seems like 
**luid_0x00000000_0x0000877D**
is card
luid - locally unique identifier ... unique during single reboot

From my perspective 
Nvidia is very simple - GPU % in use, Mem $ in use, Temp.
+ perfmon for all windows versions * (PRO cards only)
BUT
 - perfmon - PRO cards only.
 - NVWMI/nvidia-smi (installed by default with all drivers) - PRO and non PRO cards - seems like a bit more development compare to Generic GPU

Generic GPU is a bit complicated (as i see), got more info
+ GPU load by process is very intersting ... usually if you got PRO GPU for many users it is important to understand who is using most of resources. 
BUT
 - luid - ??? 
 - no Temp !!!
 - not all windows versions got Generic  GPU metrics 

P.S. I got 3 PRO hosts and 2 non PRO, i can use all of them for testing.
