### ISSUE TITLE
Need to monitor Ping, RAM, Storage, and Windows Updates

### ISSUE THREAD

**Issue by pebauer** [prometheus-community/windows_exporter#576]
Hey there,

is windows_exporter able to monitor Ping, RAM, Storage, and state of Windows Updates on a specific Windows Server 2012R2 machine? If not, how can I realize that?

Thanks in advance!

**Comment by carlpett** [comment]
Hi @pebauer,
The windows_exporter currently covers two of your cases, memory usage and storage usage. See the docs on the [memory](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.memory.md) and [logical_disk](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.logical_disk.md) collectors.
Windows update support has been discussed, but nothing has been implemented. Some suggestions in [this thread](https://github.com/prometheus-community/windows_exporter/issues/267).
Regarding ping, it wouldn't be implemented in the exporter itself, but you can build it with the [textfile collector](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.textfile.md)
