### ISSUE TITLE
Provide Helm chart for Windows nodes in Kubernetes deployments

### ISSUE THREAD

**Issue by aidapsibr** [prometheus-community/windows_exporter#578]
With Windows nodes now supported in Kubernetes it would be really helpful to get the low-level metrics this provides.

**Comment by chzbrgr71** [comment]
I got a working container/daemonSet for K8s. I have the exporter running on Windows, but I still need to figure out how to get it integrated into the Prom service overall. 

I'm planning to submit a PR shortly.

**Comment by iusergii** [comment]
Also, looking forward to it.

**Comment by chzbrgr71** [comment]
This is my PR. It still needs work, but it's a start https://github.com/prometheus-community/windows_exporter/pull/581

**Comment by carlpett** [comment]
I'll close this as a duplicate of #546.

**Comment by DerrickMartinez** [comment]
I don't think you can just run this inside a container. Typically you'd want to proxy through wins.exe
