### ISSUE TITLE
Question about getting percentage of IO usage

### ISSUE THREAD

**Issue by for-mat** [prometheus-community/windows_exporter#579]
In Linux, I can use this to get IO usage:
`irate(node_disk_io_time_seconds_total{}[2m])`
But in Windows, however, I did not find promSQL for this metric
![image](https://user-images.githubusercontent.com/43637488/88509574-f5803e80-d013-11ea-98ba-2e8130d57bfa.png)

Based on the above, I use this notation, but I find that some machines will exceed 100% and I want to know why, or how should I get the percentage of IO usage?

**Comment by for-mat** [comment]
sum by (instance,zone,volume)(rate(wmi_logical_disk_write_seconds_total{type=~"payment",job=~"payment",volume!~"Harddisk.*"}[2m])+rate(wmi_logical_disk_read_seconds_total{type=~"payment",job=~"payment",volume!~"Harddisk.*"}[2m]))

**Comment by carlpett** [comment]
Hi,
Perhaps your disk might be serving both reads and writes in parallel, which would throw that calculation off. Test `1 - sum by (instance, zone, volume) (rate(windows_logical_disk_idle_seconds_total{...}[2m]))`, that would compensate for that effect.

**Comment by zakiharis** [comment]
@carlpett 
I tried using your suggested promql. Is it means that my disks IO are low?

Or 1% is high (as equivalent to 100%) ?

![iXHMHigk8hNL](https://user-images.githubusercontent.com/1005824/97398844-dd77ce00-1926-11eb-974e-acec8d5da790.png)

**Comment by carlpett** [comment]
Hi @zakiharis,
Yes, that query would have a range of 0-1, not 0-100. You can set the dashboard panel to use that unit (Its called "Percent 0-1" or something like that), or multiply by 100.

**Comment by carlpett** [comment]
Since the original asker hasn't returned, I'll close this for now.
