### ISSUE TITLE
WMI Exporter v0.11.0 collector failure: failed collecting logical_disk metrics:<nil> counter not found

### ISSUE THREAD

**Issue by krdineshbny** [prometheus-community/windows_exporter#580]
We are using WMI Exporter in our firm and v0.11.0 is being used in more than 20k servers.
I have issues in few servers where collector fails (Windows Server 2008 R2 Enterprise)
Upon checking the event logs for exporter i see this

collector cpu failed after 0.000000s: counter not found
collector logical_disk failed after 0.000000s: counter not found
collector net failed after 0.000000s: counter not found
failed collecting net metrics:<nil> counter not found
collector process failed after 0.000000s: counter not found
collector system failed after 0.000000s: counter not found
failed collecting system metrics:<nil> counter not found
failed collecting logical_disk metrics:<nil> counter not found

wmi_exporter_collector_success{collector="cpu"} 0
wmi_exporter_collector_success{collector="cs"} 1
wmi_exporter_collector_success{collector="logical_disk"} 0
wmi_exporter_collector_success{collector="net"} 0
wmi_exporter_collector_success{collector="os"} 1
wmi_exporter_collector_success{collector="service"} 1
wmi_exporter_collector_success{collector="system"} 0
wmi_exporter_collector_success{collector="textfile"} 1

**Comment by carlpett** [comment]
Hi @krdineshbny,
When we've seen this type of error before, it has been due to issues with the machines themselves, eg corruption of the performance counters.
One first step you can try is running `lodctr /R` to rebuild the counters, but if that doesn't help you'll need to dig into the Windows installation itself to see what is going wrong. Does perfmon work on these machines?

**Comment by RemyaRChandran** [comment]
Do we require a reboot after running lodctr /R to rebuild the counters ? and will this command have any impact on the running processes/services ?

**Comment by carlpett** [comment]
No, reboot is not necessary. There should be no noticable impact on running services, unless they interact with WMI or performance counters.

**Comment by krdineshbny** [comment]
@carlpett  lodctr /R worked for many machines for me and some machines had issues with perfmon itself.
Thanks for helping out.
