### ISSUE TITLE
Memory_free_byte appears zero intermittently,confirmed with Windows Perfmon , the memory does not go to zero.

### ISSUE THREAD

**Issue by ShubhangiSGaikwad** [prometheus-community/windows_exporter#582]
Hello Team,

Using windows_exporter-0.13.0-amd64.msi , to collect iis,cpu,memory and Logical Disk Details via prometheus and grafana.

Memory_free_byte appears zero intermittently,confirmed with Windows Perfmon , the memory does not go to zero.
Refer images attached for reference , both perfmon (available memory byte) and grafana of same time duration

![image](https://user-images.githubusercontent.com/43333553/89272106-4965d580-d65b-11ea-9f9a-e206247b04a6.png)
![image](https://user-images.githubusercontent.com/43333553/89272727-31db1c80-d65c-11ea-9322-3714c34c3526.png)

Request to please guide why does Memory_free_byte appears zero intermittently. Any quick fix for this would be appreciated.

**Comment by ShubhangiSGaikwad** [comment]
![image](https://user-images.githubusercontent.com/43333553/89273025-a0b87580-d65c-11ea-8ccf-73628a0981a3.png)

**Comment by carlpett** [comment]
Hi @ShubhangiSGaikwad,
I would suspect that your "web" host did not get scraped successfully at those times, and Grafana is set to "zero if absent". You can check if the `up` metric for that host is 0 at this time to verify.

**Comment by infernix** [comment]
Hi,

Seeing the same, but there is no scrape error. In fact, cpu time metrics are collected just fine where these gaps exist.

I see gaps in various statistics, such as windows_process_cpu_time_total, windows_cs_physical_memory_bytes, windows_service_state. But then not in windows_cpu_time_total.

I've added some arbitrary multipliers to render these close together in the graph:
![image](https://user-images.githubusercontent.com/162537/98934862-fd8cbd00-24e2-11eb-8cad-012069ddf2d7.png)

This isn't happening on all servers, only some. There is nothing about this in the prometheus debug logs. I haven't been able to check the logs on the server, will ask to see if anything is there. But it looks to me as if at some time intervals, some metrics aren't being served.

**Comment by breed808** [comment]
Do the Prometheus graphs return the same values?
Also, is the CPU collector successful during these periods? `windows_exporter_collector_success{collector="cpu"}`
