### ISSUE TITLE
IIS is not working

### ISSUE THREAD

**Issue by Gum97** [prometheus-community/windows_exporter#584]
Hi all, my English is not good. So i need monitor IIS service but windows_exporter not get metric. how to fix that ?
![image](https://user-images.githubusercontent.com/21122797/89847477-5419f080-dbae-11ea-9fff-f6394a10e4aa.png)

**Comment by Smuggla** [comment]
You need to add it as it is not enabled by default.

then add the other packages you need comma separated.

```
.\windows_exporter.exe --collectors.enabled "iis,system"
```

**Comment by carlpett** [comment]
Thanks @Smuggla!
@Gum97, I'll close this since this should fix your problem. Re-open if it did not.
