### ISSUE TITLE
How to monitor custom performance counters

### ISSUE THREAD

**Issue by electron2302** [prometheus-community/windows_exporter#585]
Is there a way to collect custom performance counters, that another software provides to perfmon, for example \MyApp\counter1

Thanks in advance 🤓

**Comment by carlpett** [comment]
Hi @electron2302,
The adviced way to do this is to set up a script running in the Windows Task Scheduler which writes this data to disk, and then is read by the textfile collector.
Alternatively, if `MyApp` is an application you develop, the best solution would be to expose the metrics in Prometheus format directly from the application.

**Comment by electron2302** [comment]
Hi @carlpett and thanks for the reply.
Sadly the development of `MyApp` is not in my hands. 

`The adviced way to do this is to set up a script running in the Windows Task Scheduler which writes this data to disk, and then is read by the textfile collector.`
This sounds like an unnecessary step producing large files if it runs long enough. One of the reasons we turned to Prometheus is the compression and rotation of stored data. 

I tried using the “Collector generator” but even after fixing the generator I get errors from wmi:
`wmi: cannot load field \"Name\" into a \"string\": unsupported type (<nil>)`

And sure enough if I test with `Get-CimInstance -ComputerName "localhost" -Class "Win32_PerfRawData_MyApp_ MyApp”` in the output, the name is empty. 
In case you (or somebody else) know why that is and/or how to fix it, I would be glad to even get pointed in the right direction, since I see all the relevant names in Perfmon, and don’t quite get what these wmi instances are :/

**Comment by carlpett** [comment]
>This sounds like an unnecessary step producing large files if it runs long enough. One of the reasons we turned to Prometheus is the compression and rotation of stored data.

You'd overwrite the file at each pass, so file size wouldn't be an issue. Or am I misunderstanding you here? Anyway, there's no difference vs doing it inside the exporter from the Prometheus server's point of view, so performance-wise it's completely equivalent.

>And sure enough if I test with `Get-CimInstance -ComputerName "localhost" -Class "Win32_PerfRawData_MyApp_ MyApp”` in the output, the name is empty.

The generator currently works with WMI only, not performance counters. In many of the Windows built-in counters, there's more or less a one-to-one mapping from counters to WMI, but this isn't the case if your application writes counters itself.
