### ISSUE TITLE
Kubernetes nodes: container metrics  

### ISSUE THREAD

**Issue by iusergii** [prometheus-community/windows_exporter#588]
Hi Team,

I have a Kubernetes Cluster (AWS EKS) and I want to get [container](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.container.md) metrics from the Windows Nodes.   As it's not possible to run it in the same fashion as a node-exporter/DaemonSet on Linux yet I installed windows_exporter-0.13.0-386.msi directly to the Nodes.

The service is successfully started 
```
"C:\Program Files (x86)\windows_exporter\windows_exporter.exe" --log.format logger:eventlog?name=windows_exporter --collectors.enabled os,container --telemetry.addr :9100 
```
But I can only see OS metrics. Container one is missing and from EventLog I can see Errors:
```
Err in Getting containers:hcsshim::GetComputeSystems: The specified module could not be found.
failed collecting ContainerMetricsCollector metrics:<nil> hcsshim::GetComputeSystems: The specified module could not be found.
collector container failed after 0.001004s: hcsshim::GetComputeSystems: The specified module could not be found.
```

I saw the same errors when the exporter run inside container #453.  Is it the issue of nested virtualization with AWS VMs and is there any way to get container metrics?

**Comment by carlpett** [comment]
Hi @iusergii,
I would have expected this to work, generally. Something of a bet, but could you try installing the 64-bit version instead of 32-bit? I'm not sure if there's any compatibility issues with HCS and 32-bit installs.

**Comment by iusergii** [comment]
Hi @carlpett,
You're right, my bad I had increased node type and haven't paid attention.  64-bit version works!.
Thank you,  closing this.
