### ISSUE TITLE
Install windows_exporter on many servers with service collector and regexp for service Name

### ISSUE THREAD

**Issue by elita26** [prometheus-community/windows_exporter#589]
Hi, I use DSC to install windows_exporter on servers and I have a problem with starting the installation of service collector with regexp for services. Example service collector with a custom query works if I start it on local machine using `& msiexec.exe`, and if I try it with `Start-Process` commandlet like `Start-Process msiexec.exe -Wait -ArgumentList ...` (used by DSC) it doesn't work. The problem appears to be in `--%` - every time I try to run the Start-Process with this `--%` sequence it just displays the msiexec help. Without the `--%` it works fine but without the regexp.  No matter how I try (ArgumentList as an array, separate string variable etc.) I can't make it work. Please advice if you're familiar with this issue.
My example scripts
```
$Arguments = '/quiet /i C:\Distrib\windows_exporter-0.13.0-amd64.msi ENABLED_COLLECTORS=os,cpu,cs,memory,net,system,logical_disk,service --% EXTRA_FLAGS=--collector.service.services-where="Name=''LRT%''"'
Start-Process msiexec.exe -Wait -ArgumentList $Arguments
```
windows_exporter - 0.13.0
Windows server 2016

**Comment by carlpett** [comment]
Hey @elita26,
I'm not familiar with DSC, but could you explain why you need to add the `--%`:s?

**Comment by elita26** [comment]
Hey @carlpett 
The example with --% is written on the main windows_exporter page. As I understand it, it is necessary in order to use a regular expression, for example `--collector.service.services-where ""Name LIKE' sql%'"""`. If you do it without --%, then Windows will try to substitute the system variable. 
The process collector is done via whitelist and there are no problems there. Is it possible to make a service collector the same way as a process collector? 
Or maybe you can tell me how to make a regular expression without --% in service collector

**Comment by carlpett** [comment]
Interesting. Appears that I asked about it when that line was written too (#291) but have since forgotten :)
However, if I read the docs about it ([here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_special_characters?view=powershell-6#stop-parsing-token---)) right, you shouldn't need to use `--%` within a string. It is only necessary when present in the command line itself, not in strings passed as arguments.

Regarding the regexp part, I'd guess there's some quoting issue. If you check the arguments that is set on the installed service after removing the `--%`, what does it say?

**Comment by elita26** [comment]
Service Path to executable:
"C:\Program Files\windows_exporter\windows_exporter.exe" --log.format logger:eventlog?name=windows_exporter --collectors.enabled os,cpu,cs,memory,net,system,logical_disk,service --telemetry.addr :9182   --collector.service.services-where="Name='LRT%'"

**Comment by carlpett** [comment]
Ah, yes, I should have spotted that one. Yes, you need to use `LIKE` instead of equals. So everything works with that change?

**Comment by elita26** [comment]
No(
I made changes to the script, but now msiexec outputs me help. if i delete `LIKE` then the exporter is installed, but the service metrics are not reported(
```
$Arguments = '/quiet /i C:\Distrib\windows_exporter-0.13.0-amd64.msi ENABLED_COLLECTORS=service EXTRA_FLAGS=--collector.service.services-where "Name LIKE ''LRT%''"'
Start-Process msiexec.exe -Wait -ArgumentList $Arguments
```

**Comment by carlpett** [comment]
Ah, but you've dropped the quotes around the `EXTRA_FLAGS` argument, so it see the bit after `services-where` as a new argument, and doesn't know what to do with it, thus help screen.
If you put the quoting back (with the requisite escaping of nested quotes), it _should_ work

**Comment by elita26** [comment]
```
$Arguments = '/quiet /i C:\Distrib\windows_exporter-0.13.0-amd64.msi ENABLED_COLLECTORS=service EXTRA_FLAGS="--collector.service.services-where ""Name LIKE ''LRT%''"""'
Start-Process msiexec.exe -Wait -ArgumentList $Arguments
```
It`s works
Thank you!

**Comment by elita26** [comment]
Maybe someone will need it. 
```
$Arguments = '/quiet /i C:\Distrib\windows_exporter-0.13.0-amd64.msi ENABLED_COLLECTORS=service,process EXTRA_FLAGS="--collector.process.whitelist=""LRT.+"" --collector.service.services-where ""Name LIKE ''LRT%''"""'
Start-Process msiexec.exe -Wait -ArgumentList $Arguments
```

**Comment by carlpett** [comment]
`''"""'`
Wow, what quoting. Thanks for posting that, I'm sure it'll save someone a bit of frustration! :heart:
