### ISSUE TITLE
Clarification on windows_mssql_sqlstats_batch_requests

### ISSUE THREAD

**Issue by noahjd** [prometheus-community/windows_exporter#596]
Hello,

I would like some clarification on this particular MSSQL metric:
`windows_mssql_sqlstats_batch_requests`
I see that it is a counter, is this just keeping track of the total batch requests or do I need to apply a rate to get the actual batch requests/sec ?

Thanks!

**Comment by carlpett** [comment]
Hi,
Yes, that appears to be a counter of the total number of batch requests, so to get the per-second you'd do roughly `rate(windows_mssql_sqlstats_batch_requests[5m])` (where the window 5m can be tweaked depending on your needs and setup)

**Comment by noahjd** [comment]
Great, thanks @carlpett . Sorry for the late reply!
