### ISSUE TITLE
0.14.0 x64 MSI: Service failed to start

### ISSUE THREAD

**Issue by GSR70** [prometheus-community/windows_exporter#599]
My environment is Windows Server 2019 Datacenter, so obviously I prefer to use the 64-bit version.  My admin CLI install command is basic `msiexec /i windows_exporter-0.14.0-amd64.msi`  The installer progress gets to about 60% and the Application log in Event Viewer shows the installer attempting 'Starting server on :9182', but eventually fails
![image](https://user-images.githubusercontent.com/52212209/93133416-6ba83580-f694-11ea-9110-6b6e4992031f.png)

I revert to the 32-bit installer and the install completes without issue.  However, the 32-bit is looking for the TEXTFILE_DIR in the 64-bit location and generates event id 102's as that does not exist.  To eliminate those, I have to first manually create 'C:\Program Files\windows_exporter\textfile_inputs' and then run the 32-bit installer.

Besides not defining the collectors, and potentially 'generating a large number of metrics', where am I going wrong installing the 64-bit?

**Comment by kzz5** [comment]
I'm seeing the same behavior as well with the 64-bit installer. Windows 10 Enterprise.  Added AV exceptions but still fails to install.

I see this in event viewer.

![image](https://user-images.githubusercontent.com/71345227/93246820-f51e3d00-f752-11ea-8f80-f53c5c9fda62.png)

**Comment by brettjacobson** [comment]
We have similar problem where the service does not start as part of the installation process:

```
EventID            : 7000
MachineName        :  zzzzzzzzzzzzzzzzzzzzzzzz
Data               : {119, 0, 105, 0...}
Index              : 39733
Category           : (0)
CategoryNumber     : 0
EntryType          : Error
Message            : The windows_exporter service failed to start due to the following error:
                     %%1053
Source             : Service Control Manager
ReplacementStrings : {windows_exporter, %%1053}
InstanceId         : 3221232472
TimeGenerated      : 9/14/2020 5:23:48 AM
TimeWritten        : 9/14/2020 5:23:48 AM
UserName           :
Site               :
Container          :
```

Since the replacement string doesnt exist, it really isn't telling us why its unable to start.

Starting the service manually after the fact succeeds (after we discover it is not running).

**Comment by GSR70** [comment]
Brett, 
Unfortunately for us, once we get the error then the 64-bit installer rolls everything back.  We do, however, see this type of behavior from time to time with the 32-bit version after it's installed.

**Comment by GSR70** [comment]
One other item of note.  Although the service is set to 'Automatic', we are finding that this does not occur when the server(s) are restarted, and I've waited 15 minutes to confirm there wasn't just a delay.  We are having to manually start the service.

**Comment by kzz5** [comment]
I'm able to extract the exe from the MSI file and run it manually but it seems to always fail to start when trying to launch it as a service.

**Comment by carlpett** [comment]
> once we get the error then the 64-bit installer rolls everything back. 
@GSR70 Is this an upgrade or a clean install? #597 fixes an issue with upgrades, but we haven't seen this type of problems on clean installs before.

**Comment by kzz5** [comment]
These are fresh installs for us.

**Comment by GSR70** [comment]
@carlpett they are clean installs for us as well.  As mentioned, we don't see the same service startup issues with the 32-bit installer so that is what we had to revert to.  More than happy to arrange a remote session if that helps out your investigation.

**Comment by noahjd** [comment]
I'm having the same issue. Very similar environment.

**Comment by kzz5** [comment]
0.15.0 still fails to install with the msi installer

**Comment by yigit9194** [comment]
Hello,

I've the same issue with the 0.15.0 version on Windows Server 2012 R2 for an upgrade and fresh install. I found a strange thing but i don't if it's very helpfull.

When the error box occurs, i"ve opened the service.msc console to try to start the service and here was the error : “Error 1075: The dependency service does not exist or has been marked for deletion”. So i've checked the depedencies and there was not the "WmiApSrv" service. I don't why and how, but this service is missing on my server and it's present on the other servers...

Maybe this clue could help

**Comment by mrkwbr** [comment]
we rolled this out to about 800 Windows servers and had about 5-8% fail - most of those were 2012 R2.
after poking around, rebuilding the perf counters seems to fix the issue - i haven't been able to pin it down to x86 or x64 counters:
lodctr /R (system32 and syswow64)
winmgmt.exe /resyncperf
restart-service winmgmt -force
restarting the service doesn't seem to be needed to fix the install/service startup but is included in all the articles about how to rebuild the counters
