### ISSUE TITLE
collected metric process_start_time_seconds gauge:<value:1.600194451e+09 >  should be a Counter

### ISSUE THREAD

**Issue by sikasam** [prometheus-community/windows_exporter#602]
Instead of directly downloading the msi from the releases, we have forked the repo and built the msi to make our bits signed. 
used that msi to run in our kubernetes containers but we are getting the below error. 
Any idea of how to resolve this issue?

PS C:\app> wget http://localhost:50505/metrics
wget : An error has occurred while serving metrics:
collected metric process_start_time_seconds gauge:<value:1.600194451e+09 >  should be a Counter

**Comment by breed808** [comment]
This should be resolved as of the recent client library update in #669 
If there's still issues please let us know.
