### ISSUE TITLE
autodiscover windows node

### ISSUE THREAD

**Issue by aaronsssya** [prometheus-community/windows_exporter#604]
question

is there a sample of Prometheus ConfigMap to auto discover windows nodes?

**Comment by brettjacobson** [comment]
I think you're looking for Prometheus Service Discovery, which is highly dependent on your "cloud" provider, or other discovery mechanism.

https://prometheus.io/docs/prometheus/latest/configuration/configuration/

You would need to identify an appropriately named discovery engine `*_sd_*`  from that page.

**Comment by carlpett** [comment]
As mentioned, this is outside the scope of the exporter. Please look into the above link, or ask in the Prometheus users [community](https://prometheus.io/community/) for advice around configuring Prometheus itself.
