### ISSUE TITLE
How to enable additional collectors along with the default collectors ?

### ISSUE THREAD

**Issue by 16srana** [prometheus-community/windows_exporter#605]
Can I use command like this
`msiexec /i C:\Users\Administrator\Downloads\windows_exporter.msi ENABLED_COLLECTORS="defaults,memory`

or

do I have to add all the default collectors also in the list ?

**Comment by krdineshbny** [comment]
msiexec /i <path to msi> ENABLED_COLLECTORS=[defaults],process
