### ISSUE TITLE
WMI Exporter v0.11.0 collector cs failed after 0.010001s: Exception occurred. (Invalid class )

### ISSUE THREAD

**Issue by krdineshbny** [prometheus-community/windows_exporter#609]
We are using WMI Exporter in our firm and v0.11.0 is being used in more than 20k servers.
One of the server is having collector failure issues. osName="windows server 2008",osVersion="6.1"
Upon checking the event logs for exporter i see exception occurred

i tried reloading counters and restarted service.
lodctr /R

Still facing same same issue.
The perfmon is working without any issues.

collector cs failed   after 0.010001s: Exception occurred. (Invalid class )
failed collecting cs metrics:<nil>   Exception occurred. (Invalid class )
collector os failed after 0.008001s:   Exception occurred. (Invalid class )
failed collecting os metrics:<nil>   Exception occurred. (Invalid class )
collector service failed after 0.005000s:   Exception occurred. (Invalid class )
failed collecting service   metrics:<nil> Exception occurred. (Invalid class )

wmi_exporter_collector_success{collector="cpu"} 1
wmi_exporter_collector_success{collector="cs"} 0
wmi_exporter_collector_success{collector="logical_disk"} 1
wmi_exporter_collector_success{collector="net"} 1
wmi_exporter_collector_success{collector="os"} 0
wmi_exporter_collector_success{collector="process"} 1
wmi_exporter_collector_success{collector="service"} 0
wmi_exporter_collector_success{collector="system"} 1
wmi_exporter_collector_success{collector="textfile"} 1

**Comment by carlpett** [comment]
Hi @krdineshbny,
I assume that if you run `gwmi Win32_ComputerSystem` in Powershell you also get an error?
If so, I'm afraid we can't really help much with generic Windows troubleshooting. If that powershell call completes without error on a machine were the exporter fails, let me know and we'll reopen to take a closer look.

(I'll also recommend upgrading both the exporter as well as noting that your Windows server version is past end of life *and* it's extended support window)
