### ISSUE TITLE
install windows_exporter failed in windows 2003(32bit)

### ISSUE THREAD

**Issue by kedizhou** [prometheus-community/windows_exporter#610]
HI, friend
when i install windows_exporter in windows server 2003, i have got failed that information is "Service 'windows_exporter' failed to start. verify that you have sufficient privileges to start system service.", it means windows_exporter don't support it?

**Comment by carlpett** [comment]
Hey @kedizhou,
Correct, the Go runtime requires Windows 2008R2 or later.
If you absolutely cannot update your systems you can use versions of the exporter up until version 0.9, where Windows 2003 is still supported.
