### ISSUE TITLE
Exchange: "Error in ADAccessProcesses: counter not found"

### ISSUE THREAD

**Issue by Biomains** [prometheus-community/windows_exporter#614]
2 error messages in Application eventlog.

collector exchange failed after 0.000999s: counter not found
Error in ADAccessProcesses: counter not found

This is on Windows 2016 Std, with MS Exchange server 2016.

I had this on both wmi_exporter v.01.12.0 and on the latest windows_exporter v.014.0

**Comment by carlpett** [comment]
@rmyhren @eikaas Either of you seen this not being present before? I suppose a workaround here could be allowing to disable individual sub-collectors if they are somehow not available.

**Comment by timweissenfels** [comment]
I'm afraid the issue still persists @fischerman
