### ISSUE TITLE
Configure process collector

### ISSUE THREAD

**Issue by bonnetkar** [prometheus-community/windows_exporter#616]
Hello,

I'm trying to monitor application system resources usage such as CPU and memory and I can't have the metrics available in Grafana.

Is this correct to start the exporter like that :
windows_exporter.exe --log.format logger:eventlog?name=windows_exporter --telemetry.addr :9182 --collectors.enabled="system,textfile,cpu,cs,logical_disk,net,os,process" --collector.process.whitelist="My.Application1|My.Application2|My.Application3"

I need all the metrics available by default plus the one about these three processes.

It seems that as soon as the exporter is running, the server hosting Prometheus and Grafana gets really slow. So I guess I'm doing something wrong.

**Comment by carlpett** [comment]
Hi,
It's not clear to me what you are asking. If you are having issues with your Prometheus server, please ask on the prometheus-users maillist or on IRC - see [community](http://prometheus.io/community)

**Comment by MrChips821** [comment]
I also think there might be an issue with the process collector. I'm running it according to the docs but I can't see any windows_process metrics despite all the other collectors working OK.  I'm seeing this issue on Windows server 2016 the latest windows_exporter version.
