### ISSUE TITLE
windows_exporter doesn't start on WinXP x32 (SP3)

### ISSUE THREAD

**Issue by alexey-shab-8** [prometheus-community/windows_exporter#617]
Run cmd under user with administrative rights:
msiexec /i c:\wmi_exporter-0.10.2-386.msi
Error during installation: 
service WMI_exporter failed to start. Verify that you have sufficient privileges to start system service.
[win_exporter.log](https://github.com/prometheus-community/windows_exporter/files/5353702/win_exporter.log)
There is no problem for wmi_exporter-0.9.0-386.msi
Problem appears for wmi_exporter-0.10.2-386.msi and higher

**Comment by avonwyss** [comment]
XP is soon 20 years old and long out of extended support... Not sure why you expect the collector to work on it...

**Comment by carlpett** [comment]
Will be fixed with #611
