### ISSUE TITLE
Expose DisplayName in service collector

### ISSUE THREAD

**Issue by JDA88** [prometheus-community/windows_exporter#619]
Please expose the `Display Name` propertie of the `Win32_Service` class as a `DisplayName` label in the service collector.

Some services have very obscure names and their display name is much more informative.

**Comment by breed808** [comment]
@JDA88 I can see the label is present in the `windows_service_info` metric, and could be made to appear with a join:

```
windows_service_state + on(name) group_left(display_name) (0 * windows_service_info)
```

**Comment by JDA88** [comment]
> @JDA88 I can see the label is present in the `windows_service_info` metric, and could be made to appear with a join:
> 
> ```
> windows_service_state + on(name) group_left(display_name) (0 * windows_service_info)
> ```

You are correct I used that, thx
