### ISSUE TITLE
HyperV collector doesn't work

### ISSUE THREAD

**Issue by EljeAkh** [prometheus-community/windows_exporter#626]
Hi,
I'am trying to collect hyperv metrics and have problem with this. When i only use hyperv collector,  windows_explorer the returns text "Too many concurrent requests". If I use collect.enabled with "cpu,hyperv," the first request will return CPU and hyperv metrics. But after the first query, only the CPU will return (hyperv metrics are not returned or returned only partially).
If exclude cpu from collect.enabled (e.g. a change to os or other collectors with a hyperv collector), the result of "Too many concurrent requests" is returned again.
![Windows_exporter_HypervCollector_cuted](https://user-images.githubusercontent.com/72812421/95883984-3d497300-0d84-11eb-8076-887a30a0c826.png)

**Comment by carlpett** [comment]
Hi @EljeAkh,
Too many concurrent requests is returned if you have more than 5 ongoing scrapes at the same time. Do you have a very short scrape interval, or very many Prometheus servers scraping the machine?
It is intended to protect the machine from an ever-increasing backlog of requests if it cannot process them fast enough. If you have some use-case where you need to allow high concurrency, you can look at the flag `--telemetry.max-requests` to tune this. But beware that simply disabling it is probably only going to lead to excess load on the server.

**Comment by EljeAkh** [comment]
Thanx.
I changed the scrape interval (2s -> 5s) and it helped 👍
