### ISSUE TITLE
Getting error when enabling "container"

### ISSUE THREAD

**Issue by widdix123** [prometheus-community/windows_exporter#628]
When i enable container metrics , i get the below error ? Any ideas 
```
time="2020-10-15T14:43:36Z" level=fatal msg="Couldn't load collectors: Unknown collector \"\\\"container\\\"\"" source="exporter.go:335"
```

**Comment by carlpett** [comment]
Hi @widdix123,
This looks like an input error. You seem to have passed in the collector name with extra quotes around it.
