### ISSUE TITLE
PowerRegisterSuspendResumeNotification in Docker images due to older Go version

### ISSUE THREAD

**Issue by snoyberg** [prometheus-community/windows_exporter#629]
I believe this is an artifact of https://github.com/golang/go/issues/35447, which to my understanding was fixed in either Go 1.14 or 1.15. The currently available binaries in the releases page seem to be built with Go 1.13.3 based on the `--version` output. Note also that this repro does not work on all machines. Our production Windows Kubernetes cluster can run these executables, but my local Windows 10 Pro machine cannot.

Actions:

1. Downloads `windows_exporter-0.14.0-amd64.exe` from releases
2. Launch a Docker container using `docker run --rm -it -v C:\Users\<elided>\Downloads\:c:\Downloads mcr.microsoft.com/windows/servercore:2004`
3. Run the executable

Expected: same output as running outside of the container

Actual:

```
C:\downloads>.\windows_exporter-0.14.0-amd64.exe --version
fatal error: PowerRegisterSuspendResumeNotification failure

runtime stack:
runtime.throw(0xabcb38, 0x2e)
        C:/go/src/runtime/panic.go:774 +0x79 fp=0x158fdb0 sp=0x158fd80 pc=0x4330a9
runtime.monitorSuspendResume()
        C:/go/src/runtime/os_windows.go:294 +0x1a9 fp=0x158fe50 sp=0x158fdb0 pc=0x42f209
runtime.goenvs()
        C:/go/src/runtime/os_windows.go:531 +0x1ba fp=0x158fea8 sp=0x158fe50 pc=0x42fb8a
runtime.schedinit()
        C:/go/src/runtime/proc.go:554 +0xa9 fp=0x158ff00 sp=0x158fea8 pc=0x435aa9
runtime.rt0_go(0x158ff30, 0x7ffcce5e7034, 0x158ff30, 0x0, 0x7ffcce5e7034, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/go/src/runtime/asm_amd64.s:214 +0x13d fp=0x158ff08 sp=0x158ff00 pc=0x45f33d
```

I've built the executable myself and used that in the Docker container, and it works as expected:

```
C:\downloads>.\windows_exporter.exe --version
windows_exporter, version 0.14.0-10-g8f2f9d8 (branch: master, revision: 8f2f9d83f9379136a1c148ef1c4b3bf0d50b2a6a)
  build user:       <elided>
  build date:       20201019-08:05:47
  go version:       go1.15.3
```

It would be great if the releases could be updated to use a more recent version of Go. I'm not familiar with Go CI processes in general, but if this is something you'd like a PR for, please let me know and I'll try to put something together.

**Comment by carlpett** [comment]
Hey @snoyberg,
Thanks for the report! We'd love a PR to fix this - it should be sufficient to update the `appveyor.yml` file in the root of the repo.

Also a word of caution - running the exporter in a container doesn't behave as you might expect. Due to Windows not implementing privileged containers (yet), the exporter thus mainly exports data about the containerized Windows instance, not the container host itself, which is most frequently what people want.

**Comment by snoyberg** [comment]
Thank you for the clarification on the containers, we'll keep that in mind. We may still have a use case for a containerized run of this executable for co-running the exporter together with the app in question.

I'll take a crack at the PR, thank you for the comment about appveyor.yml.
