### ISSUE TITLE
Consider changing `windows_mssql_transactions_active_total` to type `gauge`

### ISSUE THREAD

**Issue by forgetaboutit** [prometheus-community/windows_exporter#634]
Disclaimer: I'm new to Prometheus, so I don't understand all the ins and outs of it. Also, I don't understand how the metrics for SQL server are collected yet.

When monitoring the `windows_mssql_transactions_active_total` metric I don't see monotonically increasing numbers as described in the [relevant part in the Prometheus docs](https://prometheus.io/docs/concepts/metric_types/#counter). This can be also seen in this screenshot:

![transactions_active_total](https://user-images.githubusercontent.com/1820589/96712472-7d6dae80-139f-11eb-9400-44dfcc7a20f6.jpg)

From that I conclude this metric should be of type `prometheus.GaugeValue` [here](https://github.com/prometheus-community/windows_exporter/blob/78918f70349b8b65c642a84c7f0ef18bc6320a26/collector/mssql.go#L3836).

**Comment by breed808** [comment]
Hi @forgetaboutit, thanks for submitting the issue. You are correct, metrics that are not monotonically increasing should be a Gauge.
This may have been introduced in the initial collector implementation in 27cc1072 or with the migration to perflib from WMI in 24470eb1. It would be interesting to see if anyone else has come across this issue.
