### ISSUE TITLE
Multiple Extra Flags 

### ISSUE THREAD

**Issue by aleksandarilic96** [prometheus-community/windows_exporter#635]
Hello,

I have been trying to add multiple extra flags to my windows exporter so I could monitor only specific services and processes.
I have tried multiple different ways to install the exporter but it failed.

Example

ENABLED_COLLECTORS="services,processes,cpu,cs,logical_disk,memory,net,os,system,tcp,textfile" TEXTFILE_DIR="C:\custom_metrics\" LISTEN_ADDR=127.0.0.1 EXTRA_FLAGS=" --collector.service.services-where ""Name LIKE 'xbg%'""" EXTRA_FLAGS=" --collector.process.processes-where=""Name LIKE 'firefo%'"""

or

ENABLED_COLLECTORS="services,processes,cpu,cs,logical_disk,memory,net,os,system,tcp,textfile" TEXTFILE_DIR="C:\custom_metrics\" LISTEN_ADDR=127.0.0.1 EXTRA_FLAGS=" --collector.service.services-where ""Name LIKE 'xbg%'"" --collector.process.processes-where=""Name LIKE 'firefo%'"""

Could you please let me know how can I pass multiple extra flags to the exporter?

Thanks and Best Regards

**Comment by carlpett** [comment]
Hey @aleksandarilic96,
The second form is the correct one (passing `EXTRA_FLAGS` once, with all flags in the same string). In what way is that failing? Are you installing directly from `cmd.exe`, or using Powershell or something else? The escaping rules will likely be different, so that might be what is going wrong.

**Comment by aleksandarilic96** [comment]
Hello @carlpett ,

I tried it via ps and cmd and in both cases, the installer is falling. I have passed the exact flags that I mentioned above.

I get the windows installer popup like this:

![image](https://user-images.githubusercontent.com/69651352/96889426-dcf2b980-1486-11eb-8596-32b0855e9853.png)

Best Regards

**Comment by carlpett** [comment]
Hm, what is the full, exact commandline invocation you are trying? That tends to pop up whenever it cannot parse the arguments at all.

**Comment by aleksandarilic96** [comment]
Here is the full command 

msiexec /i C:\windows_exporter-0.14.0-386.msi ENABLED_COLLECTORS="cpu,cs,logical_disk,memory,net,os,service,system,tcp,process" EXTRA_FLAGS=" --collector.service.services-where ""Name LIKE 'xbg%'"" --collector.process.processes-where=""Name LIKE 'firefo%'"""

**Comment by aleksandarilic96** [comment]
If any has been able to monitor for example 2 random process and service could you please share to command input?

Best Regards

**Comment by aleksandarilic96** [comment]
Hello,

I was able to find an answer for this issue.

If anyone needs this here are ps script for it.

Windows Exporter PS

$Arguments = '/quiet /i C:\Distrib\windows_exporter-0.13.0-amd64.msi ENABLED_COLLECTORS=service,process EXTRA_FLAGS="--collector.process.whitelist=""chrome.+"" --collector.service.services-where ""Name LIKE ''LRT%''"""'
Start-Process msiexec.exe -Wait -ArgumentList $Arguments

VMI Exporter PS

$Arguments = '/i C:\wmi_exporter-0.9.0-386.msi ENABLED_COLLECTORS=service,process EXTRA_FLAGS="--collector.process.processes-where=""Name LIKE ''Ever%'' or Name LIKE ''Disc%''"" --collector.service.services-where ""Name LIKE ''Xbox%'' or Name LIKE ''wuauserv%''"""'
Start-Process msiexec.exe -Wait -ArgumentList $Arguments
