### ISSUE TITLE
Support HTTP.sys Performance Counters in IIS collector

### ISSUE THREAD

**Issue by iinuwa** [prometheus-community/windows_exporter#641]
Thanks for this tool!

I noticed that some of the [HTTP.Sys performance counters](https://docs.microsoft.com/en-us/windows/win32/http/scenario-3--performance-counters) (HTTP Service, HTTP Service Request Queues, and HTTP Service Url Groups) are not collected by the IIS collector. Would it be possible to add them?

I'm not sure whether some of these have already been implemented. `windows_iis_worker_uri_cache_*` may cover the HTTP Service Counters. The specific counter I'm looking for is HTTP Service Request Queues/CurrentQueueSize.

**Comment by GhasemSystem** [comment]
How resolve it?
I need to "current queue size" value and other metric from HTTP.Sys

**Comment by carlpett** [comment]
Hi @GhasemSystem,
The fastest way would be to contribute the code. We'd be happy to review a pull request! Otherwise, it's on our radar, and we'll implement it when we have spare time to do so.

**Comment by tweshlyallpuri** [comment]
Hi Carlpett,

Do we have any plans for this request currently?

**Comment by breed808** [comment]
@tweshlyallpuri not currently. If you're able to contribute the code we'd be happy to review a pull request.

**Comment by breed808** [comment]
> we are checking if we can assign a dev to support this feature.

Do you mean one of your own developers? If so then you're more than welcome to submit a Pull Request.

**Comment by samisevenx00** [comment]
did we have any news about this request ? next release maybe ? we are waiting a lot for this feature.

**Comment by breed808** [comment]
Looking at the linked pull request it appears work on this has stalled.

You're welcome to contribute to the pull request or submit your own. Let me know if you have any queries on contributing.

I may have some time in the next couple weeks to address some of the concerns raised by Calle in the pull request, but would not be able to properly test the collector.
