### ISSUE TITLE
Collection timed out, still waiting for [process service cs os]

### ISSUE THREAD

**Issue by Johan-Lindvall-Stratsys** [prometheus-community/windows_exporter#643]
We are experiencing collection timeouts on some our our production machines. With debug logging enabled, the following can be seen:

```
Oct 29, 2020 @ 11:40:44.000 collector service succeeded after 14.101019s.
Oct 29, 2020 @ 11:40:44.000 collector cs succeeded after 14.101019s.
Oct 29, 2020 @ 11:40:44.000 collector process succeeded after 14.211092s.
Oct 29, 2020 @ 11:40:43.000 collector os succeeded after 13.919888s.
Oct 29, 2020 @ 11:40:39.000 Collection timed out, still waiting for [process service cs os]
Oct 29, 2020 @ 11:40:29.000 Generated WMI query SELECT * FROM Win32_OperatingSystem
Oct 29, 2020 @ 11:40:29.000 Generated WMI query SELECT * FROM Win32_Service
Oct 29, 2020 @ 11:40:29.000 collector system succeeded after 0.000000s.
Oct 29, 2020 @ 11:40:29.000 collector textfile succeeded after 0.000000s.
Oct 29, 2020 @ 11:40:29.000 Generated WMI query SELECT * FROM Win32_ComputerSystem
Oct 29, 2020 @ 11:40:29.000 collector net succeeded after 0.000985s.
Oct 29, 2020 @ 11:40:29.000 collector logical_disk succeeded after 0.000985s.
Oct 29, 2020 @ 11:40:29.000 collector cpu succeeded after 0.002985s.
Oct 29, 2020 @ 11:40:29.000 Generated WMI query SELECT * FROM WorkerProcess
```

Is this a problem with our configuration or the windows_exporter service itself?

**Comment by lukeg87** [comment]
I've seen similar issues in our environment on webserver boxes where iis collector was enabled, the exporter was also crashing and we were being alerted for boxes going down when in fact they were up. I didn't perform any debugging but the problems disappeared after rebooting the nodes.

These boxes had an older version of the exporter which was uninstalled before but we didn't reboot after installing 0.14.0

**Comment by Johan-Lindvall-Stratsys** [comment]
The timeouts happen on a machine running Windows Server 2012 R2. There are about 180 processes running on the server. We are using the latest 64bit version of windows_exporter (0.14.0). The server had been rebooted two days before the timeouts started.

**Comment by lukeg87** [comment]
Checked the boxes again, these are all w2012r2 too... i am still seeing timeouts for various collectors. Mostly iis and service, they're just less prevalent then before rebooting. I am not collecting process on these atm.

**Comment by carlpett** [comment]
Hey @Johan-Lindvall-Stratsys,
The exporter seems to be working "as intended", in the meaning that it gives up on slow queries (default timeout is 10 seconds, you can see the slow collectors finishing after 14s). The WMI subsystem shouldn't be that slow under normal circumstances, though, so something seems to be degraded on your machines. Are you seeing very high load on these machines?

**Comment by Johan-Lindvall-Stratsys** [comment]
The machine has a low overall CPU usage (5-10%). Data is collected very 15 seconds and there are about 80-100 w3wp instances (with separate application pools) running on the server.

We have been experimenting with a WMI-less implementation of the process collector and things haven been running smooth since we switched to the new implementation. Shall I open a PR?

**Comment by carlpett** [comment]
That sounds very interesting and we'd love a PR! I'm a bit confused if we are talking about the same thing, however - the process collector was switched to use perflib rather than WMI in version 0.14?

**Comment by Johan-Lindvall-Stratsys** [comment]
It still uses WMI to collect application pool names (https://github.com/prometheus-community/windows_exporter/blob/master/collector/process.go#L189) and I believe this is the reason for the slow responses.

**Comment by carlpett** [comment]
Ah, I'd forgotten about that detail, good catch! Great if you have a fix, a PR would be amazing :)

**Comment by JohanLindvall** [comment]
Opened a PR with my personal account: https://github.com/prometheus-community/windows_exporter/pull/649
