### ISSUE TITLE
No config present

### ISSUE THREAD

**Issue by fischerman** [prometheus-community/windows_exporter#647]
The Windows exporter fails to start when no config file is present.

```
C:\Users\Administrator\go\src\github.com\prometheus-community\windows_exporter>.\windows_exporter.exe
time="2020-11-02T14:30:02+01:00" level=info msg="Loading configuration file: C:\\Program Files\\windows_exporter\\config.yml" source="config.go:37"
time="2020-11-02T14:30:02+01:00" level=fatal msg="could not load config file: CreateFile C:\\Program Files\\windows_exporter\\config.yml: The system cannot find the path specified.\n" source="exporter.go:316"
```

According to docs this should work.

Version: master (https://github.com/prometheus-community/windows_exporter/commit/f623c0ed89903413c6fd7cc8ab2d447f3d20ea36)

/cc @breed808

**Comment by carlpett** [comment]
Thanks for testing the master builds @fischerman!
@breed808 I'm tempted to suggest we shouldn't have a default value for the flag. It makes it much clearer how to handle missing files. Currently we'd have to call it an error if the file is missing _unless_ it's in the install directory, in which case we should silently ignore it?

**Comment by breed808** [comment]
The original intention was to set the default config file location, but _not_ fail to start if any configuration file is missing.
I'll fix this when I'm free later today.
