### ISSUE TITLE
cpu collector dose not support fetching cup temperature metrics

### ISSUE THREAD

**Issue by zhongxinlei** [prometheus-community/windows_exporter#650]
I was using windows exporter to collect monitoring data to find out that it dose not support collecting cup temperature information. Since cpu temperature is an important element to evaluate and monitor the system, and some other exporters(like node_exporter) already included this feature to collect cpu temperature, it might be nice and necessary for windows exporter to also have this feature?

**Comment by carlpett** [comment]
Hi @zhongxinlei,
We expose temperature (on supported hardware, not every machine exposes it to Windows in a way such that we can read it) via the `thermalzone` collector.
