### ISSUE TITLE
config file is not used

### ISSUE THREAD

**Issue by omeyer99** [prometheus-community/windows_exporter#652]
Hello,
I am very new to Prometheus and should only evaluate the distribution of the Windows node export using Salt. I read that you can create a config.yml which allows you to set the port and stuff like that. 
Problem: It seems that the config.yml is not read because I have defined that port 5000 should be used but the metric data can only be read via the default port (9182).

I used the following template and only changed the port (for testing): https://github.com/prometheus-community/windows_exporter/blob/master/docs/example_config.yml

The yml file is located here: %ProgramFiles%/windows_exporter/config.yml

**Comment by breed808** [comment]
Hi omeyer99, thanks for submitting the issue. There's a couple existing issues with the configuration file at the moment which I'm working to resolve.
I'll have a look at the `telemetry.addr` value in the config file and get back to you.

**Comment by breed808** [comment]
@omeyer99 in the meantime, can you confirm the exporter is listening on the correct port? Use `netstat -anp tcp | sls LISTENING` to get a list of listening TCP ports. You should see a line with your desired port there, or the default port (9182) if the config file hasn't been applied.

If the port is correct, confirm the port is open on the firewall.

**Comment by omeyer99** [comment]
It only listens on port 9182 (Default), that means the Config was not applied.

**Comment by carlpett** [comment]
Just to double-check - are you using a custom build from master, or the latest release (0.14)? 0.14 does not have the config code in it.

**Comment by omeyer99** [comment]
I am using v0.14 (latest), is that the reason why config files are not used?
If so, when can I expect the implementation?

And sorry for the circumstances :)

**Comment by carlpett** [comment]
Yes, that is the reason. We just merged the config support yesterday, and will create a release shortly, we just need to iron out the last bugs.
I'll close this for now, and encourage you to test again with 0.15 when it is released :)
