### ISSUE TITLE
How can check IIS Server status ?

### ISSUE THREAD

**Issue by se7en102** [prometheus-community/windows_exporter#654]
Dear everyone, 
https://community.spiceworks.com/topic/2036533-how-to-monitor-a-smtp-virtual-server-in-iis-6-0
I have question like this friend. 
How can I have metrics about status of IIS server. So i will get alert if it stopping and restart service again.

**Comment by breed808** [comment]
We don't currently provide any metrics for the IIS SMTP server, but there is a perfraw WMI class available: [Win32_PerfRawData_SMTPSVC_SMTPServer](https://docs.microsoft.com/en-us/previous-versions/aa394334(v=vs.85)).
I'll have a look to see if this could be implemented with perflib.

**Comment by carlpett** [comment]
Hi @se7en102,
Just to clarify, since I think there are many ways to read your message - are you asking for metrics on the IIS SMTP server, or asking for metrics on whether the general IIS service (ie websites, applications and possibly smtp) is running?
