### ISSUE TITLE
Time collector fails on Windows Server 2012R2

### ISSUE THREAD

**Issue by davideverall** [prometheus-community/windows_exporter#658]
Getting errors when enabling the [time collector](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.time.md) on v0.15.0 

Windows application event errors every 30 seconds:

- Event 102 - collector time failed after 0.000000s: counter not found

and

- Event 102 - failed collecting time metrics:<nil> counter not found

### Testing 

- Errors are repeatable on Windows Server 2012R2 virtual machines
- Errors do not occur on Windows 10 or Windows Server 2016

**Comment by breed808** [comment]
Assuming the Windows Time service is running, is the startup type of the service "Automatic"?
Does the command `Get-Counter -listset 'Windows Time Service'` return any data?

**Comment by davideverall** [comment]
Thanks for the reply

The time service is running, however is set to manual (triggered)

command `Get-Counter -listset 'Windows Time Service'` returns: 

`Cannot find any performance counter sets on the localhost computer that match the following: Windows Time Service`

**Comment by breed808** [comment]
Can you set the service start type to "Automatic" and reboot the host? I recall coming across this with my testing VM while writing the collector, and changing the start type appeared to resolve the issue.

If this is the case, I'll need to update the documentation for this collector.

**Comment by davideverall** [comment]
I’m afraid changing the start type didn’t resolve the error.

Is there any other information I could provide to help you troubleshoot?

**Comment by breed808** [comment]
Are the Windows Time Service counters present in the Performance Monitor?
![perf_monitor](https://user-images.githubusercontent.com/3103817/99872079-ec525780-2c2a-11eb-8dbc-666c99cc8e11.png)

**Comment by davideverall** [comment]
The counters are not present.

I don't believe they are included prior to Server 2016 

[windows-server-2016-improvements](https://docs.microsoft.com/en-us/windows-server/networking/windows-time-service/windows-server-2016-improvements)

**Comment by breed808** [comment]
That's a shame. Thanks for letting me know, I'll update the documentation for the collector.
