### ISSUE TITLE
Windows App Process 

### ISSUE THREAD

**Issue by aleksandarilic96** [prometheus-community/windows_exporter#662]
Hello,

Quick question is there a way to follow if the application is running by process collector.

If the whitelisted process has stoped will he not be seen anymore in monitoring or will its value be 0 or is there some other way to monitor app processes?

Best Regards

**Comment by carlpett** [comment]
He @aleksandarilic96,
If the process is not running, it will not have exposed metrics. One way to detect this, eg for alerting, is to use the `absent` function in Prometheus. So you could do something like `absent(windows_process_start_time{process="my-process", ...more labes...}) == 1`.

**Comment by aleksandarilic96** [comment]
Exactly what I was looking for.

Thanks a lot for the help.

Best Regards

**Comment by ktpktr0** [comment]
@carlpett 
Use  absent(windows_process_start_time{process="my-process", ...more labes...}) == 1  to get whether the process is running or not. However, when multiple processes with the same name are running, how to turn off one of them
