### ISSUE TITLE
Performance monitor

### ISSUE THREAD

**Issue by GhasemSystem** [prometheus-community/windows_exporter#663]
Hello
How can i fetch counters from windows performance monitor tool via prometheus windows_exporter
In elasticsearch metricbeat exist one module specific for this needed(module windows, metricset perfmon)

**Comment by carlpett** [comment]
Hi @GhasemSystem,
I don't understand the question, could you clarify?

**Comment by GhasemSystem** [comment]
Hi @carlpett 
please read below page (metricset perfmon)
https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-windows.html

**Comment by carlpett** [comment]
We do not support adding arbitrary counters at runtime. Our experience with the underlying data is that it would generally produce metrics which are not a great fit for Prometheus systems, and that the rather low complexity of implementing new collectors make this a reasonable tradeoff.
