### ISSUE TITLE
0.15.0-386.msi install failed on Windows Server 2008 R2 SP1

### ISSUE THREAD

**Issue by xflu** [prometheus-community/windows_exporter#665]
I run 0.15.0-386.msi on Windows Server 2008 R2 SP1, after a few minutes, a message pops up saying:
> Service 'windows_exporter' failed to start. Verify that you have sufficient privileges to start system services.

![error info](https://user-images.githubusercontent.com/3182214/100053170-70d6ed00-2e5a-11eb-8035-f2937760cfb4.png)

The last few installation logs:

> MSI (s) (90:D8) [18:37:14:378]: Executing op: FileCopy(SourceName=xgf6mqi1.exe|windows_exporter.exe,SourceCabKey=windows_exporter.exe,DestName=windows_exporter.exe,Attributes=512,FileSize=13654016,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,Version=0.15.0.0,Language=0,InstallMode=58982400,,,,,,,)
> MSI (s) (90:D8) [18:37:14:379]: File: C:\Program Files (x86)\windows_exporter\windows_exporter.exe;	To be installed;	Won't patch;	No existing file
> MSI (s) (90:D8) [18:37:14:379]: Source for file 'windows_exporter.exe' is compressed
> MSI (s) (90:D8) [18:37:14:483]: Executing op: CacheSizeFlush(,)
> MSI (s) (90:D8) [18:37:14:483]: Executing op: ActionStart(Name=WixRollbackFirewallExceptionsInstall,Description=Rolling back Windows Firewall configuration,)
> MSI (s) (90:D8) [18:37:14:485]: Executing op: CustomActionSchedule(Action=WixRollbackFirewallExceptionsInstall,ActionType=3329,Source=BinaryData,Target=ExecFirewallExceptions,CustomActionData=1windows_exporter (HTTP 9182)214748364712C:\Program Files (x86)\windows_exporter\windows_exporter.exe91826windows_exporter HTTP endpoint)
> MSI (s) (90:D8) [18:37:14:485]: Executing op: ActionStart(Name=WixExecFirewallExceptionsInstall,Description=Installing Windows Firewall configuration,)
> MSI (s) (90:D8) [18:37:14:486]: Executing op: CustomActionSchedule(Action=WixExecFirewallExceptionsInstall,ActionType=3073,Source=BinaryData,Target=ExecFirewallExceptions,CustomActionData=1windows_exporter (HTTP 9182)214748364712C:\Program Files (x86)\windows_exporter\windows_exporter.exe91826windows_exporter HTTP endpoint)
> MSI (s) (90:80) [18:37:14:490]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI3896.tmp, Entrypoint: ExecFirewallExceptions
> MSI (s) (90:28) [18:37:14:490]: Generating random cookie.
> MSI (s) (90:28) [18:37:14:493]: Created Custom Action Server with PID 6700 (0x1A2C).
> MSI (s) (90:A8) [18:37:14:539]: Running as a service.
> MSI (s) (90:A8) [18:37:14:540]: Hello, I'm your 32bit Elevated Non-remapped custom action server.
> ExecFirewallExceptions:  Installing firewall exception2 windows_exporter (HTTP 9182) (C:\Program Files (x86)\windows_exporter\windows_exporter.exe)
> MSI (s) (90:D8) [18:37:14:618]: Executing op: ActionStart(Name=WriteRegistryValues,Description=Writing system registry values,Template=Key: [1], Name: [2], Value: [3])
> MSI (s) (90:D8) [18:37:14:618]: Executing op: ProgressTotal(Total=1,Type=1,ByteEquivalent=13200)
> MSI (s) (90:D8) [18:37:14:619]: Executing op: RegOpenKey(Root=-2147483646,Key=SYSTEM\CurrentControlSet\Services\EventLog\Application\windows_exporter,,BinaryType=0,,)
> MSI (s) (90:D8) [18:37:14:619]: Executing op: RegAddValue(Name=EventMessageFile,Value=#%%SystemRoot%\System32\EventCreate.exe,)
> MSI (s) (90:D8) [18:37:14:620]: Executing op: ActionStart(Name=InstallServices,Description=Installing new services,Template=Service: [2])
> MSI (s) (90:D8) [18:37:14:620]: Executing op: ProgressTotal(Total=1,Type=1,ByteEquivalent=1300000)
> MSI (s) (90:D8) [18:37:14:620]: Executing op: ServiceInstall(Name=windows_exporter,DisplayName=windows_exporter,ImagePath="C:\Program Files (x86)\windows_exporter\windows_exporter.exe" --log.format logger:eventlog?name=windows_exporter  --telemetry.addr :9182   ,ServiceType=16,StartType=2,ErrorControl=1,,Dependencies=wmiApSrv[~][~][~],,,Password=**********,Description=Exports Prometheus metrics about the system,,)
> MSI (s) (90:D8) [18:37:14:677]: Executing op: ActionStart(Name=RollbackServiceConfig,,)
> MSI (s) (90:D8) [18:37:14:678]: Executing op: CustomActionSchedule(Action=RollbackServiceConfig,ActionType=3329,Source=BinaryData,Target=RollbackServiceConfig,CustomActionData=SchedServiceConfig)
> MSI (s) (90:D8) [18:37:14:679]: Executing op: ActionStart(Name=ExecServiceConfig,,)
> MSI (s) (90:D8) [18:37:14:679]: Executing op: CustomActionSchedule(Action=ExecServiceConfig,ActionType=3073,Source=BinaryData,Target=ExecServiceConfig,CustomActionData=SchedServiceConfigwindows_exporter1restartrestartrestart060)
> MSI (s) (90:58) [18:37:14:683]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI3953.tmp, Entrypoint: ExecServiceConfig
> MSI (s) (90:D8) [18:37:14:766]: Executing op: ActionStart(Name=StartServices,Description=Starting services,Template=Service: [1])
> MSI (s) (90:D8) [18:37:14:767]: Executing op: ProgressTotal(Total=1,Type=1,ByteEquivalent=1300000)
> MSI (s) (90:D8) [18:37:14:767]: Executing op: ServiceControl(,Name=windows_exporter,Action=1,,)
> MSI (c) (5C:FC) [18:41:15:438]: Font created.  Charset: Req=0, Ret=0, Font: Req=, Ret=Arial
> 
> Error 1920. Service 'windows_exporter' (windows_exporter) failed to start.  Verify that you have sufficient privileges to start system services.
> MSI (s) (90:90) [11:43:42:183]: I/O on thread 13628 could not be cancelled. Error: 1168
> MSI (s) (90:90) [11:43:42:183]: I/O on thread 10480 could not be cancelled. Error: 1168
> MSI (s) (90:90) [11:43:42:183]: I/O on thread 3928 could not be cancelled. Error: 1168
> MSI (s) (90:90) [11:43:42:184]: I/O on thread 11480 could not be cancelled. Error: 1168
> MSI (s) (90:90) [11:43:42:184]: I/O on thread 16936 could not be cancelled. Error: 1168
> MSI (s) (90:90) [11:43:42:184]: I/O on thread 9740 could not be cancelled. Error: 1168
> MSI (s) (90:90) [11:43:42:184]: I/O on thread 13448 could not be cancelled. Error: 1168
> MSI (s) (90:D8) [11:43:42:203]: Product: windows_exporter -- Error 1920. Service 'windows_exporter' (windows_exporter) failed to start.  Verify that you have sufficient privileges to start system services.
> 
> MSI (c) (5C:FC) [11:43:42:206]: Font created.  Charset: Req=0, Ret=0, Font: Req=, Ret=Arial
> 
> Are you sure you want to cancel?
> MSI (c) (5C:FC) [11:43:46:372]: Font created.  Charset: Req=0, Ret=0, Font: Req=, Ret=Arial
> 
> Error 1920. Service 'windows_exporter' (windows_exporter) failed to start.  Verify that you have sufficient privileges to start system services.
> MSI (s) (90:D8) [12:17:11:189]: Product: windows_exporter -- Error 1920. Service 'windows_exporter' (windows_exporter) failed to start.  Verify that you have sufficient privileges to start system services.
> 
> MSI (c) (5C:FC) [12:21:11:891]: Font created.  Charset: Req=0, Ret=0, Font: Req=, Ret=Arial

**Comment by PierreNa** [comment]
Hello,
I past the amd64 on 2008 R2 but i do the all framework update before the install.
Juste try the update and retry the install. Maybe with the amd64...

**Comment by carlpett** [comment]
Hi @PierreNa,
Any particular reason you tried to install the 32-bit version on a 64-bit Windows system? The 32-bit installer is supplied as a compatibility effort, but unless you have specific needs, you should use the 64-bit version.
I'm not sure how to interpret your second comment, did it work when you switched to 64-bit?

**Comment by PierreNa** [comment]
Hi @carlpett i install the 64-bit version on all 2008R2 Windows server and i have 10 2008R2 on my infrastructure.
So i think is better to install this.
If you a problem with the install like you @xflu it's maybe you're argument with you're installation.
For me i do that : 
`C>windows_exporter-0.15.0-amd64.msi ENABLED_COLLECTORS="cpu,cs,logical_disk,memory,net,os,service,system,process" EXTRA_FLAGS="--collector.service.services-where ""(StartMode = 'Auto' AND State != 'Running') OR (name='AVP') OR (name='spooler') OR (name='W3SVC')"" --collector.process.whitelist=""w3wp"""`

**Comment by prab2014** [comment]
Am facing the same issue.  I am using below system and wmi 16 ( fresh installation)
OS- MS window server 2016
version 10.0.14393
window exporter version -windows_exporter-0.16.0-amd64.msi
note: am having admin privileges' here.
error 

![image](https://user-images.githubusercontent.com/67781436/115849280-5cffd900-a442-11eb-8d45-9702fd92244e.png)
