### ISSUE TITLE
process_resident_memory_bytes absent from metrics

### ISSUE THREAD

**Issue by skpenpen** [prometheus-community/windows_exporter#668]
I was trying to monitor memory used by exporters (https://www.robustperception.io/analysing-prometheus-memory-usage) and i found out that the metric "process_resident_memory_bytes" is absent from the exporter.

It is normally a go_client standard metric (https://github.com/prometheus/client_golang/blob/master/prometheus/process_collector.go#L101), why it is absent from windows_exporter ?
And how to monitor ram used by the exporter at the moment since "go_memstats_alloc_bytes" is not the real memory used by the system for that process.

**Comment by breed808** [comment]
Hi @skpenpen, thanks for raising this. It appears that this is due to the older client library that is currently in use (v0.9.2).
I'll raise a PR to update this to the current version (v1.8.0).
