### ISSUE TITLE
Fail windows7 - needed restart service

### ISSUE THREAD

**Issue by berekese** [prometheus-community/windows_exporter#670]
Hi, I have installed 0.14 in Windows7 but each some days (2-3) i have to restart service wmi_exporter because program doesn't show metrics. What could I do? This bug is fixed 0.15?
Should I install another version?

Thanks.

**Comment by breed808** [comment]
Hi @berekese, are you able to provide some more detail on your issue?
Is the `windows_exporter` service failing in some manner? Is the service active but not responding to HTTP requests?

**Comment by berekese** [comment]
Hi, i have news. Service doesn't start automatically when I start my Windows7.
I have installed 0.15 in Windows7 and its fixed I think (i have to do some test)  if its ok in Windows7 or I find any bug.

In Windows10 0.14 works fine. 

Thanks.
