### ISSUE TITLE
WMI perf

### ISSUE THREAD

**Issue by rismoney** [prometheus-community/windows_exporter#674]
Would adding these flags help reduce overhead?

https://docs.microsoft.com/en-us/windows/win32/wmisdk/improving-enumeration-performance

**Comment by carlpett** [comment]
Hi @rismoney,
I can't find the thread at the moment, but we tried this out a year or two ago. Sadly, it didn't show any benefit performance-wise, and also caused some issues in the libraries we used that weren't trivial to resolve.
