### ISSUE TITLE
1s resolution

### ISSUE THREAD

**Issue by rismoney** [prometheus-community/windows_exporter#675]
Is there a way I could achieve 1s resolutions using 15 second scraping?  Like can there be a local caching of data to provide to the scrape or somehow use ETW to do this?  Interested in how one might go about getting closer to enterprise wide tracing type levels of metrics, without overwhelming network.

**Comment by breed808** [comment]
This has [been discussed before](https://github.com/prometheus-community/windows_exporter/issues/270#issuecomment-439482709) in the context of the `windows_exporter`.
[Prometheus best practice](https://prometheus.io/docs/instrumenting/writing_exporters/#scheduling) is to cache only particularly expensive metrics:

>If a metric is particularly expensive to retrieve, i.e. takes more than a minute, it is acceptable to cache it. This should be noted in the HELP string.

**Comment by rismoney** [comment]
I appreciate the answer!    What I am trying to determine is, if I seek to get 1-5s level granularity of metrics, on 1000 servers, is the prometheus approach still valid for server monitoring?  It seems awfully expensive to scrape at that level.  I would think that having the ability to scrape less often but still get that resolution would be a valid use case.   My belief is that this exporter now has some of the best methodologies for querying the data of any of the system metric grabbers (api vs pdh, wmi, etc).   

It sort of feels more efficient to scrape 1x a minute, but retrieve 12 cpu samples.  Am I off base?  On 1000 servers, I feel 12000 scrapes a minute feels heavy handed.

My use case for this level of granularity are realtime financial trading platforms, where the interesting information can occur between smaller intervals.

**Comment by breed808** [comment]
> if I seek to get 1-5s level granularity of metrics, on 1000 servers, is the prometheus approach still valid for server monitoring?

I would say yes, but it is highly dependent on the exporters and collectors in use. WMI collectors in the `windows_exporter` may not return data under 1-5sec.

Counter metrics are more helpful in these cases, as you don't need to worry about missing particular readings as with Gauges. However, the more frequently you scrape the more accurate your metrics will be.

It may be worth to check in with the Prometheus developers for questions/support on your requirements.

**Comment by rismoney** [comment]
I get that.   Lets assume the expense per scrape is cheap and can be completed before subsequent scrape.  If I scrape 12 x a minute or 6 x a minute, the expense per poll is the same.   And the impact to the server is the same, just more frequent.  But it is wildly inefficient.

What I am saying is, that I believe it is a valid use case to be able to collect locally for n seconds, and scrape at m intervals.   The difference is in the http requests flying across a network by orders of magnitude.  Am I missing something?

**Comment by breed808** [comment]
> The difference is in the http requests flying across a network by orders of magnitude. Am I missing something?

I see where you're coming from. Increasing the scrape frequency will result in a larger number of HTTP requests in flight, especially with more hosts being monitored.
Prometheus can handle a large number of HTTP connections, so I don't expect an increase in the scrape frequency to cause issues with the number of active HTTP connections.

> What I am saying is, that I believe it is a valid use case to be able to collect locally for n seconds, and scrape at m intervals.

`windows_exporter` has been written with synchronous scraping in mind, so you wouldn't be able to use the exporter to cache metrics. A custom script that utilizes the [Pushgateway](https://prometheus.io/docs/instrumenting/pushing/) might be an easier way to implement this.
