### ISSUE TITLE
problem in some collectors when i run windows_exporter

### ISSUE THREAD

**Issue by GhasemSystem** [prometheus-community/windows_exporter#676]
Hi, this below text define my problem. please help me

#####When run windows exporter, it return invalid class!#####
-----------------------------------
C:\Program Files\windows_exporter>windows_exporter.exe --collectors.enabled="cs" --log.level="debug"
time="2020-12-08T12:21:02+03:30" level=debug msg="Initializing SWbemServices" source="exporter.go:262"
time="2020-12-08T12:21:02+03:30" level=info msg="Enabled collectors: cs" source="exporter.go:360"
time="2020-12-08T12:21:02+03:30" level=info msg="Starting windows_exporter (version=0.15.0, branch=master, revision=cdbb27d0b4ea9810dc35035fad281fe6468b7dd1)" source="exporter.go:412"
time="2020-12-08T12:21:02+03:30" level=info msg="Build context (go=go1.15.3, user=appveyor-vm\\appveyor@appveyor-vm, date=20201107-08:23:37)" source="exporter.go:413"
time="2020-12-08T12:21:02+03:30" level=info msg="Starting server on :9182" source="exporter.go:416"
time="2020-12-08T12:21:35+03:30" level=debug msg="Generated WMI query SELECT * FROM Win32_ComputerSystem" source="wmi.go:24"
time="2020-12-08T12:21:35+03:30" level=error msg="failed collecting cs metrics:<nil> Exception occurred. (Invalid class )" source="cs.go:57"
time="2020-12-08T12:21:35+03:30" level=error msg="collector cs failed after 0.016018s: Exception occurred. (Invalid class )" source="exporter.go:220"

#####When run query in powershell, it return correct response#####
--------------------------------------
PS C:\Users\****> get-wmiobject -query "SELECT * FROM Win32_ComputerSystem"
Domain              : ******
Manufacturer        : HP
Model               : ProLiant DL580 Gen9
Name                : ******
PrimaryOwnerName    : 
TotalPhysicalMemory : 1099378061312

P.S: some collectors is correct for example "CPU" and some collectors have problem for example "CS, IIS"

**Comment by GhasemSystem** [comment]
no idea? :(

**Comment by carlpett** [comment]
Well, no, not really, I'm afraid. What version of Windows is this on?
I haven't seen this - that the query works in Powershell but not in the exporter - before. Usually when there are WMI issues, we recommend rebuilding the performance counters. There's some instructions [here](https://github.com/prometheus-community/windows_exporter/issues/379#issuecomment-519879534) from another user that you can try.

**Comment by GhasemSystem** [comment]
Win server 2016 Standard; Build 14393.3986

yes i check this instruction before, but my problem not solved!
