### ISSUE TITLE
Windows 10 scrape duration with Service collector

### ISSUE THREAD

**Issue by davideverall** [prometheus-community/windows_exporter#678]
When the [service collector](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.service.md) is enabled on Windows 10 machines, it causes a high scrape duration to Prometheus.

#### Example on one of our Windows 10 VMs

- scrape time without service collector enabled = 200ms
- with service collector enabled = 2 seconds

I have tried to isolate the issue by running `--collector.service.services-where="Name='windows_exporter'"` to specify only a single service, however the scrape duration remains at 2 seconds.

We are not seeing the same behaviour on Windows 2012R2/2016 servers.

**Comment by carlpett** [comment]
Sadly, there's a noticable overhead to making WMI queries, regardless of whether they produce any results. 
Try running `measure-command { get-wmiobject -query "SELECT * FROM Win32_Service WHERE Name = 'no-such-service'" }` in Powershell. On a Win 10 machine I have available, while I don't see as much as 2 seconds, that measurement matches what I get in the exporter collector_duration.

**Comment by davideverall** [comment]
Thanks for the explanation.

The machine in question does take 2 seconds to run the WMI query so not much else we can do regarding this issue.

**Comment by retryW** [comment]
The two below Windows API functions can retrieve most of the required information to replace WMI in the service collector:
https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-queryservicestatus
https://docs.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-queryserviceconfiga

Would just need to find a way to get the remaining metrics as there's no point replacing any if WMI is being called at all, as it's still only the one WMI query currently.

```
type Win32_Service struct {
	DisplayName string  // = lpDisplayName
	Name        string
	ProcessId   uint32  // = dwProcessId
	State       string  // = dwCurrentState
	Status      string
	StartMode   string  // = dwStartType
	StartName   *string // = lpServiceStartName
}
```
