### ISSUE TITLE
Collection timed out, still waiting for

### ISSUE THREAD

**Issue by Monolithys** [prometheus-community/windows_exporter#683]
Hello! I see some same issues , but can't understand why it is happens, and most of all how decided it.
I using it on OS Windows 2012 R2 Standart, with not so bad hardware Xeon E31230 with 8gb RAM
Running WE as service 
`"C:\Program Files\windows_exporter\windows_exporter.exe" --collectors.enabled cpu,cs,iis,logical_disk,logon,memory,os,net,service,system,tcp --collector.service.services-where "Name='windows_exporter'"`

Before try as APP and have same problems: 
every 16 minutes some of collector do not answer for 3 min. And it is happens all times, as it was be scheduled

I was received this errors:
```
time="2020-12-16T22:22:42+03:00" level=warning msg="Collection timed out, still waiting for [cs os service iis]" source="exporter.go:202"
time="2020-12-16T22:22:50+03:00" level=warning msg="Collection timed out, still waiting for [logon iis os service cs]" source="exporter.go:202"
```
Other collector still working. But in this moment (for 3 min) "WMI Provider Host" consumed 13-14% of CPU
Logs does not show anything (i mean no errors)
I understand it may be my problem, but hope you can help me with this problem

**Comment by Monolithys** [comment]
As i understand i must set something like this on Prometheus server
```
  - job_name: 'windows_exporter'
    scrape_interval:   30s
    static_configs:
    - targets: ['s2:9182']
```
Srange, standard  scrape_interval:  sets to 15s

Or i must used 60 seconds?

**Comment by E1v1s** [comment]
The same issue on a different servers 
cpu load is low
trying to increase --scrape.timeout-margin but without results
and try to change policy of startup of wii performance adapter

**Comment by Monolithys** [comment]
I try it too, nothing changes. Try to get help from team.

**Comment by E1v1s** [comment]
We are solve problem by increasing scrape time in prometheus from 2s to 5
It's unclear for me but its work stable for 2 days now.

**Comment by Monolithys** [comment]
@E1v1s 
Hi!
May be I did not understand clear, but I try to set 
`scrape_interval:   60s`
But this did not helped any

If it is not difficult - show part from you config at Prometheus

**Comment by E1v1s** [comment]
```
  endpoints:
  - interval: 10s
    port: metrics
    scrapeTimeout: 5s
```

it's a part of config from prometheus in k8s

**Comment by Monolithys** [comment]
For me it does not helped. Some work normally, and some came with stable delay 
![image](https://user-images.githubusercontent.com/32746979/104886423-c7543980-597a-11eb-8e99-06afc1a50aae.png)

**Comment by caugner** [comment]
Same issue here, on a server with Windows Server 2016 and 16 x 2,10 GHz.

**Comment by carlpett** [comment]
This is likely a duplicate of #89. Short version (it's a long thread) is that there is a bug/limit in Windows that causes these regular latency spikes, which are under some circumstances exaggerated.
One such circumstance reported is having mounted ISO files through iDRAC. 

Unfortunately, this being a Windows bug, there's not much we can do aside from progressively replacing WMI.

**Comment by mmahmoudi-lab** [comment]
Same issue on WS 2016 only for iis collector

**Comment by Mario-Hofstaetter** [comment]
@carlpett I am currently hitting (once again) this issue:

```text
Collection timed out, still waiting for [service process]
```

I don't even need prometheus to scrape, opening <http://localhost:9182/metrics> in the browser shows the process and service metrics are missing.

There is a whole load of issues on this topic.. Is there a configureable timeout for the collector?

`timeout-margin` does not sound helpful: https://github.com/prometheus-community/windows_exporter/blob/6ba0297aa98bb4ba8964da99e7627deb9265b1e6/docs/example_config.yml#L13 

as per README:
> Seconds to subtract from the timeout allowed by the client. Tune to allow for overhead or high loads.

Couldn't find anything else?

**Comment by breed808** [comment]
Default timeout is 10 seconds, which can be changed by setting the Prometheus `scrape_timeout` setting.

`maxScrapeDuration` is a red herring here, it's used by the exporter to respect the scrape timeout sent by Prometheus (via the `X-Prometheus-Scrape-Timeout-Seconds` header).
