### ISSUE TITLE
unable to connect from a linux server ? metrics">Moved Permanently

### ISSUE THREAD

**Issue by SmartTransp** [prometheus-community/windows_exporter#684]
I have a grafana server that work with 2 linux without any problem 
I have try to add Windows server 2012 R2 
I have install and can see the service running 
when I open from my computer and also from the windwos 2012 server itself  with chrome I can see the metrixs
`http://10.129.94.2:9182/metrics`
`http://localhost:9182/metrics`
```
# HELP go_gc_duration_seconds A summary of the GC invocation durations.
# TYPE go_gc_duration_seconds summary
go_gc_duration_seconds{quantile="0"} 0
go_gc_duration_seconds{quantile="0.25"} 0
go_gc_duration_seconds{quantile="0.5"} 0
go_gc_duration_seconds{quantile="0.75"} 0.0023316
go_gc_duration_seconds{quantile="1"} 0.0149896
go_gc_duration_seconds_sum 0.127961
go_gc_duration_seconds_count 52
```

I have added the windows server to the prometheus.yml in my grafana server 
```
 - job_name: 'Server 2012'
    static_configs:
    - targets: ['10.129.94.2:9182']
```

but I can't see it 

also when I try to use curl 
I get this respone:
```
curl http://10.129.94.2:9182
<a href="/metrics">Moved Permanently</a>.
```
what is wrong and missing ? 

also where is the config file ? I can't find it 

Thanks ,

**Comment by Mario-Hofstaetter** [comment]
Your HTTP `Moved Permanently` looks like a networking issue (firewall, proxy, ... ?)

What version of windows_exporter are you running?
If I curl my windows machine (without `/metrics` route) I get an info homepage:

```
root@raspberry:/# curl 10.0.0.1:9182
<html>
<head><title>windows_exporter</title></head>
<body>
<h1>windows_exporter</h1>
<p><a href="/metrics">Metrics</a></p>
<p><i>(version=0.13.0, branch=master, revision=c62fe4477fb5072e569abb44144b77f1c6154016)</i></p>
</body>
</html>
```

**Comment by SmartTransp** [comment]
I thought so also ,
but no firewall on the 2012-server-R2(10.129.94.2)
I don't use any proxy on the network at all.

if I use from another comuter (my computer ) and enter 
http://10.129.94.2:9182/
I get a replay and see the webpage -
if there was a problem with the firewall or something , wouldn't see nothing , no ? 

also 
I don't put metrix 
just use this from the linux server
`[root@grafana-server ~]# curl http://10.129.94.2:9182
<a href="/metrics">Moved Permanently</a>.
`
if there was a problem - I woudn't get anything. 
I have download the latest version from here (a few hours ago )

**Comment by Mario-Hofstaetter** [comment]
What is the output if you do
```
curl http://10.129.94.2:9182/metrics
```
? That's the important url after all.
Also what is the state of your target in `http://<yourprometheusserver>:9090/targets` ?

If you check `http://localhost:9182/metrics` what are the label values of `windows_exporter_build_info` ?

**Comment by SmartTransp** [comment]
Yes - this one is working 
curl http://10.129.94.2:9182/metrics 
I get the all data 

my grafana\prometheus server is 10.129.250.100 
and it's online because I have 2 other server that talk to him (I can see the data)


and such data in http://localhost:9182/metrics
