### ISSUE TITLE
windows_cpu_core_frequency_mhz only showing base speed

### ISSUE THREAD

**Issue by philipsabri** [prometheus-community/windows_exporter#686]
Is `windows_cpu_core_frequency_mhz` suppose to only show base speed? Would be more useful to get the current speed.

![image](https://user-images.githubusercontent.com/4808216/103162892-f1409300-47f6-11eb-942e-cd6331d3bb4d.png)

**Comment by flurreN** [comment]
After reading some posts I understand why this is happening, been trying to find a way around it but I cant make anything useful. Have anyone got this to work?

**Comment by higels** [comment]
I looked into implementing this, but Windows doesn't provide generic access to the aperf and mperf MSRs, which is the correct way to measure this. From some profiling, it looks like taskmgr gets this number by interrupting every CPU and doing something with TSC so the implementation would be more complex than just reading something from a perf library.
