### ISSUE TITLE
windows_mssql metrics use 'instance' label like Pormetheus

### ISSUE THREAD

**Issue by ymasson** [prometheus-community/windows_exporter#690]
Hi,

The MSSQL metrics use the label 'instance'.
But, this label is automatically attached when Prometheus scrape a target.
https://prometheus.io/docs/concepts/jobs_instances/#jobs-and-instances

In Grafana, if I do query_result({job="myjob"}), and filter on label 'instance', I have targets names and MSSQL instance in the list.
It's complicated to extract the targets list.

is using 'instance' for MSSQL a good idea ?

**Comment by breed808** [comment]
Can you paste a sample of the mssql metrics you're seeing? I think the label will need to be named something more specific, such as `mssql_instance`.

**Comment by ymasson** [comment]
```
# HELP windows_mssql_accessmethods_au_batch_cleanup_failures (AccessMethods.FailedAUcleanupbatches)
# TYPE windows_mssql_accessmethods_au_batch_cleanup_failures counter
windows_mssql_accessmethods_au_batch_cleanup_failures{instance="TESTDB"} 0
# HELP windows_mssql_accessmethods_au_batch_cleanups (AccessMethods.AUcleanupbatches)
# TYPE windows_mssql_accessmethods_au_batch_cleanups counter
windows_mssql_accessmethods_au_batch_cleanups{instance="TESTDB"} 0
# HELP windows_mssql_accessmethods_au_cleanups (AccessMethods.AUcleanups)
# TYPE windows_mssql_accessmethods_au_cleanups counter
windows_mssql_accessmethods_au_cleanups{instance="TESTDB"} 0
```

**Comment by breed808** [comment]
That's definitely not good: the `instance` label is conflicting. I'll change this to `mssql_instance`.

**Comment by ymasson** [comment]
Thanks @breed808

**Comment by bryanklewis** [comment]
@breed808, @ymasson I wanted to comment on this as i think there could be a view either way.

I would argue it is correct as is and should not be modified. All metrics generated by the mssql collector have a scope or context of the database instance. The physical host has nothing to do with the identity or uniqueness of the metric. The normal value of instance as filled by __address__ by default does not apply. If the physical host name was still wanted, one could always write a relabel rule to add __address__ as host.

Now on the other hand, the full unique name of an mssql instance is technically "hostname\instance" but that would look sloppy as a single tag. So then instance stays as essentially host and the you add instance as proposed mssql_instance.

I can see it either way so im torn.

**Comment by bryanklewis** [comment]
without making any change you could accomplish the above with:
- job_name: mssql
  honor_labels: true
  relabel_configs:
  - source_labels: [__address__]
    regex: .*
    target_label: host
    replacement: $1
    action: replace

**Comment by breed808** [comment]
Thanks for the input @bryanklewis!
I can understand where you're coming from regarding the identity of the metric, though I think setting the host as the `instance` flag by default would be less confusing and would keep the metrics in line with other collectors from this exporter.

My thinking is that using the database instance as the `instance` flag would cause confusion, as it wouldn't be consistent with other collectors & metrics from this exporter. It also causes difficulty in troubleshooting (E.G. which host are these metrics being scraped from?).

I'm not overly familiar with the `mssql` exporter myself, so perhaps further discussion is required on this before a change is made.

**Comment by bryanklewis** [comment]
I mostly wanted to validate this wasn't overriding an intended feature. I think your evaluation is fair, it comes down to preference for consistency among collectors or metric naming accuracy. Sounds like consistency with the other collectors in the project is preferred. For what its worth im good with that and rather not delay the project. bias for action over analysis. ;-) thank you for taking time to consider.
