### ISSUE TITLE
upper case for windows_cs_hostname in mixed environment

### ISSUE THREAD

**Issue by ymasson** [prometheus-community/windows_exporter#692]
Hi,

In my environment, I have both Linux and Windows servers.
I use a source of truth (Netbox) to build my Prometheus targets list.

All host are in lower case.

But, for Windows hosts, FQDN and HOSTNAME are reported in upper case
```
# HELP windows_cs_hostname Labeled system hostname information as provided by ComputerSystem.DNSHostName and ComputerSystem.Domain
# TYPE windows_cs_hostname gauge
windows_cs_hostname{domain="localdomain",fqdn="TESTWSERVER.localdomain",hostname="TESTWSERVER"} 1
```

example for Linux node_exporter:
```
# HELP node_uname_info Labeled system information as provided by the uname system call.
# TYPE node_uname_info gauge
node_uname_info{domainname="localdomain",machine="x86_64",nodename="testlserver.localdomain",release="4.19.0-13-amd64",sysname="Linux",version="#1 SMP Debian 4.19.160-2 (2020-11-28)"} 1
```

In Grafana, I can do a simple `label_values(node_uname_info, nodename)` and get all Linux servers.

Bur, for Windows servers, I do `query_result({job="windows"})` with regex `/.instance="([^"]+)./`.
It will be more easy to just do `label_values(windows_cs_hostname, fqdn)`.

It is not possible to transform metrics on Prometheus Side to change it in lower case.

And, it seems it will not be implemented 
https://github.com/prometheus/prometheus/issues/1548

is it possible to uniform this Windows metric with the Linux metric and enforce a lower case ?

if you have a better solution, I'll take it.

Thanks

**Comment by breed808** [comment]
The exporter is directly returning values provided by Windows (via WMI), which would be easy enough to transform to lower case.
We tend to avoid transforming data provided by WMI/Perflib (except to standardize units, such as milliseconds -> seconds), though as these are labels I think transforming to lower case makes sense.

@carlpett what do you think?

**Comment by carlpett** [comment]
No, I do not think we want to do transformations here, especially this case which is mainly preferential. Some thoughts:
1. If you already have the name in the casing you prefer, can't you make list your Windows instances in Grafana via `label_values(up{job="windows"}, instance)`? 
2. I think Grafana has recently added Transformation support, which lets you do changes to data at presentation-time. I'm not sure you can do exactly this use-case yet, but it'd fit in better there.

**Comment by ymasson** [comment]
1. yes, I can use that to target windows servers. instance is in lower case. But it's a constraint to define the job name in every dashboard. It force to have only one scraping job and the name must never change. I not prefer a specific casing, I just want to uniform it for automation and scripting.

2. Transform functions are for values. Not for labels. I didn't found a way to change the casing in Prometheus or Grafana. But I'm not an Grafana expert.

Thanks for your answer and suggestions.
