### ISSUE TITLE
Question about this agent creating tonnes of "Audit Success" events

### ISSUE THREAD

**Issue by jellydonuts** [prometheus-community/windows_exporter#694]
Hi there, I've recently installed this agent on a Windows box and have noticed that the number of events in my EventViewer Windows Logs > Security have increased dramatically.

I'm seeing a tonne of "Audit Success" logs pointing to "the handle to an object was requested" and "the handle to an object was closed" coming from C:\Windows\System32\services.exe

Would this be related to this agent running as a service?

**Comment by breed808** [comment]
I believe that yes, when registered as a service the exporter will write to the Windows Event log (application).
I'll double-check on my VM and confirm.
