### ISSUE TITLE
question

### ISSUE THREAD

**Issue by GhasemSystem** [prometheus-community/windows_exporter#695]
Hi
Why we not implement collector for Win32_PerfRawData_Counters_* & ASP yet?
maybe add this collectors in the future?

**Comment by GhasemSystem** [comment]
hello!

**Comment by breed808** [comment]
Hi Ghasem,

Could you specify the PerfRawData counters that you need? If there's a corresponding Perflib source, adding the metrics should be straightforward.
The addition of new WMI collectors is something we'd like to avoid, as they bring performance and stability issues.

**Comment by GhasemSystem** [comment]
Hi @breed808 

for example:

Win32_PerfRawData_Counters_HTTPServiceRequestQueues ---> CurrentQueueSize
Win32_PerfFormattedData_ASPNET*                                      ---> Requests Queued, ...

**Comment by breed808** [comment]
`HTTPServiceRequestQueues` looks like it's an IIS metric and should [be available via Perflib](https://techcommunity.microsoft.com/t5/iis-support-blog/performance-counters-for-monitoring-iis/ba-p/683389). I should be able to add this metric using one of our IIS servers to gather information.

`ASPNET` appears to also have [performance metrics](https://stackify.com/asp-net-performance-counters/), but I don't have any running ASP.NET applications running that could be used to test the metric(s).

If you're able to provide performance counter information yourself, I should be able to create a collector for you. See this for details on gathering the required info: https://github.com/prometheus-community/windows_exporter/issues/666#issuecomment-732809777
