### ISSUE TITLE
How to use [defaults] in --collectors.enabled flag?

### ISSUE THREAD

**Issue by ramonsmits** [prometheus-community/windows_exporter#697]
The [flags guidance](https://github.com/prometheus-community/windows_exporter#flags) isn't very clear:

> Comma-separated list of collectors to use. Use [defaults] as a placeholder for all the collectors enabled by default."

I want to have in addition to the defaults `process`, and `container` collectors enabled. Based on the above I thought it should be the following argument:

    --collectors.enabled="[defaults],process,container"

Is this correct?

**Comment by breed808** [comment]
Yes, you're correct: the `[defaults]` entry in your list will expand to the default collectors.
Would you be interested in submitting a pull request to update the documentation?
