### ISSUE TITLE
A lot of event log on server with sql

### ISSUE THREAD

**Issue by PierreNa** [prometheus-community/windows_exporter#700]
Hello,

I need help, I have deployed the new exporter (windows_exporter 0.15) on all my infrastructure, only I detect errors on several servers running MSSQL.

The majority are 2008R2 MSSQL, and i don't know why this focus on 2008 MSSQL.

These servers have event observers filled with log windows_exporter like that : 

```
Niveau	Date et heure	Source	ID de l’événement	Catégorie de la tâche
Erreur	19/01/2021 12:15:57	windows_exporter	102	Aucun	collector mssql failed after 0.002981s: at least one child collector failed
Erreur	19/01/2021 12:15:57	windows_exporter	102	Aucun	mssql class collector availreplica failed after 0.000000s: counter not found
Erreur	19/01/2021 12:15:57	windows_exporter	102	Aucun	mssql class collector dbreplica failed after 0.000000s: counter not found
Erreur	19/01/2021 12:15:42	windows_exporter	102	Aucun	collector mssql failed after 0.002982s: at least one child collector failed
Erreur	19/01/2021 12:15:42	windows_exporter	102	Aucun	mssql class collector dbreplica failed after 0.000000s: counter not found
Erreur	19/01/2021 12:15:42	windows_exporter	102	Aucun	mssql class collector availreplica failed after 0.000000s: counter not found
Erreur	19/01/2021 12:15:27	windows_exporter	102	Aucun	collector mssql failed after 0.002000s: at least one child collector failed
Erreur	19/01/2021 12:15:27	windows_exporter	102	Aucun	mssql class collector dbreplica failed after 0.000000s: counter not found
Erreur	19/01/2021 12:15:27	windows_exporter	102	Aucun	mssql class collector availreplica failed after 0.000000s: counter not found
Erreur	19/01/2021 12:15:12	windows_exporter	102	Aucun	collector mssql failed after 0.002982s: at least one child collector failed
Erreur	19/01/2021 12:15:12	windows_exporter	102	Aucun	mssql class collector availreplica failed after 0.000000s: counter not found
Erreur	19/01/2021 12:15:12	windows_exporter	102	Aucun	mssql class collector dbreplica failed after 0.000000s: counter not found
Erreur	19/01/2021 12:14:57	windows_exporter	102	Aucun	collector mssql failed after 0.004980s: at least one child collector failed
Erreur	19/01/2021 12:14:57	windows_exporter	102	Aucun	mssql class collector dbreplica failed after 0.000000s: counter not found
Erreur	19/01/2021 12:14:57	windows_exporter	102	Aucun	mssql class collector availreplica failed after 0.000000s: counter not found
Erreur	19/01/2021 12:14:42	windows_exporter	102	Aucun	collector mssql failed after 0.002978s: at least one child collector failed
Erreur	19/01/2021 12:14:42	windows_exporter	102	Aucun	mssql class collector dbreplica failed after 0.000000s: counter not found
Erreur	19/01/2021 12:14:42	windows_exporter	102	Aucun	mssql class collector availreplica failed after 0.000000s: counter not found
Erreur	19/01/2021 12:14:27	windows_exporter	102	Aucun	collector mssql failed after 0.005002s: at least one child collector failed
Erreur	19/01/2021 12:14:27	windows_exporter	102	Aucun	mssql class collector availreplica failed after 0.000000s: counter not found
Erreur	19/01/2021 12:14:27	windows_exporter	102	Aucun	mssql class collector dbreplica failed after 0.000000s: counter not found
```

**Comment by PierreNa** [comment]
Someone please ...

**Comment by breed808** [comment]
This could be an issue with the performance counters, do you receive any errors when querying `dbreplica` or `availreplica` manually?

See https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.diagnostics/get-counter?view=powershell-7.1 for more details on retrieving them manually with `Get-Counter`.

If the metrics from these classes aren't required you can disable them with the `--collectors.mssql.classes-enabled` flag.

**Comment by PierreNa** [comment]
Hello @breed808 ,
Thanks for you're return.
I will try you're command line and i have not this counter dbreplica or availreplica ...
So i try you're commande and she does't work on W2008R2 or 2012... Can you tel me more please.
<img width="322" alt="Win_exp-test" src="https://user-images.githubusercontent.com/32876811/105369226-a1d96100-5c02-11eb-8560-e1cb76651873.PNG">
<img width="271" alt="Win_counter" src="https://user-images.githubusercontent.com/32876811/105369427-d3eac300-5c02-11eb-9934-e3ab036f3496.PNG">

**Comment by PierreNa** [comment]
@breed808 i look it's specific on the SQL 2008 Franch install, did you know why ?

**Comment by breed808** [comment]
For reference, these are the replica counters for a Windows 2012 R2 host running SQL Server 2014:

```powershell
PS C:\Users\breed808> Get-Counter -ListSet * | select CounterSetName | sls replica

@{CounterSetName=SQLServer:Database Replica}
@{CounterSetName=SQLServer:Availability Replica}
@{CounterSetName=SQLServer:Replication Agents}
@{CounterSetName=SQLServer:Replication Merge}
@{CounterSetName=SQLServer:Replication Logreader}
@{CounterSetName=SQLServer:Replication Dist.}
@{CounterSetName=SQLServer:Replication Snapshot}
```

To omit the replica metrics, you'll need to specify all the required mssql classes except for the replicas: `--collectors.mssql.classes-enabled=accessmethods,bufman,databases,genstats,locks,memmgr,sqlstats,sqlerrors,transactions`
This isn't ideal, but there's no allow/deny list behaviour in the collector at the moment.

Unfortunately I can't say why this is only occurring on a SQL 2008 French install.

**Comment by PierreNa** [comment]
Hello @breed808,

Thanks for you're return.

It's work when i specify the collector but i thinks is not a longest time solution.

Thanks for you're time and you're explications.

Whe can closed this issue.
