### ISSUE TITLE
Windows_Exporter 0.13.0 doesn't start on Windows 2016 Datacentre

### ISSUE THREAD

**Issue by anish2808** [prometheus-community/windows_exporter#701]
Hi. I'm using an ansible role to upgrade Wmi_exporter from 0.12.0 to 0.13.0 

The installation is a success where wmi_exporter gets successfully deleted and Windows_Exporter gets installed. (Verified that by using the **sc qc windows_exporter** command. 

But, windows_exporter is in a state of stopped on the services tab. And querying using the **sc start windows_exporter**
command it shows that the service_state : START_PENDING. 

I tried this (https://github.com/prometheus-community/windows_exporter/issues/551#issuecomment-655732294) but it still doesn't help. 

Any help would be highly appreciated.

**Comment by tbiles** [comment]
Did you try the 0.15.0 release?  I had similar problems going from 0.11.0 to a later release but it should have been fixed since then.
https://github.com/prometheus-community/windows_exporter/releases

**Comment by pierrenavarrete** [comment]
Yes i use the 0.15.0 release and it's ok for me on W16 Datacenter.

**Comment by anish2808** [comment]
Thank you. Using version 0.15.0 worked. 
Closing this issue.
