### ISSUE TITLE
Next Release Timeline?

### ISSUE THREAD

**Issue by majerus1223** [prometheus-community/windows_exporter#705]
Just wondering if there is any timeline for the next release?

**Comment by hartman17** [comment]
Related to this question, will     #693  be included in the next release? We are eager to implement the HTTPS config.

**Comment by majerus1223** [comment]
That's what I am looking for as well

**Comment by replay** [comment]
I'm also waiting for #693

**Comment by carlpett** [comment]
We don't have a timeline as such, but it's been a while. Let's go for it after the HTTPS support is merged :)

**Comment by majerus1223** [comment]
Sounds great to me!

**Comment by hartman17** [comment]
Now that #693 has been merged any chance we can get a new version cut?   Thank you for the time and effort you put into this project!

**Comment by Wittionary** [comment]
This issue can probably be closed :)
@carlpett
