### ISSUE TITLE
dfsr collector returned error 

### ISSUE THREAD

**Issue by bds006** [prometheus-community/windows_exporter#707]
Hello, 

After build windows_exporter.exe from the source code and run it with dfsr collector enabled, it returned below error  from the metric output:
----quote for the error-------
An error has occurred while serving metrics:

3 error(s) occurred:
* collected metric windows_dfsr_received_files_total label:<name:"name" value:"dfsr-test-{C9BCA8F8-76DB-4B79-BF13-6AD6D5CF8C31}" > counter:<value:1 >  has help "" but should have "Total number of files receieved for connection"
* collected metric windows_dfsr_rdc_received_files_total label:<name:"name" value:"dfsr-test-{C9BCA8F8-76DB-4B79-BF13-6AD6D5CF8C31}" > counter:<value:0 >  has help "" but should have "Total number of Remote Differential Compression files received"
* collected metric windows_dfsr_files_received_bytes_total label:<name:"name" value:"dfsr-test-{C9BCA8F8-76DB-4B79-BF13-6AD6D5CF8C31}" > counter:<value:435 >  has help "" but should have "Total size of files received, in bytes"
-----unquote for the error---------------------------
Could you help to check what's the issue?

**Comment by breed808** [comment]
Ah, that will be some of the metrics missing a description. Looking at the history this was me leaving them blank; I'll submit a PR to fix those up.
