### ISSUE TITLE
container_id by name

### ISSUE THREAD

**Issue by mcgizmo** [prometheus-community/windows_exporter#713]
Hello team, need some help,
I have in Grafana at metrics from my windows pods ( using windows_exporter):
if i try get metrics  for example: rate(windows_container_cpu_usage_seconds_total[5m])
I will see only container_id ( pod id) for example: docker://0040308261f7aa694ac13ca1d7fc92ee9c781892de774b4b87ea4f6a167344be  not a pod name/container name because windows_exporter can provide only at container ID
as I understand I need to do relabeling in Prometheus-operator ( I'm using helpfile for this in kube-prometheus-stack)
 how I understand I need to add metric_relabel_configs in values but I do not understand how I can do this.
 
  additionalScrapeConfigs: []
    # - job_name: kube-etcd
    #   kubernetes_sd_configs:
    #     - role: node
    #   scheme: https
    #   tls_config:
    #     ca_file:   /etc/prometheus/secrets/etcd-client-cert/etcd-ca
    #     cert_file: /etc/prometheus/secrets/etcd-client-cert/etcd-client
    #     key_file:  /etc/prometheus/secrets/etcd-client-cert/etcd-client-key
    #   relabel_configs:
    #   - action: labelmap
    #     regex: __meta_kubernetes_node_label_(.+)
    #   - source_labels: [__address__]
    #     action: replace
    #     targetLabel: __address__
    #     regex: ([^:;]+):(\d+)
    #     replacement: ${1}:2379
    #   - source_labels: [__meta_kubernetes_node_name]
    #     action: keep
    #     regex: .*mst.*
    #   - source_labels: [__meta_kubernetes_node_name]
    #     action: replace
    #     targetLabel: node
    #     regex: (.*)
    #     replacement: ${1}
    #   metric_relabel_configs:
    #   - regex: (kubernetes_io_hostname|failure_domain_beta_kubernetes_io_region|beta_kubernetes_io_os|beta_kubernetes_io_arch|beta_kubernetes_io_instance_type|failure_domain_beta_kubernetes_io_zone)
    #     action: labeldrop

**Comment by mcgizmo** [comment]
fixed

**Comment by mcgizmo** [comment]
fixed

**Comment by kotnn** [comment]
hey @mcgizmo 
How did you fix this ?

**Comment by chrism417** [comment]
@kotnn or @mcgizmo did you figure this out?

**Comment by kotnn** [comment]
no

**Comment by szediktam** [comment]
the container metrics has only container_id,  how to join  container/pod label for container metircs？
@mcgizmo

**Comment by kotnn** [comment]
![image](https://user-images.githubusercontent.com/38759038/153819997-a1c36137-cb6a-4952-aa0c-a529ae793aa0.png)

**Comment by szediktam** [comment]
@kotnn  windows-exporter expose metric `windows_container_cpu_usage_seconds_total`, not `container_cpu_usage_seconds_total`.
`windows_container_cpu_usage_seconds_total` has no label of namespace/pod/container, just container_id.
for example:
windows_container_cpu_usage_seconds_total{container_id="docker://db86fa8b8808de961a724699df886e46fbd7e70c045ac179bf83bc3dbd9a20bc"} 126.390625

**Comment by szediktam** [comment]
use group_left to join `windows_container_cpu_usage_seconds_total` and `kube_pod_container_info`, to add namespace/pod/container label for `windows_container_cpu_usage_seconds_total`:
`windows_container_cpu_usage_seconds_total * on(container_id) group_left(namespce,pod,container) kube_pod_container_info{container_id!=""}`

**Comment by szediktam** [comment]
use group_left to join `windows_container_cpu_usage_seconds_total` and `kube_pod_container_info`, to add namespace/pod/container label for `windows_container_cpu_usage_seconds_total`:
`windows_container_cpu_usage_seconds_total * on(container_id) group_left(namespce,pod,container) kube_pod_container_info{container_id!=""}`
