### ISSUE TITLE
dfsr - collector return error

### ISSUE THREAD

**Issue by bds006** [prometheus-community/windows_exporter#715]
Hello (yes it's me again), 

I got new errors for dfsr collector with the new code:

-----quote-----------------------------------------
An error has occurred while serving metrics:

6 error(s) occurred:
* collected metric windows_dfsr_bandwidth_savings_using_dfs_replication_bytes_total label:<name:"name" value:"dfsr-test-{C9BCA8F8-76DB-4B79-BF13-6AD6D5CF8C31}" > counter:<value:10 >  has help "Total bytes of bandwidth saved using DFS Replication for this folder" but should have "Total bytes of bandwidth saved using DFS Replication for this connection"
* collected metric windows_dfsr_received_files_total label:<name:"name" value:"dfsr-test-{C9BCA8F8-76DB-4B79-BF13-6AD6D5CF8C31}" > counter:<value:61 >  has help "" but should have "Total number of files receieved for connection"
* collected metric windows_dfsr_rdc_received_bytes_total label:<name:"name" value:"dfsr-test-{C9BCA8F8-76DB-4B79-BF13-6AD6D5CF8C31}" > counter:<value:62069 >  has help "" but should have "Total bytes received on the connection while replicating files using Remote Differential Compression"
* collected metric windows_dfsr_rdc_compressed_size_of_received_files_bytes_total label:<name:"name" value:"dfsr-test-{C9BCA8F8-76DB-4B79-BF13-6AD6D5CF8C31}" > counter:<value:2.50535251e+08 >  has help "" but should have "Total uncompressed size of files received with Remote Differential Compression for connection"
* collected metric windows_dfsr_rdc_received_files_total label:<name:"name" value:"dfsr-test-{C9BCA8F8-76DB-4B79-BF13-6AD6D5CF8C31}" > counter:<value:5 >  has help "" but should have "Total number of files received using remote differential compression"
* collected metric windows_dfsr_files_received_bytes_total label:<name:"name" value:"dfsr-test-{C9BCA8F8-76DB-4B79-BF13-6AD6D5CF8C31}" > counter:<value:2.571612623e+09 >  has help "" but should have "Total size of files received, in bytes"
--------un quote--------------------------------------------------------------------------------

thanks in advance!

**Comment by breed808** [comment]
Hi @bds006, not a problem. It's good to have someone testing the collectors.
Looks like the child collector metric names aren't unique, I'll fix that with another PR. One of these days I'll get the collector right :disappointed:

**Comment by breed808** [comment]
@bds006 can I get you to test the code in https://github.com/breed808/windows_exporter/tree/dfsr_unique_metric_names and let me know if there's any other runtime errors with the `dfsr` collector?
I want to make sure I've eliminated the errors before merging anything.

**Comment by bds006** [comment]
Hello @breed808 , 
I still got the errors with the code in https://github.com/breed808/windows_exporter/tree/dfsr_unique_metric_names

An error has occurred while serving metrics:

6 error(s) occurred:
* collected metric windows_dfsr_bandwidth_savings_using_dfs_replication_bytes_total label:<name:"name" value:"dfsr-test-{C9BCA8F8-76DB-4B79-BF13-6AD6D5CF8C31}" > counter:<value:10 >  has help "Total bytes of bandwidth saved using DFS Replication for this folder" but should have "Total bytes of bandwidth saved using DFS Replication for this connection"
* collected metric windows_dfsr_received_files_total label:<name:"name" value:"dfsr-test-{C9BCA8F8-76DB-4B79-BF13-6AD6D5CF8C31}" > counter:<value:61 >  has help "" but should have "Total number of files receieved for connection"
* collected metric windows_dfsr_rdc_received_bytes_total label:<name:"name" value:"dfsr-test-{C9BCA8F8-76DB-4B79-BF13-6AD6D5CF8C31}" > counter:<value:62069 >  has help "" but should have "Total bytes received on the connection while replicating files using Remote Differential Compression"
* collected metric windows_dfsr_rdc_compressed_size_of_received_files_bytes_total label:<name:"name" value:"dfsr-test-{C9BCA8F8-76DB-4B79-BF13-6AD6D5CF8C31}" > counter:<value:2.50535251e+08 >  has help "" but should have "Total uncompressed size of files received with Remote Differential Compression for connection"
* collected metric windows_dfsr_rdc_received_files_total label:<name:"name" value:"dfsr-test-{C9BCA8F8-76DB-4B79-BF13-6AD6D5CF8C31}" > counter:<value:5 >  has help "" but should have "Total number of files received using remote differential compression"
* collected metric windows_dfsr_files_received_bytes_total label:<name:"name" value:"dfsr-test-{C9BCA8F8-76DB-4B79-BF13-6AD6D5CF8C31}" > counter:<value:2.571612623e+09 >  has help "" but should have "Total size of files received, in bytes"

**Comment by breed808** [comment]
Hi @bds006, the metric names in those errors don't match up with the changes in the `dfsr_unique_metric_names` branch.

Once you've cloned the repository with `git clone https://github.com/breed808/windows_exporter.git`, are you changing branch with `git switch dfsr_unique_metric_names` before building the `windows_exporter.exe` binary?

**Comment by bds006** [comment]
Hello @breed808 , 
Thanks for remind, it works perfectly after switch the branch and rebuild. 

thank you!

**Comment by bds006** [comment]
The issue is fixed. thanks.

**Comment by bds006** [comment]
@breed808 Could you also merge it?

**Comment by breed808** [comment]
Sure, I'll get it merged.
