### ISSUE TITLE
Dashboard ID 

### ISSUE THREAD

**Issue by isaacmakhuba** [prometheus-community/windows_exporter#721]
Hi Guys,

i am new on Prometheus , do guys perhaps have dashboard ID for this exporter

**Comment by breed808** [comment]
Hi @isaacmakhuba, there's not currently any official dashboards you can use, but there are some community-provided dashboards available at https://grafana.com/grafana/dashboards?dataSource=prometheus&search=windows

Note that older dashboards may still be using metrics with the `wmi_` prefix. You can still use these dashboards, but you'll need to edit them such that the prefix is changed to `windows_`.

Let me know if you have any issues.

**Comment by Wittionary** [comment]
@breed808 This issue should be good to close.
