### ISSUE TITLE
Any interrest in adding collector for NVIDIA GPUs?

### ISSUE THREAD

**Issue by rubu** [prometheus-community/windows_exporter#725]
Hi,

we are planning to use windows_exporter to monitor [CasparCG][2] machines which consumer a lot of CPU/RAM/VRAM and sadly the third metric cannot be queried. I did a quick wrapper for NVIDIA nvml to query per process VRAM usage in my [fork][2]. It's very raw now and I'll do more testing and improvements, but would you be interrested to merge this in so that we do not have to live off a fork? :)

[1]:https://github.com/rubu/windows_exporter/tree/feature/nvidia
[2]:https://github.com/CasparCG/server

**Comment by carlpett** [comment]
Hey @rubu,
Definitely, GPU support has been mentioned in many feature requests! There's been a bunch of ideas around GPUs previously, eg #573. You appear to have a different approach here with directly calling NVIDIA libraries. Does this give you different data than the perflib counters does? Or perhaps higher resolution etc?

**Comment by rubu** [comment]
Hi @carlpett,

I guess I rushed a bit before opening this, since the scenario on which the NVIDIA libraries would actually make more use than perflib is not that common (and impossilbe in the scenario where I needed it), but I'll sum everything up and possibly end up adding gpu counters to perflib.

So in my case, I actually wanted to run CasparCG with NVIDIA GPUs in TCM not WDDM mode (tldr; - WDDM mode is the standard display device driver mode where all the memory is managed by Windows, while TCM which is recommended by NVIDIA in their API docs if GPU is not used as an actual display device leaves the GPU memory management up to the card, see [1][this]). The culprit lies in the fact that going from WDDM to WDM basically disables the ability to use OpenGL on that specific card (which I sadly did not know and stumbled upon after already having the NVIDIA metrics in place). So on Windows, the NVIDIA specific metrics would only benefit Tesla cards or GeForce/Quadro cards that have been set to TCM (possibly if only CUDA stuff is run there?). I still ended up with getting those metrics from NVIDIA nvml for now, but in WDDM mode nvml only seems to exposed the used total amount of used dedicated memory, which is fineish for me to observe leaks, but ideally per process GPU memory usage would be better (which is not available from NVIDIA nvml in WDDM mode). Thus I'll also look into adding relevant perflib counters to the existing collector and then these both things together (NVIDIA nvml as a separate collector and perflib) would cover all the cases. I haven't looked into perflib for specific counters, but since Task Manager is able to show those values I assume they should be there.

1:https://docs.nvidia.com/nsight-visual-studio-edition/reference/index.html#tcc-tesla-products

**Comment by rubu** [comment]
@carlpett btw, since I am not familiar with how the data from perflib is un marshaled - is perflib told to query only the process counters or is that set of counters actually all that is possible to get? Since in the case of the latter, debugger did not show anything gpu related there.

**Comment by carlpett** [comment]
So, basically we unmarshal anything you ask for. For example in the Cache collector we say we're interested in the `Cache` performance object: https://github.com/prometheus-community/windows_exporter/blob/795cc5ca85a05daed0e4f0315476f0472e0598f5/collector/cache.go#L11
Then, a struct that describes the fields you want to extract: https://github.com/prometheus-community/windows_exporter/blob/795cc5ca85a05daed0e4f0315476f0472e0598f5/collector/cache.go#L239-L244

So what you need to do is find the objects (#573 has a lot of them) and check what fields you're interested in.

**Comment by rubu** [comment]
@carlpett ok thanks, I'll look into that:)

**Comment by rubu** [comment]
@carlpett 

Ok I had a look at the stuff in [#573][2] and added 3 metrics (GPU Utilization/GPU Shared Memory/GPU Dedicated Memory) per pid per GPU to my [fork][1]. Also added C code to do DXGI adapter name lookup from the luids so that the metrics can be labeled with meaningful display names. I haven't finished the data aggregation, but the counters are there and the luid mapping seems fine, so I guess next week I can polish stuff to have a PR to look at.

A couple of questions:
1) These counters seem to be available only since Windows 10 Fall Creators Update. Should this functionality be made available based on OS version detection or better an option for the process collector that is off by default?
2) I'd say that keeping the NVIDIA stuff for no WDDM cards makes sense as well, any thoughts on that ?

[1]:https://github.com/rubu/windows_exporter
[2]:https://github.com/prometheus-community/windows_exporter/issues/573

**Comment by rubu** [comment]
@carlpett ok so I added all the wddm stuff needed for data aggregation and mapping to human readable gpu names, this is what the output currently looks like:
```# HELP windows_process_gpu_dedicated_memory Number of bytes of dedicated gpu memory used on the gpu.
# TYPE windows_process_gpu_dedicated_memory gauge
windows_process_gpu_dedicated_memory{creating_process_id="3704",gpu_title="Intel(R) HD Graphics 630",process="casparcg",process_id="36924"} 0
windows_process_gpu_dedicated_memory{creating_process_id="3704",gpu_title="NVIDIA TITAN V",process="casparcg",process_id="36924"} 3.33795328e+08
# HELP windows_process_gpu_shared_memory Number of bytes of system memory used as shared memory by the gpu.
# TYPE windows_process_gpu_shared_memory gauge
windows_process_gpu_shared_memory{creating_process_id="3704",gpu_title="Intel(R) HD Graphics 630",process="casparcg",process_id="36924"} 8.0207872e+07
windows_process_gpu_shared_memory{creating_process_id="3704",gpu_title="NVIDIA TITAN V",process="casparcg",process_id="36924"} 1.4630912e+08
```
So basically both dedicated and shared memory usage per process per gpu.

I tried to look into the usage, but that stuff is weird. Perflib reports a varying number of engines per gpu, and the value (even though it should be in percents?) is over 100 and does not match with what I see in task manager. For example, with this output:
```
time="2021-03-04T20:13:19+02:00" level=debug msg="Engine LegacyOverlay utilization on Intel(R) HD Graphics 630: 0.000000\n" source="process.go:325"
time="2021-03-04T20:13:19+02:00" level=debug msg="Engine VideoDecode utilization on Intel(R) HD Graphics 630: 0.000000\n" source="process.go:325"
time="2021-03-04T20:13:19+02:00" level=debug msg="Engine Copy utilization on Intel(R) HD Graphics 630: 0.000000\n" source="process.go:325"
time="2021-03-04T20:13:19+02:00" level=debug msg="Engine 3D utilization on Intel(R) HD Graphics 630: 605.223251\n" source="process.go:325"
time="2021-03-04T20:13:19+02:00" level=debug msg="Engine VideoProcessing utilization on Intel(R) HD Graphics 630: 0.000000\n" source="process.go:325"
time="2021-03-04T20:13:19+02:00" level=debug msg="Engine GDI Render utilization on Intel(R) HD Graphics 630: 0.000000\n" source="process.go:325"
time="2021-03-04T20:13:19+02:00" level=debug msg="Engine VR utilization on NVIDIA TITAN V: 0.000000\n" source="process.go:325"
time="2021-03-04T20:13:19+02:00" level=debug msg="Engine Graphics_1 utilization on NVIDIA TITAN V: 0.000000\n" source="process.go:325"
time="2021-03-04T20:13:19+02:00" level=debug msg="Engine VideoEncode utilization on NVIDIA TITAN V: 0.000000\n" source="process.go:325"
time="2021-03-04T20:13:19+02:00" level=debug msg="Engine Compute_0 utilization on NVIDIA TITAN V: 0.000000\n" source="process.go:325"
time="2021-03-04T20:13:19+02:00" level=debug msg="Engine 3D utilization on NVIDIA TITAN V: 111.361175\n" source="process.go:325"
time="2021-03-04T20:13:19+02:00" level=debug msg="Engine LegacyOverlay utilization on NVIDIA TITAN V: 0.000000\n" source="process.go:325"
time="2021-03-04T20:13:19+02:00" level=debug msg="Engine Copy utilization on NVIDIA TITAN V: 497.255440\n" source="process.go:325"
time="2021-03-04T20:13:19+02:00" level=debug msg="Engine Compute_1 utilization on NVIDIA TITAN V: 0.000000\n" source="process.go:325"
time="2021-03-04T20:13:19+02:00" level=debug msg="Engine Cuda utilization on NVIDIA TITAN V: 0.000000\n" source="process.go:325"
time="2021-03-04T20:13:19+02:00" level=debug msg="Engine Security utilization on NVIDIA TITAN V: 0.000000\n" source="process.go:325"
time="2021-03-04T20:13:19+02:00" level=debug msg="Engine VideoDecode utilization on NVIDIA TITAN V: 0.000000\n" source="process.go:325
```
task manager is showing GPU 0 - 3D 25%. Maybe that needs to be divided among gpu cores but not sure. But at least the memory part seems nice. So I am open for comments and should I open a PR?

**Comment by carlpett** [comment]
Hey @rubu,
Sorry for the slow response :( Regarding your first question, it's fine to do version detection to have different metric sets per version. You can look at the CPU collector as an example.
Regarding the usage, I would guess that the actual value is in consumed core-seconds since boot, or similar. 

Please do open a PR, I think this collector would be very appreciated by others!
