### ISSUE TITLE
Disk letters and percents in windows_process_private_bytes

### ISSUE THREAD

**Issue by wHiteeeeeeeee** [prometheus-community/windows_exporter#729]
Hi, is there any option to automatically add all partitions from windows? For example, if there is only a C drive it should be 1 graph, and if C and D it should show two graphs etc.

Second question is what should the query to windows_process_private_bytes look like to show up as a percentage?
```
100 - (1 - avg(windows_process_private_bytes{instance=~"$instance"}[15m])) by (process)) * 100 
```
not working :/

Thanks for your help!

**Comment by carlpett** [comment]
Hi @wHiteeeeeeeee,
I don't think I understand your first question. What metric are you looking at, and what is the query you've written?
In your second question, there's a couple of problems with your query:
- You are making a range vector (by adding the `[15m]` part), but `avg` doesn't deal with vectors.
- The metric returns the number of bytes per process, not the ratio of total machine memory used

For PromQL-related questions, you'll get a lot more help if you ask in the wider [Prometheus community](https://prometheus.io/community/).

**Comment by wHiteeeeeeeee** [comment]
I dealt with the first problem;)
I still have a question regarding the second question: Is there any option to show windows_process_private_bytes in percentage? It's possible to combine somehow with memory_bytes_total? How the query will look like in this case?

Thanks for the answer ;)

**Comment by carlpett** [comment]
Yes, you'd need to divide by `windows_cs_physical_memory_bytes`. Something like `windows_process_private_bytes / on(instance) windows_cs_physical_memory_bytes` (modulo label matching etc etc).

**Comment by wHiteeeeeeeee** [comment]
Thanks a lot!
