### ISSUE TITLE
Getting aspnet metrics in Perfmon

### ISSUE THREAD

**Issue by mucahidk** [prometheus-community/windows_exporter#731]
Hi,
I reviewed the IIS collector code to pull Permon metrics related to Aspnet. Although it has a similar structure, metrics do not come. I thought of using ASPNET4030319_ASPNETAppsv4030319 Perfmon for this. Should metrics be created by app name or site? How can a path be followed in this regard? Can you help me ?

**Comment by breed808** [comment]
>I reviewed the IIS collector code to pull Permon metrics related to Aspnet

Do you mean to say that you've created an ASP.NET collector, or you've attempted to modify the existing `iis` collector to scrape ASP.NET metrics?

Unfortunately I'm not able to test IIS or ASP.NET metrics, so someone else will need to assist in testing any changes you've made.

> I thought of using ASPNET4030319_ASPNETAppsv4030319 Perfmon for this

This doesn't sound like a generic Perflib source, it may be specific to an application you're running. If you're planning to create or modify a collector, you may need to query existing sources prior to scraping.

> Should metrics be created by app name or site?

Metrics should be left generic with the app name and/or site added as labels.

**Comment by mucahidk** [comment]
Yes,I created a new Aspnet collector, making its contents look like an IIS collector.

Like PerfRawData for the other IIS collector, I use it as in the following URL:
https://wutils.com/wmi/root/cimv2/win32_perfrawdata_aspnet4030319_aspnetappsv4030319/#requestssucceeded_properties

"Metrics should be left generic with the app name and/or site added as labels."  I do not fully understand this place. Can you give details? I tried it differently, but it didn't work for both the site and the app. Actually the site feels usable.

**Comment by breed808** [comment]
`PerfRawData` sources are good if WMI is the only option; a Perflib source for the collector would be preferable where possible.

>"Metrics should be left generic with the app name and/or site added as labels." I do not fully understand this place. Can you give details?

Have a look at the [Metric and label naming](https://prometheus.io/docs/practices/naming/) documentation for Prometheus.
You want to avoid encoding host- or process-specific details in the metric name, and incorporate them as labels.

E.G.
```
# bad
windows_aspnet_process_memory_bytes_process001
# good
windows_aspnet_process_memory_bytes{process_id="001"}
```

If you want me to have a closer look at your work, fork this Github project and push your commits to that repository. That will allow me to review it.
