### ISSUE TITLE
Error when serving metrics from windows_exporter with terminal_services collector

### ISSUE THREAD

**Issue by songlim327** [prometheus-community/windows_exporter#733]
Hi, 

I have recently face an error in the `terminal_services` collector. Below is the the error prompt at the `/metrics` endpoint. Any guidance for this? 

```
An error has occurred while serving metrics:

225 error(s) occurred:
* collected metric "windows_terminal_services_handle_count" { label:<name:"session_name" value:"RDP-Tcp 173" > gauge:<value:3342 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_page_fault_total" { label:<name:"session_name" value:"RDP-Tcp 173" > counter:<value:517900 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_page_file_bytes" { label:<name:"session_name" value:"RDP-Tcp 173" > gauge:<value:2.30141952e+08 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_page_file_bytes_peak" { label:<name:"session_name" value:"RDP-Tcp 173" > gauge:<value:2.52137472e+08 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_privileged_time_seconds_total" { label:<name:"session_name" value:"RDP-Tcp 173" > counter:<value:0.6438799 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_processor_time_seconds_total" { label:<name:"session_name" value:"RDP-Tcp 173" > counter:<value:1.3828121 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_user_time_seconds_total" { label:<name:"session_name" value:"RDP-Tcp 173" > counter:<value:0.7389317999999999 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_pool_non_paged_bytes" { label:<name:"session_name" value:"RDP-Tcp 173" > gauge:<value:244112 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_pool_paged_bytes" { label:<name:"session_name" value:"RDP-Tcp 173" > gauge:<value:3.14608e+06 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_private_bytes" { label:<name:"session_name" value:"RDP-Tcp 173" > gauge:<value:2.30141952e+08 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_thread_count" { label:<name:"session_name" value:"RDP-Tcp 173" > gauge:<value:66 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_virtual_bytes" { label:<name:"session_name" value:"RDP-Tcp 173" > gauge:<value:2.20352643072e+13 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_virtual_bytes_peak" { label:<name:"session_name" value:"RDP-Tcp 173" > gauge:<value:2.2035447353344e+13 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_working_set_bytes" { label:<name:"session_name" value:"RDP-Tcp 173" > gauge:<value:3.81984768e+08 > } was collected before with the same name and label values
* collected metric "windows_terminal_services_working_set_bytes_peak" { label:<name:"session_name" value:"RDP-Tcp 173" > gauge:<value:4.53287936e+08 > } was collected before with the same name and label values
```

Thanks a lot.

**Comment by breed808** [comment]
This looks like a duplicate label (`RDP-Tcp 173`). Does this error occur intermittently, or is it reproducible?
Is this occurring for multiple hosts?

**Comment by songlim327** [comment]
It does seems to happen intermittently. I have found that this can be solved once I restart the `windows_exporter` service. I will dig deeper and check if I can reproduce it. In the meantime, I think this issue can be closed. Appreciate the works and your help. Thanks.

**Comment by alinix-alinix** [comment]
Hello, that issue happens in 2-3 hours after the exporter service is restarted. 
![image](https://user-images.githubusercontent.com/79696698/109290096-36556580-7838-11eb-9e6f-116e55274a88.png)
![image](https://user-images.githubusercontent.com/79696698/109290370-93e9b200-7838-11eb-8559-598268d4e662.png)
Service itself is responding, but serves no more metrics. Btw, anyone knows how to extract RDP usernames, not session numbers? Session numbers are pretty much useless. Their order is lost after a while or after a server's rebooting. 
Many thanks!

**Comment by breed808** [comment]
I'm not too familiar with the `terminal_services` collector, it may be possible to extract a username from perflib or WMI.

It's sounding like `windows_exporter` is picking up duplicate `RDP-Tcp` sessions returned by perflib, so there may not be enough labels to ensure uniqueness, or they may be an issue with the collector and/or server.

`Get-Counter -ListSet 'Terminal Services Session'` will help in debugging this issue. This will give you a list of counters and paths that can be queried.
Check the output of these queries (E.G. `Get-Counter \Terminal Services Session(*)\Handle Count'`) when the collector is failing and we may be able to identify if there are duplicate session IDs.

**Comment by alinix-alinix** [comment]
Hello, breed808. Sorry for late response. I'm actually having difficulties providing you requested data, because here i'm using win2012 with counters using confusing russian names.
I have counter set like 'terminal sessions' with number of active, inactive and total sessions.
I have counter set like 'counter set for RDS connection broker'  looking almost similar to previous one.
I have counter set like 'counter set for RDS connection broker redirector', where i can not find anything of interest,
And the final one is a 'counter set for RPS database' which is unusable in our case as well. 

I'm sorry, i'm completely confused, maybe someone could give us a hand.

**Comment by alinix-alinix** [comment]
Ok, sort of workaround. I added a job to the windows scheduler restarting windows_exporter service once in 30 minutes. Now it's pretty much stable.

**Comment by breed808** [comment]
> I have counter set like 'terminal sessions' with number of active, inactive and total sessions.

I believe this is the relevant counter. You'll want to monitor this separately from `windows_exporter` to see if duplicate session IDs are presented by the counter.

> I added a job to the windows scheduler restarting windows_exporter service once in 30 minutes

Not ideal but I'm glad you've got it working.
