### ISSUE TITLE
Install windows_exporter-0.15.0-amd64 on windowsServer 2008 standard Failed Error: Verfiy that you have sufficient privileges to start system services

### ISSUE THREAD

**Issue by Dennis981210** [prometheus-community/windows_exporter#734]
On my WindowsServer 2008 Standard Version OS, When I try to install windows_exporter-0.15-amd64 I got some error like this:
![image](https://user-images.githubusercontent.com/46859274/108810990-56421a80-75e7-11eb-935e-a271c09ff625.png)
Well I find some history issue like me, but didn't find a way to solve this problem. In my environment I didn't install wmi-exporter before so that means my env is clean one.
How can I Fix it ? Did anyone else have some good idea?

**Comment by jpiropk** [comment]
You should check your install string? and as a result you could check the params to the windows service.
When I have seen this it usually means I passed in bad parameters to the installer and they ended up as bad windows service arguments such as too many quotes or missing quotes or other invalid situations.
