### ISSUE TITLE
Prometheus/Windows Node Exporter exe as a service

### ISSUE THREAD

**Issue by dw-scm** [prometheus-community/windows_exporter#737]
I want to run prometheus and the windows exporter as a windows service. Will NSSM take the yml configuration files or is there a different way of doing this? 

Thanks

**Comment by carlpett** [comment]
Hi @dw-scm,
The installer we provide will install the windows_exporter as a service already, so you don't need to do anything :) 
For prometheus itself, you'll need to wrap it with eg NSSM.

**Comment by dw-scm** [comment]
> Hi @dw-scm,
> The installer we provide will install the windows_exporter as a service already, so you don't need to do anything :)
> For prometheus itself, you'll need to wrap it with eg NSSM.

@carlpett thanks for the quick response, with the service running using the sc config I can enter the bin path but how do I enter the  --config.file=example.yaml?

**Comment by breed808** [comment]
I've not done this myself, but I believe you'll need to pass any argument flags to the bin path.

E.G.
```
sc config windows_exporter binpath= "$PATH_TO_EXE --config.file=example.yaml"
```

For example, the default "Path to executable" for the v0.16.0 `windows_exporter` service is:
```
C:\Program Files\windows_exporter\windows_exporter.exe" --log.format logger:eventlog?name=windows_exporter --telemetry.addr :9182
```

**Comment by dw-scm** [comment]
That also threw up errors.

I worked it out for anyone who has similar issues. Use nssm it has an arguments section you can put the flag in. Also scriptable via powershell if you need to automate this across your environments for deployments.
