### ISSUE TITLE
windows_iis_current_connections and other metrics are missing

### ISSUE THREAD

**Issue by audioscavenger** [prometheus-community/windows_exporter#738]
happily using the exporter as a service (via msi) for monitoring services and processes, but IIS is missing a ton of metrics. All it reports is **windows_iis_server_***

what i need is at least **windows_iis_current_connections**

is there any way to enable those metrics?

**Comment by breed808** [comment]
Are you getting any logs indicating an error with the `iis` collector?
The `windows_iis_current_connections` metric is sourced from the `win32_perfrawdata_w3svc_webservice` WMI class, and is enabled by default. Are you able to make manual queries to this class?
