### ISSUE TITLE
no metric reported when process is down

### ISSUE THREAD

**Issue by audioscavenger** [prometheus-community/windows_exporter#739]
when you monitor some processes, the exporter only reports metrics for those up and running.

what if we want to know that the process is down? is that something to setup specifically in Grafana?

**Comment by breed808** [comment]
There's a few different scenarios for the `windows_exporter` process:

1. Process is down and not responding. Use the `up` query in Prometheus/Grafana to alert or graph offline hosts.
2. Process is up, but relevant collector is failing. Use the `windows_exporter_collector_success` to monitor failure.
3. Process and collector is up, but collection is timing out. Use the `windows_exporter_collector_timeout` metric to monitor this.

The `absent()` Prometheus function might also come in handy here.

**Comment by cycwll** [comment]
I use the workaround and it's working good: 
   - alert: Windows Java Process Down
     expr: absent(windows_process_cpu_time_total{process="java") == 1
     for: 1m
     labels:
       level: critical
     annotations:
      summary: "Host:{{$labels.instance}}; Process:{{$labels.process}} Has been down!"
      description: "Host:{{$labels.instance}}; Process:{{$labels.process}} Has been down!"

**Comment by zycfcn** [comment]
[https://github.com/zycfcn/windows_exporter](url)  branch_name: online_warn . maybe to help you
