### ISSUE TITLE
wmi_system_system_up_time changes without reboot

### ISSUE THREAD

**Issue by carlpett** [prometheus-community/windows_exporter#74]
Last night, `wmi_system_system_up_time` changed on a handful of my machines, even though they were not rebooted. The changes were very small, for example `1484753057.401196` to `1484753057.4005969` (difference `0.0005991`).

We should investigate why this happens, since it triggers reboot alerts even for such very small changes. 

Also, the name should probably be changed, since it is not actually uptime, but rather the timestamp of the last boot. The node_exporter name is `node_boot_time`, so `wmi_system_boot_time`?

**Comment by brian-brazil** [comment]
By any chance was this in a VM of some form? We have seen such things on the Unix side, which turned out to be a virtualisation issue.

**Comment by carlpett** [comment]
They are VMs indeed. I was aware of clock skew in VMs in general, but wouldn't have expected it to affect the timestamp of booting... But I guess it depends on how the underlying source is implemented.

**Comment by martinlindhe** [comment]
If we end up changing the metrics name, i think that warrants a 0.3 version bump (semver).
Apart from that my first guess was some ntp change being broadcast to the machines, but brians vm idea might be more relevant

**Comment by brian-brazil** [comment]
@juliusv @superq What were the details of the nodes ye had with `node_boot_time` changing? There's reports of a similar issue on Windows.

**Comment by SuperQ** [comment]
The problem is related to the Microsoft HyperV time sync feature.  It sends a signal from the hypervisor to hard-step the clock every 5 seconds.  This causes the kernel and any NTP client to become very confused.  On Azure, there's no way to disable this on the hypervisor side, on Linux we have a [workaround](https://gitlab.com/gitlab-com/infrastructure/issues/1531).

**Comment by carlpett** [comment]
This is not on HyperV, though. These machines are on OpenStack with KVM.

I checked NTP, and there was no clock adjustment from w32time during that time, because that was my first guess.

**Comment by jpds** [comment]
I'm also seeing this on bare-metal Windows hosts

**Comment by jpds** [comment]
Is there a reason this metric has a decimal point? `node_boot_time(_seconds)` for example does not have this and if I run `ceil(wmi_system_system_up_time)` all is well in my graphs.

**Comment by jpds** [comment]
Added a `boot_time_seconds` metric in #277.

**Comment by martinlindhe** [comment]
> Is there a reason this metric has a decimal point?

The value is converted to the unix timestamp scale. We would lose precision if we rounded it to a whole number (second scale).

Relevant code:

https://github.com/martinlindhe/wmi_exporter/blob/fe7e5cb4d8a2656a62da4bdb75d0ff8fd814ac1b/collector/system.go#L126

**Comment by SuperQ** [comment]
@jpds Linux only uses seconds for  boot time. This is why it does not have have any floating point value.
