### ISSUE TITLE
Scraping Defined List of Services with Service collector

### ISSUE THREAD

**Issue by james-m-tubbs** [prometheus-community/windows_exporter#742]
Hi All,

Might be a dumb question here, but I'm having an issue where it looks like I can scrape all services, one service, services using a `LIKE` block, but not a list of services. I've tried the documentation and tried a few scenarios and all seem to fail.

What I want to do:
- scrape data for only for `service1` and `service2`
- provide a list to the services where block to do so

In the config.yml i've tried this, does not work:
```
collector:
  service:
    services-where:
      - Name='service1'
      - Name='service2'
```

I've also tried a few other ways but they do not work.
Comma separated lists:
```
collector:
  service:
    services-where: Name='service1','service2'
```
```
collector:
  service:
    services-where: Name='service1', Name='service2'
```
OR function
```
collector:
  service:
    services-where: Name='service1|service2'
```
```
collector:
  service:
    services-where: Name='service1 OR service2'
```

**Comment by james-m-tubbs** [comment]
Okay figured this out by diving into the code.

It looks like this flag uses [raw](https://github.com/prometheus-community/windows_exporter/blob/master/collector/service.go#L20-L23) [WQL](https://docs.microsoft.com/en-us/windows/win32/wmisdk/wql-sql-for-wmi).

The fix is:
```
collector:
  service:
    services-where: Name='service1' OR Name='service2' OR ...
```

A list of service names may still be nicer, but:
- i'm not sure how this interacts with other options (PID, for example)
- Expecting users to understand WQL to pass flags is a bad pattern IMO

**Comment by breed808** [comment]
I'll readily admit the raw WQL isn't ideal, the syntax is rather confusing, especially when attempting to add it in the MSI `EXTRA_FLAGS`. It's tripped me up nearly every time I've had to deal with it.

From a security perspective, I don't believe parsing raw WQL is a major concern. All `windows_exporter` input is expected to be from the system administrator, so the input is considered trustworthy. Happy to be corrected on this if there's concerns though.

Creating a YAML-to-WQL parser for some of our collectors would be nice, I'd like to do that when I have time.
