### ISSUE TITLE
IIS collector timeout

### ISSUE THREAD

**Issue by vaughnmb** [prometheus-community/windows_exporter#743]
How do I fix an IIS collector timeout?  In the Event Viewer, I see these log entries

- failed collecting iis metrics:<nil> Exception occurred. (Invalid query )
- collector iis failed after 17.654860s: Exception occurred. (Invalid query )

Here is the Windows Service command used to start windows_exporter: 
"C:\Program Files\windows_exporter\windows_exporter.exe" --log.format logger:eventlog?name=windows_exporter  --telemetry.addr :9182  --collectors.enabled "[defaults],iis"

**Comment by breed808** [comment]
The invalid query exception seems like you're experiencing a WMI-related error, not a timeout on the collector.
You could try manually querying the classes listed in the [collector documentation](docs/collector.iis.md) to identify the offending class.

**Comment by breed808** [comment]
Closing due to a lack of activity
