### ISSUE TITLE
Missed metrics

### ISSUE THREAD

**Issue by UAnton** [prometheus-community/windows_exporter#747]
Trying to install windows _exporter on Windows Server 2019. On one server all ok but on the second many metrics are missing.
windows_logical_disk - missed all metrics
windows_system_system_up_time - missed
windows_cpu_time_total - missed
windows_net - all missed

I'm read the documentation and try to enable collectors, but this doesn't help. Logical_disk, net, system - enabled by default but missed.
Maybe I'm doing something wrong?

**Comment by UAnton** [comment]
Found BUG. If Windows language is Russian - many metrics are missed.

**Comment by breed808** [comment]
It's possible there's a difference in Perflib classes/metrics with languages, though I would have expected an issue like this to be reported sooner if that was the case.

Are you able to investigate? If so, we might be able to identify the issue and get a fix merged.
