### ISSUE TITLE
Issue That All Aspnet Collector Metrics gauge is 0

### ISSUE THREAD

**Issue by mucahidk** [prometheus-community/windows_exporter#749]
[aspnet.zip](https://github.com/prometheus-community/windows_exporter/files/6163354/aspnet.zip)

I created 3 different collectors from collector generators for aspnet metrics. But when I look at Perfmon from the server, there are metrics. When I install Windows service, all metrics are 0 as below. What could be the reason for this? Do you have any ideas?

![image](https://user-images.githubusercontent.com/59875802/111623825-f7457f00-87fb-11eb-8a93-62c03dac1522.png)

![image](https://user-images.githubusercontent.com/59875802/111623631-aa61a880-87fb-11eb-8e7b-36bc5b54e50b.png)

**Comment by breed808** [comment]
Hi @mucahidk, would you be able to host your changes in a Github fork? That will make the changes easier to review.

It may be that the struct name or fields do not match that of the WMI class. Unfortunately I don't have a machine running ASP.NET so I'm not able to test the collectors myself.
