### ISSUE TITLE
Release checksum files (sha256sums.txt) are erroneous

### ISSUE THREAD

**Issue by dogukancagatay** [prometheus-community/windows_exporter#756]
The `sha256sums.txt` file inside release assets is not standard and cannot be compared with automated systems.

Content of checksum file of release [v0.16.0](https://github.com/prometheus-community/windows_exporter/releases/tag/v0.16.0):
```
66bedbd771746a934848884d81f2d2580bc6c635a217a637a2b4f30a17cf1d3a  386\windows_exporter-0.16.0-386.exe
17fd6166b25eb7614da1597003a4a2d2c2070dd774c27ac807f44e26f1126014  386\windows_exporter-0.16.0-386.msi
3d1a7ac0820660c31ac9d5df15f28c95ee2c483bedb6a6336a88033f0136d826  amd64\windows_exporter-0.16.0-amd64.exe
398fdf5617eca81b8d24f8e226b0bad57055e4e220741bb158b921b6e10848ba  amd64\windows_exporter-0.16.0-amd64.msi
```

The `386\` and `amd64\` parts of file names shouldn't be there.

I checked couple of checksum files of previous releases (v0.15.0, v0.14.0), the same problem exists on them as well.

**Comment by breed808** [comment]
Thanks for reporting this! I've submitted a PR which removes the arch dirs from the checksum output.
