### ISSUE TITLE
 why 360 Security Guard Report that windows_exporter Is Trojan horse virus

### ISSUE THREAD

**Issue by mrchar** [prometheus-community/windows_exporter#758]
360 Security Guard Report that windows_exporter Is Trojan horse virus HEUR/QVM202.0.9275.Malware.Gen. what does that mean? and I want to know why this happend?

**Comment by carlpett** [comment]
Hi @mrchar,
Thanks for the report! Does it only report this on a specific version of the exporter, or all versions?
I'm by no means an expert on anti-virus software, but the prefix `HEUR` indicates to me that we are triggering one of their heuristics (sort of a pattern in the executable file). So, in the best case, they simply have an overly broad pattern that we happen to match.
I checked [VirusTotal](https://www.virustotal.com/gui/file/3d1a7ac0820660c31ac9d5df15f28c95ee2c483bedb6a6336a88033f0136d826/detection) for the 64-bit, 0.16 version of windows_exporter.exe and there appears to be no other anti virus programs flagging it for now at least, but please check more with your vendor if they can provide more info.

**Comment by mrchar** [comment]
I installed windows_exporter using file windows_exporter-0.16.0-amd64.msi, and 360 report that version 0.16 is a  HEUR/QVM202.0.9275.Malware.Gen virus. now I guess this is probably a false positives.
![image](https://user-images.githubusercontent.com/51408183/114659670-9b9ce180-9d26-11eb-8712-8110378b4d14.png)

**Comment by MatthewBETTON** [comment]
Same problem when I run the msi installer and the executable version 0.16 on a Windows Server 2019 with Microsoft Windows Defender antivirus.

![image](https://user-images.githubusercontent.com/25529943/114730327-0d822480-9d41-11eb-9018-7bb95d187a24.png)

**Comment by MatthewBETTON** [comment]
If i unzip the exe or msi files and scan the contents or the exe or msi themselves, no threat is detected. The alert message is only displayed when running the installer. I also guess this is probably a false positives.

**Comment by carlpett** [comment]
SmartScreen is a slightly different case - it just notifies you that the installer/executable aren't signed with a (multi-thousand dollar) codesigning certificate, and that it might not be safe for that reason. It'll do that for any unsigned file, but it is not related to detecting a virus (in that case it wouldn't give you the "Run anyway" option)

**Comment by MatthewBETTON** [comment]
You are right, it's a different case.

After downloading installer (.exe or .msi file), you can use 'unblock-file' Cmdlet from powershell console.

```
Unblock-File .\windows_exporter-0.16.0-386.msi
Unblock-File .\windows_exporter-0.16.0-386.exe
```

"_Internally, the Unblock-File cmdlet removes the Zone.Identifier alternate data stream, which has a value of "3" to indicate that it was downloaded from the Internet._"

After that, no more notification while running the installer.
