### ISSUE TITLE
Is it possible to monitor windows applications as well?

### ISSUE THREAD

**Issue by smartaquarius10** [prometheus-community/windows_exporter#760]
Team,

I have a case where I want to monitor few applications in the windows machines along with the monitoring of machines.

The applications are like browser or few other installed software. By any chance is it possible to monitor software as well.

If yes, then what is the procedure. Can anyone help on this.  Thank you.

**Comment by breed808** [comment]
Where possible, you should use the [client libraries](https://prometheus.io/docs/instrumenting/clientlibs/) to expose metrics directly from your applications.

If this isn't possible, you could write a custom exporter to query your application, or use some custom scripts and the [textfile collector](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.textfile.md).

**Comment by smartaquarius10** [comment]
But in config file, can't we write something like this

```
collector:
  process:
    whitelist: 'firefox.+|calculator.+|notepad.+'
```

I just need to monitor if they are closed or not

**Comment by smartaquarius10** [comment]
Any help on this please

**Comment by breed808** [comment]
Your example with the regex should work, but note that you won't be able to match the process metrics to individual users.

The `process` collector will work with multiple users so long as your regex accounts for the number suffix:
> Note that multiple processes with the same name will be disambiguated by Windows by adding a number suffix, such as firefox#2. Your regexp must take these suffixes into consideration.

**Comment by smartaquarius10** [comment]
@breed808 , Hmm ok. But I think through this I'm at least able to manage the machines/workstations where access is allowed to only one user.
