### ISSUE TITLE
Which type of exception does it enable in windows Firewall if installed as window service?

### ISSUE THREAD

**Issue by smartaquarius10** [prometheus-community/windows_exporter#761]
Team,

In the documentation, it is written that if we install this application as windows service then it will enable some exception in windows firewall. 

Could you please confirm which type of exception will it add. In the organisation, it is not allowed to update windows firewall and if needed, then we need approval from the leadership.

Thank you

**Comment by breed808** [comment]
The logic for the firewall entry is present in [installer/windows_exporter.wxs](https://github.com/prometheus-community/windows_exporter/blob/db00553ca63fc38b191da8e3cdd59bed3538b746/installer/windows_exporter.wxs):

```xml
<File Id="windows_exporter.exe" Name="windows_exporter.exe" Source="Work\windows_exporter.exe" KeyPath="yes">
  <fw:FirewallException Id="MetricsEndpoint" Name="windows_exporter (HTTP [LISTEN_PORT])" Description="windows_exporter HTTP endpoint" Port="[LISTEN_PORT]" Protocol="tcp" IgnoreFailure="yes">
    <fw:RemoteAddress>[REMOTE_ADDR]</fw:RemoteAddress>
  </fw:FirewallException> 
</File>
```
`REMOTE_ADDR` is documented in the project README:
> Allows setting comma separated remote IP addresses for the Windows Firewall exception (whitelist). Defaults to an empty string (any remote address).

Note that this is only pertinent to the MSI installer; running the EXE does not modify the firewall in any way.

**Comment by smartaquarius10** [comment]
But what is the difference between remote_addr and listen_Addr. As per my understanding, listen_Addr is the address where I can access the metrics. 

So in my case, as my virtual machines are already accessible via hostname.something.com, there is no need to set listen_addr. 

I can use exe as well but the machines where I wanted to deploy this exporter are managing Robotics projects. If any separate window is open on the GUI then it might disturb the flow of RPA process. Therefore, the only option I have is to install as window service. 

Could you please explain a little bit about the usage of remote_addr. Can we ignore using it because firewall exception is strictly not allowed.

**Comment by smartaquarius10** [comment]
Any help on this please

**Comment by breed808** [comment]
> As per my understanding, listen_Addr is the address where I can access the metrics

That's correct. It defaults to `:9182`, meaning the exporter will listen on 9182/TCP on all interfaces on the host.

> what is the difference between remote_addr and listen_Addr

`REMOTE_ADDR` is documented in the project README:

> Allows setting comma separated remote IP addresses for the Windows Firewall exception (whitelist). Defaults to an empty string (any remote address).

> So in my case, as my virtual machines are already accessible via hostname.something.com, there is no need to set listen_addr.

You shouldn't need to set `LISTEN_ADDR` unless you're wanting to use a non-default port or have the exporter bind to a specific interface.

> I can use exe as well but the machines where I wanted to deploy this exporter are managing Robotics projects. If any separate window is open on the GUI then it might disturb the flow of RPA process.

The EXE can be run silently by registering as a system service with `New-Service`.

**Comment by smartaquarius10** [comment]
Oh great. Are we allowed to use exe as a window service. Let me try this stuff right away.
