### ISSUE TITLE
Is it possible to use config file in case of window service?

### ISSUE THREAD

**Issue by smartaquarius10** [prometheus-community/windows_exporter#763]
Team,

While installing this exporter as window service can we use this parameter config.file. 

Or, we can only pass the parameters within the msiexec command at the time of installation.  

Thank you

**Comment by breed808** [comment]
It's been a while since I've looked at the config file from the context of an MSI installation. From memory, you'll need to ensure `config.file` is set in `EXTRA_FLAGS` when installing the MSI.
Importantly, the config file **must** be present prior to running the installer, or installation will fail.

**Comment by smartaquarius10** [comment]
Please correct me if I'm wrong. Now we can use like this

msiexec /i <path-to-msi-file> EXTRA_FLAGS="--config.file=config.yml"

**Comment by lodzo** [comment]
FYI,

I just ran into this issue and I am unable to get it to work, 

I ran the following command: 
```
msiexec.exe /i .\windows_exporter-0.16.0-amd64.msi EXTRA_FLAGS="--config.file=C:\Program Files\windows_exporter\config.yml"
```
The installer then fails with this message: 

> Service 'windows_exporter' (windows_exporter) failed to start. Verify that you have sufficient privileges to start system services.  

(FYI, I ran it in CMD Prompt window which was opened with Administrator Privileges)

But if I remove the ` EXTRA_FLAGS="--config.file=C:\Program Files\windows_exporter\config.yml"` section the installer then works.

**Comment by kago-dk** [comment]
@lodzo 
```
msiexec /x "C:\Program Files\windows_exporter\windows_exporter-0.16.0-amd64.msi" /quiet
pause
msiexec /i "C:\Program Files\windows_exporter\windows_exporter-0.16.0-amd64.msi" EXTRA_FLAGS="--config.file=""C:\Program Files\windows_exporter\config.yml"""
pause
```
works for me.

**Comment by lodzo** [comment]
@kago-dk 
Thank you that works for me too. 
I didn't realize the file path needed to be quoted as well.

**Comment by smartaquarius10** [comment]
@kago-dk , Great thanks a lot for sharing. Closing this issue.
