### ISSUE TITLE
Manual Service Configuration?

### ISSUE THREAD

**Issue by GerryWilko** [prometheus-community/windows_exporter#766]
Hello I would like to be able to run the standalone `exe` as a service manually.

Essentially I am trying to script the configuration and patching of this exporter install. I understand the msi will configure a service for you but I would like to configure the service from powershell if possible.

I tried simply running the .exe as a service argument but this doesnt work as it does not run it with the service hooks setup up correctly.

If I manually install the MSI I notice it configures the service with the following args (ignore the .exe path this is my install location):
```
"C:\windows-exporter\windows_exporter.exe" -config.file C:\windows-exporter\config.yml --log.format logger:eventlog?name=windows_exporter  --telemetry.addr :9182
```

However adding these manually to my `New-Service` command still does not seem to work. Is there an arg I am missing here? (ignore the .exe path this is my install location)

``` powershell
New-Service -Name WindowsExporterSvc `
      -BinaryPathName '"C:\windows-exporter\windows_exporter.exe" -config.file C:\windows-exporter\config.yml --log.format logger:eventlog?name=windows_exporter  --telemetry.addr :9182' `
      -StartupType Automatic `
      -DisplayName 'Prometheus Windows Exporter'
```

**Comment by steinbrueckri** [comment]
@GerryWilko But this is more a Windows "issue" I have not yet managed to create a service with PowerShell that makes sense and also starts, in the end, I switched to [nssm](https://nssm.cc/download).

**Comment by steinbrueckri** [comment]
@GerryWilko But this is more a Windows "issue" I have not yet managed to create a service with PowerShell that makes sense and also starts, in the end, I switched to [nssm](https://nssm.cc/download).

**Comment by breed808** [comment]
Are all the arguments missing in your service, or just the `config.file` arg? I note the `-config.file` argument in your example is missing a second `-`.

If you're still having trouble registering the service, let me know and I can look into it further.
