### ISSUE TITLE
Window exporter giving an error while installation on ms 2016. "window exporter" failed to start. Verify that you have sufficient privilege's to start system services

### ISSUE THREAD

**Issue by prab2014** [prometheus-community/windows_exporter#768]
Am facing the same issue.  I am using below system and wmi 16 ( fresh installation)
OS- MS window server 2016
version 10.0.14393
window exporter version -windows_exporter-0.16.0-amd64.msi
note: am having admin privileges' here. and this is fresh installation
error 

![image](https://user-images.githubusercontent.com/67781436/115849280-5cffd900-a442-11eb-8d45-9702fd92244e.png)

**Comment by breed808** [comment]
The error message present by the MSI installer is likely a red herring, as it is often caused by an incorrect installation command rather than insufficient permissions.

Which command are you using to run the installer?

**Comment by prab2014** [comment]
this works when enabled the service  WMI on window machine.
