### ISSUE TITLE
MQMQ collector is only fetching computer queues and ignoring rest

### ISSUE THREAD

**Issue by krdineshbny** [prometheus-community/windows_exporter#769]
Hi we are using wmi exporter extensively and monitoring more than 20k servers and use standard system collectors.
We are now testing to use the msmq collector but found that it is only collecting the computer queues.
The version we use is v0.11.0
Is there any any enhancements going around msmq collector?

**Comment by breed808** [comment]
There's only been a minor logging library change to the `msmq` collector since v0.11.0, so there's no enhancements you're missing out on.

Is the `msmq` collector outputting any error or output when run?

**Comment by krdineshbny** [comment]
@breed808  the collector is not outputting any error. But these lines in the code are limiting the queues being collected.
Can this be excluded in the code so that it captures all queues in a server.
WMI output is showing those queues in the server but since the collector is set to receive only the computer queues we are not able to make full use of this collector.


if msmq.Name == "Computer Queues" {
                                                continue
}


Here is the sample WMI output of the msmq

the endpoint is capturing only this metric
MSMQQueue.Name="Computer Queues"

Whereas it ignores the rest
MSMQQueue.Name="TESTSERVER\\private$\\TEST.upload"
MSMQQueue.Name="TESTSERVER\\private$\\admin_queue$"


`__GENUS                : 2
__CLASS                : Win32_PerfFormattedData_msmq_MSMQQueue
__SUPERCLASS           : Win32_PerfFormattedData
__DYNASTY              : CIM_StatisticalInformation
__RELPATH              : Win32_PerfFormattedData_msmq_MSMQQueue.Name="Computer Queues"
__PROPERTY_COUNT       : 13
__DERIVATION           : {Win32_PerfFormattedData, Win32_Perf, CIM_StatisticalInformation}
__SERVER               : TESTSERVER
__NAMESPACE            : root\cimv2
__PATH                 : \\TESTSERVER\root\cimv2:Win32_PerfFormattedData_msmq_MSMQQueue.Name="Computer Queues"
BytesinJournalQueue    : 37676
BytesinQueue           : 1270720
Caption                : 
Description            : 
Frequency_Object       : 
Frequency_PerfTime     : 
Frequency_Sys100NS     : 
MessagesinJournalQueue : 35
MessagesinQueue        : 780
Name                   : Computer Queues
Timestamp_Object       : 
Timestamp_PerfTime     : 
Timestamp_Sys100NS     : 
PSComputerName         : TESTSERVER

__GENUS                : 2
__CLASS                : Win32_PerfFormattedData_msmq_MSMQQueue
__SUPERCLASS           : Win32_PerfFormattedData
__DYNASTY              : CIM_StatisticalInformation
__RELPATH              : Win32_PerfFormattedData_msmq_MSMQQueue.Name="TESTSERVER\\private$\\TEST.upload"
__PROPERTY_COUNT       : 13
__DERIVATION           : {Win32_PerfFormattedData, Win32_Perf, CIM_StatisticalInformation}
__SERVER               : TESTSERVER
__NAMESPACE            : root\cimv2
__PATH                 : \\TESTSERVER\root\cimv2:Win32_PerfFormattedData_msmq_MSMQQueue.Name="TESTSERVER\\private$\\TEST.uploa
                         d"
BytesinJournalQueue    : 1111111111
BytesinQueue           : 222
Caption                : 
Description            : 
Frequency_Object       : 
Frequency_PerfTime     : 
Frequency_Sys100NS     : 
MessagesinJournalQueue : 3333
MessagesinQueue        : 44444
Name                   : TESTSERVER\private$\TEST.upload
Timestamp_Object       : 
Timestamp_PerfTime     : 
Timestamp_Sys100NS     : 
PSComputerName         : TESTSERVER



__GENUS                : 2
__CLASS                : Win32_PerfFormattedData_msmq_MSMQQueue
__SUPERCLASS           : Win32_PerfFormattedData
__DYNASTY              : CIM_StatisticalInformation
__RELPATH              : Win32_PerfFormattedData_msmq_MSMQQueue.Name="TESTSERVER\\private$\\admin_queue$"
__PROPERTY_COUNT       : 13
__DERIVATION           : {Win32_PerfFormattedData, Win32_Perf, CIM_StatisticalInformation}
__SERVER               : TESTSERVER
__NAMESPACE            : root\cimv2
__PATH                 : \\TESTSERVER\root\cimv2:Win32_PerfFormattedData_msmq_MSMQQueue.Name="TESTSERVER\\private$\\admin_queue
                         $"
BytesinJournalQueue    : 0
BytesinQueue           : 0
Caption                : 
Description            : 
Frequency_Object       : 
Frequency_PerfTime     : 
Frequency_Sys100NS     : 
MessagesinJournalQueue : 0
MessagesinQueue        : 0
Name                   : TESTSERVER\private$\admin_queue$
Timestamp_Object       : 
Timestamp_PerfTime     : 
Timestamp_Sys100NS     : 
PSComputerName         : TESTSERVER`

**Comment by breed808** [comment]
I'm not familiar with MSMQ; could there be any reason to scrape metrics for  "Computer Queues" only?
If not I think we should remove the hard-coded filter and use a flag for name selection (with all names selected by default).

**Comment by krdineshbny** [comment]
@breed808  yes, by default the collector should collect all queues and there should be an option to limit the queues based on flags. Can this be added to the project enhancements?
