### ISSUE TITLE
AMD system freezes after a day or so (using v0.16.0)

### ISSUE THREAD

**Issue by staking4ada** [prometheus-community/windows_exporter#770]
Have been using an older release on a different system without problems for a year. After installing 0.16.0 on a newly built AMD 9700X MSI B550M Mortar system, it seemed to work fine but completely froze the system each time after about a day. After HW-testing, swapping various components as well as the OS (tried Windows Server 2019 and Windows 10 2019 LTSC), I finally discovered disabling the windows_exporter service did the trick. Just providing feedback, no active follow-up necessary.

**Comment by breed808** [comment]
Are there any relevant logs for the system freezes?

I think it'd be worth running the exporter with a single collector enabled, such as `cpu`, and progressively add collectors until the freeze is triggered. That would confirm if a collector is responsible.

**Comment by staking4ada** [comment]
After more extensive research and trial/error, i have come to the conclusion one of the VM's I was running on the machine must have been corrupt/faulty, since the problem has not re-occured since I removed it. I will close the issue.
