### ISSUE TITLE
Service metrics - replace WMI by direct API calls

### ISSUE THREAD

**Issue by carlossscastro** [prometheus-community/windows_exporter#771]
Hi Team,

We are running some tests with the exporter to obtain the list of services running.
While this is running ok we have run into some issues in smaller VM's with limited resources.

We were wondering if you would consider replacing the collection of those metrics using direct API calls instead of WMI which is quite more costly for the vm's.
A direct API approach would be possible either by calling advapi32.dll directly or by using GO native implementation `x/sys/windows/svc/mgr` 

One thing to note is that we would probably lose the status of the service as it is not directly exposed by the api
https://github.com/prometheus-community/windows_exporter/blob/master/collector/service.go#L113-L126

We would be able to PR this, just wanted to know your opinion beforehand.

Cheers,

**Comment by carlpett** [comment]
Hey @carlossscastro,
Yes, we'd be happy to take a contribution for this! Ideally we aim to use perflib as much as possible, but it tends to lack statuses or textual information quite frequently. But please do submit a proposal :)

**Comment by carlossscastro** [comment]
Thanks @carlpett!

We'll work on the code changes in the next few days and submit our proposal for review.
Appreciate your quick reply.

**Comment by carlossscastro** [comment]
Hi @carlpett,

We have submitted a PR for review (https://github.com/prometheus-community/windows_exporter/pull/812).
We'd greatly appreciate some feedback on the approach!

Thanks!
