### ISSUE TITLE
[DOUBT] - How to monitor percentage of physical memory used?

### ISSUE THREAD

**Issue by DgoNascimento** [prometheus-community/windows_exporter#772]
Hey guys,

Could you help me better understand how I can monitor the percentage of physical memory used in Windows Server 2016?

Checking the metrics, we have:
windows_memory_commited_bytes
windows_memory_available_bytes

Both return in bytes, however when adding via promql, we obtained a result greater than the real memory of the server.

They would have some idea of how we could carry out this monitoring.

Thank you in advance.

**Comment by breed808** [comment]
Is the `windows_memory_available_bytes` metric displaying a value greater than the physical memory?
It'd be worth checking the value of `windows_cs_physical_memory_bytes` to see if it is accurate.

**Comment by bpickhardt** [comment]
The metric windows_memory_commited_bytes is the sum of both the physical and virtual memory.  Looking in task manager on the server you can see it displays committed memory as such.  Here's two different ways to check the percentage of memory.

Physical only:
(((windows_cs_physical_memory_bytes - windows_os_physical_memory_free_bytes) / windows_cs_physical_memory_bytes) * 100)

Committed:
windows_memory_committed_bytes/windows_memory_commit_limit
