### ISSUE TITLE
SMTP collector doesn't work

### ISSUE THREAD

**Issue by nadme92** [prometheus-community/windows_exporter#773]
Hi everyone , I have a problem with smtp collector , in fact when I add the collector "smtp" in registry base (regedit) , the windows_exporter service doesn't start.

Actually it works with others collectors like (iis,adfs,exchange...) but not with SMTP. Could someone help me for this case ? 

Thanks in advance.

![service windows_exporter](https://user-images.githubusercontent.com/63863231/116440713-0e42ac80-a851-11eb-896e-10e76edecf45.JPG)
![smtp collector](https://user-images.githubusercontent.com/63863231/116440716-0edb4300-a851-11eb-9f52-ca5129b2270d.JPG)

**Comment by breed808** [comment]
It may be the `smtp` collector is causing the exporter to crash. Are any event logs generated by the exporter before it crashes?
If there's no relevant event logs, could you run the exporter EXE with the `smtp` collector enabled and review the output?

**Comment by nadme92** [comment]
Hi , thank you for your answer , we have tried to install the last version of windows_exporter v.16 
Actually there is no error when we run the windows_exporter service with smtp collector but it's still doesn't work. In fact , after executing windows_exporter service we have some errors about smtp collector in event logs and the collector return value 0 when we check the metrics in http://localhost:9182/.

Also , we have tried to run the windows_exporter.EXE but this have no return... , this action display the prompt cmd and close it quickly.

Thanks for your help.

![event smtp](https://user-images.githubusercontent.com/63863231/116868904-efa53280-ac0f-11eb-82d1-8ee6df17cd89.JPG)
![smtp localhost](https://user-images.githubusercontent.com/63863231/116868908-f03dc900-ac0f-11eb-9677-680124fc21ed.JPG)

**Comment by breed808** [comment]
Thanks, this helps to narrow it down a bit.

You're missing the required counter `SMTP Server` for the collector. You'll need to ensure the counter is present before the collector can run.

This could be due to the IIS SMTP role not being installed, or an issue with the performance collectors on the machine.

You can try [rebuilding](https://docs.microsoft.com/en-us/troubleshoot/windows-server/performance/manually-rebuild-performance-counters) the collectors if the role is already installed but there are problems with the performance counter.

**Comment by Adel-CHT** [comment]
Hello,

Is there no solution for this case? 
Is there anyone who had the same problem and managed to solve it ?

thank you in advance.

**Comment by Adel-CHT** [comment]
Hi, Thanks for your answer ,

The SMTP role is installed on the machine but I don't understand what do you mean about the performance collectors. How can I do to rebuild the collectors?

Thanks in advance for your help
![image](https://user-images.githubusercontent.com/83639786/118492931-dc6e8880-b720-11eb-9752-1a17d5c2fe0b.png)

**Comment by breed808** [comment]
You'll want to verify that SMTP metrics are present in either the Performance Monitor:
![Screenshot_20210519_065738](https://user-images.githubusercontent.com/3103817/118722463-852afe00-b86f-11eb-909c-70873c0ddce9.png)

or with `Get-Counter`. E.G.

```powershell
Get-Counter -Listset * | Select CounterSetName | Sort-Object -Property CounterSetName
```

**Comment by Adel-CHT** [comment]
Thank you for your answer.
I check the perf monitor and the SMTP metrics exists as you can see on this screenshot :

![image](https://user-images.githubusercontent.com/83639786/118774583-494f6300-b886-11eb-9dba-86dada865dde.png)

**Comment by breed808** [comment]
Apologies for the delay; do you receive the same SMTP Server entry with the `Get-Counter` command?

**Comment by breed808** [comment]
Closing due to a lack of activity
