### ISSUE TITLE
Container collector datasource is missing

### ISSUE THREAD

**Issue by Wittionary** [prometheus-community/windows_exporter#776]
Hello! The [docs](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.container.md) for the container collector lacks a datasource or WMI class.

It would be good to know:
- where the metrics are coming from and
- how the container collector is expected to be used. 

Looking through older issues, the answers to the above questions were unclear to me.

**Comment by breed808** [comment]
Unlike most of our collectors, the `container` collector uses [hcsshim](https://github.com/Microsoft/hcsshim) as a source.
You're right, the documentation could be improved to specify the collector use case ([Windows Containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/about/)).

Would you be comfortable submitting a pull request for this?

**Comment by Wittionary** [comment]
After reading additional documentation, yes, I believe so. I'll submit a PR shortly.
