### ISSUE TITLE
Is it possible to integrate this with splunk?

### ISSUE THREAD

**Issue by smartaquarius10** [prometheus-community/windows_exporter#782]
Team, 
In my organisation we already have splunk setup. Is it possible pass metrics from this package to splunk directly. Without any usage of Prometheus node. 

Thank you

**Comment by breed808** [comment]
The [Splunk Smart Agent](https://www.splunk.com/en_us/blog/devops/metrics-from-prometheus-exporters-are-now-available-with-the-sfx-smart-agent.html) sounds like what you're looking for.

**Comment by breed808** [comment]
From the description I don't think that's the case:

> By including a new prometheus-exporter monitor, our Smart Agent scrapes metrics from an exporter and sends them to Splunk. Previously, our Metric Proxy could be setup as the gateway to use Splunk as a storage backend for Prometheus. Our new prometheus-exporter monitor cuts out the requirement for going through Prometheus and instead replaces it with our agent.
