### ISSUE TITLE
nvidia smi metrics for GPU cards

### ISSUE THREAD

**Issue by oliverpool** [prometheus-community/windows_exporter#785]
Hi,

I saw that there are already 3 issues mentionning gpu monitoring (#725 , #457 and #573), but all of them seem to depend on windows API.

This allows access to a couple of metrics, like temperature, memory usage and power consumption.

I would propose to add a collector calling the `nvidia-smi.exe` executable (usually located at `C:\Program Files\NVIDIA Corporation\NVSMI\nvidia-smi.exe`).

There is a repo which already does this: https://github.com/zhebrak/nvidia_smi_exporter/blob/master/nvidia_smi_exporter.go#L18
And I would be willing to try to make a PR to integrate a similar logic into this exporter (disabled by default, obviously).

Do you think that this is a good idea?

**Comment by breed808** [comment]
As a general rule we avoid the use of external binaries with this exporter, instead preferring to source metrics directly from the OS using Perflib or WMI (happy to be corrected if I'm wrong @carlpett).
If an external binary is required, it would be best to use a separate exporter such as the one provided by @zhebrak.

#725 looks promising, as it uses the NVML library to query metrics.

**Comment by rubu** [comment]
@breed808 in #725 I actually ended up with using wddm metrics from perflib, since the NVML on Windows only works for cards that are in TCM not wddm mode, but I'll still open a pull request, since it seems that someone has already forked the feature so I guess its useful not only to me.

**Comment by oliverpool** [comment]
I don’t need this feature anymore, so closing this.
