### ISSUE TITLE
cs collector wmi_cs_logical_processors metric reports false data

### ISSUE THREAD

**Issue by 1sttec** [prometheus-community/windows_exporter#786]
On two test desktops the cs collector wmi_cs_logical_processors metric returns 0. On a test server it returns 65535. Please advise.
  
version: 0.16.0

**Comment by 1sttec** [comment]
systeminfoapi is using GetSystemInfo (lpSysteminfo) but doc here [https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/ns-sysinfoapi-system_info](https://docs.microsoft.com/en-us/windows/win32/api/sysinfoapi/ns-sysinfoapi-system_info) says to use GetLogicalProcessorInformation for logical core count instead of GetSystemInfo.dwNumberOfProcessors  
  
> ...
> dwNumberOfProcessors
> The number of logical processors in the current group. To retrieve this value, use the GetLogicalProcessorInformation function.
> ...

**Comment by carlpett** [comment]
@benridley @retryW any input?

**Comment by carlpett** [comment]
@1sttec Thanks for that extra bit of info! What versions of Windows are you testing on?

**Comment by 1sttec** [comment]
Server 2019 = 0  
Server 2016 = 0  
Server 2012 R2 = 65535  
Win 7 & 10  = 0

**Comment by benridley** [comment]
Thanks @carlpett and @1sttec!

Apologies for this, looks like one of the struct fields was incorrectly sized, so when accessing them Go would be reading the wrong memory. 

I've created a PR here to fix the issue: https://github.com/prometheus-community/windows_exporter/pull/788

**Comment by benridley** [comment]
@1sttec the fix has been merged to master now. I've tested this on a 2016 machine and it worked ok, but I'm curious how it'll go on your machines since they were getting different values. If you get a chance to test please do so and let us know. Cheers!

**Comment by 1sttec** [comment]
It appears windows_cs_logical_processor is now reporting sockets * cores but not the true logical processors # which would include those available via hyper-threading.

**Comment by benridley** [comment]
Thanks @1sttec, seems like this might be a consequence of the function we use. I found [this](https://devblogs.microsoft.com/oldnewthing/20200824-00/?p=104116) which suggests similar problems with our underlying info. 

I'll try converting the metric to use the function specified in that article which should fix this.

**Comment by benridley** [comment]
Hi @1sttec, can you please try building [my branch here](https://github.com/benridley/windows_exporter/tree/bugfix_num_cpu) and seeing if it reports the correct CPU count for you?

It's looking good on my windows machine, but so was the old way - So I just want to make sure. Thank you !
