### ISSUE TITLE
Windows exporter service stops when ever CPU or memory is high

### ISSUE THREAD

**Issue by naveenkumarsp** [prometheus-community/windows_exporter#794]
we have been experiencing the service being stopped state when ever the system has high CPU or memory. 

I have used the 64bit installer to configure exporter and the service type is kept to automatic. 

Is there any configuration i could ensure the service does not stops as monitoring metrics is quite important.  As alternative i am considering to write a script to check the service in certain interval and start it. But its more like a hack than solution.

**Comment by breed808** [comment]
When installed from the MSI, the `windows_exporter` service will attempt to restart each minute on failure:
![service_recovery](https://user-images.githubusercontent.com/3103817/121757174-02404f00-cb60-11eb-878f-7a287f350298.png)

Are there any relevant exporter messages in the event log when the service stops?

**Comment by zenzedoon** [comment]
I have the same issue , when either CPU or Memory are hight the windows_exporter stop working and can't restart , the service is putted to restart on failure set to automatic.
Any help for this issue , it is so critical for me .

**Comment by breed808** [comment]
@zenzedoon have you seen any relevant output from the exporter, or in the Event Viewer when running the exporter as a service?

**Comment by zenzedoon** [comment]
@breed808 i have this error on tyhe windows Application events: 
![image](https://user-images.githubusercontent.com/50891244/158037466-7ba0a4ee-6670-492e-a665-e3c47cb5fd64.png)
this error appears every 1 minutes on all VMs that has windows_exporter installed on it

**Comment by breed808** [comment]
That entry is unrelated to the exporter stopping under high load.

From memory, that directory should have been created by the MSI package during installation. If that's not the case, you can raise a separate issue.

**Comment by zenzedoon** [comment]
i don't have another error on the event , except the cpu or memory hight usage

**Comment by breed808** [comment]
Could you run the exporter with `log.level=debug`? Without any info it'll be hard to identify and resolve the issue :disappointed:

**Comment by zenzedoon** [comment]
Hello guys , The only solution that i found is to  add a task schedular that check the status of windows_exporter and reexecute it again if the status of the service is stopped, i made this by creation an ansible role to setup windows_exporter and enabled this task schedular .
now i have only some downtime when the CPU or RAM are 100% ( the windows_exporter stop working and the task schedular reexecute it ).

**Comment by zpeters** [comment]
We are experiencing this same issue.  We have a regular job that is maxing out at 100% cpu and the monitoring "dies" for that time.  For background we are using the windows_exporter bundled with Grafana Agent.  We are going to try to capture some debug logs to share, though it may be a few days

**Comment by fabudor** [comment]
Seems to me that the service exits with code 0 indicating that the service has done its job successfully. The restart of a service will only occur when the service has exited with a failure (a non 0 exit code)

**Comment by saber13812002** [comment]
i have installed prometheus windows_exporter by windows_exporter-0.26.0-amd64.msi and its give my server more and more memory about 4gb

this is my configuration

```
--collectors.enabled 'cpu,memory,logical_disk,net'"
```

changed it to this:

```
ad,adcs,adfs,cache,cpu,cpu_info,cs,container,diskdrive,dfsr,dhcp,dns,exchange,fsrmquota,hyperv,iis,logical_disk,logon,memory,mscluster_cluster,mscluster_network,mscluster_node,mscluster_resource,mscluster_resourcegroup,msmq,mssql,netframework_clrexceptions,netframework_clrinterop,netframework_clrjit,netframework_clrloading,netframework_clrlocksandthreads,netframework_clrmemory,netframework_clrremoting,netframework_clrsecurity,net,os,printer,process,remote_fx,scheduled_task,service,smb,smbclient,smtp,system,tcp,teradici_pcoip,time,thermalzone,terminal_services,textfile,vmware_blast    
```


That's the correct approach. To summarize:

1. **Open Command Prompt as Administrator:**
   - Press `Win + R`, type `cmd`, and press `Enter`.
   - Right-click on `Command Prompt` in the Start menu and select "Run as administrator."

2. **Reconfigure `windows_exporter`:**
   - In the Command Prompt, run the following command to set the desired collectors:
   
     ```cmd
     sc config windows_exporter binPath= "C:\Program Files\windows_exporter\windows_exporter.exe --collectors.enabled 'cpu,memory,logical_disk,net'"
     ```

3. **Restart the Service:**
   - After reconfiguring, restart the `windows_exporter` service by running:

     ```cmd
     net start windows_exporter
     ```

4. **Monitor the Service:**
   - Check your server's memory usage to ensure the changes have taken effect and that memory usage is now within expected limits.

This should help you configure `windows_exporter` to use fewer resources by disabling unnecessary collectors. If you need any further assistance, feel free to ask!
