### ISSUE TITLE
No monitoring for disks without mounted partitions

### ISSUE THREAD

**Issue by rob-scheepens** [prometheus-community/windows_exporter#795]
While doing fio testing on \\.\PhysicalDrive1 I was under the impression that this corresponded to HarddiskVolume1, sample:

`windows_logical_disk_free_bytes{volume="HarddiskVolume1"} 1.1010048e+08`

However, when I looked at the numbers more closely, none of them made sense. The sample above for example shows some 100MB free, whereas the disk is a RAW device of 24GB. As an experiment I created and mounted a partition on \\.\PhysicalDrive1 , and shortly thereafter I got metrics for HarddiskVolume3, sample:

`windows_logical_disk_free_bytes{volume="HarddiskVolume3"} 2.5697452032e+10`

This matches 24GB much more closely. Thus, it appears that no monitoring objects are created for disks that have no (mounted) partitions, as only HarddiskVolumeX objects are monitored. This makes the windows_exporter unusuable for my projects, as I typically run IO performance tests on raw devices so that results are not skewed by filesystem mechanisms, such as filesystem level caching. Since I expect this to be related to the fact that no Logical Disk objects are created by Windows for non-mounted volumes/disks, I would like to propose to also implement metrics of the [Win32_PerfFormattedData_PerfDisk_PhysicalDisk class](https://docs.microsoft.com/en-us/previous-versions/aa394262(v=vs.85)), which are identical to their LogicalDisk counterparts.

Was there a conscious decision to implement LogicalDisk metrics instead of PhysicalDisk?

**Comment by rob-scheepens** [comment]
I created an experimental implementation of physical_disk.go at https://github.com/rob-scheepens/windows_exporter/commit/4576fc0675cc8cc4148dc483949787665daca27b, but I am not seeing metrics yet. The collector is working though:
```
C:\>windows_exporter.exe --collectors.enabled="physical_disk" --log.level=debug
time="2021-06-07T23:17:10-07:00" level=debug msg="Initializing SWbemServices" source="exporter.go:248"
time="2021-06-07T23:17:10-07:00" level=info msg="Enabled collectors: physical_disk" source="exporter.go:347"
time="2021-06-07T23:17:10-07:00" level=info msg="Starting windows_exporter (version=, branch=, revision=)" source="exporter.go:399"
time="2021-06-07T23:17:10-07:00" level=info msg="Build context (go=go1.15.5, user=, date=)" source="exporter.go:400"
time="2021-06-07T23:17:10-07:00" level=info msg="Starting server on :9182" source="exporter.go:403"
time="2021-06-07T23:17:10-07:00" level=info msg="TLS is disabled." source="gokit_adapter.go:38"
time="2021-06-07T23:17:26-07:00" level=debug msg="collector physical_disk succeeded after 0.000000s." source="exporter.go:209"
time="2021-06-07T23:18:27-07:00" level=debug msg="collector physical_disk succeeded after 0.000000s." source="exporter.go:209"
time="2021-06-07T23:18:29-07:00" level=debug msg="collector physical_disk succeeded after 0.001005s." source="exporter.go:209"
time="2021-06-07T23:18:36-07:00" level=debug msg="collector physical_disk succeeded after 0.000000s." source="exporter.go:209"
time="2021-06-07T23:27:54-07:00" level=debug msg="collector physical_disk succeeded after 0.000000s." source="exporter.go:209"
time="2021-06-07T23:27:56-07:00" level=debug msg="collector physical_disk succeeded after 0.000999s." source="exporter.go:209"
```
What did I miss?

**Comment by rob-scheepens** [comment]
I created an experiment in https://github.com/rob-scheepens/windows_exporter/blob/master/collector/physical_disk.go and it seems to be kind of working:
```windows_physical_disk_write_bytes_total{disk="1"} 3.2061259776e+10```
However, the counter data doesn't seem to match yet with PerfMon.

**Comment by rob-scheepens** [comment]
I overlooked the fact that write_bytes apparently is cumulative. When using a rate() I got throughput numbers I expected.

**Comment by carlpett** [comment]
@rob-scheepens Nice work! :tada: Would you like to create a PR on the new collector?
As for why logical_disk has a collector and physical_disk not, I don't clearly remember... I think it might simply have mapped better to the common file system monitoring most users wanted.

**Comment by rob-scheepens** [comment]
@carlpett : that reasoning makes sense. Most people will use volumes instead of raw disks. ;)

I created PR https://github.com/prometheus-community/windows_exporter/pull/803.
