### ISSUE TITLE
Working Set - Private process counter is collected but not exposed as a metric

### ISSUE THREAD

**Issue by bsosnader** [prometheus-community/windows_exporter#797]
We were using windows_exporter to collect process metrics and noticed the Working Set - Private counter is not one of the metrics exposed. However, it is collected here: https://github.com/prometheus-community/windows_exporter/blob/72c46664dbd73185f19b5b8b2619ea2a17b2e706/collector/process.go#L170

Is there any reason why this is not exposed? Could we contribute this by adding a metric following the pattern of the other process metrics?

**Comment by breed808** [comment]
Hi @bsosnader, this metric appears to have been missed during the initial implementation, along with `Working Set Peak`.
You're more than welcome to submit a PR to fix this. Otherwise I can submit a fix.

**Comment by bsosnader** [comment]
Hey @breed808 thanks for taking a look--would appreciate if you were able to submit a fix, I planned to but have been lacking the time
