### ISSUE TITLE
WIndows_Exporter like a pod in k8s

### ISSUE THREAD

**Issue by OKAYRO** [prometheus-community/windows_exporter#798]
Hello, I was deployed windows_exporter like windows pod ( with helm chart)
on Windows nodes, 
How can I change config or force this pod with windows exporter to collect data from 
windows node on which he is, without install on windows node exporter, only use exporter which installed on windows pod?

Many Thanks,
Alex

**Comment by breed808** [comment]
Hi Alex, you'll want to look at #546.
