### ISSUE TITLE
net collector: windows_net_current_bandwidth name and unit don't follow best practices

### ISSUE THREAD

**Issue by max-len** [prometheus-community/windows_exporter#800]
1. As per [Prometheus best practices](https://prometheus.io/docs/practices/naming/#metric-names) metric names should **have a suffix describing the unit**; looking up metric units in docs is cumbersome: `windows_net_current_bandwidth_bits`

2. As per [Prometheus best practices](https://prometheus.io/docs/practices/naming/#base-units) metrics should **use base units**, allowing for easy comparison: `windows_net_current_bandwidth_bytes`
    > To avoid confusion combining different metrics, always use bytes, even where bits appear more common.

3. There should be a **consensus with [*NIX node exporter](https://github.com/prometheus/node_exporter)** regarding the metric name, either `speed` or `bandwidth`. I'd vote for the latter; surely it needs further discussion.

**Comment by breed808** [comment]
Yes, I think this should be renamed to `windows_net_current_bandwidth_bytes`. We'll want to follow the Perflib metric name "Current Bandwidth" as closely as possible, and stick with `bytes` as the base unit.

Would you like to submit a PR to correct the metric name?
