### ISSUE TITLE
Getting error: cannot find module providing package github.com/prometheus/common/log

### ISSUE THREAD

**Issue by shabeermm** [prometheus-community/windows_exporter#801]
C:\Users\myuser>go get -u github.com/prometheus-community/windows_exporter
go: downloading github.com/prometheus-community/windows_exporter v0.16.0
go: downloading github.com/prometheus/client_golang v1.8.0
go: downloading github.com/StackExchange/wmi v0.0.0-20180725035823-b12b22c5341f
go: downloading github.com/prometheus/common v0.15.0
go: downloading github.com/prometheus/exporter-toolkit v0.5.1
go: downloading golang.org/x/sys v0.0.0-20201015000850-e3ed0017c211
go: downloading github.com/go-kit/kit v0.10.0
go: downloading github.com/sirupsen/logrus v1.6.0
go: downloading github.com/StackExchange/wmi v0.0.0-20210224194228-fe8f1750fd46
go: downloading github.com/Microsoft/hcsshim v0.8.6
go: downloading github.com/dimchansky/utfbom v1.1.0
go: downloading github.com/leoluk/perflib_exporter v0.1.0
go: downloading github.com/sirupsen/logrus v1.8.1
go: downloading github.com/dimchansky/utfbom v1.1.1
go: downloading github.com/golang/protobuf v1.4.3
go: downloading github.com/prometheus/procfs v0.2.0
go: downloading golang.org/x/crypto v0.0.0-20201208171446-5f87f3452ae9
go: downloading github.com/go-ole/go-ole v1.2.1
go: downloading github.com/Microsoft/hcsshim v0.8.17
go: downloading github.com/konsorten/go-windows-terminal-sequences v1.0.3
go: downloading github.com/go-logfmt/logfmt v0.5.0
go: downloading google.golang.org/protobuf v1.23.0
go: downloading github.com/go-ole/go-ole v1.2.5
go: downloading golang.org/x/crypto v0.0.0-20210513164829-c07d793c2f9a
go: downloading github.com/mwitkow/go-conntrack v0.0.0-20190716064945-2f068394615f
go: downloading golang.org/x/net v0.0.0-20200625001655-4c5254603344
go: downloading github.com/jpillora/backoff v1.0.0
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/Microsoft/go-winio v0.4.14
go: downloading github.com/Microsoft/go-winio v0.5.0
go: downloading golang.org/x/text v0.3.6
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.2-0.20181231171920-c182affec369
go: downloading go.opencensus.io v0.22.4
go: downloading github.com/containerd/cgroups v1.0.1
go: downloading go.opencensus.io v0.23.0
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
github.com/prometheus-community/windows_exporter imports
        github.com/prometheus-community/windows_exporter/collector imports
        github.com/prometheus/common/log: cannot find module providing package github.com/prometheus/common/log

It seems github.com/prometheus/common/log module was removed recently, but windows exporter still references it ?
Can you check and point to the correct log / resolve the issue ?

**Comment by nickmanor** [comment]
I can confirm the same issue.
