### ISSUE TITLE
Lots of warnings: No Network Stats for container

### ISSUE THREAD

**Issue by bip7686** [prometheus-community/windows_exporter#806]
I'm running the windows exporter through wins for my kubernetes cluster.
The windows exporter is printing a lot of messages like:
```
time="2021-06-15T18:28:29+02:00" level=info msg="No Network Stats for container: 52026722c95ef2d36d3bc894dfe4ee1e910277c315e4878fa43b3dddc533e5e2" source="container.go:231"
```

WMI Setup:
```time="2021-06-15T14:26:06+02:00" level=warning msg="No where-clause specified for service collector. This will generate a very large number of metrics!" source="service.go:41"
time="2021-06-15T14:26:06+02:00" level=info msg="Enabled collectors: cache, system, os, cpu, memory, logical_disk, cs, container, service, net" source="exporter.go:347"
time="2021-06-15T14:26:06+02:00" level=info msg="Starting windows_exporter (version=0.16.0, branch=master, revision=f316d81d50738eb0410b0748c5dcdc6874afe95a)" source="exporter.go:399"
time="2021-06-15T14:26:06+02:00" level=info msg="Build context (go=go1.15.6, user=appveyor-vm\\appveyor@appveyor-vm, date=20210225-10:52:19)" source="exporter.go:400"
time="2021-06-15T14:26:06+02:00" level=info msg="Starting server on 0.0.0.0:9100" source="exporter.go:403"
time="2021-06-15T14:26:06+02:00" level=info msg="TLS is disabled." source="gokit_adapter.go:38"
time="2021-06-15T14:26:06+02:00" level=error msg="Failed to start service: The service process could not connect to the service controller." source="exporter.go:337"
```

Windows Node:
BuildNumber: 17763
Version: 10.0.17763

**Comment by carlpett** [comment]
Just to be clear, is this about missing data that should be there, or about excessive logging? Does the containers actually have network interfaces attached to them?

**Comment by Luis-TT** [comment]
The data seems to be there. How would I check if the containers have network interfaces attached to them?

**Comment by jsturtevant** [comment]
checkout how this can be done with [hostprocess containers](https://github.com/prometheus-community/windows_exporter/blob/master/kubernetes/kubernetes.md#kubernetes-quick-start). There are also examples on wiring all this up with the rest of the Prometheus stack in https://github.com/prometheus-operator/kube-prometheus/blob/main/docs/windows.md
