### ISSUE TITLE
Inaccurate windows_cpu_time_total value

### ISSUE THREAD

**Issue by sdemircan** [prometheus-community/windows_exporter#810]
We are running windows_exporter on Windows Server 2019 Datacenter. I am trying calculate total cpu usage percentage by following query:

```100 - (avg by (instance) (irate(windows_cpu_time_total{mode="idle"}[2m])) * 100)```

Query's result is not same as task the manager's reported value. For example this query's result is 2%, however task manager reports cpu utilization is 25%. Am I doing anything wrong?

**Comment by katepangLiu** [comment]
Maybe issue #494 can help you.

**Comment by breed808** [comment]
There's been some good discussion of `windows_cpu_time_total` and CPU frequency in #787

**Comment by andonovski** [comment]
> There's been some good discussion of `windows_cpu_time_total` and CPU frequency in #787

I know this is old thread, but just to add something to keep it alive until this is solved. Maybe some more people have this issue.

I have same problem with CPU usage in %. Whatever query I try it's not showing what task manager is showing, not even close.
It seems that higels is on the right track. I hope we will soon have this solved.

**Comment by veruzi** [comment]
Any fix/workaround for this?
