### ISSUE TITLE
windows_exporter-0.16.0-amd64.exe can't find textfile

### ISSUE THREAD

**Issue by scotgopal** [prometheus-community/windows_exporter#811]
Moments ago, I installed windows_exporter using the `windows_exporter-0.16.0-amd64.exe`.  It was all fine at the beginning, up until a point where the programme was not able to find the textfile in `C:\Program Files\windows_exporter\textfile_inputs`. Upon doing some probing, I found that the windows_exporter folder was not even created yet. 

Immediate solution:
Installed using the `windows_exporter-0.16.0-amd64.msi` package, and it ran fine.

**Comment by carlpett** [comment]
If you do not use the installer, you'll need to provide a lot more context yourself, such as a textfile directory, so this is expected behaviour.
Using the .msi is intended as the 95%-of-the-time solution when you do not have specific needs in your environment.
