### ISSUE TITLE
High memory usage on .16.0

### ISSUE THREAD

**Issue by jesus-velez** [prometheus-community/windows_exporter#813]
Hello!

I have a couple of servers reporting high memory usage by the windows_exporter. I am using the default configuration/collectors. Is there anyway to limit the resource usage on the exporter?

![Screen Shot 2021-07-01 at 3 05 13 PM](https://user-images.githubusercontent.com/39685313/124183387-c113ce80-da7d-11eb-8df8-6975959afa96.png)

Exporter version:
`windows_exporter, version 0.16.0 (branch: master, revision: f316d81d50738eb0410b0748c5dcdc6874afe95a)
  build user:       appveyor-vm\appveyor@appveyor-vm
  build date:       20210225-10:52:19
  go version:       go1.15.6
  platform:         windows/amd64`

OS Name:                   Microsoft Windows Server 2016 Standard
OS Version:                10.0.14393 N/A Build 14393

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
   1260     142 12748860   12496424 110,102.69  11388   0 windows_exporter

**Comment by breed808** [comment]
How long has the exporter been running on the affected hosts? When initially started, how much memory does the exporter use?

Graphing `go_memstats_alloc_bytes`, `go_memstats_alloc_bytes_total` and `go_memstats_frees_total` for this host should provide more info.

I'd also recommend navigating to http://hostname:9182/debug/pprof/heap and uploading the output here.

**Comment by jesus-velez** [comment]
Thanks for following up with me. The box has been up for 49 days so at least that much. I there any metric that records that information? 

`go_memstats_alloc_bytes`

![Screen Shot 2021-07-02 at 10 11 23 AM](https://user-images.githubusercontent.com/39685313/124294953-e8ba7380-db1d-11eb-9786-7037abe7498b.png)

`go_memstats_alloc_bytes_total`

![Screen Shot 2021-07-02 at 10 10 43 AM](https://user-images.githubusercontent.com/39685313/124294851-c7f21e00-db1d-11eb-89c2-0c0db4ecc1f4.png)

`go_memstats_frees_total`

![Screen Shot 2021-07-02 at 10 12 38 AM](https://user-images.githubusercontent.com/39685313/124295082-0982c900-db1e-11eb-9cbb-be8a492601c5.png)

[heap.zip](https://github.com/prometheus-community/windows_exporter/files/6755466/heap.zip)

**Comment by datamuc** [comment]
I have a similar thing, but we are on 0.15:
The go_memstat* things look pretty normal to me:

go_memstats.*bytes are very constant during the week:
![go_memstats_bytes](https://user-images.githubusercontent.com/51400/124760234-d29f1f80-df30-11eb-9266-1ddad5a19017.png)

go_memstats_alloc_bytes and frees_total:
![go_memstats_alloc_bytes](https://user-images.githubusercontent.com/51400/124760300-e3e82c00-df30-11eb-88e7-2a5bf4070c4b.png)
![go_memstats_frees_total](https://user-images.githubusercontent.com/51400/124760311-e77bb300-df30-11eb-9df3-9baa22664234.png)

What goes through the roof is windows_process_private_bytes:
![windows_process_private_bytes](https://user-images.githubusercontent.com/51400/124760800-640e9180-df31-11eb-9b4e-1d193a08c7e1.png)

And for what it's worth, pprof/heap and pprof/allocs:
[pprof.zip](https://github.com/prometheus-community/windows_exporter/files/6777274/pprof.zip)

**Comment by jesus-velez** [comment]
I have both versions deployed and .15 also displays the same behavior. Whatever I can do to help please do let me know. @breed808.

**Comment by breed808** [comment]
Thanks all, this is really helpful info. I'll get through the heap/alloc dumps, and will try to reproduce the issue.

**Comment by datamuc** [comment]
It doesn't happen on every machine, but if it happens it seems to be the service collector that is leaking memory.

In general the windows_exporter is leaking memory anyways, it's just that it **may** leak with the service collector a huge amount of memory.

**Comment by jesus-velez** [comment]
@breed808, I don't know what @datamuc experience is but it seems like mostly servers with sql server installed get this issue. I have the exporter on application servers and database servers and I have yet to notice anything on the application servers. Another point to add is that I have seeing it on both VM and physical servers.

**Comment by breed808** [comment]
Unfortunately the heap dumps aren't too helpful: they're showing similar results to the `go_memstats_alloc_bytes_total` metric. @datamuc I wasn't able to view the dumps you provided, could you re-generate and upload them? Yours are ASCII text files, while the dump @jesus-velez submitted was gzip compressed data.

Are we able to confirm if the excessive memory consumption occurs when disabling all collectors that use WMI as a metric source? These are currently cpu_info, fsrmquota, msmq, mssql, remote_fx, service, system, terminal_services, and thermalzone

**Comment by datamuc** [comment]
> Unfortunately the heap dumps aren't too helpful: they're showing similar results to the `go_memstats_alloc_bytes_total` metric. @datamuc I wasn't able to view the dumps you provided, could you re-generate and upload them? Yours are ASCII text files, while the dump @jesus-velez submitted was gzip compressed data.

Ok, I've accessed the urls with a browser that gave me the text files. Now I used Invoke-Webrequest and I got the binary stuff:

[pprof.zip](https://github.com/prometheus-community/windows_exporter/files/6815840/pprof.zip)

I did some more tests, in any case there was an infinite powershell loop running that hit the /metrics endpoint.

In the zip there are 2 directories, host2 are the debug/pprof infos of a host that doesn't leak so much. I've done 2 snapshots in every test.


host1 is a host that has a pretty high leak, pprof1 and pprof2 where done with the following config:

```yaml
collectors:
    enabled: "cpu,cs,logical_disk,net,os,system,textfile,memory,logon,tcp,terminal_services,thermalzone,iis,process"
```
and pprof3 and pprof4 where done with:
```
collectors:
    enabled: "cs,logical_disk,net,os,textfile,memory,logon,tcp,iis,process"
```

> Are we able to confirm if the excessive memory consumption occurs when disabling all collectors that use WMI as a metric source? These are currently cpu_info, fsrmquota, msmq, mssql, remote_fx, service, system, terminal_services, and thermalzone

I've disabled all the mentioned collectors (pprof3/4) but it was still leaking.

windows_process_private_bytes while the endless loop was running:
![image](https://user-images.githubusercontent.com/51400/125620123-a6ce7dc1-aab4-4ee1-bc9a-8ccc53f7737e.png)

And here without the loop, just normal prometheus scraping:

![image](https://user-images.githubusercontent.com/51400/125620360-700dd08f-47f0-4d6c-989f-053263db55b8.png)

**Comment by breed808** [comment]
Hmm, those heap dumps are similar to those submitted earlier, with only a few MB allocated :disappointed:

@datamuc from previous comments, it appears the `service` collector may be responsible, but host1 in your previous comment doesn't have it enabled?
It would be worth identifying the collectors responsible for the leaking. Are you free to do that?

I'll see if I can identify the commit or exporter version where the leaking was introduced.

**Comment by datamuc** [comment]
> Hmm, those heap dumps are similar to those submitted earlier, with only a few MB allocated 😞
> 
> @datamuc from previous comments, it appears the `service` collector may be responsible, but host1 in your previous comment doesn't have it enabled?
> It would be worth identifying the collectors responsible for the leaking. Are you free to do that?
> 
> I'll see if I can identify the commit or exporter version where the leaking was introduced.

Yes, we have deactivated the service collector globally because it contributed a lot to the leaks. It is better now, but still not good, so my guess is that it has something to do with the number of metrics returned? service collector has a lot of metrics.

I can do some more testing tomorrow I guess.

**Comment by datamuc** [comment]
The config:
```yaml
log:
  level: fatal
collectors:
  enabled: "process"
collector:
  process:
    whitelist: "windows_exporter|exporter_exporter"
    blacklist: ""
```

And I did run this powershell script for an hour or so:

```powershell
while($true) {
   $request = Invoke-Webrequest -URI http://127.77.1.1:5758/metrics
   $line = $request.RawContent -split "[`r`n]" | select-string -Pattern 'windows_process_private_bytes.*windows_exporter'
   ($line -split " ")[-1]
}
```

That resulted in the following graph of windows_process_private_bytes:
![image](https://user-images.githubusercontent.com/51400/125813812-7389ace2-43f7-4aef-a825-4b5a1361d55c.png)

So, if it is a collector then process collector is one of them.

**Comment by breed808** [comment]
I've been able to reproduce this with the script. The memory leak is present in the `process` collector prior to 4f891338935c9c327d32c9cc1fce72cba1f426f3, so I'm inclined to believe it may be an exporter-wide leak that isn't specific to one collector.

Alternatively, it may be a leak on the Windows side when certain WMI and/or Perflib queries are submitted. The Go memory stats aren't showing any leaks, which isn't too helpful.

I'll continue testing to see if I can identify the commit that introduced the leak.

**Comment by datamuc** [comment]
I've did some more testing. If I only enable the textfile exporter, then there is no leak.

I tried to investigate a bit. I've seen that the windows_exporter uses a library from the perflib_exporter to access most of the performance_values. Maybe both implementations, the perflib and the old WMI one are leaking?

What follows maybe wrong, I've tried to reason about the code:

I've looked into what [telegraf](https://github.com/influxdata/telegraf) is doing, because it does a similar thing. They open pdh.dll and call functions from this library. Before they [open](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/win_perf_counters/performance_query.go#L58) a new query  they close the old one?

The Close call leads to [this code](https://github.com/influxdata/telegraf/blob/master/plugins/inputs/win_perf_counters/pdh.go#L276) where they explicitly mention to free some memory.

Then I looked into the perflib_exporter, it comes with a perlfib package which provides access to the performance counters. Unlike telegraf they are not using pdh.dll because it is [to high level?](https://github.com/leoluk/perflib_exporter/blob/master/perflib/perflib.go#L6)

Anyway, it does syscall.HKEY_PERFORMANCE_DATA to get the counters. So I googled a bit for it and found [this page](https://docs.microsoft.com/en-us/windows/win32/perfctrs/using-the-registry-functions-to-consume-counter-data):

> To obtain performance data from a remote system, call the RegConnectRegistry function. Use the computer name of the remote system and use HKEY_PERFORMANCE_DATA as the key. This call retrieves a key representing the performance data for the remote system. Use this key rather than HKEY_PERFORMANCE_DATA key to retrieve the data.
> 
> Be sure to use the RegCloseKey function to close the handle to the key when you are finished obtaining the performance data. This is important for both the local and remote cases:
> 
> * RegCloseKey(HKEY_PERFORMANCE_DATA) does not actually close a registry handle, but it clears all cached data and frees the loaded performance DLLs.
> * RegCloseKey(hkeyRemotePerformanceData) closes the handle to the remote machine's registry.

But I cannot find the word "close" or "Close" anywhere in perflib_exporters codebase. So I thought, hooray, found the culprit and started a perflib_exporter which doesn't seem to leak at all. Long story short, I still have no clue what is going on. I think it is still possible that the perflib_exporter uses the perflib library a bit differently? Like reusing some datastructures while the windows_exporter is always asking for a new one or so?

**Comment by datamuc** [comment]
Does anybody have an idea? We are considering to move to telegraf and scrape that for the windows metrics.

**Comment by jesus-velez** [comment]
My priorities have shifted for the time being, but I have to come back to this issue pretty soon. I resorted to schedule a daily exporter bounce in the mean time. I can say that I found this issue has been around since the wmi exporter days. I recently logged into a server that we somehow missed on our exporter upgrades and the memory usage was really high.

**Comment by carlpett** [comment]
@datamuc That looks like a very good find, and even if the perflib exporter appears to not leak, I'd argue it it still incorrect not to close the key. It might require a bit of locking to do this right though, otherwise I think overlapping scrapes might lead to issues.
I'm not sure when I could commit to trying this out, but if anyone else wants to give it a go without the locking bits, I think we'd basically just need to add `defer syscall.RegCloseKey(syscall.HKEY_PERFORMANCE_DATA)` [here](https://github.com/leoluk/perflib_exporter/blob/da7e746e1ac6876bbb7dac385b6a415fee2a8172/perflib/perflib.go#L218).

**Comment by geraudster** [comment]
Hi, same problem here. 
So I tried to build a new package with the commit of @datamuc on perflib and performed some tests (100 req/s on /metrics during 30 minutes) to compare both versions, the configured collectors are cpu,cs,logical_disk,net,os,system,textfile,process.

The patched version (the curve on the right) seems to do better than v0.16.0 (the one on the left) in terms of memory usage:
![image](https://user-images.githubusercontent.com/191606/142456206-a290eec1-fb46-4f76-9371-650aa528f64e.png)

But a leak is still here. Do you have any other idea to fix this ?

**Comment by datamuc** [comment]
> Hi, same problem here. So I tried to build a new package with the commit of @datamuc on perflib and performed some tests (100 req/s on /metrics during 30 minutes) to compare both versions, the configured collectors are cpu,cs,logical_disk,net,os,system,textfile,process.
> 
> The patched version (the curve on the right) seems to do better than v0.16.0 (the one on the left) in terms of memory usage: ![image](https://user-images.githubusercontent.com/191606/142456206-a290eec1-fb46-4f76-9371-650aa528f64e.png)
> 
> But a leak is still here. Do you have any other idea to fix this ?

We removed the process and service collector from our configuration (and added the tcp collector, so it is: [defaults]  - service + tcp) now the memory usage is stable. It seems that every collector that makes use of github.com/StackExchange/wmi leaks.

**Comment by datamuc** [comment]
The patch above was merged into the perflib_exporter library with 
https://github.com/leoluk/perflib_exporter/pull/34.

Can sombody take care of updating the dependency in windows_exporter please?

**Comment by jesus-velez** [comment]
@datamuc  Thanks for all the work that your are putting in on this.

**Comment by datamuc** [comment]
Are the leaks in the WMI collectors tracked elsewhere? Otherwise I vote for reopening this.

**Comment by breed808** [comment]
My mistake, I'll reopen for the WMI tracking

**Comment by jesus-velez** [comment]
@breed808 do we know when the next release is coming up? I want to help testing this but when I try to create the exe file I am getting some weird common log errors.
```
cannot find module providing package github.com/prometheus/common/log
```

**Comment by jesus-velez** [comment]
@datamuc I checked all of our boxes and it seems like the problem is mainly with Windows Server 2016. We also have 2012 and 2019, neither show significant leaks. Do you have the same experience?

**Comment by jesus-velez** [comment]
I also found this, seems to be related? https://github.com/StackExchange/wmi/issues/27#issue-237024341

**Comment by datamuc** [comment]
> @datamuc I checked all of our boxes and it seems like the problem is mainly with Windows Server 2016. We also have 2012 and 2019, neither show significant leaks. Do you have the same experience?

Sorry, but I was not able to test this with [leoluk/perflib_exporter#34](https://github.com/leoluk/perflib_exporter/pull/34) on many machines because I have no direct access to them.

But the two I have tested with where indeed Windows Server 2016.

**Comment by jesus-velez** [comment]
I found that telegraf was having the same issue on Windows Server 2016. https://github.com/influxdata/telegraf/issues/6807#issuecomment-590256733

I don't know enough to be able to diagnose this myself, but looking at github.com/StackExchange/wmi, they are indeed using CoInitializeEx. What are you thoughts about this?

**Comment by jesus-velez** [comment]
> > @datamuc I checked all of our boxes and it seems like the problem is mainly with Windows Server 2016. We also have 2012 and 2019, neither show significant leaks. Do you have the same experience?
> 
> Sorry, but I was not able to test this with [leoluk/perflib_exporter#34](https://github.com/leoluk/perflib_exporter/pull/34) on many machines because I have no direct access to them.
> 
> But the two I have tested with where indeed Windows Server 2016.

@ I found that telegraf was having the same issue on Windows Server 2016. https://github.com/influxdata/telegraf/issues/6807#issuecomment-590256733

I don't know enough to be able to diagnose this myself, but looking at github.com/StackExchange/wmi, they are indeed using CoInitializeEx. What are you thoughts about this?

**Comment by jesus-velez** [comment]
@datamuc 

I found that telegraf was having a similar issue on Windows Server 2016. https://github.com/influxdata/telegraf/issues/6807#issuecomment-590256733

I don't know enough to be able to diagnose this myself, but looking at github.com/StackExchange/wmi, they are indeed using CoInitializeEx. What are you thoughts about this?

**Comment by datamuc** [comment]
Sounds promising to look deeper, but to be honest I have no idea. I was just lucky finding the leak in perflib_exporter, I have no idea of windows  related programming at all, and just know a little bit go...

**Comment by audriuz** [comment]
Same issue keeps happening in our environment since implementation as well, latest windows_exporter version didn't solve it. Was not able to identify which exact software, feature or service may impact this happening on some random servers, but part of domain controllers impacted for sure (Windows Server 2016). Those servers are impacted heavily, check attachment. It looks scary, but those gigabytes of memory mostly are taken not from physical RAM, but from virtual memory. As mentioned above, seems that removing "process" or "service" collectors solves t
![windows_exporter_process_withour_service_collector](https://user-images.githubusercontent.com/35595504/150378561-17c664c9-a0c3-47e7-a770-6ec2415c40ee.JPG)
he issue or at least improving situation significantly. Even removing "service" collector alone, improve situation a lot, please check another attachment.
![windows_exporter_process_memory](https://user-images.githubusercontent.com/35595504/150376676-0ef2a2b0-c72e-49bc-8b2a-cf6d0c9bfc56.JPG)
.

**Comment by YoByMe** [comment]
same problem here ... I have 2 servers with this problem. 
![image](https://user-images.githubusercontent.com/106162386/170042493-23455543-2b20-4781-9713-22242fc85565.png)
any news ?

**Comment by breed808** [comment]
It's been a while since I've last looked at this, but I think disabling the WMI queries in the process collector by default may improve the situation.

Would anyone be able to test the branch in #998 to see if the `process` collector continues to experience memory leaks?

**Comment by exe-r** [comment]
Experiencing similar issue with leaks on latest  `0.19.0`, windows server 2016. Any permanent fix yet or should we disable process collector? @breed808 I think in my case #998 does not solve the issue cause i have two servers now, 1 which does not have leaks and one that does, `collector.process.iis` is enabled on both.

Have the following enabled on both
```sh
collectors:
  enabled: cpu,cs,logical_disk,net,os,service,system,memory,tcp,vmware,process,iis
```

The only difference is `collector.process.whitelist`, the affected server does have more processes included.

Non affected
```sh
    whitelist: "xService.?|windows_exporter.?"
```

Affected
```sh
whitelist: "xService.?|windows_exporter.?|app.+|antivirus.+|w3wp|Scheduler|xConnector|Ccm.+|xClient|inetinfo|.+agent|.+Agent"
```

I will try to remove few processes and see if it improves

Image of the leak

![image](https://user-images.githubusercontent.com/9107242/189300911-d8054ecd-77f4-4a85-a330-1d40c3e46ca0.png)

**Comment by breed808** [comment]
It's been some time since I last looked at this, but I believe my intention with #998 was to remove a potential leak in the `process` collector.
I suspect we have multiple leaks in each of the collectors. A fix for one won't resolve them all.

I've reopened #998 in #1062 if anyone would like to test the branch.

**Comment by exe-r** [comment]
> It's been some time since I last looked at this, but I believe my intention with #998 was to remove a potential leak in the `process` collector. I suspect we have multiple leaks in each of the collectors. A fix for one won't resolve them all.
> 
> I've reopened #998 in #1062 if anyone would like to test the branch.

@breed808  Made a few tests and the most stable config was disabling `scheduler_task` collector completely. Its been 1 day since its running ok, will report back in case it changes.  We only monitor 2 scheduled tasks so not sure why such aggressive leak is happening. 

```yaml
# working config
collectors:
  enabled: cpu,cs,logical_disk,net,os,service,system,memory,tcp,vmware,process,iis,netframework_clrexceptions
collector:
  process:
    whitelist: "xService.?|windows_exporter.?|app.+|antivirus.+|w3wp|Scheduler|xConnector|Ccm.+|xClient|inetinfo|.+agent|.+Agent"
  service:
    services-where: Name LIKE 'appname%'
```

**Comment by exe-r** [comment]
Coming back to the test @breed808. After 2 weeks having 6 servers running the above config I can confirm we stable at around 40-50mb~ of memory usage with no leaks. As soon as we enable `scheduler_task` collector the leak is very aggressive. 

7 days usage example 
![image](https://user-images.githubusercontent.com/9107242/192698802-7e7bd891-2ad7-408a-995b-50bef8346128.png)

**Comment by audriuz** [comment]
I am not using "scheduled_task" collector, but main problem with memory increase is "service" collector. Only part of the servers are affected. Tried versions 0.18.1 and 0.19.0, same results. After removing "service" collector, huge difference, check the screenshot:

![image](https://user-images.githubusercontent.com/35595504/192778154-62a92f03-3de8-497f-b357-708fdb95f741.png)

**Comment by breed808** [comment]
`scheduled_task` memory leak has been addressed in #1080. I'll try to investigate the `service` collector when there's time.

**Comment by breed808** [comment]
I've not been able to reproduce the `service` collector memory leak. Graph below shows resident memory with the `service` collector enabled with `curl` hitting the metrics endpoint constantly:

![](https://user-images.githubusercontent.com/3103817/197689232-cfa74cba-9fa3-49d2-8036-fa202bd647e9.png)

**Comment by kryztoval** [comment]
@breed808 I can't replicate it reliably but I am able to replicate it. I am seeing a bit of a trend where one of the instances is gettingmore and more memory as time passes, this started exactly at the problem when I added a rasberry pi as a prometheus server and targetted the windows_exporter with it to collect data every second. I am also hitting the same windows_exporter every second with a local instance of prometheus and a netdata collector on another raspberry pi. Having a single instance did not cause the memory leak but having both made it start happening. My guess would be there is something that is leaving the connection open or it is forcefully closed without letting the server clean up.

So for me to reproduce it I had to hit the windows_exporter more than 3 times per second at the very least.

**Comment by linuxlzj** [comment]
in windows 2016， i find use wmi query exist mem leak also

**Comment by kryztoval** [comment]
This is not stale, the proccess leaks memory, specially and faster if it is being polled more than 3 times per second for whatever reason.

**Comment by jkroepke** [comment]
Can someone provide some details?

Output of 

* http://localhost:9182/debug/pprof/goroutine?debug=2
* http://localhost:9182/debug/pprof/heap?debug=1

as file attachment.

If possible, generate a trace:

```
curl -o trace.out http://localhost:9182/debug/pprof/trace?seconds=30
```

**Comment by datamuc** [comment]
We already had this here: https://github.com/prometheus-community/windows_exporter/issues/813#issuecomment-875584268

But it doesn't help, because the memory is lost when interacting with Windows API somewhere. We found the leak in perflib. But there is at least another one in WMI. I can tell because the leakage stops if I disable all the collectors that make use of WMI:

https://github.com/prometheus-community/windows_exporter/issues/813#issuecomment-948019812

**Comment by jkroepke** [comment]
@datamuc I saw there are pprof exists already exists.

However they coming from 0.16 and I would like to start at least form the lastest releases. In mean time, we included perflib libraries into windows_exporter and not longer depends on external contributors (https://github.com/prometheus-community/windows_exporter/tree/master/pkg/perflib)

**Comment by datamuc** [comment]
> > In mean time, we included perflib libraries into windows_exporter and not longer depends on external contributors (https://github.com/prometheus-community/windows_exporter/tree/master/pkg/perflib)
> 
> Interesting, I will try to come up with something next week.

Sorry, I don't have access to many windows machines anymore. The two that are left don't leak. So, if somebody still has leaks they have to do https://github.com/prometheus-community/windows_exporter/issues/813#issuecomment-1834558181 themself.

**Comment by nkPit** [comment]
Hello. On a Windows 2019 runner with an uptime of 2 months, windows_exporter (version 0.23.1) is consuming a large amount of RAM. I’m attaching the necessary files.
<img width="789" height="156" alt="Image" src="https://github.com/user-attachments/assets/940ba054-9166-4cfa-83ae-6304f563df19" />

[heap.txt](https://github.com/user-attachments/files/21524475/heap.txt)

[gorout-heap.txt](https://github.com/user-attachments/files/21524494/gorout-heap.txt)

(The command `curl -o trace.out http://localhost:9182/debug/pprof/trace?seconds=30` is supposed to produce such a strange output?)
[trace.txt](https://github.com/user-attachments/files/21524517/trace.txt)

**Comment by jkroepke** [comment]
Hi @nkPit 

consider update to latest version first.

**Comment by nkPit** [comment]
Hello, @jkroepke 
No. This issue still persists in version 0.30.
