### ISSUE TITLE
Service stops waiting for [process cs service thermalzone cpu_info os] after server restart (WMI service starts later)

### ISSUE THREAD

**Issue by HerrB92** [prometheus-community/windows_exporter#818]
Hi everyone,

if the server is restarted, then the service may report that it is waiting for some collectors and then actually stops. This does not seem to happen on every restart, but I would guess one out of three.

The log entries:
7/15/2021 4:49:19 AM: Shutting down windows_exporter
7/15/2021 4:28:49 AM: Collection timed out, still waiting for [process cs service thermalzone cpu_info os]
7/15/2021 4:23:49 AM: Collection timed out, still waiting for [process cpu_info os cs service thermalzone]
7/15/2021 4:13:09 AM: Collection timed out, still waiting for [cs service process cpu_info os]
7/15/2021 4:10:49 AM: Collection timed out, still waiting for [cpu_info cs process service]
7/15/2021 4:08:49 AM: Collection timed out, still waiting for [cpu_info service process cs os]
7/15/2021 4:03:29 AM: Collection timed out, still waiting for [process thermalzone os]

We have already set the service startup to "Delayed Start" and the recovery settings have not been changed.

Interestingly, the WMI service (which I guess is used by the windows_exporter) starts later:
7/15/2021 4:50:23 AM: Windows Management Instrumentation Service subsystems initialized successfully
7/15/2021 4:50:22 AM: Windows Management Instrumentation Service started sucessfully

The service dependencies show, that the windows_exporter depends on "WMI Performance Adapter", but not on "Windows Management Instrumentation".

May it help, if I add this dependency to the windows_exporter service as well (if this is possible)?

Regards,
HerrB92

**Comment by yrro** [comment]
Dupe of #637 and #551?
