### ISSUE TITLE
Windows_exporter Time Metrics are all 0

### ISSUE THREAD

**Issue by tahachoura** [prometheus-community/windows_exporter#819]
Hi Dears,

I have an issue please : I added --collectors.enabled"time" to export NTP metrics( NTP), in order to monitor windows NTP server.
But all metrics are 0 , even though my NTP client is synchronised...

![image](https://user-images.githubusercontent.com/11164303/125781426-031e90f7-b805-47bb-9f68-320dc952a8ff.png)

I want to monitor NTP service that I installed on windows, using Promehteus (windows_exporter) :
![image](https://user-images.githubusercontent.com/11164303/125781404-6325fd46-f6d0-4977-986c-f0a5fab80074.png)
![image](https://user-images.githubusercontent.com/11164303/125781696-dbf7f539-191b-43a8-8594-333966077d30.png)

(Maybe I can use another Prometheus exporter to export NTP metrics from windows Host ?)
Any idea please ?

**Comment by breed808** [comment]
Are you receiving metrics when querying with `Get-Counter`? E.G.

```powershell
Get-Counter -Listset * | Select CounterSetName | Sort-Object -Property CounterSetName
```

Alternatively you can confirm the counters are present with the Performance Monitor.

**Comment by tahachoura** [comment]
Hi breed808, 
Thanks for your reply : )

Output : 

![image](https://user-images.githubusercontent.com/11164303/126036803-2c02430a-111f-41be-bc38-ecaa9714caa5.png)

![image](https://user-images.githubusercontent.com/11164303/126036875-a5f4be10-952f-40d8-968b-5f7505566b05.png)


The all idea is to monitor NTP installed on Windows 10, with prometheus. 
If there is any other exporter that can export  metrics (Synchronized ? round)

In Linux machines, I am using node_exporter (node_timex_sync_status,  node_ntp_leap, node_ntp_sanity, etc.... )  to monitor chrony....  

How can I can do this in Windows ?  I didnt find any NTP exporters on Windows.... 

Thanks in advance for your answer :)

**Comment by breed808** [comment]
To my knowledge there's no dedicated Windows NTP exporter.

Could you substitute the `Windows-Zeitdienst` in the command for `CounterSetName`? If you receive results, querying with `Get-Counter -Counter "\Windows-Zeitdienst\Ausgehende Antworten des NTP-Servers` or any of the other counters will confirm if `Get-Counter` is also returning empty metric values.
