### ISSUE TITLE
Power usage metrics

### ISSUE THREAD

**Issue by edasque** [prometheus-community/windows_exporter#822]
Hi,

I was wondering if there was a way to collect total power, GPU power, CPU power metrics using this exporter?

I couldn't find a category or metrics that seemed to relate to this..

**Comment by breed808** [comment]
We don't currently have any collectors that provide power information. If you're able to find a power metric source provided by Windows (perflib, WMI, etc) we could add it.

I'm aware of some manufacturer-specific exporters for NVIDIA/AMD GPUs, though I've not seen a generic exporter so far.
