### ISSUE TITLE
crash on window server 2016 standard

### ISSUE THREAD

**Issue by FunkyYang** [prometheus-community/windows_exporter#825]
there is no counter on this window server from logs

**Comment by FunkyYang** [comment]
```
time="2021-08-17T17:56:52+08:00" level=error msg="collector logical_disk failed after 0.001001s: counter not found" source="exporter.go:206"
time="2021-08-17T17:56:52+08:00" level=error msg="collector net failed after 0.000000s: counter not found" source="exporter.go:206"
time="2021-08-17T17:57:07+08:00" level=error msg="failed collecting system metrics:<nil> counter not found" source="system.go:72"
time="2021-08-17T17:57:07+08:00" level=error msg="failed collecting logical_disk metrics:<nil> counter not found" source="logical_disk.go:162"
time="2021-08-17T17:57:07+08:00" level=error msg="collector system failed after 0.000000s: counter not found" source="exporter.go:206"
time="2021-08-17T17:57:07+08:00" level=error msg="collector logical_disk failed after 0.001002s: counter not found" source="exporter.go:206"
time="2021-08-17T17:57:07+08:00" level=error msg="failed collecting net metrics:<nil> counter not found" source="net.go:136"
time="2021-08-17T17:57:07+08:00" level=error msg="collector net failed after 0.001002s: counter not found" source="exporter.go:206"
time="2021-08-17T17:57:22+08:00" level=error msg="failed collecting net metrics:<nil> counter not found" source="net.go:136"
time="2021-08-17T17:57:22+08:00" level=error msg="failed collecting system metrics:<nil> counter not found" source="system.go:72"
time="2021-08-17T17:57:22+08:00" level=error msg="collector net failed after 0.000997s: counter not found" source="exporter.go:206"
time="2021-08-17T17:57:22+08:00" level=error msg="failed collecting logical_disk metrics:<nil> counter not found" source="logical_disk.go:162"
time="2021-08-17T17:57:22+08:00" level=error msg="collector system failed after 0.000997s: counter not found" source="exporter.go:206"
time="2021-08-17T17:57:22+08:00" level=error msg="collector logical_disk failed after 0.000997s: counter not found" source="exporter.go:206"
time="2021-08-17T17:57:37+08:00" level=error msg="failed collecting net metrics:<nil> counter not found" source="net.go:136"
time="2021-08-17T17:57:37+08:00" level=error msg="failed collecting logical_disk metrics:<nil> counter not found" source="logical_disk.go:162"
time="2021-08-17T17:57:37+08:00" level=error msg="failed collecting system metrics:<nil> counter not found" source="system.go:72"
time="2021-08-17T17:57:37+08:00" level=error msg="collector net failed after 0.000000s: counter not found" source="exporter.go:206"
```

**Comment by FunkyYang** [comment]
this is server log

**Comment by breed808** [comment]
Does this issue occur on other servers, or when running the exporter as an EXE?
Do you receive similar errors when querying metrics with `Get-Counter` or with the Performance Monitor?

**Comment by FunkyYang** [comment]
not yet on other server,I use windows_exporter-0.16.0-amd64.exe

**Comment by breed808** [comment]
Thanks, let me know if you're able to query the metrics directly via `Get-Counter` or the Performance Monitor.

**Comment by RoiDanton73** [comment]
Hi together, i have the same problem on a Windows Server 2016 the Windows_Exporter.exe runs as a Service . After installing the July Windows Updates  the exporter crashes after starting or didnt start at all.
Is there a workaround where I can continue to use the Windows exporter exe?

**Comment by tbiles** [comment]
> Hi together, i have the same problem on a Windows Server 2016 the Windows_Exporter.exe runs as a Service . After installing the July Windows Updates the exporter crashes after starting or didnt start at all.
> Is there a workaround where I can continue to use the Windows exporter exe?

There is another thread about this issue.  The exporter does not start consistently after Windows updates are applied and the system reboots.  A normal reboot with no updates does not pose a problem (at least in my environment).  This has been an issue for several version for me, and I'm currently on 0.16.0.  The only "fix" so far is to write your own service watcher and start the service if it isn't running.  This is a band aid approach, but there has been no fix offered as of yet so it is all we have right now.  I've not rolled this out widely and I'm still running it only on test servers until this problem is resolved.

**Comment by Andy-Techical** [comment]
I see this issue frequently, occurring typically when there are alot of Windows updates released and available for install.

After the updates are installed and the server is restarted, if the server is under heavy CPU load whilst the updates are installing, then the Windows_exporter service does not start up.

Usually, it is the Windows Modules Installer Worker(TiWorker.exe) service which is using up high CPU on the server to install the updates. I use mainly Windows Server 2016.

Would it be possible to put some logic in whereby the "Windows_exporter" service is checked every x minutes to check its up and running, and if not, to start it up?
