### ISSUE TITLE
vmware collector failed with exception: invalid class

### ISSUE THREAD

**Issue by compilenix** [prometheus-community/windows_exporter#826]
# Description
On a Windows Server VM the `vmware` collector fails with the following error message, as logged in Windows Eventlog:

```
Log Name:      Application
Source:        windows_exporter
Date:          26.08.2021 12:07:39 CEST
Event ID:      102
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      servername.domain.tld
Description:
collector vmware failed after 0.023253s: Exception occurred. (Invalid class )
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="windows_exporter" />
    <EventID Qualifiers="0">102</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-08-26T10:07:39.468428700Z" />
    <EventRecordID>129628</EventRecordID>
    <Channel>Application</Channel>
    <Computer>servername.domain.tld</Computer>
    <Security />
  </System>
  <EventData>
    <Data>collector vmware failed after 0.023253s: Exception occurred. (Invalid class )</Data>
  </EventData>
</Event>
```

# Enviroment
VMware vCenter 6.7.0 build  18010599
ESXi 6.7.0 build 17167734
VMware Tools 11334 (11.2.6.17901274)
Windows Server 2019 Datacenter 1809 build 17763.2114
Windows Exporter 0.15.0
Windows Exporter Service Paramters:
```
"C:\Program Files\windows_exporter\windows_exporter.exe" --collectors.enabled "cpu,cs,memory,logical_disk,net,os,service,system,tcp,process,time,vmware" --log.format "logger:eventlog?name=windows_exporter" --telemetry.addr :9182
```

# Attempted Resolutions
- Reboot Windows
- Restart Windows Exporter Service
- Restart VMware Tools Service(s)
- Reinstall VMware Tools
- Reinstall Windows Exporter

**Comment by breed808** [comment]
I can see the `vmware` collector is using WMI as a metric source; are you able to query either of the `Win32_PerfRawData_vmGuestLib_VMem` or `Win32_PerfRawData_vmGuestLib_VCPU` WMI classes?

**Comment by compilenix** [comment]
```powershell
Get-WmiObject Win32_PerfRawData_vmGuestLib_VMem
```

results in:
```
Get-WmiObject : Invalid class "Win32_PerfRawData_vmGuestLib_VMem"
At line:1 char:1
+ Get-WmiObject Win32_PerfRawData_vmGuestLib_VMem
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand
```

and

```powershell
Get-WmiObject Win32_PerfRawData_vmGuestLib_VCPU
```

results in:
```
Get-WmiObject : Invalid class "Win32_PerfRawData_vmGuestLib_VCPU"
At line:1 char:1
+ Get-WmiObject Win32_PerfRawData_vmGuestLib_VCPU
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidType: (:) [Get-WmiObject], ManagementException
    + FullyQualifiedErrorId : GetWMIManagementException,Microsoft.PowerShell.Commands.GetWmiObjectCommand
```

**Comment by breed808** [comment]
The collector relies on those two classes for metrics; are you able to investigate why those WMI classes are missing?

**Comment by compilenix** [comment]
Do you got a hint for me where to start on how to investigate why those WMI classes are missing?

**Comment by breed808** [comment]
For VMWare classes I'm afraid not :disappointed:. You could be missing some software or library that is required for the classes.

Perhaps VMWare might have documentation on these classes?

**Comment by JDA88** [comment]
It might be a stupid question but did you installed the full version of the VMTools or only a subset? Those WMI classes are created and populated by the Tools

**Comment by compilenix** [comment]
Yep, it is a "full version" install.
