### ISSUE TITLE
Impossible to install windows exporter

### ISSUE THREAD

**Issue by elderwann** [prometheus-community/windows_exporter#827]
Hello, I tried to install windows exporter on a windows os machine. prometheus-2.28.1.windows-amd64 or prometheus-2.29.1.windows-amd64. 
The prometheus.exe file is executed during very few second but nothing is installed...
I execute the file in admin mode but nothing... 
Is anyone has an idea to resolve this issue ??

Thanks a lot !

**Comment by breed808** [comment]
For `windows_exporter`, the EXE file isn't an installer, you'll want to use the provided MSI for installation. 

For Prometheus, you'll need to run the exe as a service or with some other method, such as a configuration management tool. If you still have issues, you'll need to submit them to the [prometheus](https://github.com/prometheus/prometheus/) repository.
