### ISSUE TITLE
No MSI file

### ISSUE THREAD

**Issue by ohlssrog** [prometheus-community/windows_exporter#828]
Cannot find any msi file for the installation in the zip file, what have i miss in this?

**Comment by nguyenlamlll** [comment]
If you download a zip file, is it possible that you downloaded the source code? 
If you go to a release URL, there will be links to download MSI and EXE files directly. For example: https://github.com/prometheus-community/windows_exporter/releases/tag/v0.16.0

![image](https://user-images.githubusercontent.com/20963684/131446845-62af3f91-30b9-4a50-a9ac-097289d34dfa.png)

**Comment by breed808** [comment]
@nguyenlamlll is correct, the zip archive contains the source code for the release. You'll need to select one of the MSI or EXE files for installation.
