### ISSUE TITLE
Cant install windows_exporter MSI on Windows Server 2019

### ISSUE THREAD

**Issue by zveroboy152** [prometheus-community/windows_exporter#829]
I'm unable to uninstall the it via an MSI via command line.

Attached in the commands, directory location, and the exact error that comes up.

This powershell prompt is opened with administrative permissions.
![Screenshot 2021-09-06 180511](https://user-images.githubusercontent.com/39677147/132269543-b4684f7d-3c19-4931-913a-4aa863239029.png)

**Comment by breed808** [comment]
I've been able to reproduce this as well. I think `msiexec` is requiring the MSI's full path be provided. I.E.

```powershell
msiexec /i C:\Users\example\Downloads\windows_exporter-0.16.0-amd64.msi ENABLED_COLLECTORS="os,iis,vmware,tcp,time,ad,dfsr,dhcp,dns,logon
```

Once I provided the full MSI path, the installation was successful. The error message is _not_ helpful at all though :angry:

**Comment by zveroboy152** [comment]
I was able to verify that as well.  Looks like something that should get fixed at some point. :-)
