### ISSUE TITLE
Logical Disk free_bytes and size_bytes counter not updating instantly

### ISSUE THREAD

**Issue by JDA88** [prometheus-community/windows_exporter#830]
Hi,

Ok this one is a weird one, I noticed that the value of the `windows_logical_disk_size_bytes` counter was not updating instantly after a drive extension. I then looked at the `LogicalDisk > Free Megabytes` windows counter (you probably use the raw version of this one or one of is friends) and it is not updating either.

If you wait for a bit (10-15min), the counter (on windows and on the exporter) end up updating. If you restart the exporter service, it looks liks it updates instantly (might have to test this one further).

Digging a little bit I found this old article https://www.ibm.com/support/pages/freembytes-not-matching-value-perfmon that gave me a hint.

From my understanding some disk performance counter are considered costly to calculate and are not updated in real time. It looks like the drive free space / disk sizes are part of them.
The questions are:
- Is this behavior intended for the exporter (is it the same on the node_exporter?) 
- Is there a way to do better (without altering the registry?) The API call return the correct drive size instantly. (It might be overkill to call it every time but updating the value once a minute with a cache shoule be enough.)

My main goal is to point the current behaviors to have it at least documented and then if there is a way to do better, great!

**Comment by breed808** [comment]
This is a very good find! I think at a minimum we should add this to the `logical_disk` collector documentation. Would you mind submitting a PR for the documentation?

I don't think changing the behavior of a particular collector to cache a result or return a value only every minute would be ideal, but perhaps there needs to be some discussion first.

**Comment by JDA88** [comment]
> This is a very good find! I think at a minimum we should add this to the `logical_disk` collector documentation. Would you mind submitting a PR for the documentation?

Do you think I shoud add a comment directly on the counter description or a warning at the end?

**Comment by breed808** [comment]
I think a brief note in the counter description, and a more detailed description in the [collector documentation](https://github.com/prometheus-community/windows_exporter/blob/5b92e1bd3dd87ff691383dc66ec0c66778099490/docs/collector.logical_disk.md).

**Comment by JDA88** [comment]
Ok forgive me if I didn't do it right but I tried a edit of the doc there: https://github.com/prometheus-community/windows_exporter/pull/846

**Comment by breed808** [comment]
You might be able to add the DCO via the website. If you add a `Signed-off-by` at the bottom of the commit description it may pass.

E.G. `Signed-off-by: Ben Reedy <breed808@breed808.com>`

If not you'll have to use `git commit -s --amend` to amend the commit with the sign-off.

**Comment by JDA88** [comment]
Now that the documentation is updated. There is the **enhance** option left. 
I know `Win32 `and `.NET` but unfortunately, I don’t know anything about `GO`, so I can’t really help there.

**Comment by JDA88** [comment]
The 5 min delay to spot issue have an impact on alerts reactivity
