### ISSUE TITLE
Windows exporter metrics filtering issue

### ISSUE THREAD

**Issue by anuprshetty** [prometheus-community/windows_exporter#834]
Hi All,
Is there any option to filter data which is collected by windows exporter at the metrics level?
Currently we can filter the data to be collected at the collector level.
Ex: msiexec /i windows_exporter.msi ENABLED_COLLECTORS="ad,iis,logon,memory,process,tcp,thermalzone".

Thank you.

Regards,
Anup

**Comment by anuprshetty** [comment]
Hi All,
I need support for this issue.

**Additional details about the issue:**
Currently windows exporter agent is collecting all the metrics in the enabled collectors. Due to this, windows exporter is consuming more CPU. So is there any way I can mention like only these metrics you collect from the system and don't collect everything else. So that the CPU consumption by windows exporter is reduced. 

Thank you.

**Comment by breed808** [comment]
You'll want to read @carlpett's great comment at https://github.com/prometheus-community/windows_exporter/issues/779#issuecomment-832868996

**Comment by anuprshetty** [comment]
@breed808 Thank you for the information. If I use relabeling at Prometheus side, still windows exporter will collect all the metrics from the system. So it would be helpful if metric-level filtering is implemented at the Windows exporter side along with Prometheus exporter side. So that we can reduce the CPU consumption by Windows exporter. I hope this feature is implemented in the upcoming version of windows exporter if possible.

**Comment by breed808** [comment]
Are there any collectors in particular that are causing the excessive CPU consumption?
We don't support filtering individual metrics, though some of the larger collectors expose sub-collectors that can be individually enabled or disabled.
