### ISSUE TITLE
windows_iis_worker_request_errors_total   doesn't work anymore???

### ISSUE THREAD

**Issue by DenisAlcc** [prometheus-community/windows_exporter#835]

**Comment by fantom732315** [comment]
![image](https://user-images.githubusercontent.com/90676446/133267362-e513fd38-a5ef-4509-abf8-69193321c715.png)

It works for me correctly. Did you specify the iis flag at startup?

**Comment by DenisAlcc** [comment]
> ![image](https://user-images.githubusercontent.com/90676446/133267362-e513fd38-a5ef-4509-abf8-69193321c715.png)
> 
> It works for me correctly. Did you specify the iis flag at startup?

yes, i specify the iis flag with msiexec ENABLED_COLLECTORS

**Comment by fantom732315** [comment]
Do you have this item in your metrics or is it always 0? If it is always zero, try to simulate the error

**Comment by SouenMazouin** [comment]
Hi, we are having the same problem as well. 
No worries of this kind on the 0.16.0 release but only when building the master.
I suspect a problem with the perflib integration (#832).
I'm investigating and if I find any leads, I'll let you know

**Comment by SouenMazouin** [comment]
After investigation I noticed that the IIS metrics of version greater than 8 were no longer instantiated,
there was also a small typo that prevented looping on the concerned perflib objects.

I opened a PR to fix this : #887

**Comment by breed808** [comment]
Is this resolved with the merge of #887 or is further work required?

**Comment by SouenMazouin** [comment]
Hi @breed808, the merge of #887 solved the problem for me, @DenisAlcc did that solve with you too?
