### ISSUE TITLE
MSSQL Grafana Dashboard

### ISSUE THREAD

**Issue by fantom732315** [prometheus-community/windows_exporter#836]
I searched for a long time and did not find a single dashboard for Grafana that would display MSSQL metrics. The exporter gives the correct metrics, but how can you view them in Grafana?

**Comment by theogbubbie** [comment]
I found a json from https://github.com/alekssako/grafana-dashboards/blob/master/Prometheus-Windows/SQL-Server-Monitoring.json  and updated wmi to windows. However, my multiple targets are not separated on the dashboard so I am finding a way to fix this issue of mine.

**Comment by fantom732315** [comment]
Made quite a few changes to this dashboard: corrected instances, metric names, deleted something ...

Now the dashboard works with Windows exporter v.0.16. Thanks for the tip!

https://github.com/fantom732315/Grafana/blob/e0adbe4a25c4af2ab9a392149634d31661c935cb/MSSQL%20windows%20exporter.json

**Comment by theogbubbie** [comment]
> Made quite a few changes to this dashboard: corrected instances, metric names, deleted something ...
> 
> Now the dashboard works with Windows exporter v.0.16. Thanks for the tip!
> 
> https://github.com/fantom732315/Grafana/blob/e0adbe4a25c4af2ab9a392149634d31661c935cb/MSSQL%20windows%20exporter.json

Thankyou for sharing your edits.
