### ISSUE TITLE
windows_exporter service failed to start on reboot

### ISSUE THREAD

**Issue by Abhishek-Kraj** [prometheus-community/windows_exporter#837]
Hi,

After updates and rebooting the server, the windows_exporter service was not running

The windows_exporter service failed to start due to the following error:
The service did not respond to the start or control request in a timely fashion.

![image](https://user-images.githubusercontent.com/63701596/134151921-51aa6daa-ed9f-411d-b6ef-b9b13538f1a4.png)

Delayed start
sc config windows_exporter start= delayed-auto

Restart option
sc failure windows_exporter actions= restart/60000/restart/60000/""/60000 reset= 86400

No Help on above configuration

**Comment by daveaowen** [comment]
Try setting WMI as a dependency on the service, and up the 'Restart service after' to 5 minutes. This worked for me.

**Comment by gillg** [comment]
This issues is very anoying, I had the same and finally I created a scheduled task "start-service" every hour to be sure it runs.

There is no log, no crash event, nothing to troubleshoot...

**Comment by gillg** [comment]
In theory should be solved by https://github.com/prometheus-community/windows_exporter/pull/1047
But I'm not 100% sure.

I have the feeling to always experience some issues after reboot on servers with a high load at boot.
