### ISSUE TITLE
An error when INSTALLING Windows_EXPORTER in Windows Server 2008

### ISSUE THREAD

**Issue by icepopfh** [prometheus-community/windows_exporter#838]
Hello, I am experiencing an error when INSTALLING Windows_EXPORTER in Windows Server 2008. Please help me check the cause, thank you.
windows_exporter: 0.13.0
This is my version of the operating system.
![image](https://user-images.githubusercontent.com/53719692/134292290-836005e1-b15d-4c4e-9581-2baabc6010e2.png)
An error occurred when executing the EXE file directly. 
![image](https://user-images.githubusercontent.com/53719692/134292362-3cb99c2d-27bd-47f9-9754-7ba85649dc92.png)
An error occurred during mSI installation. 
![image](https://user-images.githubusercontent.com/53719692/134292638-91413139-ba5a-4312-9229-b206be83756a.png)

**Comment by breed808** [comment]
Thanks, that stack trace has been rather helpful!
The perflib library is calling the `QueryNameTable` function with the English language as a hardcoded value: 
![QueryNameTable](https://user-images.githubusercontent.com/3103817/134770033-0aa6bcf5-5486-41d2-840b-ad436e3e2731.png)

Are you able to install an English language pack to confirm if this resolves the issue?

**Comment by xflu** [comment]
@icepopfh  I used to have the same problem.

You can install windows service the other way, using [Winsw](https://github.com/winsw/winsw) .

the config xml file example:
`<executable>D:\windows_exporter\windows_exporter-0.16.0-amd64.exe</executable>
  <arguments>--config.file=D:\windows_exporter\config.yml</arguments>`
