### ISSUE TITLE
Collection timed out when IIS collector is enabled

### ISSUE THREAD

**Issue by triciamesina** [prometheus-community/windows_exporter#839]
Hi All,

For the past few days, I haven't been able to run windows exporter when IIS collector is enabled in Windows Server 2016. I am getting "Collection timed out" when IIS collector is included in the collectors.enabled list. Otherwise, if I remove IIS and retain everything else, the exporter is running perfectly fine. 
Here is the config file I am using:
```xml
collectors:
  enabled: cpu,cpu_info,cs,logical_disk,memory,net,os,service,system,process,iis
collector:
  service:
    services-where: "Name='W3SVC' OR  Name='AppHostSVC' OR Name='IISADMIN' OR Name='MSFTPSVC' OR Name='MWMSVC' OR Name='WAS' OR Name='FTPSVC'"
  logical_disk:
    volume-blacklist: "HarddiskVolume.+|harddiskvolume.+"
  process:
    whitelist: "^w3wp|^W3WP"
log:
  level: warn
```
I've tried to add the below config but did not help:
```xml
telemetry:
  max-requests: 0
scrape:
  timeout-margin: 1
```
Can anyone help how I can run IIS collector again? Thank you!

**Comment by breed808** [comment]
Is there any relevant output from the `windows_exporter` executable when running the IIS collector? I'd recommend setting the log level to "debug" when running the IIS collector to gain as much output from the exporter as possible.

**Comment by triciamesina** [comment]
I only have these warn level logs. I will try to capture the debug level logs.

![image001](https://user-images.githubusercontent.com/16758095/135458365-e7ec5587-8fe2-43c6-a859-19b4e990f197.jpg)

**Comment by daveaowen** [comment]
I have rewritten the IIS metrics to use Perflib instead of WMI. I had the same issue as you, but after the move to Perflib, I haven't had any timeouts.

You can either build the MSI from the master branch yourself or wait for the new release.

**Comment by triciamesina** [comment]
Do you have the steps on how to create an msi build out of the master branch? Any idea when the new release will come? 
Attaching the debug level logs. Looks like only IIS collector is getting the time out.
![Debuglevel](https://user-images.githubusercontent.com/16758095/135570220-778de358-77fc-4bf0-a94c-a36b053e19e0.PNG)

**Comment by daveaowen** [comment]
Sure!

Clone the repo, install go on your machine and build the project (`go build .` in the repo). Then, move to the installer subdirectory and run the build.ps1 script and follow the instructions. Your MSI will be in windows_exporter\installer\Output

**Comment by kaffarell** [comment]
We can close this as this has been resolved @breed808
