### ISSUE TITLE
An error occurs after the exporter has been running for some time

### ISSUE THREAD

**Issue by since782312** [prometheus-community/windows_exporter#842]
**Windows version：** 
     Windows Server 2008 R2 Standard

**Service start command：**
`"C:\Program Files\windows_exporter\windows_exporter.exe" --log.format logger:eventlog?name=windows_exporter  --telemetry.addr :9182 --collectors.enabled "[defaults],memory,process,logon,logical_disk,net,tcp"`

![1632895430(1)](https://user-images.githubusercontent.com/42599738/135212133-6ec0f562-fcbc-4701-b933-a2fd339527b8.jpg)
![1632895474](https://user-images.githubusercontent.com/42599738/135212152-cfa46694-95e1-454e-9a3f-bd58d28bee3a.jpg)
![1632895509](https://user-images.githubusercontent.com/42599738/135212170-57519b90-dc9a-4ba2-9601-13521f765bf2.jpg)
![image](https://user-images.githubusercontent.com/42599738/135212850-34ddb57a-fb03-4591-b23e-5a55a721fb6d.png)

**Comment by breed808** [comment]
Without filters, the `process` and `service` collectors will be very slow, and likely to time out. The `logon` collector is also known to experience performance issues.

Do you still experience timeouts with these collectors disabled?
