### ISSUE TITLE
Collect textfile metrics not working

### ISSUE THREAD

**Issue by P1ton** [prometheus-community/windows_exporter#844]
Hi All!
I am trying to customize the assembly of metrics from a file. But it feels like he's just ignoring my file. There is no information in the logs about attempts to read the file. 
I tried without collector.textfile.directory and file in C: \Program Files\windows_exporter\textfile_inputs
I tried with collector.textfile.directory "C: \temp\metrics\"
In both cases it doesn't work
I used two version 0.14.0 and 0.16.0

Log:
`PS C:\Program Files\windows_exporter> .\windows_exporter.exe --log.level debug --log.format logger:eventlog?name=windows_exporter --collectors.enabled cpu,cs,logical_disk,net,system,service,os --telemetry.addr :9182 --collector.textfile.directory "C:\temp\metrics\"
time="2021-09-30T04:40:42+03:00" level=debug msg="Initializing SWbemServices" source="exporter.go:260"
time="2021-09-30T04:40:42+03:00" level=debug msg="Detected Windows version 6.300000\n" source="collector.go:47"
time="2021-09-30T04:40:42+03:00" level=warning msg="No where-clause specified for service collector. This will generate a very large number of metrics!" source="service.go:41"
time="2021-09-30T04:40:42+03:00" level=info msg="Enabled collectors: os, cpu, cs, logical_disk, net, system, service" source="exporter.go:338"
time="2021-09-30T04:40:42+03:00" level=info msg="Starting windows_exporter (version=0.14.0, branch=master, revision=922c08b85b60da8a444a57a84126448d7c993307)" source="exporter.go:378"
time="2021-09-30T04:40:42+03:00" level=info msg="Build context (go=go1.13.3, user=appvyr-win\\appveyor@APPVYR-WIN, date=20200907-07:33:36)" source="exporter.go:379"
time="2021-09-30T04:40:42+03:00" level=info msg="Starting server on :9182" source="exporter.go:382"
time="2021-09-30T04:40:49+03:00" level=debug msg="Generated WMI query SELECT * FROM Win32_ComputerSystem" source="wmi.go:24"
time="2021-09-30T04:40:49+03:00" level=debug msg="Generated WMI query SELECT * FROM Win32_Service" source="wmi.go:47"
time="2021-09-30T04:40:49+03:00" level=debug msg="Generated WMI query SELECT * FROM Win32_OperatingSystem" source="wmi.go:24"
time="2021-09-30T04:40:49+03:00" level=debug msg="collector net succeeded after 0.001003s." source="exporter.go:221"
time="2021-09-30T04:40:49+03:00" level=debug msg="collector logical_disk succeeded after 0.002002s." source="exporter.go:221"
time="2021-09-30T04:40:49+03:00" level=debug msg="collector cpu succeeded after 0.000000s." source="exporter.go:221"
time="2021-09-30T04:40:49+03:00" level=debug msg="collector system succeeded after 0.000000s." source="exporter.go:221"
time="2021-09-30T04:40:49+03:00" level=debug msg="collector cs succeeded after 0.018004s." source="exporter.go:221"
time="2021-09-30T04:40:50+03:00" level=debug msg="collector service succeeded after 0.348999s." source="exporter.go:221"
time="2021-09-30T04:40:50+03:00" level=debug msg="collector os succeeded after 0.362902s." source="exporter.go:221"
time="2021-09-30T04:41:04+03:00" level=debug msg="Generated WMI query SELECT * FROM Win32_ComputerSystem" source="wmi.go:24"
time="2021-09-30T04:41:04+03:00" level=debug msg="Generated WMI query SELECT * FROM Win32_Service" source="wmi.go:47"
time="2021-09-30T04:41:04+03:00" level=debug msg="collector system succeeded after 0.000000s." source="exporter.go:221"
time="2021-09-30T04:41:04+03:00" level=debug msg="collector logical_disk succeeded after 0.001002s." source="exporter.go:221"`

File:
`PS C:\Program Files\windows_exporter> cat C:\temp\metrics\test1.prom
my_sample_metric 1`
Encode - I tried ANSI (LF) and UTF-8 (LF)

Please help me to solve this problem

**Comment by JDA88** [comment]
Did you tried with the example in the documentation?
https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.textfile.md

From my experience it is very sensitive to the encoding of the file AND the type of newline character. (avoid `r`n and use only `n)

**Comment by JDA88** [comment]
I think you are missing the `textfile` in your `collectors.enabled` list
You are using:
`windows_exporter.exe --log.level debug --log.format logger:eventlog?name=windows_exporter --collectors.enabled cpu,cs,logical_disk,net,system,service,os --telemetry.addr :9182 --collector.textfile.directory "C:\temp\metrics\"`
And you should be using:
`windows_exporter.exe --log.level debug --log.format logger:eventlog?name=windows_exporter --collectors.enabled cpu,cs,logical_disk,net,system,service,os,textfile --telemetry.addr :9182 --collector.textfile.directory "C:\temp\metrics\"`

**Comment by P1ton** [comment]
> I think you are missing the `textfile` in your `collectors.enabled` list You are using: `windows_exporter.exe --log.level debug --log.format logger:eventlog?name=windows_exporter --collectors.enabled cpu,cs,logical_disk,net,system,service,os --telemetry.addr :9182 --collector.textfile.directory "C:\temp\metrics\"` And you should be using: `windows_exporter.exe --log.level debug --log.format logger:eventlog?name=windows_exporter --collectors.enabled cpu,cs,logical_disk,net,system,service,os,textfile --telemetry.addr :9182 --collector.textfile.directory "C:\temp\metrics\"`

Many thanks for the help!
