### ISSUE TITLE
Disk Latency Metric in Windows Exporter

### ISSUE THREAD

**Issue by vgoudphilips** [prometheus-community/windows_exporter#845]
Do we have Disk Latency metric in any collector in Windows exporter ?
Could not able to find it in windows exporter collectors; saw some references in wmi exporter which is old.

could you please anyone help us how to get this metric or any other alternative way to get this metric.

**Comment by zakiharis** [comment]
yes,

you can use

windows_logical_disk_read_latency_seconds_total
windows_logical_disk_write_latency_seconds_total
