### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by krdineshbny** [prometheus-community/windows_exporter#854]
Hi 

We are currently using version 0.16.0 on more than 20k servers, which is 10months old now.
There were many fixes merged into master for this project after the current release v0.16.0 
So when is the new release planned for?

**Comment by rismoney** [comment]
I normally don't hijack issues, but this one caught my eye.  20k windows servers?  What does your monitoring stack look like?  I am looking to do about 1/10th of that for windows servers and need to know if I am going the right way.  Are you doing just app monitoring, or overall health as well (down services/nodes/traditional monitoring).  Can you comment on how much scraping/frequency ingestion you are doing?  Any tips/pointers would be greatly appreciated.  I'm super early on the monitoring journey.  I am trying to get off an old nagios implementation fast.

**Comment by breed808** [comment]
The `v0.17.0` release has just been published
