### ISSUE TITLE
How to get cpu saturation metrics ? like node_load5 in node_exporter

### ISSUE THREAD

**Issue by xflu** [prometheus-community/windows_exporter#866]
There's  **node_load5** metric  in node_exporter.

It's the CPU Load average, which is a measurement of how many tasks are waiting in a kernel run queue in 5 minutes.

Does something like that exist in windows_exporter?

**Comment by breed808** [comment]
To my knowledge, Windows doesn't expose metrics comparable to the load averages found in the node_exporter.

CPU pressure could be measured using metrics found in the `cpu` collector (to an extent), but I don't believe any metrics are present for waiting kernel tasks. If you can find a metric source for those, we'd be happy to integrate them into the exporter.
