### ISSUE TITLE
Is there any indicator that can record the restart time of the process？

### ISSUE THREAD

**Issue by jihaojiemo** [prometheus-community/windows_exporter#877]
I now have a requirement to monitor whether a process has been restarted and to record the exact time of the restart. 
Whether or not it can be monitored? Thanks!

**Comment by breed808** [comment]
`windows_process_start_time` would be the metric you're looking for. Changes in the start time will indicate a restart of the process.

Note that the `process_id` label will change on restart as well, so your metric query will need to account for that.
