### ISSUE TITLE
Monitoring of disk mirrors?

### ISSUE THREAD

**Issue by frenkye** [prometheus-community/windows_exporter#878]
Hi,

I have question does current windows exporter have metrics on disk mirroring? I check few time and could not see any.

if no is it planned or way to go would be custom script into textfiles?

**Comment by breed808** [comment]
Not to my knowledge. The `logical_disk` collector _might_ expose relevant metrics for a mirrored disk.

If there's a perflib or WMI source for mirrored disk metrics, we could add another collector.
