### ISSUE TITLE
DHCP Free DHCP IPs

### ISSUE THREAD

**Issue by manuel-held** [prometheus-community/windows_exporter#880]
Hey Hi!

Is it possible to get the Number of Free IP Addresses?

**Comment by breed808** [comment]
Not currently: the perflib source used by the `dhcp` collector doesn't currently expose any lease metrics.

I'd consider this an important metric; if you can find a good source for the metric we could consider including it in the `dhcp` collector.

**Comment by firesalp** [comment]
Hello @breed808 ,

A good source of data is the powershell console with the commands listed in this documentation:
https://github.com/MicrosoftDocs/windows-powershell-docs/tree/main/docset/winserver2022-ps/dhcpserver

Get-DhcpServerv4Scope and Get-DhcpServerv4ScopeStatistics are 2 good commands to start with. To be honnest, the actual DHCP module in this exporter is not very usefull to me without this statistics!

I'm not a dev, but i'd like to know how to implement this kind of data returned by powershell. Do you have any ideas?
