### ISSUE TITLE
telemetry:   addr: not work in config file. (0.16.0)

### ISSUE THREAD

**Issue by voklav** [prometheus-community/windows_exporter#881]
Hello everyone.
I noticed that the port changes in the config file do not reflect the change.
for example:
Change the port and enable some collectors in the config file.
```yml
telemetry:
  addr: ":9192"
```
after that, the service is starting in the old predefined port. Other changes are reflected.
this is how the service was installed:

`msiexec /i C:\windows_exporter\windows_exporter-0.16.0-amd64.msi LISTEN_PORT=59182 --% EXTRA_FLAGS="--config.file=C:\windows_exporter\config.yml"`

the flag appears to have a higher priority than the config and the config cannot change it
I reinstalled the service without specifying the port and again: the default port cannot be changed from the config file.

**Comment by breed808** [comment]
The flag having a higher priority than the config file is by design. The port specified in the config file should have an effect if no flag is specified, so that may need further investigation.

I'll see if I can reproduce this.
