### ISSUE TITLE
Poor perflib performance

### ISSUE THREAD

**Issue by vx-i** [prometheus-community/windows_exporter#886]
Hi all,

I'm facing very poor performance since some time on one of my VM's. My command is very simple:

`"C:\Program Files\windows_exporter\windows_exporter.exe" --log.format logger:eventlog?name=windows_exporter --collectors.enabled "service" --collector.service.services-where="Name='windows_exporter'" --telemetry.addr :9182  ` 

The result looks like this:
```
go_info{version="go1.15.6"} 1
go_threads 10
process_cpu_seconds_total 1.578125
windows_exporter_build_info{branch="master",goversion="go1.15.6",revision="f316d81d50738eb0410b0748c5dcdc6874afe95a",version="0.16.0"} 1
windows_exporter_collector_duration_seconds{collector="service"} **0.8274979**
windows_exporter_collector_success{collector="service"} 1
windows_exporter_collector_timeout{collector="service"} 0
windows_exporter_perflib_snapshot_duration_seconds **55.2513731**
windows_service_info{display_name="windows_exporter",name="windows_exporter",process_id="12848",run_as="LocalSystem"} 1
```
Sure, I can rise the timeout to 1 min, but it is just a workaround. I would like to understand why perflib is triggered. And why it took so long. 

I see this behavior with version 0.15 and 0.16.

**Comment by breed808** [comment]
Does this only occur with the `service` collector on a single host? Is this reproducible with other hosts and/or collectors?

**Comment by vx-i** [comment]
The issue also occurs on e.g. os collector, but only on this machine. All other windows_exporters manage it under 1 sec.

**Comment by vx-i** [comment]
I've tried perflib_exporter.exe and got all data in 1,2 sec.

**Comment by breed808** [comment]
Both the `service` and `os` collectors source metrics from WMI in the `v0.16.0` release. We've had issues with WMI before; it's not performant and a little unstable as a metric source.

Are you able to build and test from the `master` branch? Both collectors have been modified to remove WMI as a metric source (though the `service` collector requires a flag set, see the [documentation](https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.service.md)).

**Comment by breed808** [comment]
@vx-i could you try the `v0.17.0` release and let me know if the problem persists?

**Comment by vx-i** [comment]
After some tests I can confirm that `os` performs very good. But `service` is still an issue. It takes approx. 30-50 seconds.

I'm using this command: "C:\Program Files\windows_exporter\windows_exporter.exe" --log.format logger:eventlog?name=windows_exporter --collectors.enabled "service" --collector.service.use-api --telemetry.addr :9182   

Maybe it has to do with the big amount of services? Is there a way to filter API results?

**Comment by breed808** [comment]
The API method for the `service` collector doesn't currently support filtering, though we may be able to add it in a future release.

Does filtering with the WMI method reduce the collection time to a reasonable level?

**Comment by vx-i** [comment]
Here are some results. I'm still not sure if WMI is the bottleneck. See service collector versus perflib snapshot. Anyway the difference for filtered WMI result is only 0.5 sec. And 1 sec for API result.

`"C:\Program Files\windows_exporter\windows_exporter.exe"
--log.format logger:eventlog?name=windows_exporter
--collectors.enabled "service"
--collector.service.services-where="Name='windows_exporter'"
--telemetry.addr :9182   `

windows_exporter_build_info{branch="heads/tags/v0.17.1",...,version="0.17.1"} 1
windows_exporter_collector_duration_seconds{collector="service"} **0.8885495**
windows_exporter_collector_success{collector="service"} 1
windows_exporter_collector_timeout{collector="service"} 0
windows_exporter_perflib_snapshot_duration_seconds 57.8265943


`"C:\Program Files\windows_exporter\windows_exporter.exe" --log.format logger:eventlog?name=windows_exporter --collectors.enabled "service" --telemetry.addr :9182   `

windows_exporter_build_info{branch="heads/tags/v0.17.1",...,version="0.17.1"} 1
windows_exporter_collector_duration_seconds{collector="service"} **1.3782044**
windows_exporter_collector_success{collector="service"} 1
windows_exporter_collector_timeout{collector="service"} 0
windows_exporter_perflib_snapshot_duration_seconds 53.0060279


`"C:\Program Files\windows_exporter\windows_exporter.exe" --log.format logger:eventlog?name=windows_exporter --collectors.enabled "service" --collector.service.use-api --telemetry.addr :9182   `

windows_exporter_build_info{branch="heads/tags/v0.17.1",...,version="0.17.1"} 1
windows_exporter_collector_duration_seconds{collector="service"} **0.3734373**
windows_exporter_collector_success{collector="service"} 1
windows_exporter_collector_timeout{collector="service"} 0
windows_exporter_perflib_snapshot_duration_seconds 31.3720412

Finally a working example with os collector.

`"C:\Program Files\windows_exporter\windows_exporter.exe" --log.format logger:eventlog?name=windows_exporter --collectors.enabled "os" --collector.service.use-api --telemetry.addr :9182   `

windows_exporter_build_info{branch="heads/tags/v0.17.1",...,version="0.17.1"} 1
windows_exporter_collector_duration_seconds{collector="os"} 0.0130009
windows_exporter_collector_success{collector="os"} 1
windows_exporter_collector_timeout{collector="os"} 0
windows_exporter_perflib_snapshot_duration_seconds 0.0020014

**Comment by breed808** [comment]
That's interesting, is there anything unusual on this host, such as a high number of services that would need to be collected?

If you're able to reproduce this on another machine I might be able to assist, otherwise you could try attaching a [debugger](https://github.com/go-delve/delve) to view what is occurring during the snapshot. Sorry I can't be of more help than that...

**Comment by vx-i** [comment]
@breed808 The problem has not recurred in the last 6 months. Without me doing anything. Strange. I will close this issue.
