### ISSUE TITLE
DFSR backlog size metric

### ISSUE THREAD

**Issue by bbeattie-phxlabs** [prometheus-community/windows_exporter#890]
At the moment I'm collecting the DFSR backlog size through the text collector, but I suspect `collector/dfsr.go` would be a more appropriate place for this data to be extracted. Is this something anyone else would be interested in, or is text collector the preferred approach here? (Maybe the backlog size was intentionally excluded for reasons unclear to me.)

**Comment by breed808** [comment]
It would depend on the metric source. Perflib would be preferred, but we can use WMI or a Windows API where there's no other option.

If it is in Perflib, then apologies: I likely missed that during the initial `dfsr` collector implementation.

**Comment by bbeattie-phxlabs** [comment]
https://docs.microsoft.com/en-us/powershell/module/dfsr/get-dfsrbacklog into text collector is how I'm currently scripting it.

**Comment by breed808** [comment]
Powershell commands should be left to the `textfile` collector unless there's no other choice. Are you aware of a metric source at a lower level?

Perflib has been used as a metric source for the current `dfsr` collector, but there may be more.
