### ISSUE TITLE
can not read static metrics on ver17 

### ISSUE THREAD

**Issue by wellsyu** [prometheus-community/windows_exporter#904]
An error has occurred while serving metrics:

3 error(s) occurred:
* collected metric "windows_textfile_mtime_seconds" { label:<name:"file" value:"exportertextfile.prom" > gauge:<value:1.640743254e+09 > } was collected before with the same name and label values
* collected metric "windows_textfile_mtime_seconds" { label:<name:"file" value:"exportertextfile.prom" > gauge:<value:1.640743254e+09 > } was collected before with the same name and label values
* collected metric "windows_textfile_mtime_seconds" { label:<name:"file" value:"exportertextfile.prom" > gauge:<value:1.640743254e+09 > } was collected before with the same name and label values

**Comment by breed808** [comment]
Duplicate of #899. We should have a new release to fix this soon.
