### ISSUE TITLE
Build to to windows exporter  MSI file  

### ISSUE THREAD

**Issue by snmsmanager** [prometheus-community/windows_exporter#910]
Hello,

As per the guide , I have build the promethues windows exporter as exectable file and need to convert/build to to MSI file since need to use in AD policy server. Please explain the steps to do this concversion.

**Comment by breed808** [comment]
The steps to build the MSI files can be seen in the [CI configuration](https://github.com/prometheus-community/windows_exporter/blob/master/.github/workflows/ci.yml#L91).

You'll want to note the `Install Build deps`, `Build` and `Build Release Artifacts` steps.

**Comment by akrauza** [comment]
Assuming you have already have built or downloaded the MSI release from the release pages, you can follow the below steps:
1. Download the Windows 10 SDK (https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/)
2. Run the installer, and when prompted for which components to install, uncheck *all* of the options except `MSI tools`
3. Navigate to (assuming you are running a x64 box) `C:\Program Files (x86)\Windows Kits\10\bin\10.0.22000.0\x86` and run the `Orca-x86_en-us.msi` installer. Orca will now be installed and found in your start menu.
4. Open Orca from the start menu, and open the MSI from the file menu
5. Select `Properties` from the left, and configure as required. Below is a screenshot of my configuration from my home AD environment. The only line I had to customize is highlighted in green: `ENABLED_COLLECTORS`.
![image](https://user-images.githubusercontent.com/9043657/148856890-a3205348-a01b-442b-a7c1-ed2c35abf4dc.png)
6. Configure AD Group Policy as you would any other MSI.
