### ISSUE TITLE
windows_cpu_time_total description uses inconsistent terminology

### ISSUE THREAD

**Issue by rob-scheepens** [prometheus-community/windows_exporter#914]
Under https://github.com/prometheus-community/windows_exporter/blob/master/docs/collector.cpu.md#metrics, the Description for windows_cpu_time_total lists "system", but there is no such metric. Windows metrics are "idle", "dpc", "user", and "privileged". 

Sample:
```# TYPE windows_cpu_time_total counter
windows_cpu_time_total{core="0,0",mode="dpc"} 0.734375
windows_cpu_time_total{core="0,0",mode="idle"} 762.03125
windows_cpu_time_total{core="0,0",mode="interrupt"} 0.578125
windows_cpu_time_total{core="0,0",mode="privileged"} 5.640625

**Comment by breed808** [comment]
I don't think the description was originally intended to match the `mode` label, but I agree that it's best to reduce ambiguity here.

I'll modify the docs to fix this.
