### ISSUE TITLE
How can Prometheus monitor Windows processes with the same process name?

### ISSUE THREAD

**Issue by jihaojiemo** [prometheus-community/windows_exporter#916]
If I have two Python processes on my Windows computer, taskList doesn't tell them apart, but Windows's built-in performance counters do. I then tried to monitor both processes using Python #1 and Python #2 respectively, but Prometheus still only found monitoring data for one process named Python.

**Comment by breed808** [comment]
Could you provide more context on the issue? When you say that monitoring data is only found for one process, are you implying only a single Python process is being exposed?

Are the Python commands identical? What command flags are being passed to the exporter, and is there any relevant output from the exporter?

The `process` collector will expose metrics for duplicate process names, as the process ID and creating process IDs are included as flags.
