### ISSUE TITLE
IIS Site metrics Disappear 

### ISSUE THREAD

**Issue by peter-miroshnikov** [prometheus-community/windows_exporter#918]
I cant figure out why but since last week my `windows_exporter` doesn't report metrics for the sites on my `IIS`.
It works but only for `app_pools`.

Here are logs from the exporter.
![image](https://user-images.githubusercontent.com/1169237/149729526-00c8ae81-2b70-497a-9ed3-557fef7b95f1.png)

It starts as expected and works. If clearly states that the IIS metrics are collected.
But i can never see `windows_iis_requests_total` metric or any other metric that is `site` related.

I would like point out that those metrics worked as a charm since day 1 that i installed the windows exporter until last week.

Any guide or tips in how to tackle this problem will be greatly appreciated.

**Comment by breed808** [comment]
Initially I thought this might be related to #903, but your screenshot shows that you're using `v0.16.0`, not `v0.17.x`.

Did this issue start with a particular exporter version? Has anything changed on the host regarding IIS?

**Comment by aymericDD** [comment]
This PR merged in release **v0.17** should add the missing metrics https://github.com/prometheus-community/windows_exporter/pull/887
