### ISSUE TITLE
parsing error due to invalid escape sequence

### ISSUE THREAD

**Issue by aaronstutzer** [prometheus-community/windows_exporter#919]
error in event viewer:
`Error parsing "C:\\Program Files\\windows_exporter\\textfile_inputs\\app_conn_count.prom": text format parsing error in line 32: invalid escape sequence '\A'`

line 32 in the file:
```
mssql_connections{app="MSC20\AUCTI-orders-orders_publish-127.0.0.1"} 7710-3
mssql_connections{app="MSC20\AUCTI-Sessions-sessions_publish-127.0.0.1"} 7710-6
```

it seems like we get the error randomly. no changes and there is an error and later all is good again. the name of `app` does not change

**Comment by breed808** [comment]
Assuming this is a custom script pushing metrics to the `textfile` collector, you'll need to ensure you escape any backslashes in your label values.


From the [Prometheus docs](https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details):
> label_value can be any sequence of UTF-8 characters, but the backslash (\\), double-quote ("), and line feed (\n) characters have to be escaped as \\\\, \\", and \\n, respectively.
