### ISSUE TITLE
windows_exporter failure windows_process_thread_count help text

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [prometheus-community/windows_exporter#920]
I just test-updated to windows_exporter version `0.17.1` and collecting metrics now fails with this error:

```text
> curl.exe http://localhost:9182/metrics

An error has occurred while serving metrics:

2 error(s) occurred:
* collected metric windows_process_thread_count label:<name:"creating_process_id" value:"1348" > label:<name:"process" value:"sqlbrowser" > label:<name:"process_id" value:"6732" > gauge:<value:7 >  has help "Number of threads currently active in this process." but should have "Number of threads currently active in this process. An instruction is the basic unit of execution in a processor, and a thread is the object that executes instructions. Every running process has at least one thread."
* collected metric windows_process_thread_count label:<name:"creating_process_id" value:"1348" > label:<name:"process" value:"sqlwriter" > label:<name:"process_id" value:"7012" > gauge:<value:2 >  has help "Number of threads currently active in this process." but should have "Number of threads currently active in this process. An instruction is the basic unit of execution in a processor, and a thread is the object that executes instructions. Every running process has at least one thread."
```

Removing the `--collector.process.whitelist` Parameter causes the error to return for many (all?) process names with the same message.

I searched the repository for the mentioned text, it is contained in two different collectors:

<https://github.com/prometheus-community/windows_exporter/search?q=Number+of+threads+currently+active+in+this+process>

however `terminal_services` is not active in my case. I then looked at revision `0.17.1`:

The first mentioned HELP text is in fact used by the process collector:

<https://github.com/prometheus-community/windows_exporter/blob/d9f4264fc4ee183462fc23032ce9b60444411b87/collector/process.go#L123-L126>

This seems to somehow collide with this metric? Even though this collector is not enabled?

<https://github.com/prometheus-community/windows_exporter/blob/d9f4264fc4ee183462fc23032ce9b60444411b87/collector/terminal_services.go#L144-L147>

I am unfamiliar with golang and therefore not sure where `Namespace` and `subsystem` are set.

----

The Windows Service is running the exporter as:

```text
"C:\Program Files\windows_exporter\windows_exporter.exe" --log.format logger:eventlog?name=windows_exporter --collectors.enabled [defaults],process,mssql     --collector.textfile.directory C:\windows_exporter\textfile_collector --collector.process.whitelist="ax.+|AX.+|sql.+|SQL.+" --collector.service.services-where="Name LIKE 'ax5%'"
```

At the same time as upgrading to 0.17.1 I changed the MSI setup parameter to use `--collectors.enabled [defaults],process,mssql`

I then stopped the service, and started the exporter with all defaults:
```text
C:\Program Files\windows_exporter\
❯ .\windows_exporter.exe
```

Metrics collection is successful ✔ 

Next I started it as: `.\windows_exporter.exe --collectors.enabled process`
Metrics collection is successful and returns process metrics✔

Next I started it as: `.\windows_exporter.exe --collectors.enabled "[defaults],process"`
Metrics collection is successful and returns process and other metrics metrics✔

Next test: `.\windows_exporter.exe --collectors.enabled "[defaults],process,mssql"`
Metrics collection is successful and returns process and other metrics metrics✔

Restarted the exporter as windows service, the error is still reproducible.

Startet it from powershell with:
```text
.\windows_exporter.exe --collectors.enabled "[defaults],process,mssql" --collector.process.whitelist="ax.+|AX.+|sql.+|SQL.+"

time="2022-01-19T16:10:27+01:00" level=warning msg="No where-clause specified for service collector. This will generate a very large number of metrics!" source="service.go:48"
time="2022-01-19T16:10:27+01:00" level=info msg="Enabled collectors: net, cs, system, logical_disk, process, cpu, textfile, mssql, service, os" source="exporter.go:348"
time="2022-01-19T16:10:27+01:00" level=info msg="Starting windows_exporter (version=0.17.1, branch=heads/tags/v0.17.1, revision=d9f4264fc4ee183462fc23032ce9b60444411b87)" source="exporter.go:400"
time="2022-01-19T16:10:27+01:00" level=info msg="Build context (go=go1.17.5, user=runneradmin@fv-az177-480, date=20220102-09:24:12)" source="exporter.go:401"
time="2022-01-19T16:10:27+01:00" level=info msg="Starting server on :9182" source="exporter.go:404"
time="2022-01-19T16:10:27+01:00" level=info msg="TLS is disabled." source="gokit_adapter.go:38"
```

Metrics collection is successful ✔ (???)

Tried starting with `--log.level=debug`  as windows Service (`"C:\Program Files\windows_exporter\windows_exporter.exe" --log.level=debug --log.format logger:eventlog?name=windows_exporter --collectors.enabled [defaults],process,mssql     --collector.textfile.directory C:\windows_exporter\textfile_collector --collector.process.whitelist="ax.+|AX.+|sql.+|SQL.+" --collector.service.services-where="Name LIKE 'ax5%'"`)

but there are now debug logs in the Windows Event Log?

... Investigating...

**Comment by breed808** [comment]
The `thread_count` metric in the `terminal_services` collector is a red herring: the `Namespace` and `subsystem` variables are used to build the full metric name.

So `windows_process_thread_count` and `windows_terminal_services_thread_count`. It's also worth noting that the `terminal_services` metric was renamed in fc33fa32.

Let me know if you need any assistance with troubleshooting.

**Comment by Mario-Hofstaetter** [comment]
@breed808 I have a test machine running `(version=0.17.1, branch=heads/tags/v0.17.1, revision=d9f4264fc4ee183462fc23032ce9b60444411b87)` just fine (windows service, same settings).

Locally on my notebook the error is still present and I've no clue what's going on. What are my options?

**Comment by Mario-Hofstaetter** [comment]
So I have now updated to `0.18.0` on my notebook and the error is gone for the moment.
No idea what was happening there before... @breed808 

Thus closing this issue for now.
