### ISSUE TITLE
 Problem installing as a service using MSI specifying web-config.yml to use TLS (0.17.1)

### ISSUE THREAD

**Issue by camaluq** [prometheus-community/windows_exporter#922]
I have had problems installing windows_exporter as a service on windows 10 using msiexec specifying a web-config.yml with the tls certificates like [here](https://github.com/prometheus/exporter-toolkit/blob/master/docs/web-config.yml): 

```
tls_server_config:
  cert_file: server.crt
  key_file: server.key
```

msiexec /i windows_exporter-0.17.1-amd64.msi EXTRA_FLAGS="**--web.config.file web-config.yml** --telemetry.addr :443"

Error:
cannot start windows_exporter: open web-config.yml: **The system cannot find the file specified**.

It works fine running it directly (when i use double quotes in the exe path):

`"C:\Program Files\windows_exporter\windows_exporter.exe" --telemetry.addr :443 --web.config.file "C:\Program Files\windows_exporter\web-config.yml"`

Or installing as a service with msiexec without specifying web-config.yml because don't have space (c:\program files\).

`msiexec /i windows_exporter-0.17.1-amd64.msi EXTRA_FLAGS="--collector.textfile.directory I:\textfile_collector\ --telemetry.addr:9090"`

In my case, the quickest thing has been to move the installation to c:\windows_exporter\ and change the execution of the service:

`sc config windows_exporter binPath="c:\windows_exporter\windows_exporter.exe --telemetry.addr :443 --web.config.file "c:\windows_exporter\web-config.yml"`

I think it would be a good idea to fix the problem in future releases.

You can fix the problem in creating the service using code or you can change the installation path so that you don't have to deal with the problem of spaces in c:\program files

Cheers,
cam

**Comment by breed808** [comment]
Regarding the first command you've run, which is failing: `msiexec /i windows_exporter-0.17.1-amd64.msi EXTRA_FLAGS="--web.config.file web-config.yml --telemetry.addr :443"`

Does this also fail when providing an absolute path to the `web-config.yml` file? E.G. `msiexec /i windows_exporter-0.17.1-amd64.msi EXTRA_FLAGS="--web.config.file C:\windows_exporter\web-config.yml --telemetry.addr :443"`

**Comment by camaluq** [comment]
When path is without spaces it works whether I specify the full path or not. E.G. `C:\windows_exporter`
The problem is when the path contains spaces because it is difficult to pass a path with quotes as an argument: E.G.

`msiexec /i windows_exporter-0.17.1-amd64.msi EXTRA_FLAGS="--web.config.file C:\Program Files\windows_exporter\web-config.yml --telemetry.addr :443"`

The msi installs in C:\Program Files

Cheers,
cam

**Comment by stephanrenggli** [comment]
If you specify the extra flags like this it should work: `EXTRA_FLAGS="--web.config.file=""C:\Program Files\windows_exporter\webconfig.yml"""`

**Comment by camaluq** [comment]
> Try
> 
> `msiexec /i windows_exporter-0.18.0-amd64.msi LISTEN_PORT=9100 EXTRA_FLAGS="--config.file=""C:\Program Files\windows_exporter\config.yml"" --web.config.file=""C:\Program Files\windows_exporter\web-config.yml"""`

I can confirm that it works fine! Sorry for the confusion.

Thanks,
cam
