### ISSUE TITLE
How to write a process restart alarm rule?

### ISSUE THREAD

**Issue by jihaojiemo** [prometheus-community/windows_exporter#926]
A process restart can be indicated by windows_process_start_time. If the value of this indicator changes, it indicates that the process is restarted. For example: windows_process_start_time{process="ACDG",instance="10.35.236.40"}, what if this cannot be greater than or less than?

**Comment by breed808** [comment]
> what if this cannot be greater than or less than?

Apologies, could you clarify this sentence?

**Comment by jihaojiemo** [comment]
> > what if this cannot be greater than or less than?
> 
> Apologies, could you clarify this sentence?



Because other indicators are greater than or less than a value when writing alarm rules, for example: `windows_process_handle_count{process="cmd", instance="{instance}"} > 5`.
But how to write alarm rules for `windows_process_start_time`? which cannot be greater than or less than a number.

**Comment by breed808** [comment]
Thanks, that helps to clarify.

In this instance you're wanting to detect change in a gauge metric, rather than compare it to an unknown threshold. Use [`delta`](https://prometheus.io/docs/prometheus/latest/querying/functions/#delta) to determine if the start time has changed.

E.G. to determine if the process has restarted in the past 2 hours `delta(windows_process_start_time{process="ABCD", instance="1.2.3.4"}[2h]) != 0`

**Comment by jihaojiemo** [comment]
> 谢谢，这有助于澄清。
> 
> 在这种情况下，您希望检测计量指标的变化，而不是将其与未知阈值进行比较。使用[`delta`](https://prometheus.io/docs/prometheus/latest/querying/functions/#delta)以确定是否开始时间发生了变化。
> 
> EG 确定进程是否在过去 2 小时内重新启动`delta(windows_process_start_time{process="ABCD", instance="1.2.3.4"}[2h]) != 0`

Thank you very much for your reply

**Comment by jihaojiemo** [comment]
> Thanks, that helps to clarify.
> 
> In this instance you're wanting to detect change in a gauge metric, rather than compare it to an unknown threshold. Use [`delta`](https://prometheus.io/docs/prometheus/latest/querying/functions/#delta) to determine if the start time has changed.
> 
> E.G. to determine if the process has restarted in the past 2 hours `delta(windows_process_start_time{process="ABCD", instance="1.2.3.4"}[2h]) != 0`

I understand now, Thank you very much for your reply!!!
