### ISSUE TITLE
failed to collecting windows_tcp_connections_established on release 0.17.1

### ISSUE THREAD

**Issue by csrlsm** [prometheus-community/windows_exporter#929]
i can not pull the metrics with windows_tcp_connections_xx on release 0.17.1
but it works on release 0.15.0

**Comment by breed808** [comment]
There's only been two minor housekeeping updates to the `tcp` collector between v0.15.0 and v0.17.1, so I'm not confident this is from a code change.

Could you provide more context on the issue? Is the exporter logging any errors? Are other collectors or metrics from the `tcp` collector not functioning correctly?

**Comment by csrlsm** [comment]
here is my config :
# Note this is not an exhaustive list of all configuration values
collectors:
  enabled: cpu,cs,logical_disk,net,os,memory,service,system,textfile,tcp,time
collector:
  service:
    services-where: Name='windows_exporter'
log:
  level: warn
scrape:
  timeout-margin: 0.5
telemetry:
  addr: ":9182"
  path: /metrics
  max-requests: 5

when i was run with 0.17.1 version , it return error as follow:
time="2022-02-09T11:37:59+08:00" level=error msg="failed collecting os metrics:<nil> The system cannot find the file specified.
" source="os.go:137"
time="2022-02-09T11:38:02+08:00" level=error msg="collector os failed after 3.354676s: The system cannot find the file specifie
d." source="exporter.go:207"

**Comment by breed808** [comment]
There's no output from the `tcp` collector in those logs. Try changing the log level to `debug`, and confirming if any other TCP metrics are failing.
