### ISSUE TITLE
collect number of lockedout ad accounts

### ISSUE THREAD

**Issue by djagoo** [prometheus-community/windows_exporter#930]
Would it be possible to add a metric for the total number of current lockedout ad accounts?

**Comment by breed808** [comment]
The `ad` collector doesn't currently expose any relevant metrics for locked accounts (it sources metrics from `Win32_PerfRawData_DirectoryServices_DirectoryServices`.

You could write a script to gather the metrics yourself and expose them with the `textfile` collector.
If you're able to find a metrics source (WMI, Perflib, etc), we could add them to the exporter.

**Comment by djagoo** [comment]
I wrote a script which performs an ldap query and pushes the metrics to the pushgateway. The only other source I found was using powershell but no WMI or Perflib.

If nobody else finds a solution using a better source you can close this issue. 

Thanks
