### ISSUE TITLE
Invalid namespace - Could not query WebAdministration namespace for IIS

### ISSUE THREAD

**Issue by eliassal** [prometheus-community/windows_exporter#933]
Hi, I run the exporter on a win10 with IIs latest version of IIS as follows

.\windows_exporter.exe  --collectors.enabled   os,iis,cache,logical_disk,memory,net,process,service,tcp 

in debug level, I see in the log this namespace error

> Could not query WebAdministration namespace for IIS worker processes: Exception occurred. (Invalid namespace ). Skipping" source="process.go:205"

all other perf counters come without any error.  Any idea or someone has met this and resolved it? Thanks

**Comment by breed808** [comment]
The `process` collector will attempt to query the `root\WebAdministration` WMI namespace during collection. If this fails, the IIS worker process name won't be included in the `process` flag for metrics exposed by the `process` collector.

You'll need to confirm if the `root\WebAdministration` namespace is present on the affected host(s).

**Comment by eliassal** [comment]
Hi, you are correct, it was missing, I added it and now the error disappeared. However, as soon as I try anything in (win10 or win server 2019)

> http://mywin10:9182/metrics

or

> http://myWinServer2019:9182/metrics

I get so many errors

```
label:<name:"status_code" value:"401" >  counter:<value:0 > } was collected before with the same name and label values
...
...
label:<name:"status_code" value:"403" > counter:<value:0 > } was collected before with the same name and label values
```

and so ion as you can notice in the snapshot
![iisCollector](https://user-images.githubusercontent.com/8447864/151946909-523b0357-7f27-4bc7-95bf-435b62b71963.jpg)

**Comment by breed808** [comment]
MSI and EXEs are available at the release page: https://github.com/prometheus-community/windows_exporter/releases/tag/v0.18.0

**Comment by eliassal** [comment]
Thanks, I downloaded it. However, in prometheur interface I get figures which are different from what I see in Grafana in spite oif the fact I use the same query. Have you seen this, or can it be a sync issue? Thanks again

![prometDifferent](https://user-images.githubusercontent.com/8447864/151958271-f3a1eb8b-9c7b-40bb-afee-565520e7932f.jpg)

![prometDifferent_002](https://user-images.githubusercontent.com/8447864/151958374-5e264599-10d7-40bc-9021-264832be77df.jpg)

**Comment by breed808** [comment]
Is the discrepancy also present when using the `rate()` function?

**Comment by eliassal** [comment]
Yes, with rate they are almost similar but not the case with increase

**Comment by breed808** [comment]
The [increase documentation](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase) states that some extrapolation is performed to cover the full time range, though I'm unsure if this would be responsible for such a large difference in metrics.

It would be interesting to see if the issue persists with a larger range, such as `1h`. Either way, this doesn't appear to be caused by the exporter, as the issue is from metric differences between Prometheus and Grafana, rather than collection.
