### ISSUE TITLE
IIS collector site and app whitelist and blacklist are ignored in version 0.18.0

### ISSUE THREAD

**Issue by JDA88** [prometheus-community/windows_exporter#936]
Hi, the 4 following flags are completely ignored in version 0.18, the same flags work as expected in version 0.16

- --collector.iis.site-whitelist
- --collector.iis.site-blacklist
- --collector.iis.app-whitelist
- --collector.iis.app-blacklist

It can be an huge issue because **all** the sites and apps are listed

PS: I only tested with the command line

**Comment by breed808** [comment]
The site & app checks were removed in 82f17fd60723c0d1a8ad184e4c427c4f623165ca but the flags were left as-is.

I'll add the checks back and see if anything else is required to fix this.

**Comment by JDA88** [comment]
Once the fix is in place, if you can provide me a test build I can do the checks and compare various combination with  0.16.0

**Comment by breed808** [comment]
Are you comfortable building from a feature branch? I don't believe artifacts from our PR pipelines are available to all users.

`git clone https://github.com/breed808/windows_exporter.git -b iis_flags` then run `go build` when in the `windows_exporter` directory.

**Comment by JDA88** [comment]
Unfurtunatly no. I have 0 knowledge in GO and I'm complete noob with git.

**Comment by breed808** [comment]
OK, try downloading https://file.io/B58kNccUa0J3 and extracting the archive. I've included a checksum and PGP signature to add trustworthiness to downloading a random EXE off the internet.

**Comment by JDA88** [comment]
Great I'll look at it

**Comment by JDA88** [comment]
Here are the test results:

`--collector.iis.site-whitelist="Site1"`

:heavy_check_mark: Same result for the 0.16.0 and test build, except the test built add the `metric{site="_Total"}` which is not present un 0.16.0

`--collector.iis.app-blacklist="Site1"`

:heavy_check_mark: Same result for the 0.16.0 and test build, except the test built add the `metric{site="_Total"}` which is not present un 0.16.0

`--collector.iis.site-whitelist="Site1"`

:x: Does not work. 0.16.0 show only the metrics for "Site1", but test build show ALL sites metrics + `{site="_Total"}`

`--collector.iis.site-blacklist="Site1"`
:x: Does not work. 0.16.0 show all sites metrics except for "Site1", but test build show ALL sites metrics + `{site="_Total"}`

**Comment by JDA88** [comment]
For the `{site="_Total"}` metrics on sites, I don’t know if it’s an expected behavior or an artefact but if it’s expected, in my opinion, we should be able to opt-in / opt-out with the whitelist / blacklist options once they start working again

**Comment by breed808** [comment]
Thanks for testing that. I think I've identified the issue with the sites, can you extract and run https://file.io/3TRE25Ji0w0M and let me know if it is resolved?

**Comment by JDA88** [comment]
I have tested the 4 filters separately and the combination we plan to use in production:
```
--collector.iis.app-whitelist "App1"
--collector.iis.app-blacklist "App1"
--collector.iis.site-whitelist="Site1"
--collector.iis.site-blacklist="Site1"
--collector.iis.app-whitelist="App1|App2" --collector.iis.site-blacklist=".+"
```
Results: 0.16.0 and the testbuild v2 have exactly the same output. `{site="_Total"}` is also gone

Thank you very much for the fix!

**Comment by breed808** [comment]
Thanks again for testing, it's really helpful :+1:
I'll raise a PR to get this into `master` and the next release.

**Comment by JDA88** [comment]
Sorry to ask about that but when is the next version (0.18.1?) planned? 
I don't know if it't automatic every week if there is a bug fix or if it's manual :)

**Comment by breed808** [comment]
Releases are manual; I'll cut a v0.18.1 release soon for you
