### ISSUE TITLE
Current implementation of the "*_state" metric might be suboptimal from a dashboard / storage perspective

### ISSUE THREAD

**Issue by JDA88** [prometheus-community/windows_exporter#938]
I have been playing with the windows_exporter metrics and Grafana for a while now and I have come across a few issues with the current implementation of the "*_state" metrics, for example `windows_service_state` or `windows_iis_current_application_pool_state` (there are probably more but those are the one I have worked with)

1. Metric count:
    - For every Windows service that we monitor we have 8 metrics and for every IIS application pool we have 7. 
When you have thousands of servers monitored and each of them have multiple services or pool this multiplication factor add up very fast.
I have an impact on storage or on SAS pricing if you use Grafana Cloud.
2. Dashboards and graphical representation:
    - The current implementation make it impossible (or at least I did not managed it) to use the `State timeline` grafana visualization which is the perfect visualization for something that can change state
3. Consistency:
    - State in `windows_service_state` is lowercase, and in `windows_iis_current_application_pool_state` it's upercase

My proposition would be to Replace (or Add to) the currents implementation (1 metric per state per item) with a single metric per item with a value that represent the state.
For example replace:
```
# HELP windows_service_state The state of the service (State)
# TYPE windows_service_state gauge
windows_service_state{name="w32time",state="continue pending"} 0
windows_service_state{name="w32time",state="pause pending"} 0
windows_service_state{name="w32time",state="paused"} 0
windows_service_state{name="w32time",state="running"} 1
windows_service_state{name="w32time",state="start pending"} 0
windows_service_state{name="w32time",state="stop pending"} 0
windows_service_state{name="w32time",state="stopped"} 0
windows_service_state{name="w32time",state="unknown"} 0
windows_service_state{name="w3svc",state="continue pending"} 0
windows_service_state{name="w3svc",state="pause pending"} 0
windows_service_state{name="w3svc",state="paused"} 0
windows_service_state{name="w3svc",state="running"} 1
windows_service_state{name="w3svc",state="start pending"} 0
windows_service_state{name="w3svc",state="stop pending"} 0
windows_service_state{name="w3svc",state="stopped"} 0
windows_service_state{name="w3svc",state="unknown"} 0
```
With:
```
# HELP windows_service_state The state of the service (1 - Stopped, 2 - Start Pending, 3 - Stop Pending, 4 - Running, 5 - Continue Pending, 6 - Pause Pending, 7 - Paused)
# TYPE windows_service_state gauge
windows_service_state{name="w32time"} 4
windows_service_state{name="w3svc"} 4
```

Of curse the `HELP` of `windows_service_state` should include the code to state corespondance, like the `HELP` of `windows_iis_current_application_pool_state` already does.

Implementation on Grafana using the `State timeline` is then very easy, you use the `Value mappings` to set the display name and the colors:
![image](https://user-images.githubusercontent.com/67072186/152120952-0cd474db-b6be-4c9d-99ea-a42216a23cb4.png)
And you get the perfect representation of services over time:
![image](https://user-images.githubusercontent.com/67072186/152122001-e6cf19aa-38fb-4212-bdd2-1130decf1ade.png)

From my point of view (but I can be dead wrong) the single metric per item have only advantage
- Much more efficient in storage and metrics count
- Represent the true history of the state and it's easyer to graph / display

Query examples with the new version
- Query a specific state:
    - Old: `windows_service_state{name = "example_service", state="running"} == 1`
    - New: `windows_service_state{name = "example_service"} == 4`
- Query a percent of uptime:
    - Old: `avg_over_time(windows_service_state{name = "example_service", state = "running"}[1d])`
    - New: `count_over_time((windows_service_state{name = "example_service"} == 4)[1d:]) / count_over_time((windows_service_state{name = "example_service"})[1d:])`

PS: You can easily convert the current implementation to a single metric per item with a rule (this is what we currently do for the services) and then filter the orriginals metrics
```
     MIN without (state)(windows_service_state{state = "stopped"}          * 1) +
     MIN without (state)(windows_service_state{state = "start pending"}    * 2) +
     MIN without (state)(windows_service_state{state = "stop pending"}     * 3) +
     MIN without (state)(windows_service_state{state = "running"}          * 4) +
     MIN without (state)(windows_service_state{state = "continue pending"} * 5) +
     MIN without (state)(windows_service_state{state = "pause pending"}    * 6) +
     MIN without (state)(windows_service_state{state = "paused"}           * 7) +
     MIN without (state)(windows_service_state{state = "unknown"}          * 0)
```

**Comment by breed808** [comment]
Apologies, I've not had time to give this an in-depth review so far.

My initial impression is that this is both well thought out and has merit; it echoes my frustration monitoring services a couple years back with this exporter.

The point regarding label consistency should be addressed regardless of the decision to adopt this approach or retain the current labelling scheme.

The current method with the `state` label allows a user to determine uptime of a service. E.G. `avg_over_time(windows_service_state{name = "example_service", state = "running"}[1d])`.
Could this be done with the proposed method of differing values? Off the top of my head I think counting value occurrences might work, such as
```
count_over_time((windows_service_state{name = "example_service"} == 4)[1d:]) / count_over_time(windows_service_state{name = "example_service"}[1d])
```

**Comment by JDA88** [comment]
For the label consistency, I agree, it should be addressed separately if the current labelling scheme persist.

For the uptime, I can confirm that your query works perfectly on our dataset (Using the condensed metric). Do you have other example of query people might use?

I will add your xample to the original post and what might look the new HELP for `windows_service_state`

**Comment by breed808** [comment]
Revisting this after your recent link (thanks for the reminder!): did you envision this change to include only the `windows_service_state` metric? Or others such as `windows_service_status` and `windows_service_startmode`?

**Comment by JDA88** [comment]
You are right we can do even better; I propose we go from this:
```
# HELP windows_service_state The state of the service (State)
# TYPE windows_service_state gauge
windows_service_state{name="lanmanserver",state="continue pending"} 0
windows_service_state{name="lanmanserver",state="pause pending"} 0
windows_service_state{name="lanmanserver",state="paused"} 0
windows_service_state{name="lanmanserver",state="running"} 1
windows_service_state{name="lanmanserver",state="start pending"} 0
windows_service_state{name="lanmanserver",state="stop pending"} 0
windows_service_state{name="lanmanserver",state="stopped"} 0
windows_service_state{name="lanmanserver",state="unknown"} 0

# HELP windows_service_start_mode The start mode of the service (StartMode)
# TYPE windows_service_start_mode gauge
windows_service_start_mode{name="lanmanserver",start_mode="auto"} 1
windows_service_start_mode{name="lanmanserver",start_mode="boot"} 0
windows_service_start_mode{name="lanmanserver",start_mode="disabled"} 0
windows_service_start_mode{name="lanmanserver",start_mode="manual"} 0
windows_service_start_mode{name="lanmanserver",start_mode="system"} 0

# HELP windows_service_status The status of the service (Status)
# TYPE windows_service_status gauge
windows_service_status{name="lanmanserver",status="degraded"} 0
windows_service_status{name="lanmanserver",status="error"} 0
windows_service_status{name="lanmanserver",status="lost comm"} 0
windows_service_status{name="lanmanserver",status="no contact"} 0
windows_service_status{name="lanmanserver",status="nonrecover"} 0
windows_service_status{name="lanmanserver",status="ok"} 1
windows_service_status{name="lanmanserver",status="pred fail"} 0
windows_service_status{name="lanmanserver",status="service"} 0
windows_service_status{name="lanmanserver",status="starting"} 0
windows_service_status{name="lanmanserver",status="stopping"} 0
windows_service_status{name="lanmanserver",status="stressed"} 0
windows_service_status{name="lanmanserver",status="unknown"} 0

# HELP windows_service_info A metric with a constant '1' value labeled with service information
# TYPE windows_service_info gauge
windows_service_info{display_name="Server",name="lanmanserver",process_id="1000",run_as="LocalSystem"} 1
```

To this:
```
# HELP windows_service_state The state of the service (1 - Stopped, 2 - Start Pending, 3 - Stop Pending, 4 - Running, 5 - Continue Pending, 6 - Pause Pending, 7 - Paused)
# TYPE windows_service_state gauge
windows_service_state{name="lanmanserver", display_name="Server"} 4

# HELP windows_service_start_mode The start mode of the service (0 - Boot, 1 - System, 2 - Automatic, 3 - Manual, 4 - Disabled)
# TYPE windows_service_start_mode gauge
windows_service_start_mode{name="lanmanserver", display_name="Server"} 2

# HELP windows_service_info A metric with a constant '1' value labeled with service information
# TYPE windows_service_info gauge
windows_service_info{name="lanmanserver",display_name="Server",process_id="1000",run_as="LocalSystem",current_state="Running",current_start_mode="Automatic"} 1
```

List of changes:
- `windows_service_state`
  - Remove the `state` label and use the value [Integers come from the API](https://learn.microsoft.com/en-us/dotnet/api/system.serviceprocess.servicecontrollerstatus?view=dotnet-plat-ext-7.0)
  - Add the `display_name` label here. It's usefull, and doesn't change that often (if ever)
  - Update the `# HELP` to reflect the change
  - **(Question)**  Should we rename this metric to ease the migration?

- `windows_service_start_mode`
  - Remove the `start_mode` label and use the value [Integers come from the API](https://learn.microsoft.com/en-us/dotnet/api/system.serviceprocess.servicestartmode?view=dotnet-plat-ext-7.0)
  - Add the `display_name` label here. It's usefull, and doesn't change that often (if ever)
  - **(Question)**  Should we rename this metric to ease the migration?

- `windows_service_status`
  - In my opinion we should remove this one, it’s redundant (+confusing) with `windows_service_state`, and it’s more related to the WMI communication API than the real status of the service. PowerShell `Get-Service` does not expose this for example
  - If you want to keep it we should merge it as one like the others

- `windows_service_info`
  - Add the start_mode
  - **(Optional)** We can add a `current_state` label here it can be used with a join for display purpose in dashboard or alarms
  - **(Optional)** We can add a `current_start_mode` label here it can be used with a join for display purpose in dashboard or alarms


With all those change we would go from 26 metrics to 3 or 4 metrics per service
If we go further with this you want me to create a separate issue for other collectors with similar issues? like IIS for example

**Comment by breed808** [comment]
@JDA88 I'm back and have started implementing this. Regarding the `windows_service_info` metric, were the `start_mode` and `current_start_mode` labels intended to have different values?

**Comment by JDA88** [comment]
`windows_service_info` label `current_start_mode` value should match the `windows_service_start_mode` _integer_ value.

I removed the `start_mode` from the list it was an error I think

**Comment by JDA88** [comment]
Here is a grafana dashboard to use with this new metric:

```
{
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 16,
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "prometheus"
      },
      "description": "Warning the \"Merge Consecutive\" value break the display",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "fillOpacity": 70,
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "insertNulls": false,
            "lineWidth": 0,
            "spanNulls": false
          },
          "mappings": [
            {
              "options": {
                "0": {
                  "color": "#808080",
                  "index": 7,
                  "text": "Unknown"
                },
                "1": {
                  "color": "semi-dark-red",
                  "index": 0,
                  "text": "Stopped"
                },
                "2": {
                  "color": "light-green",
                  "index": 1,
                  "text": "Start pending"
                },
                "3": {
                  "color": "orange",
                  "index": 2,
                  "text": "Stop pending"
                },
                "4": {
                  "color": "dark-green",
                  "index": 3,
                  "text": "Running"
                },
                "5": {
                  "color": "purple",
                  "index": 4,
                  "text": "Continue pending"
                },
                "6": {
                  "color": "dark-blue",
                  "index": 5,
                  "text": "Pause pending"
                },
                "7": {
                  "color": "light-blue",
                  "index": 6,
                  "text": "Paused"
                }
              },
              "type": "value"
            }
          ],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 19,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 7,
      "options": {
        "alignValue": "left",
        "legend": {
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": false
        },
        "mergeValues": false,
        "rowHeight": 0.9,
        "showValue": "never",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "prometheus"
          },
          "editorMode": "code",
          "exemplar": true,
          "expr": "windows_service_state{instance=\"$instance\"}",
          "interval": "",
          "legendFormat": "{{display_name}}",
          "range": true,
          "refId": "A"
        }
      ],
      "title": "Services status history",
      "transformations": [
        {
          "id": "convertFieldType",
          "options": {
            "conversions": [
              {
                "destinationType": "number",
                "targetField": "Value"
              }
            ],
            "fields": {}
          }
        }
      ],
      "type": "state-timeline"
    }
  ],
  "refresh": "10s",
  "schemaVersion": 38,
  "style": "dark",
  "templating": {
    "list": [
      {
        "definition": "label_values(windows_service_state,instance)",
        "hide": 0,
        "includeAll": false,
        "label": "Server",
        "multi": false,
        "name": "instance",
        "options": [],
        "query": {
          "query": "label_values(windows_service_state,instance)",
          "refId": "PrometheusVariableQueryEditor-VariableQuery"
        },
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "type": "query"
      }
    ]
  },
  "time": {
    "from": "now-24h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h"
    ]
  },
  "timezone": "",
  "title": "Windows - Services",
  "weekStart": ""
}
```

**Comment by breed808** [comment]
> `windows_service_info` label `current_start_mode` value should match the `windows_service_start_mode` _integer_ value.
> 
> I removed the `start_mode` from the list it was an error I think

I'm guessing the intention is the same for the `current_state` label? I don't mind adding these, though it would result in a much larger number of `windows_service_info` metrics.

**Comment by breed808** [comment]
Hmm, perhaps higher cardinality/time series might have been a more appropriate phrase.

There's 5 possible start mode flag values and 7 possible states, so adding the two flags would increase the maximum possible time series per Windows service by a factor of 35 for `windows_service_info`. Changes to service start modes would be rare, but state changes are uncommon and would result in an increase in the number of time series per service.

Again, I'm fine with implementing this, but want to raise the cardinality increase in the unlikely event there's any reported performance issues with the `service` collector after this change.

**Comment by JDA88** [comment]
You are right, from a cardinality perspective if the service change state a lot it will be the case. 
`current_start_mode` should not change often, but `current_state` it's possible.

From my perspective (and our use cases) the `windows_service_info` metric is there to enhance the alarms and is dropped on the remote storage. So, I might be biased.

**Comment by breed808** [comment]
That's alright, I'm comfortable adding it now and leaving open the option of removing the `current_state` label in the future, or hiding it behind a feature flag if necessary.

I've raised #1334 for the implementation of this. Are you comfortable compiling binaries from this feature branch to test, or would you prefer I provide those?

**Comment by JDA88** [comment]
I’m deeply sorry I’m a total noob on GO ecosystem, if you can provide a windows exe it would be great :)

**Comment by breed808** [comment]
> There must be an reason, why a metric for each state is preferred and I personally would like to know the reason before moving away from this pattern. I also raise the question in CNCF slack to get an better insight here.

Thanks for taking this approach, perhaps I should have done that earlier. I'm keen to discover the reasoning here, so let us know what you find.

**Comment by JDA88** [comment]
> There must be an reason, why a metric for each state is preferred and I personally would like to know the reason before moving away from this pattern. I also raise the question in CNCF slack to get an better insight here.

Although I understand the conversion of enum to StateSet it create a huge amount of metric and has a lot of downsize:
- It’s inefficient on the storage side
- It’s way harder to graph on a dashboard
- It's expensive on remote storage where you pay by metric (Grafana cloud for example)
- It generate much more network trafic on exporters

If you find valid reason to do so I’m happy to hear them but working with those for the past two year we moved away from them for the above reasons and a few more.. Conversion is easy from the StateSet to the Single one I just wanted others to benefit from it.

**Comment by jkroepke** [comment]
@JDA88 I agree with you, and I may share the same feeling. However I would like to know, why almost all official exporters favorite the current approach rather than the approach.

I would also like to discovery first, why the current approach (state-as-label) is the favorite one. 

@SuperQ I saw you across some platforms (reddit, slack) that you mostly recommends StateSets instead gauge. Do you can give us an insight here?

**Comment by SuperQ** [comment]
State Set is basically exactly how it is currently implemented. Prometheus does not currently support ENUM data as proposed.

The proposed solutions are exactly what we try and avoid in Prometheus because it makes it difficult to use.

**Comment by SuperQ** [comment]
The one optimization I would recommend is to make the `0` value output optional. This would reduce the storage needs by reducing the number of metrics. But it has the down side of being less ergonomic for alerting since you have missing data for states that you want to check against `0`.

**Comment by jkroepke** [comment]
>  is more difficult

@JDA88 from alerting point of view, the single metric is more difficult and less intuitive

For example, a query like

```yaml
alert: ServiceState
expr: windows_service_state{state=~"stressed|unknown"} > 0
for: 10m
labels:
  severity: critical
annotations:
  summary: Service {{ $labels.name }} is in state {{ $labels.state }}
```

are much more readable then

```yaml
---
alert: ServiceState
expr: windows_service_state == 6
for: 10m
labels:
  severity: critical
annotations:
  summary: Service {{ $labels.name }} is in state stressed
---
alert: ServiceState
expr: windows_service_state == 8
for: 10m
labels:
  severity: critical
annotations:
  summary: Service {{ $labels.name }} is in state unknown
---
```

And the state label can be re-used in the Alert description while the second example requires a distinct alert rule for each state.

@breed808 I'm also more on the reject way, since users can use recording rules to convert the StateSet to a single metric (see first post), but for know I would follow the recommendation by the Prometheus team here. (Thanks Ben!) I would stay with the current approach to have the same metrics experience across windows and node exporter.

**Comment by SuperQ** [comment]
Sorry, I don't have an extensive article explaining the rationale for the existing boolean-based state sets.

To add, I would love to have a first-class option for supporting ENUMs in Prometheus metrics. There are lots of server-side optimizations we could add to reduce the storage cost and improve the ergonomics. But someone needs to design and implement these features.

**Comment by JDA88** [comment]
You are right the alerting part is the only place where it is more readable (and it can be fixed with templating). But I still think it is not the case in all other scenarios.
I also have to agree that the "default" experience should be similar among all exporters.

Maybe the idea of a flag `–experimental.enum.as_gauge.enable`  to switch between the two would be nice, while waiting an hypothetical native Enum implementation on the Prometheus side. But it is harder to maintain on the dev side.

**Comment by breed808** [comment]
Thanks all, there's been some really good discussion on this topic. I'm in favour of keeping to the status quo at this stage, due to the reasons already stated in this thread (keeping to the existing standard, alerting).

That said, if any improvements to state metrics are made available in the future (such as enum types) I'd be happy to revisit this.
