### ISSUE TITLE
os collector fails when paging file is disabled (>= v0.17.0)

### ISSUE THREAD

**Issue by MrNiceforest** [prometheus-community/windows_exporter#939]
Having the Windows paging file disabled on all volumes results in the "os" collector failing on v0.17.0 or newer with below error.
Either running an older version (i.e. v0.16.0) or setting a paging file again (w/ system reboot for some reason) mitigates this, but would be great if this could be fixed in the exporter/collector again in an upcoming version.
Tested on both Windows 10 LTSC 2021 and Windows Server 2022.
```
failed collecting os metrics:<nil> The system cannot find the file specified.
collector os failed after 0.003015s: The system cannot find the file specified.
```

**Comment by breed808** [comment]
There's been similar issues raised with the recent changes to the `os` collector, but there hadn't been an association with the paging file until now.

I'll see if I can reproduce this myself, and determine the cause.

**Comment by ticteam** [comment]
same issue here!
collector os failed after 0.001917s: CreateFile R:\pagefile.sys: The system cannot find the file specified.
- windows_exporter version 0.18.1
- Windows server 2016
- EventID 102
started with:
`"C:\Program Files\windows_exporter\windows_exporter.exe" --log.format logger:eventlog?name=windows_exporter --collectors.enabled ad,cpu,dns,dhcp,exchange,iis,logical_disk,logon,memory,net,os,process,service,system,tcp --telemetry.addr :9182 `

**Comment by to-kr** [comment]
This is a problematic line of code: it requires ExistingPageFiles in the registry. **ExistingPageFiles key is missing when paging file is disabled.**

The workaround we use until fixed is to create an empty registry key, before running windows_exporter.
`
reg add "HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management" /v ExistingPageFiles /t REG_MULTI_SZ
`

https://github.com/prometheus-community/windows_exporter/blob/4d2a247e509e5ca85c6d8a9e8522174a2c7a5775/collector/os.go#L182

**Comment by breed808** [comment]
Thanks @to-kr, you've made it very easy to fix this :+1:

**Comment by alexandream87** [comment]
I have 2 servers with Windows Server 2012 R2 and the page file is active. The collector tries to fetch a file from drive "z:", but it doesn't exist.
For some reason this value is in the environment variable ExistingPageFiles.

`level=error msg="collector os failed after 0.00
5006s: CreateFile Z:\\pagefile.sys: The system cannot find the path specified."
source="exporter.go:207"`

**ExistingPageFiles:** `\??\C:\pagefile.sys \??\Z:\pagefile.sys`
