### ISSUE TITLE
windows_cs_logical_processors show only physical cores

### ISSUE THREAD

**Issue by AvdeevArtem** [prometheus-community/windows_exporter#944]
Hello.
Windows_cs_logical_processors return only physical cores but should return logical cores. I have servers with 96 logical cores and windows_cs_logical_processors return me value 48.

```
# HELP windows_cs_logical_processors ComputerSystem.NumberOfLogicalProcessors
# TYPE windows_cs_logical_processors gauge
windows_cs_logical_processors 48
```

windows_hyperv_hypervisor_logical_processors work fine and return right value 96

OS:
Windows server 2016, 2022
Windows 10
Exporter version:
0.17.1, 0.18.01

**Comment by JDA88** [comment]
Can you please give me the following values in the "Performance > CPU" tab of the Task Manager of the Hyper-V Host please?

- Sockets
- Cores
- Logical processors
- Host logical processors (If availeable)

Should look something like this:
![image](https://user-images.githubusercontent.com/67072186/154956306-192f3b6f-b434-465c-8519-0cca033c397d.png)

**Comment by Oscaramr** [comment]
@JDA88 you got a NASA computer? wtf 64 cores anyways https://i.imgur.com/uzFnPLO.png i want to get the 8 not 16 how could i do that

**Comment by JDA88** [comment]
I think your need is different from @AvdeevArtem issue, no?

The current version of the Exporter only expose `Logical Processors`. It doesn't expose the number of Sockets, the number of core per Processors and the fact that Hyper-Threading is enabled or not

I think of two way to fix this in the exporter:

- Create a few new metrics:
`windows_cs_sockets_count 2`
`windows_cs_cores_per_socket_count 8`
`windows_cs_logical_processors_count 16` (renamed from `windows_cs_logical_processors` as the `_count` suffix make sense)
The Hyper-Threading can be deducted by query if (`windows_cs_sockets_count` * `windows_cs_cores_per_socket_count` != `windows_cs_logical_processors_count)` then Hyper-Threading is enabled

- Change the current label `core` in the existing metric  `{core="0,0"}` to `{socket="0",core="0"}` 
Count by `socket` would give you the physical processors count
Count by `core` would give you the physical processors core count
Then the same query as above to get the Hyper-Threading status

**Comment by AvdeevArtem** [comment]
@JDA88 Hello.
![Screenshot_15](https://user-images.githubusercontent.com/45825379/155614242-9e7c2f37-46ce-4310-9a31-21853258d3ce.png)

**Comment by JDA88** [comment]
Thanks, @AvdeevArtem 

Ok, so your system have:

- 2 Physical CPU
- 48 Core each 
- Hyper-Threading is enabled

What does the following PowerShell command return?
`Get-WmiObject -class Win32_processor | ft NumberOfCores,NumberOfLogicalProcessors`


I might have an idea of what's appending but unfortunately I do not currently have a dual (or more) socket Windows with Hyper-Threading enable on hand to reproduce.

Maybe there is a bug that `windows_cs_logical_processors` return the wrong value on multi socket computers. Can someone esle make the test?

**Comment by jagbarcelo** [comment]
In my case, a Windows Server 2019 with **dual** Intel(R) Xeon(R) Gold 5218R CPU @ 2.10GHz:

Task Manager:
![image](https://user-images.githubusercontent.com/6704109/155750866-ffd784b1-2d2c-499a-ba5e-a3472814a631.png)

```
PS C:\> Get-WmiObject -class Win32_processor | ft NumberOfCores,NumberOfLogicalProcessors

NumberOfCores NumberOfLogicalProcessors
------------- -------------------------
           20                        40
           20                        40
```

The output of the url /integrations/windows_exporter/metrics:
```
# HELP windows_cs_logical_processors ComputerSystem.NumberOfLogicalProcessors
# TYPE windows_cs_logical_processors gauge
windows_cs_logical_processors 80
```

I'm not exactly using windows_exporter directly but through grafana-agent. I hope it helps anyway:
```
C:\Program Files\Grafana Agent>agent-windows-amd64.exe -version
agent, version v0.23.0 (branch: HEAD, revision: 36b8ca75)
  build user:       root@360da2ffbf37
  build date:       2022-02-10T15:31:14Z
  go version:       go1.17.6
  platform:         windows/amd64
```

**Comment by JDA88** [comment]
@jagbarcelo Thanks for the feedback, on your side everything is working fine. I'm out of ideas :(

**Comment by AvdeevArtem** [comment]
```
PS C:\Windows\system32> Get-WmiObject -class Win32_processor | ft NumberOfCores,NumberOfLogicalProcessors

NumberOfCores NumberOfLogicalProcessors
------------- -------------------------
           24                        48
           24                        48
```

windows_cpu_processor_performance show me 96 lines

This is strange because on 60 servers with relatively new CPUs the metric shows the wrong values, but on servers, with older CPUs like the Dual Xeon e-2690 v4 the metric shows the correct values

**Comment by 3rmack** [comment]
This is still the issue on version 0.24.0
