### ISSUE TITLE
Stop using SELECT * FROM WMI calls

### ISSUE THREAD

**Issue by Sarkie** [prometheus-community/windows_exporter#951]
We are tracking high cpu from WMIPrvSE.exe with windows_exporter being the WMI Client.

When calling WMI, please only select the columns you want, rather than all of them, this will reduce CPU and reduce the time it takes to run the query by up to 90%.

https://github.com/prometheus-community/windows_exporter/blob/master/collector/wmi.go

Example blog post I like to reference.

https://evilgpo.blogspot.com/2014/11/wmi-filter-queries-and-thoughts-on.html

**Comment by breed808** [comment]
Which collectors are causing high CPU in your environment?

**Comment by Sarkie** [comment]
Sorry @breed808 let me get the exact ones for you, but in general it is best practice to only Select the columns you need.

**Comment by Sarkie** [comment]
@breed808 do you have a list of WMI classes you use?
That might make it easier.
e.g. Win32_Process is very slow for instance always.

**Comment by breed808** [comment]
There's no collated list for the WMI classes in use. You'll have to review each collector that is currently using the `github.com/StackExchange/wmi` library.

**Comment by Sarkie** [comment]
That's ok, I'll enable all the collectors and monitor for you and feedback.

I assume it's hard to to update the query to only send the columns you want?

**Comment by breed808** [comment]
It would be difficult, though not impossible.

Classes are provided by the collector and queries are located in the [`wmi.go`](https://github.com/prometheus-community/windows_exporter/blob/master/collector/wmi.go) file. We could add additional queries, or specify the query inside the collector.

**Comment by Sarkie** [comment]
Let me collect all the ones that are problems for high cpu.

**Comment by Sarkie** [comment]
I thought this was fixed. I will look again
