### ISSUE TITLE
Feature Request: Support for Corsair PSU sensors

### ISSUE THREAD

**Issue by fusionstream** [prometheus-community/windows_exporter#953]
Hi.

A sensor for Corsair PSU metrics would be cool if added.

**Comment by fusionstream** [comment]
hi

**Comment by jkroepke** [comment]
Hi, 

@breed808 if you agree, I would recommend to stop accepted vendor specific collectors, since we are not able to observe them.

**Comment by breed808** [comment]
I think that's fair, we're not able to provide adequate support for such collectors. We don't often make breaking changes to the internal collector package structure; maintaining a fork with the vendor-specific collector would be possible for anyone needing such collectors.
