### ISSUE TITLE
How does windows_exporter support ARM?

### ISSUE THREAD

**Issue by jihaojiemo** [prometheus-community/windows_exporter#957]
Is there an exporter that supports monitoring ARM systems? Or how to monitor an ARM operating system?Thakns!

**Comment by breed808** [comment]
Go supports cross-compiling to different architectures by setting the `GOARCH` environment variables when running `go build`. See https://go.dev/doc/install/source#environment for more info.

I've not previously built ARM binaries of the exporter, though it'd be nice if someone could test if the exporter works correctly on an ARM device.

If there's sufficient demand an ARM binary could be added to new releases.

**Comment by kmf** [comment]
Would love ARM Support.

**Comment by breed808** [comment]
@kmf would you be interested in testing ARM binaries?

**Comment by kmf** [comment]
Only running Windows in a test VM. 
But I'll try to help where I can.

**Comment by breed808** [comment]
Let me know if the attached works. I've built it from master with `GOARCH=arm64`.

[windows_exporter_aarch64.zip](https://github.com/prometheus-community/windows_exporter/files/9431838/windows_exporter_aarch64.zip)

**Comment by kmf** [comment]
Works like a Charm :)

```
# HELP windows_system_context_switches_total Total number of context switches (WMI source: PerfOS_System.ContextSwitchesPersec)
# TYPE windows_system_context_switches_total counter
windows_system_context_switches_total 5.087025e+06
# HELP windows_system_exception_dispatches_total Total number of exceptions dispatched (WMI source: PerfOS_System.ExceptionDispatchesPersec)
# TYPE windows_system_exception_dispatches_total counter
windows_system_exception_dispatches_total 24478
# HELP windows_system_processor_queue_length Length of processor queue (WMI source: PerfOS_System.ProcessorQueueLength)
# TYPE windows_system_processor_queue_length gauge
windows_system_processor_queue_length 14
# HELP windows_system_system_calls_total Total number of system calls (WMI source: PerfOS_System.SystemCallsPersec)
# TYPE windows_system_system_calls_total counter
windows_system_system_calls_total 4.6622314e+07
# HELP windows_system_system_up_time System boot time (WMI source: PerfOS_System.SystemUpTime)
# TYPE windows_system_system_up_time gauge
windows_system_system_up_time 1.6612322662899492e+09
# HELP windows_system_threads Current number of threads (WMI source: PerfOS_System.Threads)
# TYPE windows_system_threads gauge
windows_system_threads 1882
# HELP windows_textfile_scrape_error 1 if there was an error opening or reading a file, 0 otherwise
# TYPE windows_textfile_scrape_error gauge
windows_textfile_scrape_error 1
```

**Comment by breed808** [comment]
Nice! I'll amend the CI/CD configuration to include an ARM64 build.
