### ISSUE TITLE
Feature Request:  Support for User Input Delay Performance Counters

### ISSUE THREAD

**Issue by mrclemensiii** [prometheus-community/windows_exporter#958]
Starting in Windows 2019 and higher Microsoft has released some new performance counters for Remote Desktop Session Hosts: https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/rds-rdsh-performance-counters

The ability to capture data for "User Input Delay per Process" and User Input Delay per Session(Max and Average)" 

The CimClasses involved are

- Win32_PerfRawData_LSM_UserInputDelayperProcess
- Win32_PerfFormattedData_LSM_UserInputDelayperProcess
- Win32_PerfRawData_LSM_UserInputDelayperSession
- Win32_PerfFormattedData_LSM_UserInputDelayperSession

**Comment by mrclemensiii** [comment]
@breed808 looks like the classes are available through Perflib.

PS C:\Windows\system32> Get-Counter -ListSet User* | Sort-Object -Property CounterSetName | Select CounterSetName

CounterSetName              
--------------              
User Input Delay per Process
User Input Delay per Session

**Comment by breed808** [comment]
@mrclemensiii do you currently use either the `terminal_services` or `remote_fx` collectors? We're considering merging the User Input Delay metrics to one of these collectors, due to the small number of new metrics.
