### ISSUE TITLE
Expose SSH session

### ISSUE THREAD

**Issue by sbudaraj-vcc** [prometheus-community/windows_exporter#960]
Is there any metric that shows the info of ssh sessions or users in a machine? This could be very useful to observe the usage of cloud instances or workstations. I found node_exporter for Linuz has a collector, logind, is there any for windows?

**Comment by breed808** [comment]
Native SSH functionality is relatively new to Windows, and after checking a test Windows 11 machine there are no SSH performance counters exposed.

There's a small chance some counters have been exposed via WMI. If you can find a suitable metric source, let us know and we can include it in the exporter.
