### ISSUE TITLE
windows-exporter-daemonset powershell is not found in nano windows server

### ISSUE THREAD

**Issue by dzmitry-lahoda** [prometheus-community/windows_exporter#961]
https://github.com/prometheus-community/windows_exporter/blob/4d2a247e509e5ca85c6d8a9e8522174a2c7a5775/kubernetes/windows-exporter-daemonset.yaml#L25

gives
```
Error: failed to start containerd task "configure-firewall": hcs::System::CreateProcess configure-firewall: The system cannot find the file specified.: unknown
```

so seems nanoserver has no powershell out of box

**Comment by dzmitry-lahoda** [comment]
seems this would be better `mcr.microsoft.com/powershell:lts-nanoserver-1809`

**Comment by breed808** [comment]
Are you expecting to set firewall rules within the container itself, rather than using a `NetworkPolicy`? I'm not familiar with Windows containers, but setting firewall rules inside a container appears to be an anti-pattern.

If the firewall rule is required, it'd be better to set the `configure-firewall` container as an init container for the pod.

**Comment by dzmitry-lahoda** [comment]
i took example provided in this repo to configure firewall in host windows node and fixed it. it configures firewall in host node, not inside container.

**Comment by breed808** [comment]
Ah, that makes sense :+1: I've not had an opportunity to use the container yet, so I'm a bit unfamiliar.

Would it perhaps be easier to configure the firewall from the host, rather than the pod?

**Comment by dzmitry-lahoda** [comment]
running scripts direcly on node, not from container, is violation of aks support conditiona. and overall complicated within autoscaled ask 1.23 cluster.

**Comment by breed808** [comment]
Thanks, that's enough context. I'll update the documentation with the correct init container image.
