### ISSUE TITLE
windows_exporter doesn't collect include hostprocess containers in the container count

### ISSUE THREAD

**Issue by jsturtevant** [prometheus-community/windows_exporter#964]
## Problem
When running hostprocess containers on a node with windows_exporter running the `windows_container_count` metric isn't incremented.  

This is because the container collector queries hcs for the containers and with hostprocess containers the container doesn't exist in hcsshim: https://github.com/prometheus-community/windows_exporter/blob/4d2a247e509e5ca85c6d8a9e8522174a2c7a5775/collector/container.go#L184

In Kubernetes this isn't so bad as there is a metric on [Kubelet ](https://github.com/kubernetes/kubernetes/pull/105406/files) that could give this value for pods. But doesn't do it at the "container" level.

## Desired result
The metric to increment when a HostProcess container is started.

**Comment by breed808** [comment]
Is there a source available for hostprocess containers that we could use? E.G. sum the result of our current `hcsshim` and potential hostprocess source.
