### ISSUE TITLE
how to see the origin ip of the IIS in grafana

### ISSUE THREAD

**Issue by pauloligorio** [prometheus-community/windows_exporter#966]
Greetings,

Guys, I use this grafana dashboard to monitor IIS and other resources of our servers(https://grafana.com/grafana/dashboards/2129) but I would like to see the IP connection origin to get better information of who is accessing our platform, is there any metric that exports this ?

**Comment by breed808** [comment]
You'll want to use a log aggregation service for this. Scraping the logs and exposing source IPs as metrics and/or labels would increase cardinality to an unacceptable level.

The logging solution will depend on your needs. [Loki](https://grafana.com/oss/loki/) and the [Elastic Stack](https://www.elastic.co/elastic-stack/) are popular solutions, though there are plenty of alternatives.
