### ISSUE TITLE
cannot scrape metrics on network drive

### ISSUE THREAD

**Issue by genzo0101** [prometheus-community/windows_exporter#97]
I would like to scrape metrics on usage of a network drive. I tried wmi_exporter but it only exposes local drives. In my understandings, Win32_LogicalDisk, Win32_MappedLogicalDisk are required to scrape network drives but wmi_exporter does not currently support these. 

I also thought of using helper script but wmi_exporter also does not support a function like textfile-collector from node_exporter. I might be able to use mtail on windows but it would take time and effort. 

I would like you to support wmi classes above and/or a function like textfile-colllector.

**Comment by carlpett** [comment]
This seems simple enough, the class Win32_MappedLogicalDisk doesn't appear to have anything unexpected in it. 

I'm a bit surprised that you do not see the disk already, though. On my machines mapped disks are returned by the existing logical disk query. What version of Windows are you running?

**Comment by genzo0101** [comment]
I am using Win Server 2012 R2. Do you mean you can see the disk that is mounted via network mapped to a drive letter with wmi exporter in a default configuration?

**Comment by carlpett** [comment]
Sorry, turns out I checked the wrong thing. `Win32_LogicalDisk` does contain mapped drives, but we actually use the underlying `Win32_PerfRawData_PerfDisk_LogicalDisk` class, which does not.

Sadly it looks like there is no "PerfRaw" class for the mapped logical disk, either. We prefer to use those classes, since they often contain less manipulated data. We'll have to consider using the mapped disk class directly, then.

**Comment by GedPL** [comment]
Hi guys,

I've just wanted to ask if above is resolved or maybe there is any workaround to obtain network mapped drive metrics ?
Thanks in advance !

Ged

**Comment by breed808** [comment]
@GedPL not yet, but I'll see if I can write up a collector or sub-collector for this class.

**Comment by GedPL** [comment]
Hi @breed808 ,
Actually I've created such a separate collector (logical_mapped_disk) based on your logical_disk code and Win32_MappedLogicalDisk class. I can share this one if you want :)

Thanks !
Ged

**Comment by breed808** [comment]
Yes please, we'd be happy to receive a pull request for this :+1:

**Comment by GedPL** [comment]
Will do once completed. Thanks !

**Comment by cleroyer** [comment]
Greatly need this. Please advise about pull request
