### ISSUE TITLE
module mssql missing windows_mssql_availreplica* metric

### ISSUE THREAD

**Issue by nguoingoai** [prometheus-community/windows_exporter#972]
Install command 
`msiexec /i D:\soft\windows_exporter-0.18.1-amd64.msi ENABLED_COLLECTORS=cpu,cs,memory,net,logical_disk,os,system,tcp,mssql EXTRA_FLAGS="--collectors.mssql.classes-enabled=accessmethods,availreplica,bufman,databases,dbreplica,genstats,sqlstats,locks,memmgr,sqlerrors,transactions,waitstats" LISTEN_PORT=9100`
access http://localhost:9100/metrics 
I see the following category metric 
windows_mssql_accessmethods* 
windows_mssql_bufman*
windows_mssql_collector*
windows_mssql_databases*

I can not see any metric about 

Win32_PerfRawData_MSSQLSERVER_SQLServerAvailabilityReplica

Does I missing something ? 
I need monitor replication status (public, subscription) and the performance of replica status

**Comment by breed808** [comment]
Your command appears to be correct. Are you able to query the WMI class manually to confirm if the metrics are present?

**Comment by nguoingoai** [comment]
![Screen Shot 2022-05-16 at 11 01 01](https://user-images.githubusercontent.com/28948005/168517790-1dd6106e-9699-4fda-964b-07db07747f30.png)
Example metric here

**Comment by breed808** [comment]
@nguoingoai can you query the WMI class? The [`Get-Object`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/get-wmiobject?view=powershell-5.1) command will allow you to perform the query.

**Comment by nguoingoai** [comment]
What is the WMI  classname of SQLServer:Replication Object ? Can you show me the name

**Comment by breed808** [comment]
I'm not 100% certain, but https://github.com/prometheus-community/windows_exporter/blob/6042ea3e51aeb7c6bf5c6c0b80da39601df7c80a/collector/mssql.go#L2337 or https://github.com/prometheus-community/windows_exporter/blob/6042ea3e51aeb7c6bf5c6c0b80da39601df7c80a/collector/mssql.go#L2634 would be a good place to start.
