### ISSUE TITLE
Need to convert the error log to at least warning if not info - no instances found in W3SVC_W3WP or W3SVC_W3WP_IIS8 - skipping collection 

### ISSUE THREAD

**Issue by chavalikesavanand** [prometheus-community/windows_exporter#975]
The following error logs Cluttering windows event logs - Need to convert the error log to at least warning if not info
1. no instances found in W3SVC_W3WP - skipping collection.
2. no instances found in W3SVC_W3WP_IIS8 - skipping collection.
File iis.go - line numbers 1344 and 1600

**Comment by aa-matthias** [comment]
is there a way to disable stats of the web service cache? I'm experiencing this error as well.

```ps1
$strComputer = "."

$objWMi = get-wmiobject -computername localhost -Namespace root\CIMV2 -Query "Select * from Win32_PerfRawData_W3SVC_WebServiceCache"

foreach ($obj in $objWmi)
{

	write-host "Name:" $obj.Name

}
```

results in:

Name:

**Comment by chavalikesavanand** [comment]
Any updates on this please?
