### ISSUE TITLE
How to log to a file (rather than stdout / stderr / eventlog)

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [prometheus-community/windows_exporter#979]
Running `.\windows_exporter.exe --help` [reveals](https://github.com/prometheus-community/windows_exporter/blob/4d771d2bcedd4b29f0bf2bade1a45f5e0ee3198d/log/log.go#L65):

```text
      --log.format="logger:stderr"
                                 Set the log target and format. Example:
                                 "logger:syslog?appname=bob&local=7" or
                                 "logger:stdout?json=true"
```

So till here, and from looking at the installed windows service from the MSI installer, it is known that:
- `--log.format logger:eventlog?name=windows_exporter` -> Logs to windows (application) eventlog
- `--log.format logger:stdout?json=true` -> Logs to stdout, in `json` format
- `--log.format logger:stderr` -> Logs to stderr in default format

Is it possible to log to a custom text-file? In JSON? Something like:

```text
--log.format logger:file?json=true&path=C:/windows_exporter/mycustom.log.json
```

Sorry if it is obvious, I could not find anything in the repo and don't know golang.

**Comment by Mario-Hofstaetter** [comment]
Push

**Comment by breed808** [comment]
This may be possible, if our logging library supports writing to a file.

I'll have a look into it and let you know.

**Comment by gabriellus** [comment]
+1
When I used to run the exe and > to a .log file, i got all kinds of goodness. Now after running the MSI install, the Windows EventS are very lacking detail. "Duplicate metrics detected in files". Um, which files?

**Comment by awohlmut71** [comment]
any news about this topic?

**Comment by Mario-Hofstaetter** [comment]
@breed808 after updating to 0.24.0 , is there any documentation on this besides the PR #1192?
I did not see any changed markdown files in the PR.

_Originally posted by @carlpett in https://github.com/prometheus-community/windows_exporter/pull/987#pullrequestreview-973594822_
> Maybe needs an update to the docs? We should probably explicitly mention that we dont't do log rotation and leave that responsibility of the user

Any info yet on how to do this?
README and https://github.com/prometheus-community/windows_exporter/blob/master/docs/example_config.yml 
do not mention anything besides setting the log `level`.
https://github.com/go-kit/kit/issues/701 is useless too.

If a log file can grow infinitely, potentially filling the whole disk partition (worst case), it is not suitable for any production system.
Thus again forcing users to use workarounds like https://github.com/winsw/winsw .. ([see also](https://github.com/prometheus-community/windows_exporter/pull/987#issuecomment-1134681644) )
