### ISSUE TITLE
there is no windows after the exporter starts_ os_ physical_ memory_ free_ Bytes index

### ISSUE THREAD

**Issue by Iatbzh** [prometheus-community/windows_exporter#980]
## Reproduction method: after downloading MSI files, run the installation between

**Comment by linjm1** [comment]
system: windows 2016 datacenter
version: 0.18.1
problem: there is no some metrics ,such as windows_os_physical_memory_free_bytes;windows_os_info

**Comment by breed808** [comment]
Hi all, are you able to confirm the `os` collector is running? If not, is it failing or outputting any useful information to STDOUT or the event log?

Running the exporter with `--log.level=debug` would assist in gathering output from the collector.
