### ISSUE TITLE
Can't install both .exe and .msi package

### ISSUE THREAD

**Issue by amigthea** [prometheus-community/windows_exporter#983]
When I execute the .exe it gives me this error in the terminal window

```
panic: ReqQueryValueEx failed: The system cannot find the file specified. errno 2

goroutine 1 [running]:
github.com/leoluk/perflib_exporter/perflib.QueryNameTable({0x89eb20, 0xb})
        C:/Users/runneradmin/go/pkg/mod/github.com/leoluk/perflib_exporter@v0.1.1-0.20211204221052-9e3696429c20/perflib/nametable.go:43 +0x257
github.com/leoluk/perflib_exporter/perflib.init.0()
        C:/Users/runneradmin/go/pkg/mod/github.com/leoluk/perflib_exporter@v0.1.1-0.20211204221052-9e3696429c20/perflib/perflib.go:269 +0x29
```

when I execute the .msi packages the installer freeze for some time and then it pops this error
```
Service 'windows_exporter' (windows_exporter) failed to start. Verify that you have sufficient privileges to start system services.
```
I know that's not a problem of privileges because yesterday it worked, I installed and uninstalled the .msi packages a few times without problem, same machine and same windows account (with admin privileges)

**Comment by trippinnik** [comment]
what are the command line params on the service? what cli params did you launch with?

**Comment by Azertooth** [comment]
The .exe is not an installer

**Comment by Azertooth** [comment]
> what are the command line params on the service? what cli params did you launch with?

It would output the same error even without any command line params
Beside that, for the .exe, I just doubleclick on it and that error pops out

**Comment by breed808** [comment]
@Azertooth it sounds like the exporter is failing to start. Check the event logs to see if the exporter is outputting any useful information.

@usefree I can't speak for the Ansible role as I'm unfamiliar with it, but please also check the event logs to see if the exporter is logging any errors.

**Comment by usefree** [comment]
@breed808 the problem is not in Ansible role at all, please, don't take it to your attention. The problem is : now the exe file of wondows exporter could not be used for creating windows service with ``sc`` command. And there are no other messages in windows logs except ``The windows_exporter service failed to start due to the following error: The service did not respond to the start or control request in a timely fashion.``
thanks!

**Comment by Azertooth** [comment]
> @breed808 the problem is not in Ansible role at all, please, don't take it to your attention. The problem is : now the exe file of wondows exporter could not be used for creating windows service with `sc` command. And there are no other messages in windows logs except `The windows_exporter service failed to start due to the following error: The service did not respond to the start or control request in a timely fashion.` thanks!

I can confirm the same vague logs in the event collector

**Comment by breed808** [comment]
Are any flags being provided to the MSI installer? I recall experiencing the same issue some time ago. The `EXTRA_FLAGS` provided to the MSI installer were incorrect, causing the exporter to fail on startup and resulting in the installation failing.

It may be worth running the EXE with the same flags that have been provided to the MSI, and reviewing the output.

Hopefully that helps. I'm not sure I can be of much further assistance without more info.

**Comment by SuperSonicFlea** [comment]
I have recently had the same issue on 2 machine. they are AWS instances which our IT built from images. Fix for me was to rebuild the resource counters. 
launch cmd as admin and execute: lodctr /r
Note: on one machine rebuild gave me a error but a second run worked and then installation of windows exporter worked fine.
What led me to this discovery was I tried to open performance counter and got a error and then found I could one add any counters.
