### ISSUE TITLE
Windows perf counter name vs windows exporter metric name

### ISSUE THREAD

**Issue by catchsachinr** [prometheus-community/windows_exporter#993]
Is there already somewhere mapping available that can suggest the parity between windows exporter metrics from host vs windows perf counter?

**Comment by breed808** [comment]
There's no mapping available, though it's safe to say that the exporter metrics are a subset of the Perflib metrics.

You can view the counter sets in use by viewing each invocation of the `registerCollector` function. E.G. https://github.com/prometheus-community/windows_exporter/blob/6042ea3e51aeb7c6bf5c6c0b80da39601df7c80a/collector/cpu.go#L20
