### ISSUE TITLE
New release for Windows_exporter so we have tagged Windows Containers

### ISSUE THREAD

**Issue by phillipsj** [prometheus-community/windows_exporter#994]
It's great to see Windows containers being published. There hasn't been a release since that support has been added so we have some tagged container versions. Is that something that is planned?

**Comment by AngryMandragora** [comment]
+1

**Comment by jsturtevant** [comment]
@breed808 is there anything blocking a new release? any way I can help?

**Comment by breed808** [comment]
I've released v0.19.0. Let me know if there's any issues accessing the tagged container.
